### ISSUE TITLE
Gantry Improvement suggestion

### ISSUE THREAD

**Issue by Adgenodux** [gantry/gantry5#1002]
Hello and congrat for this awsome tool Gantry 5

I'm a gantry beginner but i have a suggestion about the Layout Module Instance.

Currently, into the layout page, we only see the look we designed but it could be usefull to see, into the Instance module boxes, the names of the modules assigned instead of 2 x "Module Instance", and eventually the modules ID's.

This could be nice too to display the module name into the Module Instance configuration box, before the Module ID and into the "Pick Module" window, there could be nice to see the modules ID's.

Thanks for the attention,

Sincerely,

Adgenodux

**Comment by w00fz** [comment]
Hi!
thanks for your feedbacks. We have the ability to change the title of any particle. So when you create a Module Instance, you can rename it in order to quickly visualize what Module it is referring to:

![module instance](https://cloud.githubusercontent.com/assets/11734/11158726/f8f731c2-8a0e-11e5-915b-2b103efdb0c0.jpg)

I like your suggestion for showing the ID. The only reason we never showed it was because we didn't think it was of any relevance. 
I implemented it now though, looks like this :)

![picker_id](https://cloud.githubusercontent.com/assets/11734/11160336/57aed784-8a1d-11e5-9a69-4668c4e7a71c.jpg)


Thank you!

**Comment by Adgenodux** [comment]
Hi and thanks for your fast reply,

Thanks also for the info regarding the naming of modules instances and for the implementation that surely help.

I appreciate the answer you gave to my request and that demonstrates your responsiveness.

Thanks again for your awesome work and i wish you all the best success.

Nice to communicate with you again,

Sincerely,

Adgenodux
