### ISSUE TITLE
Suggestion for a "mirror" capability for sections/rows/particles

### ISSUE THREAD

**Issue by Bokelmann** [gantry/gantry5#1018]
A  Suggestion for a "mirror" capability for sections/rows/particles for layout-outlines.
I added a sketch so you can see what I mean. The concept has some rough edges of course.
For example how to get the reference to a row in section from specific outline.

But I think we could build outlines faster this way ...
A system with 3 options:
1: Mirror an entire **section** to an outline
2: Mirror a **row** into a section
3: Mirror **particles** into rows

![mirror3](https://cloud.githubusercontent.com/assets/11684846/11305238/f8fa3794-8fab-11e5-85fe-7c6e633f139d.png)

**Comment by mahagr** [comment]
Related to #340, but allowing particle inheritance from any outline.

**Comment by cworf** [comment]
Any idea where this is on the priority list? I just launched a news site for my client, and have since decided I will not be utilizing any more themes which are built around G5. I absolutely love G5 but If the number of unique pages exceeds 5 or so. It becomes a *major* hassle to make the simplest of updates. essentially the quickest way to update a change to the header or footer or something else which is mirrored site wide is to open every single outline in a new tab (15 tabs for this site) and go down the list making the same adjustment on each tab. making a link change or adding a name to the copyright section is a process that takes up to 10 minutes, as opposed to 5 seconds, and when you are charging clients $30/hour for your time, this is a problem. 
Considering mirroring was a feature utilized in gantry 4, I'm super surprised it was not a priority in the update to 5, I hardly ever see major software updates completely scrap a major feature. I would love to be able to use some of the newer templates and make use of the awesome features of G5, but this one setback is such a time hog I will unfortunately have to wait. hopefully not long! :)

**Comment by w00fz** [comment]
Like said many times, at this very moment our priority is to bring Grav support into Gantry, second most is the inheritance with mirroring, so basically the issues you are bringing up.

As a side note, G4 never offered any mirroring. Layouts in G4 have always been hardcoded and it only ever offered one layout per template, you never really had much freedom as you do with G5, where you can create your own layout and that can be either shared across the whole site or individual and completely different for each page.
We didn't really scrap this feature from G4, it just never was there.

We understand this is a big hassle right now but it is non blocking and like explained we definitely are going to implement it. Many people take advantage of the fact that everything is stored into files and when they need to do mass editing they just do search & replace within their favorite editor. This is definitely more efficient than it would be using the interface.  

G5 is still an open source project and we are trying our best to get to it all. It requires time and internal discussions for this to be implemented right.

**Comment by w00fz** [comment]
This is now implemented as part of our Inheritance effort.
