### ISSUE TITLE
SCSS processor issue

### ISSUE THREAD

**Issue by dudewithamood** [gantry/gantry5#1032]
I'm not sure how G5 is processing SCSS files but I've encountered a problem using Bourbon's background-image mixin. My code:

```scss
@include background-image(linear-gradient(to left, #000000, #ffffff));
```

is processed as:

```css
background-image: - webkit-linear-gradient(right, #000000, #ffffff);
background-image: linear-gradient(to left, #000000, #ffffff);
```

Notice the space in the first line between the first hyphen and the word 'webkit'.

The code that generates this is line 19 in Bourbon /vendor/bourbon/helpers/_render-gradients.scss:

```scss
$vendor-gradients: -#{$vendor}-#{$gradient-type}-gradient(#{$pre-spec} $gradients);
```
 
That code looks fine to me so my assumption is that it's the processor.

**Comment by w00fz** [comment]
Hello there,
This is sort of a known issue with Bourbon and SCSS preprocessor compiler. Because Bourbon has a mixin which also matches the CSS specs `linear-gradient`, when the compiler work it does a mess mixing the two together, getting out of it an unexpected result.

If you look at my reply in https://github.com/gantry/gantry5/issues/810#issuecomment-143590173 you will see how to workaround this issue (you can read few comments back also for more details).

In your use here you are also nesting mixins and that might be a new issue with the compiler, have you tried separating the two? 

```sass
$linear = linear-gradient(to left, #000000, #ffffff);
@include background-image($linear);
``` 

Also worths noticing that if you really just need 1 linear gradient, you can safely just use:

```sass
@include linear-gradient(to left, #000000, #ffffff);
```

Without the `background-image` mixin, it will do the same thing.

**Comment by dudewithamood** [comment]
Ah, okay, I've used both your solutions now in different instances where they would be applicable and it solves the problem.

Thank you.
