### ISSUE TITLE
Particle variations don't take effect

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#104]
For me particle variations don't do any change.
Menu particle / settings/ Block/ Variations - ...
@kevlardev

**Comment by w00fz** [comment]
Seems to be working fine for me. I applied `Box 2` and I see the variation applied on frontend. What are you trying exactly?

**Comment by kevlardev** [comment]
This is an issue with the menu particle specifically in the navigation position. Because the menu items are using flex for same height flush boxes on the menu items in the navigation position, simple text-align rules wont reposition the flex items (justify-content: center by default). Im adding some conditions for align-left and align-right to reposition the items so you can get the intended effect with the menu.
