### ISSUE TITLE
Mobile menu icon flash when reload / change page

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#105]
Mobile menu icon (off canavas) flash when reload or change page, in full view, where it should be hidden. 
I think this happen only in Chrome, i use windows 8.1, latest chrome Version 42.0.2311.90 m

@kevlardev

**Comment by w00fz** [comment]
Do you have only the `mobile-menu` particle in offcanvas?
This is most likely due the fact that JavaScript is in charge of determining whether the offcanvas section is empty or not, as well as moving the menu in `mobile-menu` particle. You might see the hamburger icon disappearing because the JavaScript won't fire until it reaches that block of code.
So when you refresh the hamburger is there, once the JS kicks off it will see the offcanvas section empty and hide it which might look like a flashing: it happens fast but not fast enough.
Unfortunately we cannot control this via php. We have no way of knowing how the page is going to be rendered so JS is the only good candidate for this kind of operation. What we can do is to have the hamburger always show hidden and then the JS would make it appear if it's needed, so basically the opposite of what's happening now, but it would be flashing in rather than out.

**Comment by adi8i** [comment]
Yes, only mobile-menu is there. Hmm, i hope you understand it right. 

I am talking about full view, so for desktop, mobile menu hamburger is hidden, so is fine. But when refresh the page will show until the page will load, like 1 sec. And this is happen in chrome only. I was thinking at css. Something may be wrong there, an z-index element something like this. You know better. :P

**Comment by mahagr** [comment]
I am seeing the same flashing on menu appearing and disappearing on mobile.

**Comment by w00fz** [comment]
Yes that's exactly what the issue is. The icon is there until the javascript starts running and do its work to determine whether the icon should be showing or not.
Depending on different factors: how fast your machine is, how fast is your internet, how long it takes for the page to load, the `flashing` you see might take longer or shorter.

Like i said we don't have a way to know if it should be showing or hiding via CSS, Twig, PHP. The only place we can determine this is via JS and unfortunately JS has to wait for the DOM to be available before hiding the hamburger.

**Comment by w00fz** [comment]
Alright guys, I changed the behavior here. Instead of flashing in, the hamburger icon now starts hidden and if needed it shows (aka, flashes in).
This is still doing exactly as before but it should be looking better to the eye since you won't have the element disappearing under your nose.
