### ISSUE TITLE
Error while installing Hydrogen (Permissions?)

### ISSUE THREAD

**Issue by iTerentius** [gantry/gantry5#1056]
While installing the Hydrogen theme I get a mkdir permissions error. Hydrogen is the only theme or plugin that has had an issue:

RuntimeException
Creating directory '/var/www/vhosts/labs.medicomhealth.com/wp-content/themes/g5_hydrogen/custom/config/default' failed on error mkdir(): Permission denied

Open: /var/www/vhosts/labs.medicomhealth.com/wp-content/plugins/gantry5/src/vendor/rockettheme/toolbox/File/src/File.php
        // Silence error for open_basedir; should fail in mkdir instead.
        if (!@is_dir($dir)) {
            $success = @mkdir($dir, 0777, true);
 
            if (!$success) {
                $error = error_get_last();
 
                throw new \RuntimeException("Creating directory '{$dir}' failed on error {$error['message']}");
            }
        }

**Comment by newkind** [comment]
777 is not safe, try setting wp-content/themes/hydrogen/custom a 775 permissions

**Comment by iTerentius** [comment]
It is not 777. It is 775. That 777 is in the rockettheme code.

**Comment by iTerentius** [comment]
We do have a different owner than www-data for the entire install and subfolders. I believe the reason was to give FTP access on this server. The group is still www-data and works fine for everything else we run. Is it possible that this would be the issue?

**Comment by allstarrunner** [comment]
I had this exact same issue a few days ago, spent about 2 days trying to figure it out with no luck. I set all my directories to 777 just to see if I could get it to work, but then I just got a new error: 

JFTP: :store: Bad response.
JInstaller: :Install: Failed to copy file /opt/bitnami/apps/joomla/tmp/install_5668f015a8f6d/MD5SUMS to /opt/bitnami/apps/joomla/htdocs/templates/g5_hydrogen/MD5SUMS

before I did the 777 thing, I tried to create my own directories that the install was saying permission denied on, but I got the same mkdir(): Permission denied error. 

Everyone kept saying (not people from here) use "sudo" when installing, but I wasn't able to since it was being installed through the Joomla interface and not directly from the command line. I will be interested to see if someone here knows an answer to this. I had no problem installing the framework, just the hydrogen theme.

**Comment by mahagr** [comment]
First issue was in WP and second one in Joomla. The issues are related but different.

@iTerentius Your issue is related to the fact that Gantry wants to create a few files for both configuration and css files on the fly. Most themes do not generate new content on the fly, which is why they work when Gantry 5 theme fails. If you have installed theme via ftp, you may have permission issues or filesystem has been mounted as read only for the server.

@allstarrunner This issue isn't related to Gantry as Joomla installer fails to copy the file. Maybe you have moved the site from one server to another or changed Joomla FTP settings?

**Comment by iTerentius** [comment]
Thanks all. I'm working with my server admin to get something permissions-wise that will hopefully fix this. I appreciate the help.

**Comment by allstarrunner** [comment]
@allstarrunner This issue isn't related to Gantry as Joomla installer fails to copy the file. Maybe you have moved the site from one server to another or changed Joomla FTP settings?

@mahagr I never moved the site and I never changed FTP settings. Just to give you  more information in case you see this again, using an AMI through AWS is how I setup the VM that I was running Joomla and eventually tried to use Gantry on. When I setup the VM (through Bitnami) their documentation said that, by default, when we run things from the command line we are not a root user, and we have to use sudo to gain that ability when installing things. I ended up switching to a web host I already had because I decided ubuntu wasn't for me, so this problem doesn't affect me anymore. But I will be curious to see if any other people have the same issue I had trying to use gantry the AWS route.
