### ISSUE TITLE
QUESTION: G5-specific components, elements

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#107]
I wonder if G5 will have its specific components, elements, live customizer like getuikit.com.
This might make easy to create sample contents.

**Comment by w00fz** [comment]
uIkit is a CSS framework, G5 is a template framework so customizing elements is arbitrary to the platform, the template and the use of a template. When you have a CSS framework, you already know the elements to be expected because what you provide are styles for it which makes things easier to customize live.

We have no plans to implement anything like that in G5 at the moment. What we do is give template styles customizations from the Styles panel. Perhaps in the future we might look into different approaches.

Thanks
