### ISSUE TITLE
Gantry 5.2.5 issue with Outline and Tabs opening in a modal window and other issues

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#1076]
On this site http://www.rockettheme.com/forum/joomla-template-xenon/252546-help-for-initial-setup when I selected Base Outline the window opened modally and certain functions weren't clickable. This was with a Xenon template.

These are similar issues with a users Kraken site. See http://www.rockettheme.com/forum/gantry5-for-joomla/252564-gantry-5-2-5-template-edit-gui-errors

**Comment by DanGthatRokGallery** [comment]
Another user with this issue
http://www.rockettheme.com/forum/joomla-template-isotope/251093-layout-flex-slider-changes-are-not-saving?start=10#1259746

**Comment by marktaylor46** [comment]
Another member with same/similar issue here: http://www.rockettheme.com/forum/joomla-template-xenon/252508-template-layout-folder-open-in-a-popup-without-any-content?start=0#1259351

**Comment by mahagr** [comment]
I experienced the same issue. Reloading page helped, but before that all the actions caused modal to be opened.

@w00fz It looks like that sometimes URLs are missing &format=json, meaning that the links in the page are returning data as text/html instead of application/json.

I've not run into this issue before, so maybe some change in 5.2.5 is causing this to happen in random.

**Comment by marktaylor46** [comment]
Yes I myself have seen it on my locals too. I confirm it only started happening after G5.2.5 update. It weird how the tabs open in modals rather than the tab.

**Comment by marktaylor46** [comment]
Another member with same issue http://www.rockettheme.com/forum/joomla-template-ambrosia/252629-updated-to-gantry-5-2-5-via-joomla-updater-and-template-areas-no-longer-wor?start=0#1259994
