### ISSUE TITLE
Clicking and Dragging Modules and Particles Doesn't Always Take

### ISSUE THREAD

**Issue by FrugalGeek** [gantry/gantry5#108]
Noticed that when you click and drag particles and modules to the right side of the menu it sometimes kicks the button back and doesn't let you drop the item in place. If I click and drag very quickly it seems to be a bit more reliable than when I take my time.

See linked video for examples.

https://www.dropbox.com/s/69kj0j13u6l68hw/ScreenFlow.mp4?dl=0

**Comment by w00fz** [comment]
Yes this is kind of a known issue. The only droppables zones are the menu items and not the parent white container. When you are with your pointer at that 1-2px gap you are effectively hovering the container and none of the dropzones, that's why it is considered an unmatched drop and returns back to initial state.
I haven't found a way to get around this tbh. Frankly it's very minor issue.

**Comment by w00fz** [comment]
This is more complicated than I hoped it would be, like explained, because the gap between the menu items is not a droppable area, making it so is really complicated because it would be solely based on coordinates and never be very accurate.

Since this hasn't come up at all in all these period of time and was very minor anyway, I'll just go ahead and close this one. Good news is I was able to fix #132 which was related to this but easier to manage since all the sub items are vertical vs horizontal.

Maybe in the future I will find a better logic to handle this.
