### ISSUE TITLE
Gantry 5.2.5: white screen of death instead of translated pages (qtranslate-x)

### ISSUE THREAD

**Issue by wat123** [gantry/gantry5#1081]
After updating Gantry to 5.2.5 on wordpress it gives a white screen of death instead of translated pages (qtranslate-x).

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Invalid resource http://'; in /www/wp-content/plugins/gantry5/src/vendor/rockettheme/toolbox/ResourceLocator/src/UniformResourceLocator.php:287

Do you have any ideas how to fix it?

**Comment by mahagr** [comment]
@wat123 Does reverting back to 5.2.4 fix it?

**Comment by wat123** [comment]
Yes, reverting back to 5.2.4 fix it.
Updating to 5.2.5 and 5.2.6 gives a white screen of death.

**Comment by newkind** [comment]
Can you give me exact steps to replicate the issue ?

**Comment by wat123** [comment]
1. Install wordpress.
2. Install Gantry 4.
3. Install qTranslate-X, qTranslate slug, All in One SEO Pack & qTranslate-X and some other plugins such as TinyMCE Advanced and etc.
5. Create the content in english.
6. Install Gantry 5 (do not remember which version), Timber, RokCommon Library.
7. Create translations in other languages.
8. Updated Gantry until 5.2.4 without any problems.
9. updated Gantry to 5.2.5. - WHITE SCREEN

**Comment by newkind** [comment]
Hi,

I just tried to replicate it and qTranslate-X is fine. The issue I had is with qTranslate slug plugin which is using deprecated calls in it's widget :

`Notice: The called constructor method for WP_Widget is <strong>deprecated</strong> since version 4.3.0! Use <pre>__construct()</pre> instead.`

Which was leading to Warning :
`Warning: Cannot modify header information - headers already sent`

This could look like a blank page to you. Can you please disable the qTranslate slug plugin and see if it's working fine for you ? If this is the issue - it has nothing to do with Gantry but with WordPress dropping deprecated calls. qTranslate Slug plugin author should fix their widget code.

Thanks!

**Comment by newkind** [comment]
Closing this because of the inactivity - feel free to re-open it.
