### ISSUE TITLE
Menu Editor - Order - First Item on Second Row

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#1086]
See the screencast
http://screencast.com/t/c2sU9ZNpuY

**Comment by mahagr** [comment]
@w00fz Looks like JS issue.

**Comment by w00fz** [comment]
It is a JS issue but not Gantry, more like engine. I've seen this before and I wasn't able to fix it.
The problem is that because those elements are displaying inline, the browser thinks the top/left coordinates of that item are beginning at the previous line, throwing the calculations off.

This is always only the case for the first item of the new row, all other items are properly handled.

Sorry I just could never find a way to fix it, at least it is usable, still.
