### ISSUE TITLE
Gantry5 Hydrogen mobile menu malfunction on Android

### ISSUE THREAD

**Issue by seraxes** [gantry/gantry5#1099]
I've setup the main menu and an offcanvas mobile menu as shows in the Gantry 5 documentation.
The mobile menu doesn't work most of the time on android mobile devices (Android 5.x Firefox, Chrome), or on Apple devices.
The main navigation appears instead of the offcanvas mobile menu and submenus can't be opened.
When resizing the browser in desktop everything works fine.

**Comment by w00fz** [comment]
Seems to be working fine for me on my tests. Do you have an URL to point to so that I can take a closer look?

**Comment by seraxes** [comment]
http://fazeday.com

**Comment by w00fz** [comment]
After many refreshes I was able to get it to fail once and what I noticed is that it was actually failing because of the Twitter iframe which prevented the rest of JS to continue processing and causing the Menu not to do its thing on mobile devices.

My suggestion is to use HTML/JS to render the follow button, rather than iframe (which is slower anyway). This should also guarantee that the problem never occurs again.

So where you have the HTML for rendering that iframe (which I assume is a Custom HTML module?), instead of the `<iframe>...</iframe>` just output the following:
```js
<a href="https://twitter.com/fazedaydk" class="twitter-follow-button" data-show-count="true" data-show_screen_name="true">Follow @fazedaydk</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
```

**Comment by seraxes** [comment]
Thanks, I read something about iframe causing offcanvas malfunctions and you found It was indead the problem! 
The Twitter module is a Joomla Extension, I may have to create custom html module isntead to get rid of the iframe.
