### ISSUE TITLE
Can't retract the submenu after opening it

### ISSUE THREAD

**Issue by FrugalGeek** [gantry/gantry5#110]
Tried retracting the submenu of the blog top-level menu item several different ways. Was unable to and found that the entire menu editor got glitchy and unresponsive. 

See linked video for examples.

https://www.dropbox.com/s/69kj0j13u6l68hw/ScreenFlow.mp4?dl=0

**Comment by w00fz** [comment]
This is a non issue. By design we do not allow retracting opened sublevels. Adding the capability is extra code that doesn't really buy anything. Unless you see a point for that?
The Menu Editor is just supposed to give a rough representation of the menu on frontend, it doesn't have to work 100% the same way as on frontend where dropdowns can collapse and such.
