### ISSUE TITLE
Submenu dropdown is not working in Gantry v5.2.7 / g5_hydrogen on Safari Browser 

### ISSUE THREAD

**Issue by sahil-github** [gantry/gantry5#1100]
Hello Gantry Team

I have updated to latest version (i.e.Hydrogen (v5.2.7 / g5_hydrogen)) and now facing a problem that onHover submenu dropdown is not working on safari browser. it is working fine on other browsers.
After discussion with @n8Solution on https://gitter.im/gantry/gantry5 , it seem that it is an issue. Please help me to sort out this issue.

screenshot:https://files.gitter.im/gantry/gantry5/nMmo/blob

**Comment by w00fz** [comment]
I went to the site but I don't see any horizontal menu, it's only in the offcanvas.
I tested on a local copy with Safari and Hydrogen and the dropdowns work as expected. Could you point to an url where this is still an issue?

Also, what Safari version are you running ? Only 8+ is supported.

**Comment by sahil-github** [comment]
i m viewing on the desktop version on safari version 5.1.7 and its not working.
i have also tested out gantry 5 hydrogen them demo https://newf1.nl/ which also facing problem of submenu dropdown.
i have main menu containing HOME, WORLD, BUSINESS, FEATURES etc. i have mention the screenshot link in previous message  i.e. https://files.gitter.im/gantry/gantry5/nMmo/blob

**Comment by N8Solutions** [comment]
@sahil-github If you read @w00fz last sentence he clearly states that Gantry is only supported on Safari version 8 and above.  I just checked and my MacMini, which is very old and I used to test your site, is running Safari v.5.1.10.  So the fact that it is not working correctly in the versions of Safari that you and I are using is expected since they are not supported, i.e. needs to be version 8 or better.

If you are unable to upgrade your Mac and If you have access to a newer Microsoft Windows machine I would highly suggest you install VMWare and install a newer version of Mac OS X so you can properly test your sites out in Safari.  I am doing this now as we speak.

**Comment by sahil-github** [comment]
Thanks Gantry Team for your for your support and Reply.
