### ISSUE TITLE
Wondering about Grav-location of css-compiled

### ISSUE THREAD

**Issue by Tyrion2737** [gantry/gantry5#1101]
Hello,

I wonder if it is intention that my location of css-compiled (only this) is user/gantry5/themes/g5_hydrogen and not user/themes/g5_hydrogen/custom like in Joomla and WordPress.

Olli

**Comment by mahagr** [comment]
To be honest, we haven't locked the location yet, so it may change in the future.

The reason I moved `custom` folder directly into user is that in Grav its better location to keep any custom files in Grav. Though `css-compiled` is different as it is more similar to resized images in Grav than user content..

**Comment by w00fz** [comment]
We actually discussed about putting it under `data/gantry5/custom`.

Basically anything that is volatile and subject to user configurations, so pretty much anything that goes in `custom/` like user overrides or css compiled files, cannot and should not be located under Grav's main theme folder because otherwise on the next update of the theme, all your customizations would get lost.

So to answer your question, yes that is intentional.

**Comment by Tyrion2737** [comment]
I was only wondering because my custom.scss is in user/themes/g5_hydrogen/custom/scss. Somewhere in user/gantry5/themes/g5_hydrogen it seems to not get loaded ...

Olli

**Comment by Tyrion2737** [comment]
Now my custom.scss gets loaded in user/themes/g5_hydrogen/scss, too 😀 Do not know what it was.

**Comment by mahagr** [comment]
Actually after talking with @rhukster, `assets/gantry5` may be better place for compiled CSS. For the configuration stuff, I'm still not fully decided -- we cannot put it under `user/config` because all of it gets loaded on every page load, but I don't think `data` is proper location either as its meant for data filled by end users, like forms.
