### ISSUE TITLE
Blank menus should have a message indicating that the menu is empty

### ISSUE THREAD

**Issue by FrugalGeek** [gantry/gantry5#111]
Switched to an empty menu and it appears as a tiny white line with a cogwheel over the right side of it. Didn't allow me to click and drag anything (particle or Module) into it to establish content. It should instead post a notice letting folks know that the menu is blank and needs content before it can be edited.

See linked video for examples.

https://www.dropbox.com/s/69kj0j13u6l68hw/ScreenFlow.mp4?dl=0

**Comment by w00fz** [comment]
Hmm. This seems a valid point. Although I am not sure if we should be dealing with empty menus at all. @mahagr ?

Part of me thinks empty menus shouldn't be even showing in the switcher and not be selectable. Especially in an eco-system such as Joomla. All kind of issues I can think of with allowing empty menus. No configuration could ever be assigned to it for instance. So I think we should just hide them from the switcher or at the very least if it gets selected, output some sort of notice "Menu is empty, add a new item from the platform before continuing"

/cc @mahagr

**Comment by mahagr** [comment]
Menus aren't usually really empty, but may be written with another language and filtered out. Although the same issue also happens if you add a new menu but do not add anything into it.

We really cannot just not display the menu as many menus are available (not empty) only with specific languages. So you may have main menu in English (or default), French and German.

This is really something we should deal with around the same time we add language support to the menu.

**Comment by w00fz** [comment]
For now I'm just showing a message instead of the broken bar.
