### ISSUE TITLE
Particle percentage width issue

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#1121]
I had 2 particles of width 80 and 20 respectively in a row
I had then added another
G5 scaled them to 33.3 each
I had scaled the 1st on the row to 15, 3rd to 10 by entering the numbers manually
G5 scaled the middle particle to 74.9
Why is this so?

**Comment by w00fz** [comment]
This is known and sort of a `won't fix`, until we can rework the layout manager at least. The shortcut for manually changing the size via settings is there just for convenience but we do suggest to rely on the resize handles which are always accurate.

The issue you see only happens when you have floating numbers, recalculating all the siblings from within the modal has proven to be quite complicated when it's not fixed values.

We decided that since we advice to use the handles to resize anyway, this case can be overseen for the time being.

I think we also already have an issue of this kind already.

Thanks for bringing it up though!
