### ISSUE TITLE
Update issue with 3.5B2 and PHP7

### ISSUE THREAD

**Issue by photodude** [gantry/gantry5#1133]
The following was a preliminary test of an existing 3.4.8 site upgraded to 3.5B2 and PHP7

After the update to 3.5B2 and PHP7, an out of date component notice was given for gantry 5, During the update of Gantry 5 the following error occurred.
```
Warning: Parameter 1 to PlgSystemRedirect::handleError() expected to be a reference, value given in Unknown on line 0
```
```
Fatal error: Uncaught Error: Call to a member function add() on null in /libraries/joomla/cache/storage/memcache.php:466
Stack trace: #0 /libraries/joomla/cache/storage/memcache.php(287):
JCacheStorageMemcache->lockindex() #1 /libraries/joomla/cache/cache.php(292):
JCacheStorageMemcache->clean('_system', 'group') #2 /libraries/joomla/cache/controller.php(69):
JCache->clean('_system') #3 /tmp/install_56b39e729e97f/install.php(99):
JCacheController->__call('clean', Array) #4 /libraries/cms/installer/adapter/package.php(423):
Pkg_Gantry5InstallerScript->postflight('update', Object(JInstallerAdapterPackage), Array) #5 /libraries/cms/installer/adapt in
/libraries/joomla/cache/storage/memcache.php on line 466
```

**Comment by mahagr** [comment]
Both the warning and fatal error come from Joomla, not from Gantry 5.

First error comes from the `System - Redirect` plugin, second one from `Memcache`'s clean() function. I recommend you disabling both if it makes a difference and trying again. I suspect that both of the issues are bugs in Joomla itself.

**Comment by w00fz** [comment]
I would love to get G5 fully J3.5 tested. We were quite diligent to ensure most of the code was PHP7 compatible during development, but it's been hard testing this against Joomla, since it has still some issues with it. For instance, we know Gantry has been working great with Grav, which supports PHP7 out of the box.

So I think this is definitely Joomla related issue and I'm going to close the issue for now. 
I thank you for opening it and please feel free to reopen or add to the issue anytime you feel there are errors that might be Gantry 5 related.

We haven't fully started testing Joomla 3.5 with Gantry so an extra pair of eyes is definitely welcome!

Cheers.

**Comment by photodude** [comment]
@w00fz, @mahagr 
This is the follow up I got from a Joomla member

" https://github.com/joomla/joomla-cms/blob/3.5.0-beta2/plugins/system/redirect/redirect.php#L55 should not be receiving its parameter by reference, signature should match JErrorPage::render() (though the plugin's method shouldn't need to be aware of Throwables). 
The method it calls if it's not handling 404's, JError::customErrorPage() probably should be made aware of Throwables similar to JErrorPage (or even better just proxy to that class instead)."

So this is a Joomla Issue. 

I will keep testing here and there with J3.5... 3.5-Beta3 should be coming soon as a utf8mb4 collation issue is addressed. Hopefully that will be the last of the major blocker issues for 3.5

**Comment by w00fz** [comment]
Sweet, thanks for the update. We'll keep a close eye on it too. 👍
