### ISSUE TITLE
Renaming outlines causes "404 Outline not found" and/or "403 Forbidden Oops, Forbidden."

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#1137]
As mentioned in https://github.com/gantry/gantry5/issues/1125, in WP when renaming an outline several times, it can throw a 404 or 403 error.

Seen this in Gantry 5.2.8 (which was latest then) and also the latest CI (at the time which has now been released as 5.2.9) on a WP Xenon RocketLauncher.

**Comment by igor-gp** [comment]
Just a note around this, i can confirm that whatever it is that's happening is affecting everything on the server. I have other applications running and once this Gantry glitch happens, all other applications stop working properly too. So it's doing something at server level, which then corrects itself in a few minutes. 

I have just seen the same 404 error happen in Grav too, when i saved the new GitHub paths in the active theme using the admin panel.

**Comment by mahagr** [comment]
Sounds like there may be some PHP bug going on which is triggered by a library we are using in both Grav and Gantry...?

**Comment by flaviocopes** [comment]
@igor-gp can you detail the 404 problem in the [Grav issues](https://github.com/getgrav/grav/issues) with as much details as you can? Thanks

**Comment by igor-gp** [comment]
Sure, i have just done a video of it and posted it in a new issue, really strange

**Comment by igor-gp** [comment]
Please if you can look into this issue with Gantry that would be awesome, i am losing so much time since this bug keeps happening when i'm doing dev and then i can't do anything until some time passes.

I'm happy to give you access to my install so you can test it out, so far seems to only be happening in WordPress for me.

**Comment by igor-gp** [comment]
Doing some more tests but it could be on the server side, particularly mod_security. I included this in my .htaccess and so far it hasn't happened yet! I will keep testing and let you know if that's solved it and if so, then maybe you can think through anything that can be done to prevent it on the Gantry side. Otherwise it would just mean some people might need to include that code.

`<IfModule mod_security.c>
SecFilterEngine Off
SecFilterScanPOST Off
</IfModule>`

@kat05 maybe you can test that out too?

**Comment by igor-gp** [comment]
@mahagr I can confirm that the issue is solved by the inclusion of the above code into the .htaccess file (above). Since that, i have not had the errors.

**Comment by mahagr** [comment]
Good that you found the issue; that mod_security is causing all kinds of really crazy issues. I don't think there's anything we can do to fix the issue in our end as we just send some basic JSON data, which has nothing else than nested array of key/values in it.

**Comment by w00fz** [comment]
I'm going to go ahead and mark this as solved. If we can find a way to work around this via core we will do.

Thank you all for helping tracking down the issue.

**Comment by bevels** [comment]
For anyone unfamiliar with .htaccess (it can be kinda picky)

If you're running the WP version of Gantry include the script provided by @igor-gp between the #BEGIN and #END Wordpress tags, like so...

```
# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /yoursite/
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

<IfModule mod_security.c>
SecFilterEngine Off
SecFilterScanPOST Off
</IfModule>

# END WordPress
```

**Comment by mahagr** [comment]
Another user found our that commenting out following mod_security rules: 377619, 340144, 387123, 350096 fixed the issue for him.
