### ISSUE TITLE
Gantry5 Child-theme not working.

### ISSUE THREAD

**Issue by yone920** [gantry/gantry5#1149]
I tried to cried a child-theme for hydrogen theme gantry 5, but it is not working. I tried it in wordpress and it keep referring to g-hydrogen theme.

**Comment by w00fz** [comment]
How did you add the child theme? The wordpress way or the Gantry way?

You can see [in the docs](http://docs.gantry.org/gantry5/theme-development/change-theme-name) how a theme (`helium`) as been implemented to extend the base `hydrogen`. Perhaps this is what you are looking for?

**Comment by newkind** [comment]
@w00fz he's using WP way of doing Child themes. This is most likely stream issue as it loads style.css from the parent dir and also doesn't necessarly allow to override other files. Me and @mahagr are aware of this issue, but we didn't had time to jump on it yet ;)

**Comment by newkind** [comment]
Ok, this wasn't working properly not because of the Gantry 5 issue, but because of a bug in Hydrogen theme itself. I have fixed this now and also created a sample Hydrogen Child theme to be used as an example. 

Gantry 5 child themes will require two files more than regular WP child themes.

The files are :

1. gantry/theme.yaml - modified from the parent theme
2. includes/theme.php - with added extra parent paths to the gantry-theme:// stream

Please check the hydrogen-child theme to get the point of how to do it. The documentation is also in the works.

Thanks!

**Comment by newkind** [comment]
The docs are here! :) 

[http://docs.gantry.org/gantry5/theme-development/create-child-theme-wordpress](url)

Thanks @FrugalGeek

**Comment by janpeeters70** [comment]
Might it be an idea (as a service) to provide the Child Theme as a download from the documentation. Would be great, thanks.

**Comment by newkind** [comment]
Child themes for Helium and Hydrogen are already in the repo ready to be downloaded : https://github.com/gantry/gantry5/tree/develop/themes/helium-child/wordpress https://github.com/gantry/gantry5/tree/develop/themes/hydrogen-child/wordpress

**Comment by janpeeters70** [comment]
Hi @newkind You might have missed my point: I suggested to add them as a download **from** the documentation. Just for convenience.
