### ISSUE TITLE
Slideshow Particle works on wp?

### ISSUE THREAD

**Issue by prankyboy** [gantry/gantry5#1177]
Hello
Starting from sticky header tutorial on Gantry5 doc I've found the Slideshow particle. 
I'd like to know if someone use it on wp, I'm experiencing some prob.
After installation in child theme dir I see the particles but after the setting and savin I've this error:

`An exception has been thrown during the rendering of a template ("Undefined mixin breakpoint: failed at `} ` /web/htdocs/www.distribuzionepubblicita.net/home/wp-content/themes/g5_hydrogen_child/custom/scss/_slideshow.scss on line 18") in "@nucleus/page_head.html.twig" at line 16. `

**Comment by JoomFX** [comment]
Hey @prankyboy 

I'm the developer of the Slideshow particle :wink: 

The error message says "Undefined mixin breakpoint". Did you follow the installation instructions from the [Documentation(http://www.inspiretheme.com/documentation/gantry5-particles/slideshow)? 
To be more precise, did you add the following code to your `custom.scss` file:

```
@import "dependencies";
```

**Comment by prankyboy** [comment]
Hy man, glad to meet u!

I'm checkin the issue, u know it's a production site so I have just a little heartquake in my knees :-D
Anyway yes seems to me I've follwd all the instructions. Now my mate has deleted all the files and the site is... normal. I start again...

**Comment by JoomFX** [comment]
Hey :wink: 

This is really not a serious issue. I mean, the error message is normal, because in the `_slideshow.scss` I use core G5 variables. And in order for this variables to be recognized, you need to have `@import "dependencies";` at the very top of your `custom.scss` file. It is explains in the Gantry 5 documentation. [Here its is](http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet#dependenciesscss), the "Dependencies.scss" section.

Let me know how it goes :wink:

**Comment by prankyboy** [comment]
It works. Of course.
Thx a lot JoomFx.

_If I'm not wrong I bought a template of yours called purity some years ago... :-)_

**Comment by JoomFX** [comment]
No problem mate! I'm glad you figured it out.

Oh, glad you have one of mine G4 templates. Yep, I have PurityFX :smile: 

Can you just go ahead and close this issue so we do not disturb the G5 developers :wink:

**Comment by prankyboy** [comment]
;-)
