### ISSUE TITLE
More enhancement suggestions

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#119]
We need to edit a particle in order to disable/enable it.
Instead each particle might have a small toggle for this purpose in layout mode.
Moreover particles in layout mode might have small "enable/disable icons" for different view-ports so that we don't need to enter specific classes in edit window.

**Comment by w00fz** [comment]
I know there are many useful things that would be nice to have right at the particle level. The problem is all of this would just make the layout manager too cluttered and although you might find enable/disable very useful yourself, some other people might not even ever use that toggle at all and just delete particles when not needed.

I think we should just keep the LM as clean as possible and everything that is an option stay in the cog-modal.
