### ISSUE TITLE
Suggestion for improving access to g5 template.

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1202]
This has come up a couple of times in the forum so I thought i'd raise an issue. When accessing a template from Joomla template manager I think it shouldgo directly to the "layout" tab rather than the "styles" tab. I think it's more common that you would want to look at the layout than do things on the styles tab.

Secondly when accessing Gantry 5 themes, if there is only one theme, then I think this also should go directly to the layout of the "default" outline for that one  theme.

These ideas are suggestions to improve the workflow and reduce clicks to do things.

**Comment by DanGthatRokGallery** [comment]
I agree Mark. I have my Quick Admin in the Control panel set to go to the Home outline -> Layout tab. However it has issues for me as my link doesn't include the realtime created Joomla security token thats appended to the Layout link :(
However I assume that would be taken care of by the Devs for this change :+1:

**Comment by mahagr** [comment]
@w00fz What do you think?

I think that the reasoning for going to styles tab was the following:

1. changing colors is the first thing you want to do on new site
2. it was like that in Gantry 4

Also styles is probably what users are expected to see when they go to change settings of the theme.

Not that I disagree, but for new users layout may not be the best starting point.

**Comment by marktaylor46** [comment]
Obviously whichever tab you pick is goin gto be wrong some of the time. But, in reality if you are clicking on a template in template manager the last place you've want to be going is "styles" - because you wouldn't generally change colors etc there. You'd be doing that in the "base outline". The same is true of "settings" tab for particles too, you are unlikely to be wanting to that in a specific outline too, so for me the most likely thing you at least want to look at is the layout (even if not to change it - just look). So that's why I think it would be better to show the layout tab first.

Also, the components > Gantry 5 Themes initial page adds no value if you only have one theme installed - you may as well just go straight to the base outline of that one theme (in this case I can see an argument for going to the styles tab first).

AS I said, this has been instigated by comments from members in the forum about "too many mouse clicks" to do common things (when developing a site).

I hope that helps.

**Comment by mahagr** [comment]
The above explanation is exactly what I wanted to hear and I agree that changing anything else than layout does not generally make sense unless you are in base outline. And you can enter to base outline from Components > Gantry 5, which then makes sense to point to the base outline of the only installed theme (maybe then Styles / Settings tab are more suitable entry points?).

**Comment by DanGthatRokGallery** [comment]
Since we're on this topic any chance of including the Body outlines in the main Template Manager screen. The too many clicks happens when I have to enter a Preset Outline just to get to the dropdown so I can access Base Outline, Offline and Error Outlines.

**Comment by JoomFX** [comment]
I'm not sure I agree with the idea of adding the "Body", "Error" and "Offline" outlines to the Template Manager screen in Joomla.
The reason is that these outlines are not used/accessed very often. I for one, have never used the "Body" outline, never. The "Error" outline is needed more often though. But adding these Outlines to the Template Manager screen will increase the number of "options" even more and therefore will bring more confusion. Remember, in the default Joomla you usually have just one outline/style - have a look at Protostar for example. Yes, the default Joomla and Gantry are two different things, but the Joomla users are used the default Joomla way.

On the other side, most of the times I access the Gantry 5 Admin, I need to go to the "Base" outline. Currently I open the "Default" outline and from there I go to the "Base" outline. So adding the "Base" outline to the Template Manager screen is actually a very good idea.

@mahagr Matias, sorry but it is still bugging me... whenever we discuss Outlines, the first thing that comes to my mind is the "Default vs Base" thing. You explained it very well in https://github.com/gantry/gantry5/issues/295, you explained that this is how it should be because of the way Joomla works, but I just cannot help myself... isn't there really a way to have only the "Base" outline in the Template Manager? As it was in Gantry 4 - there was just one "Master" outline/style?

**Comment by marktaylor46** [comment]
I wouldn't want to see the system outlines in template manager either - they're rarely altered so I think the existing access is fine.

@JoomFX With regard to the "base outline" showing in template manager - I'm not keen on that either since the base outline does not have a "layout" that would not be in accord with the reason I created this ticket in the first place... i.e. that when choosing a template in template manager it should go to the "layout" tab rather than the "styles" tab.

**Comment by JoomFX** [comment]
@marktaylor46 You are right Mark!

But in the near future (in 5.4) the "Layout" tab will be back in the "Base" outline.
And what I'm really dreaming about, what I really want to see one day (and I believe it will be a great usability improvement that will massively reduce the confusion) is to have just the "Base" outline that will hold the defaults for everything and will do the job that the "Default" outline currently does.

If you think about it we have the following:

**Base Outline** - hold the **defaults** for everything (soon there will be a Layout tab again)
**Default Outline** - is is called "default" but it does not hold the defaults, because the "Base" outline does that. It only offers a "Layout" tab (which will be back in "Base" soon).

Guys, I'm sure that Matias is sick of me and my "Default vs Base" think. But I just cannot help it. 
I have absolutely no problem to work with Gantry 5 and the way it is now, I'm already used to it. But for me having "Base" (that holds the defaults) and "Default" (that does NOT hold any defaults) does not make much sense.

Matias, I want to apologize in advance for bringing this up again :smile:

**Comment by marktaylor46** [comment]
I'm aware of the 5.4 future - but I want to improve things now. G5.4 is not there yet and not coded yet (and still subject to change) so I'd like to address the "too many clicks" debate now (it keeps coming up). This is a relatevely minor change suggestion that could make a big difference...

Anyway... that for everyone's views....  :)

**Comment by mahagr** [comment]
The reason why we do not have system outlines in template layouts is that they do not act like the other layouts. Same is true for base. You cannot assign, rename or delete them. They are needed to display internal pages (with the exception of base) and having any of them in template styles page would just confuse more, not to mention all the extra logic I would need to put into there to make Joomla to support them.

The reason why base outline isn't default template layout comes from the fact that default template layout can be changed. Gantry 4 has some extra logic to make sure that the Master works, but it plays against Joomla rules. For Joomla there's no difference between template layouts, they all act the same and can be assigned or marked as default. If we want to use template styles as Joomla has meant them to be used, there would be no inheritance between them. Every outline would have all the settings defined and making a change would mean changing all of them.

Of course we could just assign one of them as the new Master (or base), but what happens if you delete it? Do we loose all the settings? And what happens when you change the default; do we copy the old base settings to the new one? If so, how to deal with the old base, which is no longer base? We cannot keep all the settings set either as then we would loose the benefit of having inheritance.

If you can solve all of these problems in a simple way and without having logic changes in template manager (all the logic changes in there are ugly hacks, searching and replacing html, intercepting tasks etc) I would love to get rid of base outline as it is.

PS. for the same reason base outline cannot be added to template manager...

**Comment by JoomFX** [comment]
@mahagr Thanks for the explanation (again) Matias.
Well, since you've designed it that way (with both "Base" and "Default") I believe it is the best possible solution :wink: 

I should stop with the "Base vs. Default" thing once and forever, I guess :smile: 

Anyway, then my only request (sorry for going offtopic) is, once the Inheritance is implemented, to have the "Layout" tab in "Base" and then "Default" to inherit the layout from "Base". As it is with everything else - "Default" inherits "Styles", "Settings" and "Page Settings" from "Base". For the sake of consistency and to reduce confusion, it must inherit the "Layout" as well.

**Comment by igor-gp** [comment]
@JoomFX i agree, that would be a great enhancement to have that inheritance.

I know you can go into the code and copy and paste into the outline files whatever you like, but nothing beats having that in the UI. In instances when users have several outlines, making changes to the footer for example should affect all other outlines if changes are made in the base layout. Otherwise you need to go into each one separately which is time consuming.

**Comment by w00fz** [comment]
Changing the default entry to something else is really just very subjective more than anything. To me Styles makes the most sense because 1. it's the first tab, 2. colors/presets have been always the main entry for G4 and even in G3 we always had colors at the very top of the list.
We could argue that since Layout is such an important and powerful tool in G5, that allows for changing sizes and adding positions and modules and this and that, it could be considered the most common entry point and more relevant than Styles, but then again, we cannot predict in anyway what your intentions are when you enter an outline. Are you going for changing colors? page settings? layout? We just don't know.

Eventually in the future I could store in the browser storage which tab you are clicking and keeping that persistent across the session (or just persistent), so it would always load the latest tab you've been in, but i am really not too happy about the extra work and functionality I would have to put in just for that.

In any case, I'm going to close this issue because the other mentioned suggestion about Layout in Base, will make its appearance in 5.3. With Inheritance, it does now make a lot of sense to have the Layout back in Base.

Cheers!
