### ISSUE TITLE
Module instance edit fails with "You are not permitted to use that link to directly access that page"

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1215]
This seems to have been introduced with Joomla 3.5.

When you now edit a module instance on the layout and click on the "To edit the Module please use the Joomla's Module Manager" you now get an error message that says "You are not permitted to use that link to directly access that page"

**Comment by hennysmafter** [comment]
This is probably a browser caching issue. As it happens on Chrome but not on IE, FF, Opera, Safari, NightlyFF and a few others. Please confirm if this is also at your end. This bug is already present in Chrome since J 2.5 and I honestly don't understand why this is not fixed a Joomla's end or Google's.

I don't think this has something to do with Gantry.

**Comment by marktaylor46** [comment]
That the problem the link is wrong - it's not a valid link and it happens even if I have every cache turned off. Also, it doesn't happen in J3.4.8.

**Comment by marktaylor46** [comment]
Just to make it clear this is the link I am talking about (which is G5).

![2016-03-29_16-26-40](https://cloud.githubusercontent.com/assets/11683218/14113486/20797d04-f5cb-11e5-9393-92021dc6c7c5.png)

**Comment by mahagr** [comment]
@marktaylor46 Didn't test it in Joomla 3.4, so please test it for me. It should work, though.

**Comment by marktaylor46** [comment]
tested in both J3.4 and J3.5 and it appears ok to me :)
