### ISSUE TITLE
Option to disable or enable collection.list items

### ISSUE THREAD

**Issue by nicutor** [gantry/gantry5#1228]
Hi,

After working a lot with collection.list items, I think that will be great to add a way to enable/disable an item. 

Each item have a lot of settings and sometimes the users don't want to remove it, but, keeping it disabled until they will decide to use it again.

This option can be added near to items buttons like the Duplicate one: https://github.com/gantry/gantry5/issues/1220

Thank you for consider it.

**Comment by mahagr** [comment]
I'm not 100% sure how the setting should work; it needs some support in the particle end as well.

I think the best way to do something like this would include adding a new option for each item, something like "Enabled / Disabled" toggle. Particle must manually take account of this setting and skipping any items which aren't enabled. This means that there's no automatic support for disabling items, which I think is OK, as not all particles need to support it.

Additionally there could be a new icon in the list, which you could use as a shortcut to enable/disable item from the list, but it is not really required to make the feature to work.

BTW: You can already do all of this in your own particles -- just the visual clue in the list is missing.

My next question is: which particles should have this support?

**Comment by nicutor** [comment]
I think this should be a global thing not only for some particles. This should be everywhere a collection.list is used.

I don't know how to add "Enabled / Disabled" toggle yet but I will take a look on all particles to find it out.

I am used to do this by set a variable on each item like this on .yaml:

```
.disabled:
  type: input.checkbox
  label: Disabled
  description: If checked, this item will be disabled.
  default: false
```

And then on .html.twig

```
{% for item in items if not disabled %}

...
...
...
{% endfor %}
```

However, the twig docs says that:


> The loop.length, loop.revindex, loop.revindex0, and loop.last variables are only available for PHP arrays, or objects that implement the Countable interface. They are also not available when looping with a condition.

I was limited by this before, so, probably my way is not the best option.

If you can add "Enabled / Disabled" toggle on each Item from collection.list and add the new icon on list, will be perfect.

**Comment by mahagr** [comment]
Your solution cannot be global thing just because of already modify .html.twig in your example. Global means that particle wouldn't need to have changed to make feature to work and clearly even your example isn't obeying that rule. So while the feature (global toggle) needs to be implemented, its not something that can be enabled without particle itself supporting the feature.

**Comment by w00fz** [comment]
I agree with Matias.

What you are doing with the checkbox for enabling / disabling is the proper way of tackling this and also very elegant.

We cannot have a global setting because every particle twig handle the output their own way, Gantry doesn't really know what's in there. The other problem is that cycling through the items is something that happens within the twig and not at the Gantry level, so we wouldn't have a way to catch disabled items either.

What you are doing is really the right and only way to handle this. Probably you see the need of this being a core feature because all your collection particles provide a way to disable single items, but so far we (RocketTheme) never really had seen the need for such a functionality, if we ever do we will probably approach it the same way as you did, with a checkbox/dropdown to enable the individual item and then cycle through all the items except the ones disabled

**Comment by nicutor** [comment]
Hi @w00fz and @mahagr, 

I there is no way to put this on particle backed side, then, I will continue to do it in my way live before.

Thank you both for reading, replying and thinking on a solution for this.
