### ISSUE TITLE
Is there a "Base Layout"?

### ISSUE THREAD

**Issue by newjie** [gantry/gantry5#1230]
The "base outline" let us edit base particles for all outlines, which can be overriden in various outlines. I am wondering if there is a "base layout", where several outlines can share a part of layout, like the Navigation bar. 
Currently, every outline has their own copy of layout. I use "outline-home" for my home page and "outline-default" for my other pages and I find that every time I want to change the layout of "Navigation section", I need to manually change both the home layout and default layout.
I don't remember I had to do this in gantry 4.

**Comment by mahagr** [comment]
There is base layout, but right now it is implemented only in WordPress because of Joomla has its own template styles system, which allows you to change the default style.

We disabled the base layout mostly because of it was very confusing to users, mostly because of layout inheritance hasn't been implemented yet. With layout inheritance base layout will make a lot more sense as it can be used to add common stuff to every layout out there.

The reason why layout inheritance hasn't been implemented yet is that it is really complicated feature to implement and we decided to postpone it to the G5.4 version because of the changes it required.

**Comment by newjie** [comment]
Is there any workaround for my dilemma? Right now the only thing I can think of is combine everything in the Navigation Bar to a single particle, that way I can edit this particle and every outline will change

**Comment by mahagr** [comment]
There are two ways to attack the issue, which is why we weren't that concerned about it in the past.

First way is to use base outline settings for common particles (like logo, menu, copyright etc) allowing you to change them from base outline and get the content automatically updated everywhere.

Another way is to use module positions and put particle into a module.

**Comment by w00fz** [comment]
As stated above, Layout will make its way back when we hit 5.3, in the meantime you can use one of the approaches suggested that Matias.

Cheers!
