### ISSUE TITLE
Filepicker - wrong file path

### ISSUE THREAD

**Issue by Trust7** [gantry/gantry5#1236]
I added a particle with filepicker to my template. I choose a file inside the particle and save changes and after that when I check how it looks on the frontend I have a path to the file "gantry-media://filename.extension". I understand that Gantry is not making a correct path out of "gantry-media://". Is it a bug or am I doing something wrong?

![filepickerproblem](https://cloud.githubusercontent.com/assets/17771389/14512295/0b08325c-01de-11e6-814f-bc3ce530420b.jpg)

I also wanted to ask why there is no documentation on the filepicker. For example how to define extension filters in Yaml?

**Comment by w00fz** [comment]
You can set the extensions filter via `filter` attribute, ie for an image you would do:

```
filter: '\.(jpe?g|gif|png|svg)$'
```

Quite likely the problem is in your `twig` file. The stream format is Gantry's but you need to translate it for the browser to a proper path. To do so you need to use the `url()` twig filter, ie:

```
<a href="{{ url(particle.miniatura) }}" ... 
```

You can have a look at the logo particle to see how it's used there.

**Comment by Trust7** [comment]
You're right. Instead of "{{ url(particle.plik) }}" I wrote "{{ particle.plik }}". Thank You for quick answer!
