### ISSUE TITLE
how to automatically compile .scss file other than custom.scss

### ISSUE THREAD

**Issue by newjie** [gantry/gantry5#1238]
Currently the custom.scss file will be automatically compiled to .css file and included for every page. But I want to have some .scss files that are only included in some certain pages. 

I add a custom css/js atom for the page's outline, and put my.scss in it. It is included in the page without compilation all the scss syntax got ignored.  Is there any more proper way to do this?

**Comment by w00fz** [comment]
You can't do it like that. If you want to build your own SCSS you need to use 3rd party compilers, there are plenty windows / mac / linux.

The automatic SCSS compiler that we use in admin, it's a bit more complex than just regularly compiling sass because it depends on variables, custom sass functions and paths that are dynamic and only known to Gantry.

However if what you are looking for is just compiling regular SASS, then you can do so by using compilers.

A few apps:
 - http://koala-app.com/
 - https://mhs.github.io/scout-app/

A good article:
 - http://www.sitepoint.com/my-favorite-sass-tools/

**Comment by mahagr** [comment]
There is actually issue on this, #215. It has just not been priority as there are some other things that are more important than creating multiple CSS files on demand.

**Comment by mahagr** [comment]
You can use this code to compile any scss file from the standard locations:
```
{% assets with { priority: 0 } %}
    <link rel="stylesheet" href="{{ url(gantry.theme.css('test')) }}" type="text/css"/>
{% endassets -%}
```

**Comment by mahagr** [comment]
Documented.

**Comment by newjie** [comment]
By "Documented" do you mean this is included in docs.gantry.org? If yes I can't find it.

**Comment by w00fz** [comment]
It's in the docs but in a `5.3` feature branch, which means is still not yet live. It will become once we release Gantry 5.3 and merge the branch in.

In the meantime, you can look at the change here https://github.com/gantry/docs/commit/6a7749fbbb94f25a73bd7898e67474404bc80d4f

**Comment by newjie** [comment]
I've read the related 5.3 docs. Just to clarify, if I want to make a .scss file available to a certain outline only, I can modify the .twig file of any particle within this outline, correct? Furthermore, since attaching the .scss file with a certain particle doesn't make sense(it should be related with the outline but not any particle), I think the best practice is to create a custom atom and edit its twig file, is this perception on the right track?

**Comment by mahagr** [comment]
SCSS file will be available in all outlines, but with the variables coming from selected outline. Basically it allows you to add dynamic css files to a particle, which takes some settings from the outline.

Basically there's going to be just a single css file shared between all the particles, but each outline has its own version of the css file.
