### ISSUE TITLE
Mega Menu for Gantry 5

### ISSUE THREAD

**Issue by sanek4life** [gantry/gantry5#1245]
I'm using Gantry 4 and create menu with 2nd and 3rd level for show without click on mouse, and show 4th level of menu with hover the mouse on menu.

This menu on my site with 3rd level for show and 4th level with hover the mouse (Oculus template):

![menu gantry 4](https://cloud.githubusercontent.com/assets/3662519/14700153/21c93a4a-07a6-11e6-9007-39ed99ed43f8.png)

and this is same menu on Gantry 5 (Xenon template):

![menu gantry 5](https://cloud.githubusercontent.com/assets/3662519/14700165/3153ba62-07a6-11e6-9027-6cf621887693.png)

1st question: How i can create menu (for show on Desktop), for show 3rd level without click on mouse, and how i can create 4th level menu with hover the mouse on menu using Gantry 5 template?

2nd question: Why I need to click on the mouse to see the drop-down menu? why can not I just point your mouse to see this drop-down menu? (i mean 3rd level of menu on Gantry 5)

Gantry 4 have good menu for Desktop and very bad for mobile.
Gantry 5 have good menu for mobile and very bad for Desktop.

Why developers not can create good menu??? i need Desktop menu from Gantry 4 and mobile menu from Gantry 5 for my site! Why i'm not can put on my site good menu for mobile and Desktop at one moment???

**Comment by w00fz** [comment]
There are an infinite amount of ways one can create a menu, all right and all wrong. Gantry 4 was handling all the subitem dropdowns the same way, in Gantry 5 we reworked and approached it in a more modern and touch-device friendly way. This is why sublevels in Extended mode (megamenu as you call it) are sliding and not expanding as it was in Gantry 4. Simple mode dropdowns don't have the sliding approach and will expand as you are asking.

If you have to click on a menu to expand Simple mode dropdowns, most likely you are using a touch-device or a multi-purpose PC (with touch screen). This is not a bug, it's a feature, that was needed to make touch-devices compatible (in Gantry4 this was very clunky).

We don't have any intention to change any of these behaviors or provide other menu types,  in the near future. G5, as opposed to G4 which was relying on RokNavMenu, comes with a built-in menu system, which allows you and any developer who likes, to come up with their own menu particle. It will require some Twig, some JS and some CSS to create your very own menu particle, which is no different than any other particle, except that, if you ever venture into this, you will notice how much complex a menu is to build 😄

**Comment by sanek4life** [comment]
@w00fz I pay for this subscription to RocketTheme in the hope that I will have a website with good design and menu.

in the gantry 4 was very bad mobile menu, gantry 5 poor design and no mega menu!

for whom you are doing all this? for 5-page websites???

**Comment by FrugalGeek** [comment]
We try to design themes that meet the needs of the vast majority of our customers. Themes are essentially a starting point for your development, and we run the risk of making things too complex if we provide several different types of menus to meet several specific (in this case very rare) use cases.

This is one of the reasons Gantry is an open source platform, and we make our themes so they can be easily modified and expanded on by the developer.

There is nothing preventing you from creating your own menu that does exactly what you're asking for. But in the case of our provided menus, we had to go with the needs of the many before we start tackling the specific needs of individuals.

**Comment by Bonitto** [comment]
While I am no longer a current subscriber, I was excited and looking forward to renewing my subscription when I finally was able to see how intuitive and amazing Gantry 5 is to use. But I can't lie, the nav limitations have sadly made my pursuit come to a full stop. I completely understand that there must be a balance to meet the majority of customers but I can't help but feel a bit disappointed with the lack of versatility or the decision developers made to completely omit implementing any form of a mega menu support with multiple columns and or rows.

Especially since recent trends for website usability are increasingly moving in this direction. Not to mention it is a common request in multiple threads in your forum from your existing subscribers. 

Navigation and ease of use are by far the most important aspects of usability. And forgive my slight rant as I know it's easier said than done but I can't help but feel you guys have already accomplished so much with probably making the best template framework to let this become an oversight (Especially when this functionality is available in T3). 

Nonetheless for now, I guess I'm stuck with T3 as the mega menu options for Joomla as far as modules go are not too appealing and I was refraining from adding unnecessary bloat. I look forward to the day you guys decide to reconsider. =) Thanks so much though for what you've provided for free to the community so far.

**Comment by NativeRadio** [comment]
I have been a RocketTheme Developer member since at least 2010. In that time you have always been on the bleeding edge and made your developer's lives better. Well you've totally screwed Gantry 5 with this major menu FLAW! To limit a developer to a level 1, 2 column option is lazy and pathetic! Gantry 4 had this option. RokNav Menu had this option. To take it out, and to have done so for over 2 years, is why we will never again use a Gantry 5 system. It is also why we will never trust you again! Probably the biggest coding blunder in RocketTheme's history!

**Comment by uglyeoin** [comment]
Just in case anyone arrives here, I believe multi-column menus exist now.
