### ISSUE TITLE
Multi row layout

### ISSUE THREAD

**Issue by nikola3244** [gantry/gantry5#1249]
Well, a picture is worth a thousand words, so look:
![new](https://cloud.githubusercontent.com/assets/15911110/14740910/c2ebb8b6-0892-11e6-8c21-2dc80a6d7e7d.jpg)
This is just edited in Photoshop so you can see what I mean.
If someone has better idea for title or description, edit it.

**Comment by mapadale** [comment]
![image](https://cloud.githubusercontent.com/assets/15608906/14742316/73c62a72-0893-11e6-8893-130e9cb3bc07.png)
Unedited using the Gantry 4 Framework Layout in Gantry 5.

**Comment by w00fz** [comment]
This is something that we did have working in the very first implementation of the Layout Manager, back in the alpha stages. In fact, that version allowed pretty much any kind of drag and drop, turning a particle into a row, adding multi columns / multi rows, new sections, sections reordering, etc.

It looked like the perfect way to go, until we realized we had to step back, rewrite and simplify a lot because not only the code was getting incredibly complex and very hard to maintain, debug and bug fix, but it was also causing a lot of confusion (even internally for the team) on the way things were working, too much freedom turned out to make it less intuitive than it should have been.

So our approach to LM ever since has been to keep the UI and UX simple and easy to follow, and let everything else being handled via the YAML for those cases where one wants more out of it.

The multi row/single block is something that has been requested before and it might seem like a simple addition, however there are a tons of implications involved. For example, even if it doesn't look like so, what you have there is a Block, containing 2 grids (rows). The first grid has 1 block, containing one particle, the second grid has 2 blocks, containing 1 particle each. So as you can see this is a nested implementation of blocks and grids that brings in a lot of complexity in the way we handle things.

```
Main
  - Grid 3
    - Block 1
      - Module
    - Block 2
      - Page Content
    - Block 3
      - Grid 3-1
        - Block 3-1
          - New Module
      - Grid 3-2
        - Block 3-2
          - Module 2
          - Module 3
```

We feel like this is going to make things just way too complicated for both us and the end-user, so at this moment we are not foreseeing us implementing any of this.

Although I won't negate this would be incredibly nice to have, nor that we won't ever consider it. If and when we rewrite again the Layout Manager, we will certainly consider this feature as well.

Thank you for your feedback!

**Comment by nikola3244** [comment]
Thanks for the detailed answer. 
I firstly thought it's a simple feature, but after some of thinking how I could implement it I realized that it actually is very complex.

I will stick with my CSS approach for a while.

**Comment by mahagr** [comment]
In the mean time there may still be way to do this; you can create a particle which contains other particles. We already have this functionality kinda there, but I have never tried it.
