### ISSUE TITLE
Honour new "display in menu" field in Joomla 3.5.1

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1255]
A new field was introduced on the options tab of a menu item in Joomla manager in V3.5.1 of Joomla. This field is used to prevent certain menu items from being rendered at all. Obviously the new field works with a standard Joomla Menu module, but I think we should also change Gantry 5 to honor this field too.

![2016-04-26_15-32-27](https://cloud.githubusercontent.com/assets/11683218/14822373/57eeb144-0bc6-11e6-8ffe-7a44f8039682.png)

**Comment by w00fz** [comment]
There was actually an issue / suggestion (#1020) for having the enabler in menu items so that menu items could be easily get hidden via menu editor which I liked but we still haven't implemented.

I think the two issues are now related, on non-Joomla platforms it would be all controlled via Menu Editor, while in Joomla we would now just tie it up to this setting.

**Comment by bloominari** [comment]
Agree, it would be great if you also include this in Gantry 5. Thanks guys!

**Comment by w00fz** [comment]
This is now fully implemented in #1020, we just need to get the Joomla setting hooked up.

**Comment by marktaylor46** [comment]
Just wondering if we grey out the menu item in Gantry 5 menu editor when this is set (like we do when we disable particles on layout) - I think that would be useful?

**Comment by mahagr** [comment]
Its already doing that.

**Comment by marktaylor46** [comment]
Lovely - just thought I'd ask (should have tried it really - LOL). :)
