### ISSUE TITLE
Suggestion for the menu editor

### ISSUE THREAD

**Issue by dyvel** [gantry/gantry5#1256]
Hi

I have 2 suggestions for the menu editor:

1. When using the menu editor to build a "mega menu" I would love a feature to enable the menu "on click" instead of on mouse over. And also let the menu display until you click away from it - not just when the mouse if moved away. 

2. Being able to create multiple "rows" in a submenu. E.g. one row with 4 columns and another row with just 1. It would allow for a very powerful setup where we could use a row for a "call to action" while still have the normal navigation on top/below.

**Comment by w00fz** [comment]
Hi,
I am not sure I understand your first point. In the Menu Editor it is all `click` driven, there isn't mouse hover. On the front-end we have both and it's automatically decided based on the device. If it's a touch device a click-only mode kicks in, since touch devices do not have hover. If you are on desktop it is hover. Finally we have a 3rd case for those all-in-one pc devices that support both touch and mouse, in which case the user can use both hover and click. Which side are you referring to?

Regarding multiple sub-columns, at this moment we have no plans on implementing it. We feel like the menu, as is, provides already plenty of features and adding support for sub-columns is a very specific use case that would add a lot of complexity to the already complex menu system we provide.

I think eventually we could revisit it in the future and think about expanding it but for the moment we haven't really seen the need for it.

**Comment by dyvel** [comment]
Regarding the click function, I'm not talking backend. I'm talking frontend, and how we "activate" the dropdown menu. This website illustrate what I thinking about: http://nrs.com - check out the menu, how it's submenu is activated by mouse click.

**Comment by w00fz** [comment]
Then that's what I thought and because we are already automatically handling hover/touch per-device, as is, all the logic is in place. If you try on an iPad or you enable touch simulator in chrome, you will see it works by click exactly like on that site.

You can force this behavior by adding the `g-menu-hastouch` class to the `.g-main-nav` menu. A quick jQuery snippet would be something like:
```js
jQuery('.g-main-nav').addClass('g-menu-hastouch');
```

However if you absolutely don't want any hover effect, then you will also need an addition JS snippet:

```js
G5.$('.g-main-nav .g-menu-item').off('mouseenter', G5.menu.bound('mouseenter')).off('mouseleave', G5.menu.bound('mouseleave'));
```

That basically removes completely the mouseenter and mouseleave logic. Unfortunately, that `G5.$` is not exposed in the current version of Gantry, but I can attach here a compiled version of it for you to use and make sure that it makes it to the next release.

That said, I personally wouldn't like this as an option in Gantry itself, the automatic behavior is mostly what everyone looks for and an option that rarely gets used would just take up space. However, i'll discuss this internally also and see what the other thinks.

For now, you do have a way to make the menu behave like you want already, I hope that helps.

**Comment by DrVolt** [comment]
Actually several customers of ours asked for menu like the one dyvel described in point 1.
Some of them even want more: like having an 'x' placed on menu item in order to close it down.

See this example here: (https://www.kepware.com/)
If you click on on Item, an 'x' appaer beside it in order to close it.
We have been asked a menu like this one, but I don't know how to achieve that in Gantry.

It would be an useful addition for us.

**Comment by w00fz** [comment]
We are going to add point 1, we have talked about this internally and it seems like a welcome feature.
Regarding the (x) however, that is beyond the Gantry core scope, it is something that should be implemented at a template level. Also worth mentioning is that you have a frontend JS hook you can rely on. Adding an onClick even on any element you want to trigger `G5.menu.closeAllDropdowns();` will close the menu, acting like the (x) you are looking for.

Thanks for the suggestions!
