### ISSUE TITLE
Dependencies not found 404 error

### ISSUE THREAD

**Issue by mbogart24** [gantry/gantry5#1269]
I have been having a problem that I can't seem to fix using the G5 Hydrogen template.
When a call is made for dependencies it gives a 404 error and slows down the site.
The error is encountered when :
" script src="/media/jui/js/jquery.min.js" 

![screenhunter_24 may 04 14 53](https://cloud.githubusercontent.com/assets/16159220/15030763/1dee6f36-1209-11e6-8e29-6ebb606c39b5.jpg)

![screenhunter_19 may 04 14 41](https://cloud.githubusercontent.com/assets/16159220/15030351/a8b98360-1206-11e6-88dc-15d6bf796639.jpg)

![screenhunter_20 may 04 14 45](https://cloud.githubusercontent.com/assets/16159220/15030404/ea88ba7c-1206-11e6-9c43-cdbc870d7707.jpg)

![screenhunter_21 may 04 14 47](https://cloud.githubusercontent.com/assets/16159220/15030486/5c2dc816-1207-11e6-8468-276a85007b21.jpg)

![screenhunter_22 may 04 14 48](https://cloud.githubusercontent.com/assets/16159220/15030487/5e38deac-1207-11e6-9649-41d053954bfa.jpg)

**Comment by mbogart24** [comment]
So I guess I found a work around... seems like a major bug to me.
I renamed _dependencies.scss to dependencies with no .scss or underscore and moved it to the 
custom/css folder which the error seemed to be looking for: 

(index):31 GET http://www.airheads.org/templates/g5_hydrogen/custom/css/dependencies 

![screenhunter_23 may 04 14 51](https://cloud.githubusercontent.com/assets/16159220/15032239/9f1bbdd4-1213-11e6-881e-b42f2039812f.jpg)

There is still a small error but it works.

**Comment by w00fz** [comment]
You shouldn't be calling your file `dependencies`, gantry comes already with a `_dependencies.scss` file which you load via `@import 'dependencies'`; This is not a bug it's by design (have a look [here](http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet#dependenciesscss)).

Rename your scss file to `my_dependencies.scss` and use `@import 'my_dependencies';` to load them, this is a SASS syntax, you need the extension on the physical file but you load it without specifying the extension `.scss` is implicit.
Also a SASS convention is the use of the underscore prefix, which identifies the file as a module, also in this case you don't specify the prefix when importing, this is why we provide a `_dependencies.scss` file and you can just import it through `@import 'dependencies'`.

I am not sure how you correlated the JS error with the dependencies files, the two things have really nothing to do with each other.

Also please edit the URL of your last post, thank you.

**Comment by mbogart24** [comment]
...at some point something in the Javascript is looking for "/templates/g5_hydrogen/custom/css/dependencies " - NO EXTENSION AND NO UNDERSCORE !
Unless that file is there I get a 404 error. It doesn't help if the file is the "correct" name

See the image for the JS error.

**Comment by w00fz** [comment]
Are you getting the error right now? I'm looking at your site, home page, and I don't see it. If you could revert it to the broken state I can take a look.

**Comment by mbogart24** [comment]
Look at new.airheads.org, our test site.
I "fixed" the main site and would rather not disturb it as there have been
so many complaints.

There you can see the case where _dependencies.scss is here:

/new.airheads.org/html/templates/g5_hydrogen/scss

and @dependencies is in the custom.css file.


Mark Bogart
Aliso Viejo, CA
949.354.2412

**Comment by w00fz** [comment]
What's in your `custom.scss`? I do see the JS issue but that seems to be caused by the `mod_responsivegallery` module, could you try disabling it?

**Comment by mbogart24** [comment]
I have disabled that module (no change)

....and attached the scss file.




Mark Bogart
Aliso Viejo, CA
949.354.2412

**Comment by w00fz** [comment]
Are you sure it's disabled? I still get the error and still see the JS loading.

```
  <script src="/modules/mod_responsivegallery/js/gallery.js"></script>
  <script src="/modules/mod_responsivegallery/js/jquery.tmpl.js"></script>
  <script src="/modules/mod_responsivegallery/js/jquery.easing.1.3.js"></script>
  <script src="/modules/mod_responsivegallery/js/jquery.elastislide.js"></script>
```

Also don't think GitHub lets you attach files via email reply :D

**Comment by mbogart24** [comment]
You were correct, it wasn't fully disabled.
Now it is. Still the same.
I just can't figure out where that 
get: http://www.new.airheads.org/templates/g5_hydrogen/custom/css/dependencies
is coming from if not a Gantry thing.


[custom.txt](https://github.com/gantry/gantry5/files/251019/custom.txt)

**Comment by w00fz** [comment]
I think the issue comes from the file [`home.css`](http://new.airheads.org/templates/g5_hydrogen/custom/css/home.css).

You have added that in the `custom/css` folder but you named it `.css`. If you want to import dependencies you need to call it `.scss` and let it be transpiled to CSS.

How and were are you loading the `home.css` file?

**Comment by mbogart24** [comment]
I was just going to mention that I have 5 custom css files in the custom/css folder and I have used
@import "dependencies";  ...in all of them.

**Comment by w00fz** [comment]
Well you can't import in `CSS` like that, only in `SASS`.

In CSS you need to explicitly pass the full filename (`dependencies.css`); in SCSS you need only the name without the extensions.

https://developer.mozilla.org/en-US/docs/Web/CSS/@import
http://sass-lang.com/guide#topic-5

Two very different things, but this is not a Gantry issue, you just need to decide if you want to go CSS or SASS for those files :)

**Comment by mbogart24** [comment]
I deleted that and it fixed it !!!
I guess that goes to my misunderstanding of scss.
Is there any need to use :  @import "dependencies";  anywhere but the custom.scss ?

**Comment by mbogart24** [comment]
Thank you so much for your help on this !
Operator trouble !

**Comment by w00fz** [comment]
The `dependencies` we provide with Gantry includes some utilities and mixins, as well ass [bourbon sass mixins](http://bourbon.io/).
Really depends what you are trying to do, by the look of your CSS files, you aren't really doing anything too complex that would require importing dependencies. 

Also note that when you import dependencies via SCSS but don't use it, it won't add any overhead to your compiled CSS files. People usually just import it at the top of their SCSS in case they ever going to need it, knowing that if they aren't actually using it nothing wrong happens.

Glad it's resolved!
