### ISSUE TITLE
customization problem gantry 5, error in the documentation.

### ISSUE THREAD

**Issue by astenio** [gantry/gantry5#1275]
Encountering
I'm no experte, I'm just studying the framework, to make sure that the degree of customization meets my projects, the documentation has a chapter talking about customizing the template, where you have the option to customize the panel sections to apply an image to the background, so far so good, I know that many would like it, especially me.

But after some tests and break a little head with the header of a project I'm testing I realized that the Section does not have its CSS> background> img, what happens is that within the section is created a new <div> with the class (section-background) which is totally different to assign an image to the background of one or more sections.

attention this only occurs if the User follow the steps of the granty5 documentation, if it does not do so this option will not exist.

![lwzfflt 1](https://cloud.githubusercontent.com/assets/7676600/15091111/4db1b018-1414-11e6-9bb0-7511cae6df08.png)

**Comment by w00fz** [comment]
What the documentation is explaining is just one of the many possible ways to customize Gantry by interacting with the twig, yaml and admin.
The approach we took was to wrap the html with a new `div.section-background` that would only show if there was an image actually selected in the section field.

This is just one way of doing it, if you want it to behave differently you can just move the logic in that twig file.

For example if you want the classname on the actual `<section>` you could edit it in the line above:

```
<{{ tag_type }} id="{{ attr_id }}"{{ attr_class|raw }}{{ attr_extra|raw }} >
```

Or you could manipulate the `attr_class` based on the `attr_background`. There are plenty of ways to achieve different effects, the documentation is just showing off one of them, so that you can get an idea of where to start looking at.
