### ISSUE TITLE
Pick RokGallery images in particles

### ISSUE THREAD

**Issue by topwebs** [gantry/gantry5#1284]
I'm concerned with the lack of support of Gantry 5 particles for using RokGallery images. Clients are used to using RokGallery to manipulate and size images and use them in RokSprocket. Many clients lack the expertise to do these things in external apps. Are there any plans to allow Gantry 5 to interface with RokGallery via RokCommon? If not, I hope some way can be found to be able to pick RokGallery images in particles.

**Comment by nicutor** [comment]
@topwebs there is already an issue opened about this: https://github.com/gantry/gantry5/issues/1027

**Comment by alisamii** [comment]
A couple of good, relatively light options to consider as alternatives to RokGallery using jQuery are:

https://github.com/tuyoshivinicius/jQuery-Picture-Cut
https://github.com/odyniec/imgareaselect

I think that a simple media manager/image cropper built into Gantry can be very useful, and allow for users to be able to remain within the Gantry component in order to do simple image manipulations.

RokGallery is useful for developing a comprehensive image gallery, and may be a good additional component, however reducing the dependence on external components (even from RT) would be beneficial...plus that fact that this feature would then be available for other platforms (such as Grav) which do not have RokGallery.

**Comment by nicutor** [comment]
+1

**Comment by mahagr** [comment]
I closed the first request because of this one has more information and discussion in it.

I like the idea of having image cropper (and automatic image resizing + retina support) in gantry itself.

**Comment by topwebs** [comment]
I still would like to advance the idea of RokGallery integration as well. Clients use RokGallery to manage images and use them in multiple places and in multiple sizes. But the gantry image cropper is a good idea too. I'm not sure which idea would be more work.

**Comment by nicutor** [comment]
This will be very helpful until another replacement of rokgallery will be made. Thanks for consideration :)

**Comment by mahagr** [comment]
In the mean time: have you tried doing this via RokBox? I think it integrates to gallery.

**Comment by mahagr** [comment]
RokGallery isn't in active development anymore. No need to have this feature.
