### ISSUE TITLE
Split a container 

### ISSUE THREAD

**Issue by elleonblanco** [gantry/gantry5#1288]
Hello again all:

I would like to split the main container in the default outline(top and bottom). How would I go about doing this?

 It would also be nice if you could create a drag and drop outline constructor so we could easily create custom outlines.

**Comment by mahagr** [comment]
Start by reading this:

http://docs.gantry.org/gantry5/advanced/creating-layout-presets

**Comment by elleonblanco** [comment]
Hi mahgar:
Will do.. Thanks for the push. Learning where to look is half the battle. :)

**Comment by w00fz** [comment]
Im not too sure what type of UI with drag and drop you are thinking of, but I can only imagine you mean creating new sections, or moving them around, since the whole Layout Manager is basically entirely drag & drop.

We purposely avoided implementing such functionality for several reasons, the main being that we want this type of interaction being a developer reserved action.

As you will notice in the docs linked above, the structure of the yaml files is fairly easy to read and reason about. The whole structure has been simplified a lot since we first launched gantry and it is now much easier to create a Layout.

A layout defines the structure of an entire rendered page, which includes sections, order of sections, containers, wrappers, classes, variations, etc. This structure alone doesn't do much except for rendering a page, it is then the template itself that takes care of styling every part of that structure, based on how a developer has decided to do.

If we did let anyone (meaning, the end-user) freely interact with the structure by easily add new sections, removing them, reordering them, etc, it would become a template developer nightmare, there are just so many possible combinations a template could behave and infinity unpredictable others.

This is what led us to prevent "easy" access to this manipulation, we want the developers to be the ones who change the structure and reorder / add sections, based on arbitrary decisions and based on what their template can support, so that they can also then style for it too.

If you are a template developer then the only way to go is through that link above, you will need to touch yaml files and most probably CSS/SCSS.

I hope this makes sense to you

**Comment by elleonblanco** [comment]
Thanks for the great explanation Djamil. Now that I know the where, the how is actually very easy. The toughest part is learning how all the parts fit together and where to look for them in the first place.
Knowing you all is priceless. :-)

**Comment by w00fz** [comment]
No problem, feel free to jump on the Gitter chat if you have any further questions!
