### ISSUE TITLE
Joomla Article Particle behaviour with sub-categories

### ISSUE THREAD

**Issue by ajduke2** [gantry/gantry5#1295]
The Joomla Articles particle allows the selection of a Category. But it does not look at articles in sub-categories of the selected category. Not sure if that is how it was intended to work or not, but it would be a good enhancement to have an additional field to include/exclude articles in sub-categories.

**Comment by mahagr** [comment]
I thought we have it already, but looks like it was not added to the final particle.

There are just so many settings already. What do you think @w00fz @newkind @hexplor?

**Comment by newkind** [comment]
IMHO it should pick up only the selected categories, not child categories etc. otherwise if you have a category and this category has child categories but you don't want them to appear in the particle you'd have to exclude them somehow etc. If you want something to appear in particle - just select it in settings.

**Comment by mahagr** [comment]
Right now there's a possibility (in our Joomla API) to include subcategories from the next n levels. That would allow us to add second option for `Include Children` for up to 1, 2 ... all levels. 

Of course you cannot mix different nesting levels, but that's not what you usually want to do. Usually you either want no child categories or all child categories.
