### ISSUE TITLE
Atoms drag & drop broken in Layout Manager (Joomla)

### ISSUE THREAD

**Issue by metska** [gantry/gantry5#1299]
Drag & drop Atoms not woking on Page settings after updating 5.2.17, but particle dragging working fine in Layout.

Gantry 5.2.17
Joomla 3.5.1
Browsers: Chrome & Vivaldi

Image: trying to drag Google Analytics

![2016-05-20 12 36 00 pm](https://cloud.githubusercontent.com/assets/2114176/15424208/0f0cf018-1e8a-11e6-8f0e-02124a6828c1.jpg)

**Comment by JoomFX** [comment]
Yeah, I can confirm the issue in Firefox 46.0.1 as well.

**Comment by adi8i** [comment]
Same here

**Comment by w00fz** [comment]
Sorry about this guys, I accidentally deleted my `w00fz/Sortable` fork branch where I was using a patched version of SortableJS, I have now forked it in `gantry/Sortable` and re-applied the patch so that this won't happen again. I also patched the packages in the 5.2.17 release to fix the problem. There are 2 ways to go about fixing this for your sites:

1. Grab the updated package from [Gantry.org](http://gantry.org/downloads). You don't need Hydrogen, just the *Gantry 5 Component* if you are Joomla or *Gantry 5 Plugin* if you are Wordpress. Once downloaded you can simply reinstall it on top of your current version and it will have the patched file.

2. Download this attached [main.js.zip](https://github.com/gantry/gantry5/files/275125/main.js.zip) and replace the `main.js` file that you find in `administrator/components/com_gantry5/js/main.js` if you are Joomla or `wp-content/plugins/gantry5/admin/js/main.js` if you are Wordpress.

Thank you and sorry for the trouble.

**Comment by szavaij** [comment]
The same problem, Atom Drag/Drop doesn't work on Page settings. I put down UIKit for Gantry 5 to its place, but now the Drag/Drop for the other Atoms it's not possible.
Gantry/Template: 5.4.11/g5_helium
Joomla: 3.6.5
