### ISSUE TITLE
Make left sidebar display below main content on mobile?

### ISSUE THREAD

**Issue by n8115** [gantry/gantry5#1307]
Is there any way to have a left sidebar render below the main content box instead of stacking on top, only when on mobile? (gantry 5 Wordpress)

**Comment by w00fz** [comment]
It is possible, the stacking is an automatic responsive behavior that Gantry uses and sets that by the CSS. You can definitely change this by applying custom CSS so that it behaves as you want.

If you inspect the page you can see the size classes are still intact and that there is a CSS mediaquery forcing all sizes to 100% width. You just need to look at tweaking that.

I would advice you to target that portion of the page only so that everything else continues stacking up as that is the default behavior and you only want to change this for a specific subset of your page.
