### ISSUE TITLE
Checkbox is not saved in Page Settings > Atoms

### ISSUE THREAD

**Issue by hennysmafter** [gantry/gantry5#1309]
So sorry to be posting a issue. I updated Gantry to the latest version 5.2.17 on a fully updated Joomla site with php 7 also latest version.

**The Problem**
G5 Admin > Base Outline > Page Settings > Add Analytics, fill in UA & Anonimity > Save.
G5 Admin > Default Outline > Page Settings > Atom Area check the checkbox > Save.
Now refresh the page or switch outlines. The checkbox becomes unchecked so it is actually never saved and therefore no Analytics is added to the frontend.

Hopefully the above is clear. If you need more details or a login let me know!

**Comment by nikola3244** [comment]
I can confirm this issue on Gantry 5.2.17 and Joomla 3.5.1

**Comment by mahagr** [comment]
@w00fz can you take a look on this one?

**Comment by nikola3244** [comment]
More info: As soon as the Analytics atom is deleted from Base outline, the atom field checkbox is checked on the Default outline (without even saving the Default outline again).

**Comment by w00fz** [comment]
This is not a bug, the atoms override becomes unchecked because the atoms values all match the ones in Base Outline, therefore there isn't any override, turning the checkbox of the atoms area unchecked.

If you check the atoms area overrides and edit the Analytics to change any of the fields value (check something else or change UA), when you save and reload you will see the checkbox sticking.

**Comment by hennysmafter** [comment]
Alright very clear!
