### ISSUE TITLE
Changing font colors?

### ISSUE THREAD

**Issue by Outernaut** [gantry/gantry5#1326]
The Gantry GUI is excellent. No issues there, but for the end user, reading it can be a challenge because light-grey (Lg) on light-grey or even white background is difficult to see on many of our monitors. Until recently, the light-grey fad or or "greyed-out" use to mean non-functional.

Light-grey on light-grey background really doesn't make any sense. Normally,m anyone looking at it the first time might think nothing will work because it is "greyed-out', or, ...'if you can't make it readable, it can't be all that good'.

Please consider making the fonts on the GUI clearer, and more succinct.  Consider, that some color-blind persons will not even see the fonts. You have a choice of 4,294,967,296 color combinations to choose from. Is grey on grey really the best choice?

I am not a GUI developer, but am an end user of Gantry and fight with my eyes to read the GUI. My last visit to the doctor showed my eyes to be in perfect condition - and my 6 monitors are all on different computers, with another comp having it's own three and the GUI is tough to read on them all.

O
p.s. Sorry to bother you all with this, but it's the only way I could find a means of communicating with the Gantry folks.

**Comment by w00fz** [comment]
Hi, this is the right place for reporting suggestions or issues of this kind.

Could you highlight in a screenshot which fonts you are suggesting to darken? Are you referring to the tabs labels?

![gantry 5 dev - administration 2016-06-01 14-07-22](https://cloud.githubusercontent.com/assets/11734/15725764/3d6b9ce4-2802-11e6-8dfa-c32133e4cf12.png)

All our fields are in cards with white background and dark grey which i think are quite readable and contrast-y

![gantry 5 dev - administration 2016-06-01 14-08-19](https://cloud.githubusercontent.com/assets/11734/15725804/67cd64f4-2802-11e6-8510-40ebce022ae5.png)

The reason for the most part we have white to dark gray colors only is because those are the most neutral colors and since Gantry is cross platform, we want to make sure it fits well.

**Comment by Outernaut** [comment]
Hi and thanks w00fz for your interest. I greatly appreciate someone taking the time to consider the changes.
As requested, I have included a screen cap with examples of un-clicked and clicked items.

![gantry-scrncap](https://cloud.githubusercontent.com/assets/19696413/15728403/02de8cee-2811-11e6-9b33-d714a98a5b07.png)

**Comment by w00fz** [comment]
I see, those are overlays applied on top of the text and input field. As you can see in your screenshot, when you click on a field you are setting it to 'override' mode, which means now you are in control of the value and you can change that `2`.

Any other value is hidden under this overlay because it's sort of "irrelevant" to the user, since it is not overriding and it's all coming from the Base Outline.

The only way to darken that text is to make this overlay more transparent, the risk is that you will then have a hard time distinguishing between the active and inactive overrides.

**Comment by w00fz** [comment]
What do you think, would this satisfy more the contrast for both the overrides and non-overrides cases? I made a tad more transparent the overlay so that the underneath text has more contrast.

![gantry 5 dev - administration 2016-06-01 16-36-20](https://cloud.githubusercontent.com/assets/11734/15729239/3547787a-2817-11e6-88d4-05fc3673934a.png)

**Comment by mahagr** [comment]
I have troubles of seeing the difference in the second image with my current monitor settings -- would it be better to make the font darker instead of making background lighter?

**Comment by w00fz** [comment]
This is with darker text, `#111`

![gantry 5 dev - administration 2016-06-02 10-48-20](https://cloud.githubusercontent.com/assets/11734/15755050/ed73c258-28af-11e6-8c26-18d837d159ea.png)

Does it make any difference?

**Comment by mahagr** [comment]
Makes a huge difference, at least to me.

**Comment by w00fz** [comment]
What about you @Outernaut ?

**Comment by Outernaut** [comment]
There is a slight improvement in the image. The words selected, 'Title' and 'Show' are both slightly darker, but I see very little difference between the 'Image' and 'Intro' and the other unchecked boxes. I don't know what it will look like 'live'. 

It is an improvement and I understand the problem in darkening them up. Amazing support. I am surprised that not a lot more people are using it. They'll come around :)

Thanks folks for the hard work and support

O
