### ISSUE TITLE
CIBuild: inheritance: "drag particles here" wells disappear

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1368]
I've started testing inheritance and this is the first thing I found. I may well be doing things incorrectly but still I don't think this is correct.

I used Sienna for testing this:
1. I created two outlines (ytest1 abd test 2) both using "home positions" preset but with all content cleared from the layouts. In test 2 outline I click on settings for "Top Main" section
2. I clicked on Inheritance tab and just change inheritance dropdown to "test1" outline and clicked on "APPLY & SAVE"
3. notice how all the "drag particles here" wells have disappeared from every section.

I don't think this can be right?

![2016-06-18_17-11-14](https://cloud.githubusercontent.com/assets/11683218/16172118/fa4f607e-3578-11e6-8501-418b20d40657.png)
![2016-06-18_17-12-01](https://cloud.githubusercontent.com/assets/11683218/16172119/fe26c138-3578-11e6-9ddd-422af65e28d6.png)
![2016-06-18_17-12-38](https://cloud.githubusercontent.com/assets/11683218/16172120/009b5c12-3579-11e6-995d-b0294e6f3946.png)

**Comment by w00fz** [comment]
Actually this has always been like this, you can test it with 5.2.18. It's not really related to the Inheritance, it's in the Save and applies to any empty grid.

Basically every time you save the empty grids get removed because we don't want those stored in the yaml file. It's just part of the cleanup.

**Comment by w00fz** [comment]
Ideally, it would be nice if this was handled in the save task rather than from the JS (like it is now), that way I didn't have to clear any of the grids before sending the data.
I agree that this is not really very convenient if you decide to continue after a save as you have to then add grids manually again.

In the end this comes down to cosmetic more than anything, it's not really a bug per se.

**Comment by mahagr** [comment]
There's no reason to keep on doing this anymore as this is leftover from the older save format. So lets fix it and make sure empty stuff won't get saved.

**Comment by marktaylor46** [comment]
Yeh I see what you mean now - but we should fix this... it's just weird as it is now and you have to refresh the page for the wells to magically reappear - from a user perspective it's not right.
