### ISSUE TITLE
Gantry 5 Particle module doesn't show the type of used particle

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#1373]
Gantry 5 Particle module should show next to the "Edit Particle" and on the green label the type of particle that was used otherwise it's very confusing and you have no idea what kind of particle is that.

![irinydun7g9u0jevmyla2fg558mjre](https://cloud.githubusercontent.com/assets/1641534/16172427/27442d48-3589-11e6-9907-2c9992342f9b.png)
![znxnnyrqrl2cpxizy220zrr6hap0t7](https://cloud.githubusercontent.com/assets/1641534/16172426/274302ba-3589-11e6-819f-091f5b4c2415.png)

**Comment by blizam** [comment]
+1

**Comment by mahagr** [comment]
I'm going to reopen the issue for the further discussion.

**Comment by w00fz** [comment]
The idea here was to have the type in parenthesis because you might have 10 particle modules of the same type but different name.
Technically is not good practice naming your G5 Particle Modules the same way as the particle name. So if you have Accordion on frontend in the Footer section and is about FAQs, perhaps a better name would be `Frontpage FAQs`, now you would notice how that makes more sense when it's `Frontpage FAQs (accordion)`.

This is why @newkind brought it up in the first place, in our RL we mostly name our Particle Modules in a descriptive way rather than associate its name to the type of particle. With a long list of particles, especially if you filter by type in Joomla, you really had no clue whatsoever about what type of particle that was, until you opened it and looked.
Searching made it a bit cumbersome than it is now.

I initially tried to have it on a second row but because Joomla uses 1 row across the whole tables, it was looking weird. Perhaps I could give it a different greyish, badge like style, instead?

**Comment by JoomFX** [comment]
@w00fz Thanks for the detailed explanation Djamil, as always :wink: 

I somehow do not like this addition, really.
I do understand your concerns, I do understand that you have a different naming approach than we do, but still I do not think it is necessary.
But this is just my opinion, my taste, etc.

I'm all-in for a better UX, but this duplicate text and this long text strings in the badge is just not to my liking.

So, this addition comes because of the way you name your particles. But then what is the Module Title option for?
In the Module Manager you will have the following:

```
Frontpage FAQs - Frontpage FAQs (accordion)
```

Anyway, it is up-to-you guys.
I do not like this, but it might be just me :wink:

**Comment by w00fz** [comment]
In the module manager you will have only `Frontpage FAQs (accordion)`, not `Frontpage FAQs - Frontpage FAQs (accordion)`

**Comment by w00fz** [comment]
Ok I see! The title repeated in the badge is an issue. I somehow missed it from your screenshot. It's supposed to be just the type.
Has this changed @mahagr ? When I first implemented this it was just `title + (type)`

**Comment by JoomFX** [comment]
Yeah, I was just about to edit my previous comment, because the Module Title option very often is rendered (if not switched OFF) on the Frontend.

But still, in Joomla there is a `Note` field in the module, which is very handy for describing what the module is about.

**Comment by w00fz** [comment]
Fine, I'll remove it. :)

**Comment by JoomFX** [comment]
:smile: 

Thanks for that, really!

But if you guys think that it'll be better for the RT templates and themes, than of course keep it.
We can just get some more opinions/votes.
Or give it some time and see what the customer feedback will be :wink:

**Comment by w00fz** [comment]
Really wasn't just for RT templates, but the way we noticed people using and naming modules. It's rarely happens that titles are repeating the feature type name.
Usually people use the title to describe it, like my example above.

**Comment by JoomFX** [comment]
Yeah, it is probably just the way I'm used to see/do things.
I'm also used to the RokSprocket module where the badge shows the type of the modue (`List`), not the actual thing (`Frontpage FAQs`).

What I'm probably trying to say is that a **Badge** should be nice and short, because it a Badge :wink:

**Comment by mahagr** [comment]
No, there has been no change after the implementation. And yes, I agree.

**Comment by w00fz** [comment]
Alright I changed my mind again :)
I'll reintroduce the feature, but not explicit text, just tooltip, so when you hover over the badge you get the `Particle Type: accordion`

**Comment by mahagr** [comment]
:+1:

**Comment by JoomFX** [comment]
@w00fz the last change of your mind is the perfect solution, I think :wink:

**Comment by w00fz** [comment]
![gantry 5 dev - administration - modules site 2016-07-05 11-28-58](https://cloud.githubusercontent.com/assets/11734/16595388/b1119b1a-42a3-11e6-9864-75b714fdd635.png)

**Comment by JoomFX** [comment]
@w00fz Can we remove the second line (Particle type) from inside the "Gantry 5 Particle" module as well? The text next to the "Edit Particle" button.

![g5particle](https://cloud.githubusercontent.com/assets/7753940/16670623/bf885bfa-44a3-11e6-92b6-0af843bf55a7.png)

I guess you left it there on purpose, but I just have to try :smile:

**Comment by w00fz** [comment]
I forgot I added it there as well, I'll remove it and make it tool tip.

**Comment by JoomFX** [comment]
@JoomFX :heart: @w00fz 
:smile:

**Comment by w00fz** [comment]
Done
