### ISSUE TITLE
CI Build: Inheritance: inconsistent use of section lock/text

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1404]
Please see the following screenshot:

![2016-06-30_11-50-47](https://cloud.githubusercontent.com/assets/11683218/16486107/5d6fe878-3eba-11e6-888c-f284bd2215c7.png)

Notice the differences in how the lock of a section is represented. One with lock only and one with lock and text. I think this should be represented consistently. My personal preference would be only to show the lock (keeping the tooltip) as there is no need to show the text.

But also note that in the one case it's shown at the bottom of the section and in the other at the top of the section - again I think it should be consistent and one or the other.

**Comment by w00fz** [comment]
Like we discussed privately, this is not an inconsistency per-se, everytime there are side-by-side sections only the lock is displayed, since you can get to a very narrow view of a sidebar. Everytime else, this is taking the full width which 99% of the time is free of overlapping and having the extra detail about what a section is inheriting from is useful.

I'm open to change to a global lock + tooltip, but I'd like more feedbacks in this regards, otherwise I'm keen to just keep it as it is, which i find more useful.

**Comment by mahagr** [comment]
I kind of prefer having it as it is unless someone has a better idea how the information should be displayed.

**Comment by w00fz** [comment]
I'm going to set this closed for the time being. Like previously said, I'm open to reconsider this later on when 5.3 is released and more people use it to see if this actually needs to be consolidated.
We can all agree that if that's going to happen, the direction is going to be all locks + tooltips.

Thanks for the feedbacks.
