### ISSUE TITLE
Problem with gantry.document.addScript() example from docs

### ISSUE THREAD

**Issue by mrak1990** [gantry/gantry5#1414]
Example of using new feature in version 3.5
```twig
{% do gantry.document.addScript(url('https://cdnjs.cloudflare.com/ajax/libs/mootools/1.6.0/mootools-core.min.js'), 10, 'head') %}
```
raise error
```
Method Timber\FunctionWrapper::__toString() must not throw an exception, caught TypeError: Argument 1 passed to Gantry\Framework\Base\Document::addScript() must be of the type array, string given, called in /var/www/87bpm/wp-content/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Template.php on line 604
```
![alt text](http://fs5.directupload.net/images/160708/7cwcg8xx.png "")

**Comment by w00fz** [comment]
Thanks for opening the issue @mrak1990 

@mahagr in the docs you mention `{% do gantry.document.addScript(url('https://cdnjs.cloudflare.com/ajax/libs/mootools/1.6.0/mootools-core.min.js'), 10, 'head') %}` as said above, it throws because the first argument is a string. 

Changing it to `addScript({ src: url('…') }, 10, 'head')` works but seems to be you either have a wrong doc explanation or the implementation is not fully working.

Can you look into it?

**Comment by mrak1990** [comment]
```twig
gantry.document.addStyle(url(...), 5)
```
works as expected

**Comment by w00fz** [comment]
You mean `addScript({ src: url('…') }, 10, 'head')` works as expected? with the `{ src: ... }`?

**Comment by mrak1990** [comment]
No, addStyle() work, not addScript()

**Comment by w00fz** [comment]
Oh I misread it, so definitely a bug with add Scripture. Thanks.

**Comment by w00fz** [comment]
This should be fixed now

**Comment by mrak1990** [comment]
confirmed
