### ISSUE TITLE
Auto upgrade to Gantry 5.3.0 and to Hydrogen 5.3.0 produced two errors

### ISSUE THREAD

**Issue by pintobuck** [gantry/gantry5#1418]
I'm using Joomla 3.51, Gantry 5.3.0 and Hydrogen template 5.3.0 (after the upgrade).

A few hours ago, I used my Gantry 5 website with no problems.

I just did the auto upgrade on Gantry and Hydrogen a few minutes ago.

Error #1 - Upgrade Hitch - I checked both auto upgrade boxes for Gantry and Hydrogen. Gantry upgraded ok, but Hydrogen 5.3.0 said it did not install, because I had to upgrade Gantry first.  My solution was run the Hydrogen update again, because Gantry 5.3.0 had already installed. Then Hydrogen 5.3.0 installed correctly.  Maybe this is a minor annoyance that you want to address, or maybe my methodology was wrong.  

Error #2 - Exhausted Memory Error -  After doing both upgrades, I received an exhausted memory error, which appeared on the front end and back end, too. I tried access my site a couple of times with the same result. My work-around was to put this in my .htaccess file: php_value memory_limit 128m
That solved the problem for me. Interestingly enough, after the problem was resolved the first time, I returned my .htaccess file to: php_value memory_limit 64m
and I had no further problems.

**Comment by w00fz** [comment]
Hello @pintobuck 
The first glitch you describe is Joomla, when you check them both it executes the upgrade in their its order and it might happen that the template goes in before than the framework.
Often times we upgrade the framework requirements for the template to match the latest one, so that you cannot upgrade a template unless you have the latest framework installed.
What you did is the right way of proceeding, I usually always first upgrade the framework and then the template.
What you see is not an issue per-se, it's by design a way of blocking you from upgrading a template when you have a version of gantry that is not supported.

Regarding the 2, it is recommended that you keep it at 128m (i have it at 512m for developing purpose), your workaround where you later reverted to 64m is only going to temporary fix the problem for you because the moment the framework needs to recompile the SCSS (this is where the memory is needed), the same memory limit will be triggered.
I suggest that you keep it at at least 128m at all times. Gantry itself doesnt require a lot of memory, but recompiling the SCSS does (Styles and custom.scss`).

**Comment by mahagr** [comment]
Most Gantry 5 themes need around 70-80MB of memory to compile all SCSS files in PHP 5.4-5.6. In PHP 7 compiling takes less memory because of the optimizations they have done.

**Comment by pintobuck** [comment]
Thank you for the info and advice. I'll make the memory change on my site..
