### ISSUE TITLE
Inheritance Enhancement

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#1456]
I love how inheritance works. It's a perfect solution to managing repetitive sections and blocks.

However, I think there is a way it can be improved.

Right now, you can inherit **from** another outline, but there isn't a way to inherit **to** an outline.

If you are in the process of upgrading a pre-inheritance template (other uses cases are also possible), you have to go into each outline and set the inheritance from within the outline.

It would be good to be able to reverse the workflow as well, by going into the Inheritance tab in, for example, the navigation section of the base outline, and directly select multiple outlines to apply the inheritance to, something along the lines of what you see in the mock-up below.

![retina_institute_of_the_carolinas___the_macular_degeneration_center_-_administration](https://cloud.githubusercontent.com/assets/1498512/16914641/71873400-4cf3-11e6-9f3e-e6bf5de47109.jpg)

It would also be good if you could remove the inheritance from here. So, for example, if you accidentally added inheritance to the **Offline** Outline, and you didn't want to do that, you could simply deselect it and the inheritance would be removed and the outline's default, pre-inheritance settings would take effect.

**Comment by w00fz** [comment]
I'm not sure I like this. All settings in an Outline, including Section and Particle Inheritance, are there specific to that Outline. What you are asking to introduce is going to break this system by introducing a delegation to external Outlines of which the current one doesn't know anything about.

While I can understand where you are coming from and that the transition to the new Inheritance is not automatic at it requires you adapt your current Outlines to it, I also think this is a one-time deal and only for pre-existing themes. Going forward you will now setup everything based upon Inheritance, leaving this request of yours out of the loop.

My suggestion is that  you make the changes to the yaml files directly, rather than trying to use to admin. It will speed up time tremendously. Do it once for one outline and see how it gets saved, then apply to the rest.

Your proposal is only ever going to be somewhat useful on the first attempt to convert a theme from pre 5.3 to Inheritance 5.3.

**Comment by mahagr** [comment]
Another issue I see on doing this is that if you make an error, you accidentally destroy all content in the target section. We already have had issues raised not being clear enough that data will be destroyed upon inheritance.
