### ISSUE TITLE
Problem with Javascript in Gantry 5 for WordPress?

### ISSUE THREAD

**Issue by GiannisZ** [gantry/gantry5#1481]
Hello everyone,

I have created my first widgets for WordPress but it seems that I have a problem with javascript in Gantry 5 Layout.

For example, I am using Javascript to show a field (Icon, Icon 2 etc) only when a select option is selected but it doesn't work on the layout tab when I select to add a widget. However, it works fine when I go to WordPress's widgets page.

Could anyone help me with this?

How it should be:
<img width="527" alt="2016-08-04 2 09 29" src="https://cloud.githubusercontent.com/assets/7051009/17385030/92049f0e-59e8-11e6-8d2e-fb3872be3c11.png">

and how it looks like on Gantry 5 layout:
<img width="411" alt="2016-08-04 2 09 05" src="https://cloud.githubusercontent.com/assets/7051009/17385037/a3d6f16e-59e8-11e6-91b2-72f3a67ec5df.png">

It seems like it ignores the js file...

**Comment by newkind** [comment]
Yes, right now custom CSS/JS coming from widgets don't work in the Layout Manager. We are aware of this issue and we have a ticket about it here : https://github.com/gantry/gantry5/issues/677

Right now the only workaround is to use Widget Position particle instead of Widget Instance and use your Widget like a regular widget until this is fixed. Sorry about that.
