### ISSUE TITLE
Disabling particles not working

### ISSUE THREAD

**Issue by dudewithamood** [gantry/gantry5#1496]
Wordpress 4.5.3, Gantry and Hydrogen 5.3.2

Particles and atoms disabled under the Particle Defaults tab are still listed under particles in the Layout tab for all layouts.

**Comment by mahagr** [comment]
Looks like its true, also in Joomla. Existing particles of that type are correctly grayed out (disabled), but the particles are showing up in the Particles list and when added to the layout, they show up as enabled.

There aren't any atoms in particle defaults (unless you have old installation and overrides for atoms).

@w00fz I think we should hide disabled particles from the particle list to make it shorter if user has decided not to use some of the particles.

**Comment by w00fz** [comment]
This was already like that, disabled particles wouldn't show up in Layout Manager. Maybe you introduced the issue when we changed to Particle Defaults? Can you have a look? Thanks.

**Comment by mahagr** [comment]
@w00fz Looks like the particles are already marked as disabled and LM says they are disabled, but they are still showing up and you can drag them.

By removing particles from the list LM breaks.

BTW: It looks like we are missing logic to handle missing particles in the layout; they are shown in blue instead of grey (I think we should use dark grey stripes and have a message that they are missing).

**Comment by dudewithamood** [comment]
Beautiful, thank you.
