### ISSUE TITLE
SCSS editor

### ISSUE THREAD

**Issue by dudewithamood** [gantry/gantry5#1498]
Feature request... for a field type that is a SCSS editor (or something like that). So rather than, say for a section, having a field for background color and a field for font and a field for font color and on and on... have one field that allows all these to be specified.

I imagine that it wouldn't need to work at an element level but to apply the styling to whatever the field related to such as a section or a particle block.

Control of what styling can be done can be specified in the YAML file where the field is defined e.g. background, text/paragraph and/or spacing.

**Comment by dudewithamood** [comment]
Something like this: http://www.cssportal.com/css-style-editor/

**Comment by mahagr** [comment]
@w00fz What do you think? I think we had another feature request for html editor.

**Comment by dudewithamood** [comment]
This would be slightly different to an HTML editor in that there would be no HTML, creating only CSS, with a little example box like in the link above. I've simulated it slightly in that I've added a textarea field to section.yaml like this:

```
    style:
      type: textarea.textarea
      label: Custom styling
```

And then modified section.html.twig with these lines:

```
{% set attr_style = segment.attributes.style|e %}
{% set attr_style = attr_style ? ' style="' ~ attr_style|trim ~ '"' %}
<{{ tag_type }} id="{{ attr_id }}"{{ attr_class|raw }}{{ attr_style|raw }}{{ attr_extra|raw }}>
    {{ html|raw }}
</{{ tag_type }}>
```

Then in Layout, in Section Settings, I insert the styling I want e.g. 

```
color: #FF0000;
border: 2px solid #6D6D6D;
padding: 4px;
font-family: helvetica;
```

**Comment by w00fz** [comment]
I think it's perfectly fine if you want to do that for your own templates as a custom field. However, I don't think this should be part of Gantry core.
It adds a layer of complexity that we don't want, it will also make themes a lot more prone to error. The user will now have unlimited access to styles right from the UI, possibly introducing issues or conflicts with other extensions or the theme itself. The admin is meant to be a simple manager for what the template developer has decided should be customizable, if we break this promise then the developers will have a really hard time trying to debug or fix issues.

The place for CSS/SCSS is in CSS/SCSS files, it only makes sense to keep that separated so that developers and advanced users who know what they are doing can deal with that. We already have a low-level attribute (Tag Attributes) that allows for inline styling, more than that I think will just get out of control.

Also, the HTML editor Matias has mentioned, is something completely unrelated to this issue.

**Comment by dudewithamood** [comment]
No worries, I will attempt to write it myself. I imagine it can make things simpler, and perhaps I didn't explain it carefully enough as there's a lot more behind my idea that's initially obvious. But I also see the perspective that Gantry is intended towards Themes and developers is slightly different to the perspective I have.

**Comment by dudewithamood** [comment]
While I think about it though, I do agree about keeping functions separate between 'developer' type users and other users (who perform other administrative functions on a website). I'm using a plugin that gives me some control over user's access to capabilities based on role but find I don't have any control with Gantry: users either have access, or they don't... should I log this as a feature request?

**Comment by mahagr** [comment]
In Joomla Gantry already follows ACL allowing you to prevent users from doing some tasks. For example if you deny user from editing menus, Gantry will not show menu manager to that user. Same is true for outlines, you can prevent user from creating (etc) them.

**Comment by dudewithamood** [comment]
That's good news, assuming it shouldn't then be too challenging to extend this to Wordpress. Will create feature request...

**Comment by dudewithamood** [comment]
Regarding creating a custom field of the type I suggested, is there any documentation on this that could help a little? I've managed to identify that I'd need to at least create the following two files but am not sure how it all comes together:

1. /gantry5/admin/templates/forms/fields/input/stylepicker.html.twig
2. /gantry5/admin/templates/ajax/stylepicker.html.twig

Thanks...

**Comment by mahagr** [comment]
There's really nothing hidden that happens; you just need to create the logic you need for the input field to render/load js/css properly.
