### ISSUE TITLE
Bootstrap affix-top

### ISSUE THREAD

**Issue by mark118** [gantry/gantry5#151]
Is it possible to apply bootstraps affix-top to the header or navigation in desktop view? Would really love that.

**Comment by kevlardev** [comment]
Were using bootstrap 2 with Joomla in gantry5 (as its what joomla uses at its core presently so we are forced to use it) so the affix top js and css assets are not available as they are a bootstrap 3 feature. There will also be a few additional tweaks necessary to get a fixed header working properly when combined with our offcanvas panel implementation. We do plan to have a tutorial in the future (as well as future themes) that will detail how to add a fixed section at the top for header/navigation use.

**Comment by mark118** [comment]
Hi Kevin, thank you for your response. Affix is part of bootstrap 2, I've used it with afterburner2 :-)
http://getbootstrap.com/2.3.2/javascript.html#affix 
I'm looking forward to further developments!! 

Regards,
Mark

**Comment by kevlardev** [comment]
Oh my mistake, for some reason i thought it was added in bootstrap3. But ya there will need to be some other considerations to make it functional in our current structure with the way the page surround and offcanvas panel work. It can be done, but will require more than just targetting a particular div. Again we do plan to document a fixed top section setup as well as have the capability in future themes.

**Comment by Omegatcu** [comment]
To be honest i don't get why you have to use Bootstrap 2 in Gantry5.
I would like to know your thoughts on that because BS2 is a mayor pain when you want to integrate any other Bootstrap 3 Extension.

**Comment by kevlardev** [comment]
Bootstrap 3 is not backward compatible with bootstrap 2 and Joomla's core component output (as well as many third party extensions) are written using the bootstrap 2 classes and expected rules. In order to properly support Joomla's output and those extensions, we have to include Bootstrap 2. We don't use any bootstrap classes or assets in our Gantry 5 base, only for the Joomla platform support (as we wanted to keep Gantry 5 itself platform and framework independent).
