### ISSUE TITLE
Responsive background image

### ISSUE THREAD

**Issue by nkorop** [gantry/gantry5#1514]
Hello!

I am trying to find a solution to make the background image for section responsive. How is it possible?

And another question... how can we put an image as background on the back?

**Comment by newkind** [comment]
Please take a look at the `background-size: cover;` property. I think that this is what you're looking for : http://www.w3schools.com/cssref/css3_pr_background-size.asp

Also read more about `z-index` in CSS, it's a way to layer different html containers.

**Comment by nkorop** [comment]
ok @newkind but where we make these changes...? In which file?

**Comment by newkind** [comment]
Depends if it's your theme made from scratch or a 3rd party. If 3rd party, I'd advise to use the Custom SCSS file : http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet

**Comment by nkorop** [comment]
@newkind it worked perfect! Thank you!

**Comment by pintobuck** [comment]
Info:
The background-size CSS also worked for me with the following limitations.
I'm using a Custom HTML particle to create an input form in my template. (Joomla 3.73, Gantry 5, Hassium template by jvgTheme.)

Custom.scss that worked best for me was:
`.class-name
{
	background: url(/images/image.jpg;    
	background-repeat: no-repeat;
 	background-size: 100% 100%;
 }`

This allowed the background image to be full sized to the Custom HTML particle's window in the front end of my template, and the background image would shrink responsively.  
The two background-size options that worked for me were:
`background-size: contain`;
`background-size: 100% 100%`;

The following options allowed the Custom HTML particle's window to shrink proportionately in my template front end, but the background image remained full sized, so that less and less of the background image was displayed as the browser window shrank. 
So, not good were:
```
background-size: contain;
background-size: auto;
background-size: 800px 200px
```

**Comment by joniale** [comment]
Example using @media request.

     div{
      width:100%;
      height:400px;
      background:url('http://placehold.it/350x150/f22/fff');
      background-size:100% 100%;
    }
    @media screen and (max-width : 480px){
        div{
         background:url('http://placehold.it/480x150/f12/fff');
         background-size:100% 100%;
       } 
    }
    @media screen and (max-width : 320px){
        div{
         background:url('http://placehold.it/320x150/e12/fff');
         background-size:100% 100%;
       } 
    }
