### ISSUE TITLE
File Picker Sorting

### ISSUE THREAD

**Issue by mr910** [gantry/gantry5#1518]
Would be awesome to have the ability to sort items in the 'File Picker' by filename, size, and date.

**Comment by w00fz** [comment]
See https://github.com/gantry/gantry5/issues/1015#issuecomment-242159151

**Comment by hennysmafter** [comment]
Would be cool to add a full URL as well.

**Comment by w00fz** [comment]
That's already possible at the twig level.

**Comment by hennysmafter** [comment]
@w00fz Can you explain how you would do such a thing. As I don't understand what you mean with `at the twig level` is this something my clients can easily do in the backend if not then it is not possible yet. As I look at how the NOOB does stuff and not the developer as developer can always do everything.

**Comment by w00fz** [comment]
No this is frontend. In the admin we use Streams, so full URL is not an option, unless you manually specify it without passing through the picker.
We won't be adding any possibility to pick a file and get back the full URL from the picker. It's just not portable and doesn't make much sense since we have Streams.
