### ISSUE TITLE
UX Suggest to gantry

### ISSUE THREAD

**Issue by saman222** [gantry/gantry5#1529]
1-Use the sticky menu for "save layout" "Recompile CSS" and ...
2-I want to add note to any block to don't confused in the feature.in this time we can set the my idea name,but it's not enough.I want to can add the note to any block or section or grid.Is it possible?

**Comment by w00fz** [comment]
We considered making the inner toolbar sticky but the problem is that Gantry is cross platform and all the platforms (Joomla, Wordpress (?), Grav) have already their own sticky menu. Adding an extra one would end up taking too much room and it's not something that really fits this design. If we get to rework the whole Gantry UI thank I think it might be possible to take that in consideration.

Regarding the notes, no this is not possible, the only thing you can do is give each particle and section a significant name. With sections it's easy because they already are unique and individual so whatever name you give is going to be unique.
For particles you just need to make sure you give a significant name to each. Most of the time you can even repeat the names. For instance if you have a Logo in both the header and footer, you don't need unique names because it's obvious thanks to the section what the Logo refers to.

We don't have any naming for blocks or grids, because it doesn't really matter.
A block is always tied to the particle so once you give a good significant name to a particle, it will refer to the block as well, by reflection.

Grids, on the other hand, are purely a structural medium, they need to be defined and they need to render but their only ever function is to wrap blocks/particles to define rows in the frontend. They don't need identification, except internally, if you need to identify them individually then there's something wrong in what you are doing. Keep in mind that you can give ids and class names to grids, by identification i mean spotting them in the yaml file. 

Grids are strictly tied to the flexbox grid approach we use, there is a hierarchy that is respected and that goes from the *section* to the content of a *particle* (`Section ➡️ Container (optional)  ➡️ Grid ➡️ Block ➡️ Particle ➡️ Content`). The Grid is always parent of one or multiple blocks and its only siblings are always other grids.

All of this to say that because the whole structure of a Layout is hierarchical, there is no reason to have notes and I don't even think it's something useful to have. Both the Admin and the layout.yaml are simple representation of what's going to be rendered in the frontend. The most significant parts of a layout are the Sections and the Particles. Grids are also very volatile, they can be sorted, they get completely removed and lost when they are empty or dynamically generated as you add a new one in a Section, notes would be very unreliable on them.
