### ISSUE TITLE
force layout manager to check and correct wrong % settings loaded from yaml file?

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#153]
in _joomla_-_gantry4.yaml i changed:
```
top:
  container:
    - [position-top-a 33.3,position-top-b 33.3,position-top-c 33.3]
```
to
```
top:
  container:
    - [position-top-a 33.3,position-top-b 33.3,position-top-c 33.3,position-top-d 33.3,position-top-e 33.3,position-top-f 33.3]
```
the % add up to 200% on purpose, cause i wanted to know what happens :)

when reloading this layout in the layout manager, the %es are taken over as they are, meaning they don't correctly add up to 100% as they should. on frontend the modules will display fine for now though.

when you now delete one or more of the top particles within the layout manager, the % do not get corrected and depending on which of the particles you've deleted first, there seems to be a very narrow particle either at the very left or very right of the top section, which will also cause issues on the frontend.

so i was wondering if there is a way that the layout manager can check and recalculate % loaded from a yaml file if they are not correctly adding up to 100%.

it appears that the only way to get the layout manager to recalculate the % correctly is by using the 'equalize the widths in the blocks' option for the top section

![g5_layoutno100](https://cloud.githubusercontent.com/assets/5719486/7399877/8922327e-ee7e-11e4-9e11-a867763843e0.jpg)

**Comment by w00fz** [comment]
We are aware of this and discussed this issue at some point before. 

Let's start by saying that what you are doing there (editing the presets yaml / creating new presets) is something considered advanced.

When we added the ability to easily create layouts simply like you did there, it was really meant for development purposes only. The true output of a layout is WAY more complex than these presets ([example of a fully saved layout](https://github.com/gantry/gantry5/blob/develop/themes/hydrogen/common/layouts/home.yaml)), in fact these presets are limited to only structure and sizes and their solely purpose is to help getting started with a new preset layout structure.

The preferred method should always be to change attributes, sizes, ordering and such via admin, unless you know what you are doing (which I know you do, I'm just saying as a rule of thumb in general :wink:).

With that said, we decided that the amount of code involved to prevent issues like this from happening wasn't really worth considering this is meant for advanced users only and it can be easily prevented by simple math addition operations (a row must always match 100%).

It would be nice if we could normalize a manually created layout but it isn't a simple task at all. Imagine having a row with all the sizes different from each other: `20 | 30 | 80 | 10 | 5 | 95 | 22`, how would you even normalize that? We have no way on knowing what you really meant it to be and equalizing something like that is definitely not going to be what the user would have expected, otherwise the user would have used same values for each of them.

I think the fact that the LM breaks is a good thing in this case, it will alert the developer that something is not right and leave him to figure out what has been done wrong and correct it, rather than Gantry trying to correct it.

**Comment by kat05** [comment]
that makes total sense. :)
