### ISSUE TITLE
Gantry 5.3.4 hiding menu item are visible

### ISSUE THREAD

**Issue by Tigor68** [gantry/gantry5#1532]
Joomla 3.6.2
When I've update from Gantry 5.3.2 to 5.3.4, I see my hide element of menu (disable at Template -> Menu Editor). All my efforts was failed.
What's happend?

**Comment by mahagr** [comment]
Did you try to save it again?

**Comment by Tigor68** [comment]
Of course, I've switched on/off many times with saving and recompilations. But nothing happend

**Comment by DanGthatRokGallery** [comment]
I can confirm this on J362 with Gantry 5.3.4 using the Citadel and Photon templates.
Prior to this Gantry 5.3.1 would delete the de-powered menu items <li> statement and it properly would not take up any space on the nav bar.
Gantry 5.3.4 on the other hand leaves the <li> intact and issues two CSS statements:
display:none;visibility:hidden however the display:none is then overridden by a display:inline-block statement.

**Comment by marktaylor46** [comment]
I confirm this as a big issue too. Basically if you change the mobile menu breakpoint to a larger value that normal then the area containing the "normal" desktop menu should collapse completely and not take any space. e.g. logo 20% menu 80% should result in logo 100% when the menu changes from desktop to mobile... but it does not anymore, what happens is that a "hidden" class get's add to the "80%" g-block and the logo g-block get's left as "size-20" - this did not happen in Gantry 5.3.2.

**Comment by w00fz** [comment]
I'm not sure what the issue is, the only SCSS differences from 5.3.2 to 5.3.4 are RTL related, everything else has to do with Grav or admin SCSS. There is no menu particle changes, there are however Menu class changes which don't look related to the problem at all.

I'm not seeing anything that could have changed that behavior, to me it looks like it should behave exactly like it always did. Please have a look at the diff between https://github.com/gantry/gantry5/compare/5.3.2...5.3.4, perhaps you guys can spot something useful that might have triggered this.

Thanks.

**Comment by kat05** [comment]
There are also new threads in the RT forum about the same issue.

**Comment by DanGthatRokGallery** [comment]
Hi Djamil
"I'm not sure what the issue is, the only SCSS differences from 5.3.2 to 5.3.4 are RTL related, everything else has to do with Grav or admin SCSS. "

It has to be more than that. When I run 5.3.1 I select the Home menu item to Disable than on the Front End the entire <li> for g-menu-item101 is GONE, i.e. NOT generated in the page output at all. So I would think that would be something other than CSS or SCSS.

**Comment by w00fz** [comment]
Really there's nothing more than the files changed as I linked above, nothing else magical happens.

**Comment by w00fz** [comment]
@JoomFX made me notice that there are a couple of issues here that got mixed up.

1. Disabling a menu item from Gantry's Menu Manager still displays it on frontend (**this is a legit bug and I can reproduce!**) // reported by @Tigor68, @DanGthatRokGallery, @kat05  
2. When the menu moves from desktop to offcanvas, the menu position is still visible, meaning that any siblings particles still maintain their size, ie, [ logo 20% | menu 80% ], when menu goes in offcanvas, logo retains its 20% size. (**this is not a bug, has always been like this and it is working as expected**) // reported by @marktaylor46 

I'll look at the issue **1** as that's what's been reported and definitely a legit issue. I'm sorry I didn't see this before, I got side-tracked by Mark's other issue which is not related to this one at all!

**Comment by w00fz** [comment]
Ok this is fixed, please try the latest CI Build as soon as my last commit is green.
