### ISSUE TITLE
1.1.4 Timber Update

### ISSUE THREAD

**Issue by mr910** [gantry/gantry5#1542]
Updating Timber to 1.1.4 causes the following error in WordPress

**Template "@nucleus/page.html.twig" is not defined in "partials/page.html.twig" at line 1. 
/wp-content/plugins/gantry5/src/vendor/twig/twig/lib/Twig/Loader/Chain.php**

**Comment by mahagr** [comment]
Looks like Timber did backwards incompatible API change on a bugfix release.

https://github.com/timber/timber/compare/1.1.3...1.1.4#diff-2b463b80d9628e49eecc8b4821f1ea15L115

The fastest way to fix the problem is to go back to Timber 1.1.3 while I'm looking into a workaround/detection for this issue.
