### ISSUE TITLE
Inheritance issue

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#1544]
Hey guys,

I noticed a strange behavior in G5 when "Default" inherits from "Base".

The installation where I noticed the issue uses a template installed with the new installer (if that matters).
Basically, when I do some changes to the Layout YAML file, reload it in "Base" and save it, the changes are not automatically reflected in "Default". Here, [this video](https://youtu.be/2kS85C-ECuk) shows the issue (sorry Matias, I know I could have shown the issue in a 30sec video :smile: ).

In order to apply the changes to "Default" I need to re-select the inheritance, see [this video](https://youtu.be/TIsKmAgxpMA) (sorry, forgot to record it in the first video :smile: )

**Comment by mahagr** [comment]
This is expected behavior. Even if base gets inherited by default, they are not the same layouts. Inheritance only affects what's inside of the section, not the whole layout.

Default is not a special case, it acts just like any other template style out there. In fact you can assign any template style as being your default. Or multiple at once. Think of multi-language setup where you have English, German, Spanish etc..

**Comment by JoomFX** [comment]
Alright, I see. Thanks Matias.
I just wanted to let you know, so if it was a bug you are aware if it.

Yeah, I know about "Default". We've discussed "Base" and "Default" many times ;)
