### ISSUE TITLE
Particle collections: Can we have option to disable one of the items?

### ISSUE THREAD

**Issue by newjie** [gantry/gantry5#1550]
For example, in custom css/js atom, while debugging, sometimes I'd like to temporary disable one of the scripts, but I have to remove it. To add it back, I have to input everything again. For this atom, reinput everything for an item is fine, but in other occasions where the item has a lot of information in it, like owlcarousel or other slideshow particle, reinput everything will be painful. So I think a "disable" button, like the one for a section, is needed for collection items.

**Comment by alisamii** [comment]
I second this.

I was thinking of adding exactly this idea because it can be a real advantage to add disabled items in collection lists. Sometimes it is for debugging. Other times it is because the item should not be published before a certain date, or may be published on and off, so being able to enable/disable is very useful.

**Comment by mr910** [comment]
Great idea!

**Comment by w00fz** [comment]
This is something that should happen from the field itself. It is already possible right now without any Gantry modification.

If you add a new `enabled` field in your item blueprint, you can then toggle each item individually to be enabled or disabled. In your twig, then, while looping through all the items, you can look at the `enabled` value that's been stored and skip it if it's disabled.

This is not something we can control internally via Gantry because we don't know anything that is happening inside the Particle twig. The Particle is responsible for cycling through all the items and render them, which by reflection makes it also responsible for handling scenarios like the one described by you.

**Comment by mahagr** [comment]
The only place where this is missing is in the collection itself. This has been brought up before; people want our collection widget to have support from doing this from the list level.

**Comment by alisamii** [comment]
Once again, I agree.

Something like this:

![screenshot 2016-09-06 11 23 04](https://cloud.githubusercontent.com/assets/1498512/18268524/721d66ac-7424-11e6-96c5-4de7f4c4c441.png)

**Comment by newkind** [comment]
I kinda agree that this would be useful, although i think that the icon should be the first one on the list (before the trash can).

**Comment by nicutor** [comment]
+1

I've added an .enabled field on each collection.list item in order to fix this.
