### ISSUE TITLE
input.range settings for particles not cleared when override disabled

### ISSUE THREAD

**Issue by dudewithamood** [gantry/gantry5#1551]
In Wordpress, when editing input.**range** fields in particle settings and 'enabling the override' is disabling/turned-off for one of the options, I would expect if to revert to particle defaults as set for the base outline (as it does for other field types).

What happens is that it retains the override value once saved.

**Comment by w00fz** [comment]
This seems to be working just fine for me. Here is what I did:
1. I have a `min: 0`, `max: 100` and `default: 50` in my blueprint.
2. I go in Particle Defaults in Base and change the field value to something like `80` and save.
3. I go in an Outline -> Layout, I load the settings and I see the field is inheriting `80` from Base.
4. I click the field to override and change to something like `20` and apply & save
5. I edit again the field and I see my `20` is preserved as well as the override option enabled
6. I uncheck the override and apply & save
7. I edit again the field and I see it is now inheriting from Base with `80` value.

Am I missing something? This is the expected behavior.

**Comment by dudewithamood** [comment]
7 didn't happen for me. This is on my localhost... I checked on a live site and it worked perfectly... going to investigate further and see what could be different. If it's just my localhost I'll close.

**Comment by dudewithamood** [comment]
I deleted the particle YAML under custom/config/default/particles - the problems gone and I cannot reproduce. Sorry for wasting your time on this one - I could have checked more thoroughly.

**Comment by w00fz** [comment]
No worries 👍

**Comment by marsivo** [comment]
nectify.com

**Comment by marsivo** [comment]
http:\\nectify.com
