### ISSUE TITLE
Color of navigation icon on mobile

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#158]
When the background-color of the header section is white, the navigation icon on mobile devices take the same color and is not visible.
![gantry5b4-toggle](https://cloud.githubusercontent.com/assets/3976174/7411405/07adcec8-ef38-11e4-8e9a-266517549f6c.png)
Suggest to change the color value from **_offcanvas.scss**
<code>.g-offcanvas-toggle {
	font-size: $core-font-size + 0.5;
	color: $white;
}</code>

**Comment by Omegatcu** [comment]
hmm make the default the font-color - that should do it for almost every case.

**Comment by mariantanase** [comment]
i removed the instruction <code>color: $white;</code> from **.g-offcanvas-toggle** class and now it works.

**Comment by kevlardev** [comment]
Ya the toggle is a bit tricky as it doesn't reside in any particular section but at the top of the page surround. It can end up being on top of any background or any section depending on a layout and there is really no way to control it based on the section color its on top of (since its not a child of those sections). I think im going to have to make this a colorchooser parameter that is set along with the offcanvas panel options so that users will have full control over what color they want the toggle to be.

**Comment by kevlardev** [comment]
New configuration option added in a5205befae28f14b4b2e6ca28df2a6f981f9d830
