### ISSUE TITLE
add styling for basic g4 module suffixes

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#159]
i think it would help a great deal if basic suffixes such as box1-4 and title1-4 as well as the icon suffixes would be made available in g5 templates. 

![g5_modulesuffix](https://cloud.githubusercontent.com/assets/5719486/7416776/53714ca6-ef27-11e4-82cf-520837635d56.jpg)

**Comment by w00fz** [comment]
If you check in the block tab of the particle there are Variations you can pick from. Way more user friendly than in G4 as you get the whole list available in one dropdown and you can mix and match (at your own risk :smile_cat:).
Although if they have been all styled accordingly, that I don't know :)

**Comment by kat05** [comment]
i'll try that. :) i was only wondering if there was a way to make it work for regular joomla modules, which are already set up on a g4 site. if people than start using a g5 template and just load those modules in, then it would be great if those suffixes would work out of the box instead of having to use the block settings.

**Comment by kevlardev** [comment]
Unfortunately with the way our blocks work in the layout system, the old joomla module suffix approach wont work properly for things like box / title, though it will still work fine for other accessory suffixes like icon, etc. We have box and title suffixes set up in the layout manager prepopulated, i didnt add icon ones as there are literally hundreds of possible ones and it would be out of control. Instead, i was looking at doing an iconpicker approach but still have to sort out the best way to present it.

**Comment by kat05** [comment]
are suffixes like nopaddingall or nomarginall supposed to work for regular joomla modules? at the moment they do not it seems. iconpicker sounds great! :)

**Comment by kevlardev** [comment]
No, all the margin and padding for blocks in the layout wrap the modules (or particles or whatever other content there is), so anything that effects or negates those has to be applied to the blocks as well. The approach now is to use the layout manager to apply block level effects (margins and paddings, background color effects for "blocks", etc). This is also platform independent and so these block suffixes will work on any type of content rather than just joomla modules.
