### ISSUE TITLE
Location of new images via image picker

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1597]
as discussed with @mahagr 

JOOMLA:
New images added via image picker should not be put into /templates/xxxx/custom/images but instead should be added to JROOT/images This is required because of the scenario where multiple Gantry 5 templates are used for a single site without this change a particle can be looking for the image file in the wrong template.

It would also be nice if we can fix this for installations where the image files have already been put in the "wrong" location.

**Comment by mahagr** [comment]
Old files aren't affected by the change. I don't think its safe just to copy everything from `[theme]/custom/images` into upload/images folder.

**Comment by w00fz** [comment]
This looks like a breaking change, custom folder now is not so portable anymore if uploads go outside the theme scope.
Also how does this behave with overwrite of files? Looks to me this nukes completely the safe-overwrite of uploads we had in place where uploading an image that already existed in the platform or theme would never be truly overwritten, thanks to the custom folder.

I don't approve this change ☹️

A better solution should have been defaulting the file picker to `gantry-themes://hydrogen/images/..` instead of the current theme `gantry-theme://images/..`

**Comment by mahagr** [comment]
Well, the change should be alright as long as you doesn't have the same file in both uploads and theme.

I don't agree putting files into custom folder anymore, its total pain which I learned while porting Gantry to Grav. It just doesn't make sense to use different save location than the system does by default as its really confusing for the poor user who is assuming that every upload goes into a single location.

If I had to do this again, I would have 2 streams configured to the file picker by default:

* gantry-media://
* gantry-theme://images

And let user to pick which one to use.

**Comment by marktaylor46** [comment]
http://screencast.com/t/MtbNhBkVIn

video above of issue

**Comment by gyvermac** [comment]
2 streams seems to be the right choice. One in JROOT/images an the other in the theme (where you put images that are specific to the theme).

**Comment by mahagr** [comment]
I'm actually going to add a new configuration option for this. Reopening.

**Comment by mahagr** [comment]
For backwards compatibility, I chose to implement configuration option which allows users to pick up which location they want to use (defaulting to the old behavior).

**Comment by marktaylor46** [comment]
Where is this configuration option please? - and shouldn't we have G5 docs updated too?

**Comment by mahagr** [comment]
Its in the plugin settings (all platforms).

In Joomla `System - Gantry 5`, in the rest inside the Gantry 5 plugin.

@FrugalGeek ^

**Comment by kat05** [comment]
This works fine for me now in latest CI.

**Comment by dudewithamood** [comment]
Oh yay - happiness! Thank you...

**Comment by topwebs** [comment]
Why can't the configuration option to pick the image file path be in the image picker? We would like to store some standard images in the template and the rest in the Joomla images folder. The switch should be in the image picker, not have to find a system plugin and toggle back and forth all the time.

**Comment by mahagr** [comment]
@topwebs Its actually something we had before in file picker (allowing you to choose location in there), but got rid of because of using a single stream seemed to be a better option. Right now the option in Gantry kind of does just what you want.. Kind of..Unfortunately the option has a side effect if you have overrides as it changes lookup ordering, so files with the same name will be switched around every time you change the setting.

Personally I would store the files into a single location only, but as there seems to be disagreement where the location should be (theme vs uploads). Its also hard to change this now as so many existing sites may break on change like this.
