### ISSUE TITLE
Gantry 5 Back-end should let ppl to choose link color and link hover color

### ISSUE THREAD

**Issue by newjie** [gantry/gantry5#1626]
I think these two colors are the essential accent of the page. Currently, in Base Outline's style page, we can set accent color 1 as link color, but no where to choose link hover color. And by default, it is a:hover{inherit}, it looks a little weird to me, so every time I build a new page I have to write some custom css for hovered link color. I think this should be included in the back-end setting.

**Comment by JoomFX** [comment]
Hey @newjie ,

I do believe that the way it currently is, is the best and optimal one.
I do see people opening issues for the link hover color, for the menu hover color and for other minor styling adjusts. So yeah, you are not the only one.

But guys, there simply cannot be options in the Admin for whatever each and every one of you want. It will bloat UI and it will bring unnecessary confusion and as a whole - it will give a worse UX. The simple (the less options), the better.

The link hover styling and the menu hover styling are a theme/template decision. If you want to change/customize it just use the [custom.scss](http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet) file. There is absolutely nothing wrong in adding custom code to the custom.scss file, that's why it's there.

There simply shouldn't be Hover styling options in the Admin. Consider the following example - imagine that there is a "Link Hover Color" option in the admin. And you choose it to be Green. But then imagine that you have a Section that has the same Green background - then, when the user hovers on a link in this Green section, the text will become invisible as it will have the same color as the section background. And then again, in order to fix this you will need to use the custom.scss file in order to change the hover styling of the link only for this particular section.
Another example - some people might not want the link to change its color on hover - they might want the link text to become underlined or whatever.

What I'm trying to say is that the hover styles are something quite specific and whenever the user wants to customize them, he just needs to use the custom.scss file.

**Comment by mahagr** [comment]
I agree with @JoomFX. 

First, all of the styling options are controlled by the theme, not Gantry (with the exception of Hydrogen and Helium which are considered to be part of Gantry), and its really template designers decision which aspects he/she wants users to be able to change from admin. 

Second.. I agree that people really, really want to change link colors and it fully makes sense to change (lets say) brown links in a blue site to match the rest of the site. I'll discuss with our designers of the possibility to add the option.

**Comment by johncarter-oz** [comment]
I really respect the contributors who have made Gantry 5 what it is today. That said, this suggestion of setting hyper-linking colors... but for those using the Helium template and because it is free, many people will start with it (like me). I found it difficult because the accent colours were used as the colour overlays on the underlying image. So lets say you choose white for the 1st of your accent colours, then the image will have a whitish overlay fading in towards the bottom left of the block. Any white text (yes the hyper link will be white) is not going to look good against the background image....
Of course, @JoomFX is quite correct in saying it can be added to the custom.css file but for newbies (and I am still a little new to this) it is an extra layer of difficulty where most of Gantry 5 is so easy to use straight out of the box (so to speak) which is what makes it so attractive and as we get more experienced we can do amazing things with it.
So I would like to put my vote forward in favour of adding hyper link coloring in the Gantry admin.
Thank you

**Comment by newkind** [comment]
Added link color options in theme settings.

**Comment by mahagr** [comment]
:+1:

**Comment by johncarter-oz** [comment]
@newkind you are one of a kind! Thank you so much. I am really loving Gantry 5 and the community is better than any other community!

**Comment by newkind** [comment]
lol no problem ;)

**Comment by khatwanir111** [comment]
Hii Thanks for the latest update!! @newkind I can't see Link color settings anywhere in Theme setting!! I am on Wordpress!

**Comment by newkind** [comment]
Have you updated properly your theme? Settings should be right next to the accent colors.

**Comment by khatwanir111** [comment]
@newkind look at the screenshot attached!
![img_20170406_124326](https://cloud.githubusercontent.com/assets/13481700/24742252/15114038-1ac7-11e7-8bc7-9d0029280c82.jpg)

**Comment by newkind** [comment]
For me it looks like you haven't updated Helium theme. The change is in theme not the Gantry plugin.

**Comment by khatwanir111** [comment]
I had updated both the plugin and theme. Look at the top of the screenshot you can see the version on Helium v5.4.11 @newkind

**Comment by newkind** [comment]
Please clear the cache in Gantry and other caching plugins that you might use. 
Other thing is wheter you updated all of the required files in theme? Blueprints? SCSS?

**Comment by khatwanir111** [comment]
I tries to clear cache in Gantry and I update all the files, Here is how I followed. Extracted all the files of latest Helium theme and then uploaded all the files to my server and overwrite all the files at ..>wp-content>themes>helium> . The only extra folder in old theme was "Custom" folder and it is as it was now. Correct me if I had followed any step wrong. The link color option still not showing @newkind . Thanks for helping!!

**Comment by newkind** [comment]
That's correct. I'd have to check your site and ftp to see what could be the issue. If you'd like me to do it, please ping me on Gitter.

**Comment by khatwanir111** [comment]
Thanks for Helping! @newkind I actually deleted g5_helium folder and reuploaded the folder and It's there now besides the Accent color. Just to be sure can you Guide me some proper steps for updating theme in future updates and handle with custom folder!

**Comment by newkind** [comment]
Your steps were fine. Not sure why it didn't appear. It's as simple as replacing everything in theme besides `custom` directory.

**Comment by xoomserve** [comment]
Hello newkind,
First of all, I would like to thank you and all the others who are supporting this unique work.
When I say, unique, I mean it exactly as its look like.

My issue, is to add the same color picker for the link ONLY inside part of the layout (Footer for example) and I already did it with your great Gantry 5 documentation.

But, How to assigne it to the a:, a:hove & a:visited?

I added this part in my /custom/blueprints/styles/footer.yaml

`    regular:
      type: input.colorpicker
      label: Link Color
      default: "#4db2b3"`
But it does nothing and only I got the box for color inside my Admin dashboard.

The full code for the footer is:
`name: Footer Colors
description: Footer colors for the Hydrogen theme
type: section

form:
  fields:

    background:
      type: input.colorpicker
      label: Background
      default: "#ffffff"
    text-color:
      type: input.colorpicker
      label: Text
      default: "#666666"
    regular:
      type: input.colorpicker
      label: Link Color
      default: "#4db2b3"`

Would you please just advise me how to fix my issue?

Thank you,
Tariq
