### ISSUE TITLE
Home outline loses it's ability to render after updating to Joomla 3.6.3

### ISSUE THREAD

**Issue by prototype2118** [gantry/gantry5#1634]
Upon updating to Joomla 3.6.3 with the ambrosia template (ver 1.1.4) the default outline renders on the homepage even though the home outline is assigned to the home menu item.  Duplicating the home outline and reassigning has no effect, clearing the cache on both joomla and gantry has no effect, and recompiling the css has no effect.  No matter what is done, you cannot get the home outline to render on the home menu item.

Question is, why won't joomla or gantry let the home outline render properly when it is correctly assigned in the gantry 5 template manager component and also correctly assigned in the menu setting and template settings within joomla?  This behavior was not observed in any previous versions of joomla and of course no other plugins were installed or updated.

If you go into joomla template settings and assign the home outline for all pages and make it as if it was the default outline, then the homepage will render with the correct outline.  But this is obviously unacceptable because then every single page of the site will render with that home outline as well.

**Comment by marktaylor46** [comment]
Please see https://github.com/joomla/joomla-cms/issues/12499

More on RT site if you are a member http://www.rockettheme.com/forum/gantry5-for-joomla/264092-joomla-3-6-3-update-template-assignments-not-honored

**Comment by mahagr** [comment]
Yeah, this one is a tricky issue for sure.

There are no bugs in either Joomla or Gantry, but a change in Joomla CMS API does make the issue to show up. Recent version of Joomla added possibility to add custom preprocess rules for the router in https://github.com/joomla/joomla-cms/pull/8986. Unfortunately this change basically breaks the tradition that `router.php` file only gets called when the component is active. It causes a lot of issues with many components having their logic in that file (= bad coding practises).

The only way to fix this issue is to uninstall the offending component or waiting author to fix their router code. Unfortunately finding the component that breaks on Joomla 3.6.3 may be tricky as the only way is to create a test site and remove components one by one until the issue goes away.

PS. Please report bug to the author of the component once you find out which one was causing the issue. With the change in Joomla logic, its very important that no code (includes included) gets run outside the functions in that file.

**Comment by prototype2118** [comment]
Thank you @marktaylor46 - We had both adsmanager and djclassifieds installed.  djclassifieds had us comment out the "JHTML::_('behavior.modal');" in /administrator/components/com_djclassifieds/lib/djcategory.php and we completely uninstalled adsmanager as per your post on the RT forums.  Problem has been resolved now.
