### ISSUE TITLE
Duplicated template doesn't show

### ISSUE THREAD

**Issue by karbal1** [gantry/gantry5#1677]
Hello,

I am using Gantry, Helium, template for my new website... I duplicated the template so that I can use different lay-out for the different pages.
When I choose the templatestyle in my menu manager, nothing happens... even when I choose a complete different style (a joomla template)
Does somebody can thing what I did wrong?
http://bit.ly/2fquc71

Thanks in advance!!

**Comment by mahagr** [comment]
Check if you have the same issue when setting template style to Protostar.

I'm aware of two cases when template styles stop working in Joomla:

1) you have a plugin that checks template style too early (or uses JHtml call, which basically does the same)
2) you have Joomla 3.6.4+ and you have installed a component with broken router (same issue as with 1)

**Comment by karbal1** [comment]
Hello,

Thanks for the quick answer and the support!
Yes I have the same issue with Protostar, the contactpage is now set to protostar but doesn't show it...
I checked the plugins but I don't find one who could cause this problem...
I don't have a broken router neither...

**Comment by mahagr** [comment]
This issue is really, really hard to track down. As I said, its always either a system plugin or a component causing it.

Plugins can be disabled to check if style gets assigned properly after disabling, but unfortunately current version of Joomla has a bug which makes checking components hard. Basically its not enough to disable components one by one, but you need to uninstall them. So take a backup from your site and create test site from it. Then just start uninstalling components until you find the one causing the issue. Or if you have no content yet, just go ahead and uninstall stuff..

**Comment by karbal1** [comment]
Hi, after searching for a while I found the plugin that caused the issue... It was jck modal... It works fine now! Thank You!

**Comment by mahagr** [comment]
Good that the got solved, I'll close this issue.
