### ISSUE TITLE
Feature Suggestion: Container Inheritance

### ISSUE THREAD

**Issue by brandonchance** [gantry/gantry5#1679]
I'd love to see "Container Inheritance" in the future. Just spend a few minutes trying to figure out why the size of a section wasn't changing, even though I was modifying it in the Base Outline; then it dawned on me that there is no inheritance for split sections.

Wordpress 4.6.1  |  Helium

**Comment by mahagr** [comment]
Can you add screenshot to point out what exactly you're thinking?

**Comment by brandonchance** [comment]
Sure! Here's a visual for the reason I think the enhancement would be helpful. (So when you modify the width of the blocks inside the container, that information would be passed to other pages. The 2 sections shown in the picture are being inherited on another page, but not there width or container classes
![image](https://cloud.githubusercontent.com/assets/15754732/20354632/cae49a9e-abec-11e6-83de-fea3c5ffb792.png)

Potential solutions could be either adding an inheritance tab, or just adding the inheritance options to the options that are already there.
![image](https://cloud.githubusercontent.com/assets/15754732/20354623/c350fbba-abec-11e6-8b85-65b0567d34bc.png)

Hope this helps, let me know if any of that didn't make sense!

**Comment by mahagr** [comment]
Got what you're trying to say..

Inheriting container is a bit troublesome, which is why we left it out in the first place. First most containers aren't named, which makes it impossible to inherit them. Second what you're trying to resize are blocks inside the container. If you look into settings of sections, block size isn't inherited as same section can be present in multiple different configurations (fullwidth, with sidebar, with 2 sidebars etc).

**Comment by brandonchance** [comment]
Ah, I think I understand. So even if IDs were added to the container, inheritance would have trouble grabbing information from the children/child size?

**Comment by mahagr** [comment]
Yes, as the size information isn't stored into container but into the section. The issue is that the same section can be elsewhere in another layout, so there's really no way to know what you'd want to do. At least of what I can think of..

**Comment by brandonchance** [comment]
Ah okay, I see.

Just to give you ideas in the future, could the container act as a middle-man for the information? Pulling the information from the child size & storing it in itself, and then pushing the information from the container to an inherited container?

Like so:
![image](https://cloud.githubusercontent.com/assets/15754732/20359126/73e36580-abfc-11e6-9081-5ba591faf06b.png)

**Comment by mahagr** [comment]
What happens if you have container with left|content|right and inside inherited layouts you have only left|content and content|right.. Or if your default is missing one of them and child has both?

**Comment by brandonchance** [comment]
I was thinking the container inheritance would grab all child information, so if the Base Outline container has "left|content|right", the inherited layout would get left|container|right and any content that was in the Base Outline container

**Comment by mahagr** [comment]
Which is why I asked how to lead with the other two cases when its not true..? The issue here is that its hard to make this logic to work when things you assume aren't true. Also adding extra logic "look ahead" slow down the page load, where the logic is really simple right now (inherited stuff just gets cloned).

**Comment by brandonchance** [comment]
Ah, I understand now. I'll think on it, and if I figure out anything I'll reopen the thread! Thanks for helping me understand the issues surrounding this; it opened my mind a good deal!
