### ISSUE TITLE
per outline custom scss

### ISSUE THREAD

**Issue by shoulders** [gantry/gantry5#1692]
I can see the need for an outline specific custom scss (ie custom_19.scss) whilst keeping the normal custom.scss

it has been mentioned here #76 in passing but I thought I would just add it as a proper issue for feedback etc..

**Comment by marktaylor46** [comment]
You don't need a per outline CSS file because you can qualify your CSS statements to make them outline specific. There is a class on the BODY tag of the page of the form "outline-999" (where 999 is the outline ID that is being used). So you can use this in your CSS selectors to make a CSS statement only apply to a specific outline. 

Similarly you will also find a class on the BODY tag of the form "itemid-99" which tells you the menu item ID that is being used. So again you can make your CSS page specific by using that in your CSS selector too.

Regards, Mark.

**Comment by dudewithamood** [comment]
I see potential benefit in loading styling only when it's needed - perhaps a per layout custom.scss is not the ideal way to go but styling per container/section/block as mentioned in #974 is working for me.

**Comment by marktaylor46** [comment]
I don't see the need for this at all. Creating lots of "page" or "outline" specific files seems to me to be a maintenance nightmare for the few bytes of download time you might potentially save (which would be indicernable in a real-world response time). You should just uses the classes that I mentioned above to further qualify your CSS statements. Nevertheless, if that's what you want you can already do it now on the "page settings" tab of your outline you can add a CSS or JS file as an asset or you can add a custom CSS/JS atom.

**Comment by mahagr** [comment]
This feature is now implemented, though not by fixed SCSS file, but by adding support to add SCSS files just like you would add CSS files into your pages:

- Allow custom SCSS files to be inserted from particles and atoms by `<link rel="stylesheet" href="particle.scss" />`
- Allow custom SCSS files to be inserted from both `Page Settings` / `Assets` / `CSS` and `Assets Atom`
