### ISSUE TITLE
A second menu will not go inside offcanavas on mobile view

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#170]
Here is an example with 2 menu particles, first one is placed in header and second one in navigation. On mobile view only the first one from header section will go in offcanavas, the second one will still be there. You can see in the pic. 

I was wondering how this should work. @kevlardev 

![2](https://cloud.githubusercontent.com/assets/9744973/7441149/f423da34-f0e3-11e4-80ea-7d9e272113f9.PNG)

![1](https://cloud.githubusercontent.com/assets/9744973/7441150/f7b895c2-f0e3-11e4-9c1b-92e1b91ef2e0.PNG)

**Comment by w00fz** [comment]
Yes this is intentional in Hydrogen. Only one menu is tied to the auto placement into the offcanvas section. Since we wanted to keep things simple, we felt that adding the extra logic to support unlimited menus from any section would add too much weight.
It is doable but does require customizing the template JS and probably CSS and Twig as well.
Maybe in the future we will add support for more menus but at this stage the first menu found in the page is the one that's going to be used.
