### ISSUE TITLE
Helium - Layout position trouble.

### ISSUE THREAD

**Issue by pobo3** [gantry/gantry5#1701]
I have a link on the home page in each line of code plug.
I can not understand how they got there. It appeared even in the html block, where only the text and the picture.
It seems this is a problem position of your template.
![2016-11-22_11-45-14](https://cloud.githubusercontent.com/assets/22922112/20519431/a091d3d8-b0ab-11e6-9077-077f5173e8e4.png)

Anyone know how to fix it?

Thanks

**Comment by marktaylor46** [comment]
Most likely that caused by unbalanced html tags in your content and the browser/firebug is deperately trying to match up content - view source and you will probably find they're not there. Use W3C validator to find your missing/extra html tag in your content. 

http://validator.w3.org/

Regards, Mark.

**Comment by mahagr** [comment]
I tend to agree with @marktaylor46, I've never seen this in any template. Which template are you based on?

**Comment by mahagr** [comment]
Closing the issue due to inactivity, assuming it was fixed.
