### ISSUE TITLE
display: flex will cause alignment issue

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#171]
`g-toplevel` is one of the classes that use flex, and text-aling will not work . @kevlardev maybe you can change this with inline, inline-box , you know better :dancer:

**Comment by kevlardev** [comment]
The flex display is only being used when the g-toplevel is in the navigation section (this ensures that the tabs for each menu item all stay the same height as eachother as well as the navigation bar itself no matter how many menu elements are present in the item such as subtext and icons). Because of this, typical text alignment of the items themselves wont work, however weve added conditions for this to our box variations.

By default the menu items are centered, however you can align them left/right using these variations. Select the gear on the menu particle in the navigation section in the layout manager to access the configuration options. Select the Block tab and under the Variations field, select Align Left or Align Right. It will make use of flex alignment to properly position those menu items.

**Comment by adi8i** [comment]
No no, the menu is ok :). But flex seems to add an issue to other section, as soon as i will remember where i've seen that i will come back with a comm :d

**Comment by w00fz** [comment]
Feel free to reopen when you remember :dancer:
