### ISSUE TITLE
Joomla articles troubles Helium template

### ISSUE THREAD

**Issue by pobo3** [gantry/gantry5#1720]
Helium template
I posted a module to display articles of joomla on the main page.
When you go to the selected article - I stay on the front page, but the url has changed.
It looks as if the url is generated automatically. But the article does not open.
site / 12-russkij / eto-mozhno-uvidet-tolko-v-kaliningradskoj-oblasti / 18-kusochek-staroj-germanii-na-zapade-rossii

**Comment by JoomFX** [comment]
This is how Joomla works - if you do not have a menu item for this article ("Single Article" or "Category Blog") the article will be opened on the Homepage. And since there is no "Page Content" particle in the layout of the "Home" outline, nothing is rendered and you do not see anything.

You can search on Google for "joomla article opens on the home page" and you will find a lot of materials.

The solution is to create a menu item for this article (either in your main menu or in a hidden menu) so the article can have its own page. You can also search on Google for "joomla hidden menu".

**Comment by pobo3** [comment]
Thanks

**Comment by mahagr** [comment]
Even if you added the Page content into the home page, you would still have the issue where all the wrong modules (and layout) is shown in the page. So there's really no way around this except of making sure that you have menu item created for your articles.
