### ISSUE TITLE
Change in core SCSS not detected after Gantry 5 update when in "production" mode

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1752]
In the recent update to Gantry 5.4.1 we changed core SCSS file (in nucleus) for responsive utility classes. The utility classes stopped working on some member sites. I have tracked this down to the sites being in "production" mode and the changes in SCSS not being detected (and therefore recompile of SCSS did not occur). A clear of cache and recompile from base outline does fix the issue with sites but we should detect the changes in core SCSS in Gantry 5 in the future and do a recompile.

As discussed with @mahagr

**Comment by mahagr** [comment]
As updating Gantry or the theme seems to cause issues so often, I'm thinking of adding a short checksum into every compiles CSS file. The checksum should contain 

    md5(GANTRY_VERSION . THEME_VERSION)

in a form of

    /*91956bfd03a23bcfab14c356c60e090f*/

Checksum like that will allow a quick way to detect if either Gantry or the theme has been updated since the last page load.
