### ISSUE TITLE
Do not change links which aren't using Gantry streams in platform filter events

### ISSUE THREAD

**Issue by freelancerteam** [gantry/gantry5#1756]
Using J3.6.4 and using CDN for Joomla!. Update gantry from 5.3.9 to 5.4.1 Now all links to CDN location are wrong. 
An url should look like <img src="https://ds86mekjkhhc5..............
with 5.4.1 is looks like  <img src="/https://ds86mekjkhhc5..............

I am sure the issue comes from 5.4.1 as soon I downgrade to 5.3.9 it works fine.

**Comment by mahagr** [comment]
Just install 5.3.9 back for now.

**Comment by marktaylor46** [comment]
Just adding that this issue is also breaking roksprocket too. in that urls are being incorrectly assembled when you page the roksprocket strips - see the callisto demo and try to page the roksprocket strips. The demo breaks completely with a forever spinner - but if you try it locally the Roksprocket will work but the images do not show because of the broken urls.

Regressing to Gantry 5.3.9 does fix the issue.
