### ISSUE TITLE
Textarea box only resizeable vertically

### ISSUE THREAD

**Issue by tastyracer** [gantry/gantry5#1777]
When any form uses a 'textarea' field, rendered box is only resizeable vertically, not horizontally (all browsers that support feature).
Has been verified as bug by @mahagr  
![gantry-bug](https://cloud.githubusercontent.com/assets/24894424/21615516/be169a42-d1d5-11e6-881d-d6fcd34e57c5.JPG)

**Comment by w00fz** [comment]
This behavior is something we wanted to have as default and comes from the engine Nucleus. The reason to force the vertical resize only is by choice so that a textarea never overflows its container. You are also the first one ever noticing it! 😀

However, I can understand this not being the desired behavior for everybody and fortunately it is something you can easily fix in your `custom.scss` by just adding this lines:

```sass
textarea { resize: both !important; }
```
