### ISSUE TITLE
RSFirewall is flagging these files as malware

### ISSUE THREAD

**Issue by shoulders** [gantry/gantry5#1800]
When i run RSFirewall scan it flags the following files as malware because of the 777 permission rules. Is this something that can be changed as 777 is usually unsafe.

````
Warning! Ignoring these files means that the next time the scan will be performed, these files will no longer be checked for malware. If you want to revert the process go to 'Firewall Configuration / System Check' and delete them manually from the 'Ignore files and folders' field.

	libraries/gantry5/classes/Gantry/Component/Filesystem/Folder.php	Unsafe directory creation - 0777 permissions.	mkdir($dst, 0777
	libraries/gantry5/classes/Gantry/Component/Twig/TwigCacheFilesystem.php	Unsafe directory creation - 0777 permissions.	mkdir($dir, 0777
	libraries/gantry5/vendor/rockettheme/toolbox/File/src/File.php	Unsafe directory creation - 0777 permissions.	mkdir($dir, 0777
	libraries/gantry5/vendor/twig/twig/lib/Twig/Cache/Filesystem.php	Unsafe directory creation - 0777 permissions.	mkdir($dir, 0777
````
![unsafe gantry](https://cloud.githubusercontent.com/assets/319997/21962129/d40a44ae-db15-11e6-81a4-57bc2619bfe8.png)

**Comment by mahagr** [comment]
There's nothing unsafe creating a folder with 0777 permission as it is the default value of the PHP function.

http://php.net/manual/en/function.mkdir.php

PHP uses `umask()` to mask the given value -- in PHP it's impossible to set permission to 0777 unless you're using `chmod()` or if your php.ini has been badly configured.

This warning is just RSFirewall developer being paranoid as most of the injected scripts use `mkdir($foo, 0777)`, but that's mostly because of it is what PHP documentation asks you to do in the second example. I asked them to at least change their warning message as it is not true, but they didn't want to do it.

**Comment by mahagr** [comment]
Just to clarify my comment: this is a bug in RSFirewall.

I know that they are flagging the function call because of its used in most malware, but it is also what PHP recommends to be used. PHP also takes care that the call is safe by default. Even Joomla itself uses the default value in multiple locations, though it isn't explicitly specifying it in the second parameter.

I also find it odd why RSFirewall catches `mkdir($dir, 0777)` but not `mkdir($dir)`. It basically means that I can hide malware from RSFirewall just by changing the function call.

**Comment by shoulders** [comment]
I appreciate the technical feedback.

Do you mind if I re-flag this to them as I have an active subscription?

And should I close this ticket as it seems an issue with RSFirewall?

**Comment by mahagr** [comment]
I have already spoken about this with them. They disagree with me and I respect that.

Honestly, I don't really have nothing against changing my code to remove the parameter, the issue is that we are also using twig library which will trigger the same warning and we have no control over it (library is automatically added by our build system). So it really wouldn't make any difference -- Gantry would still be flagged. I also know that if I reported this bug to twig, they would just laugh to me.

All I think is that the warning message `Unsafe directory creation` is wrong as there's nothing unsafe with it. Having something like `0755` wouldn't help either as it will break numerous shared hosting sites (or at least would prevent files from be deleted from ssh/telnet/ftp).
