### ISSUE TITLE
navigation section is displayed on mobile view

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#181]
![2](https://cloud.githubusercontent.com/assets/9744973/7470741/23200d3a-f328-11e4-8f0d-dd8a027978c3.PNG)

As you can see in the picture on mobile, the menu will go inside off canavas, but the section will still be there. 

In `navigation` section i have `menu particle` and a `module position` that have `hidden phone` class

**Comment by kat05** [comment]
is your image link broken?

**Comment by adi8i** [comment]
image ? no i can see it

**Comment by adi8i** [comment]
![1](https://cloud.githubusercontent.com/assets/9744973/7475595/3d72f53e-f351-11e4-88d3-04da40d275fd.PNG)

here is the image again :)

**Comment by mahagr** [comment]
It's not easy to hide a block, what do you think @kevlardev @w00fz ?

**Comment by adi8i** [comment]
Well i can add some css, so for me is not a big deal, but i am just saying :)

**Comment by adi8i** [comment]
Ok found it, just add `hidden-phone` to Navigation section. 
Sorry for the mess, i can easily fix things like this for my website. But i open issues just to highlight think i find.. you know :)

**Comment by w00fz** [comment]
One thing I wanted to add in the future  is a more user friendly viewport classes picker to be used from the Block, so instead of having to specify manually the hidden-X class you would click on mobile/tablets/desktop icons.
That should make it more appealing and user friendly but again, not something for right now. I would like to see more feedbacks after we release in this regards, I wouldn't want this to be a feature that rarely gets used.

// Djamil Legato // From iPhone //
