### ISSUE TITLE
Grav: Forgot password form does not recognise invalid email entries

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#1813]
The Forgot password form does not recognize if an invalid input has been made such as a row of random characters that do not even contain an @ character. Also when adding a valid email address which is not used for any user, this won't be recognized as a wrong entry. For both cases I am getting a notification that an email with instructions has been sent, which can't be true.

![grav_g5_forgotinvalidemail](https://cloud.githubusercontent.com/assets/5719486/22104210/7b6bd304-de3e-11e6-90f1-aeb837c786e5.jpg)

**Comment by mahagr** [comment]
I remember seeing the opposite issue in Grav issues which allowed the attacker to find out user accounts from the site. It was fixed to send the same message for real users and non-users.

Not a Gantry5 issue.

**Comment by flaviocopes** [comment]
Good catch, the form uses `type: text` instead of `type: email`. I will change it so there will be automatic email validation when submitting the form.

As for the message even if the email is not valid, it's ok, to avoid information disclosure, so a malicious user won't know if an email is actually a valid login name.

**Comment by mahagr** [comment]
Fixed in login plugin.
