### ISSUE TITLE
Grav: file upload element in forms not working

### ISSUE THREAD

**Issue by paulhibbitts** [gantry/gantry5#1815]
There seems to be an issue with the file upload item for Grav forms when used with Gantry, the file drop zone is not enabled and for both the Hydrogen and Helium themes the following is displayed:

![2017-01-20_08-42-49](https://cloud.githubusercontent.com/assets/1812771/22157487/c37c44fe-deec-11e6-822d-272466e604c7.png)

Thanks very much, loving Gantry on Grav!
Paul

**Comment by mahagr** [comment]
Gantry forces Twig `autoescape` setting to be true for security reasons (nobody ever remembers to escape variables) and that causes some issues with Grav, which by default has the option turned off.

While I'm working towards solving this issue in Gantry, it is really a bug in Grav template files as Grav has an option to turn autoescape on, but at the same time, it doesn't really work properly with the option turned on. Also like I said before, nobody ever escapes variables making most of Grav to be potentially vulnerable to XSS attacks. So right now, every output with a variable in every template file should use either `|e` or `|raw` filter for every single variable in twig -- if it's not, I consider that a bug.

This issue is something I've raised multiple times and is something Grav 2.0 is likely going to enforce, but what cannot really be fixed for 1.x because of B/C indications it has.

My recommendations:

* When developing, always set `Twig` > `Autoescape` setting to `true`.
* In all Twig files, use either `|e` or `|raw` filter for all variables or use `{% autoescape 'html' %}` tag to make sure there are no XSS issues in your template files
* Report or create a pull request to fix all twig files not obeying the rules

**Comment by mahagr** [comment]
Fixed in form plugin:

https://github.com/getgrav/grav-plugin-form/commit/a4c9360996a28dfc3a09cf84112c728d5cbb0495
