### ISSUE TITLE
Changing style color with override - color not reseting

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#182]
Best explained through example.
1. in hydrogen home template go to style tab - preset 1 is chosen.
2. tick the accent one color to override the value then pick any other color
3. now untick the accent color again (change your mind) 
4. you can also save at this point too.

I would expect the color to reset back to the preset value - but it doesn't - it still leaves the other color that was chosen. If you refresh the screen it does reset back to the color value of preset1.

![2015-05-05_13-37-26](https://cloud.githubusercontent.com/assets/11683218/7472584/f615b2d2-f32b-11e4-95db-76fc7c1aa8b6.png)

**Comment by adi8i** [comment]
For me is working fine but you need to click `extras - clear cache` or `recompile css`  and will work for sure :P try them

**Comment by marktaylor46** [comment]
No that's not the issue I am talking about. It's only a screen issue - nothing to do with recompiling or what it does on frontend. - it's just in that page. Follow the steps that I gave and you'll see what I mean. It should work like changing a setting in an override template in Gantry 4, i.e. tick the box and you can change it, untick the box and it greys out again and reset to the MASTER inherited value (it's not quite the same in G5 - but the mechanics should be the same).

**Comment by adi8i** [comment]
Ok, you mean that in accent color 1 box after disable you still see the old color value, instead of default one :P .  But is still working fine  @w00fz

**Comment by marktaylor46** [comment]
Yes, that is what I mean. Yes, it works in practical terms - but it's not correct, once you uncheck the override it should reset to it's inherited (original) value. Try the equivalent in G4 and you'll see the difference - it would be nice if it behaved the same way.

**Comment by w00fz** [comment]
We decided not to implement the G4 behavior of resetting the value to the inherited one once unchecked, until we have Reset to Defaults implementations.
It really is more cosmetic than anything that adds quite some extra overhead to the admin because for each field we will have to keep track of both the Original and Right-Before-Unticked values and toggle between the two as you check/uncheck. We have this in our list but it's very low in priority.
Also please keep in mind G5 is not meant to be a port of G4, you will see new things as well as missing ones and it's not said that everything that was in G4 will see the light in G5.

**Comment by mahagr** [comment]
Also what if you changed the color, changed your mind and reverted back and changed your mind again wanting the new color. Now it behaves just like you'd expect to!
