### ISSUE TITLE
Conflict between "Gantry 5 Particle" module and Advanced Module Manager by RegularLabs

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#1832]
Hey Matias,

It seems that the latest version of "Advanced Module Manager" (7.0.1) is in conflict with the "Gantry 5 Particle" module.
Here, have a look at [this video](https://youtu.be/k_E96OwyIxI), it shows everything.

I was wondering if you can do something from the Gantry side in order to prevent the conflict. That's why I'm opening this issue.
I also asked our customer who reported the problem to open a new discussion in the RegularLabs forum so Peter can look at it and see if he can (and if he is willing to) fix it from the extension side.

**Comment by alisamii** [comment]
@JoomFX @mahagr @w00fz 
I can confirm that this is happening.
If you click on the edit particle button with AMM active, you get kicked out of the module and back to the list of modules with the module you were editing now locked because you exited the editor incorrectly.

**Comment by alisamii** [comment]
I am doing some testing, and it appears that the problem may be a change in how Gantry is working,

I tested the following configurations:

`Gantry 5.4.5` and `AMM 6.2.10`
Result: `No Error`
`Gantry 5.4.6` and `AMM 6.2.10`
Result: Loads a page that says `0 Call to a member function getField() on null` with a button to return to the admin main page.
`Gantry 5.4.5` and `AMM 7.0.3`
Result: `No Error`
`Gantry 5.4.6` and `AMM 7.0.3`
Result: Exit out of the module and back to the modules list. No error displayed.

**Comment by JoomFX** [comment]
Thanks for chiming in Ali.
By the way, before I opened this issue I tested with all Gantry versions back to 5.3.6 and the issue was present in all of them.
Therefore, I believe that there is something in the latest AMM release that has changed.

Anyway, it will be great if the conflict can be fixed from Gantry side.
Otherwise we would need to hope that Peter will be willing to modify his extension.

**Comment by alisamii** [comment]
@JoomFX That's off, because I tried the latest AMM with G5.4.5 and I didn't have the problem, but I had the problem with 5 versions of AMM and G5.4.6. Peter already replied to your customer's comment on RegularLabs saying it's not him and that Gantry needs to solve it.

I wanted to put the ball back in his court and that's why I tested latest AMM and the version immediately before (before the 7.0.* release) and latest Gantry and the version immediately before it. When I did that, I realised that rather than putting the ball back in Peter's court, I had to bounce it back to our favourite developers here!.

**Comment by JoomFX** [comment]
Ha! You are right Ali.
I wasn't clicking on the "Edit Particle" button when I was downgrading Gantry. I was just installing an old version after old version and every time I was just opening the module in the Module Manager. And as soon as I see that there is a big gray box I was closing the module, assuming that the same issue exists.

Anyway, yes everything works fine with 5.4.5 and it breaks in 5.4.6.

**Comment by coolman01** [comment]
Hi Guys
Are you any further on this? It's causing me grief in a site i'm building.
To dowgrade, do I just reinstall an earlier version and where can I get that from?
Regards
David

**Comment by coolman01** [comment]
Found the older versions. Still an issue, but that may be linked to hikashop, where I'm having the conflict with their brand new version 3

**Comment by mahagr** [comment]
I can confirm that everything works fine in 5.4.5 but not in 5.4.6. I tried to track down the issue and I am suspecting that there may be some JS conflict with Mootools, which gets loaded by AMM.

@w00fz Something you changed in the latest version seems to break the page. HTML output doesn't really change (except for timestamps and some HTML ids), so it has to be JS change which is causing this issue.

**Comment by coolman01** [comment]
Peter from Regular Labs has been working on this issue on my site. You can read the discussion 
[https://www.regularlabs.com/forum/advancedmodulemanager-pro/43386-modules-showing-on-child-items-in-hikashop-version-3?start=20#67869]here(url)
It seems to be pointing at Gantry as the main problem. Perhaps he can offer an insight.

**Comment by coolman01** [comment]
More Info: Peter suggested that I try a module position, rather than a module instance - and that worked!

I also updated to Gantry 5.4.6 and it continued to work. I hope that help to point you in the right direction.
Regards
David

**Comment by mahagr** [comment]
@coolman01, your issue is different from the issue mentioned in this issue.

Module instance is never meant to work like module position but like inline module, which is much more restricted in Joomla. It seems to cause some issues in AMM (see #1685), though I've not had a chance to take a look what it could be.

**Comment by coolman01** [comment]
@mahagr OK - thanks for that. That helps me to understand that better.

**Comment by w00fz** [comment]
FYI this is not a JS conflict, Gantry5 does not use any framework such as mootools or jquery and the codebase is 100% fully namespaced and wrapped in anonymous functions, meaning there could never be a conflict with 3rd parties.
It was designed this way exactly to avoid potential issues and has been working great all this time.

The problem with AMM is a conflict in the data set naming. Both Advanced Module Manager and G5 are using a `data-position=""` data set to identify some elements/settings in the DOM which are obviously meant for different purposes.

I'm going to namespace ours to be `data-g5-position=""` which must have slipped because we also tend to namespace datasets. Probably a good idea for Regular Labs would be to also start namespacing their datasets so this type of issue would get very hard to ever occur again, with us or with any other 3rd parties.

**Comment by coolman01** [comment]
@w00fz - thanks for that. I've passed this on to Peter.

**Comment by regularlabs** [comment]
Just to chime in:
Advanced Module Manager doesn't use the `data-position=""` itself.
I see there are some core Joomla elements that use this (color field and module ordering field).

**Comment by w00fz** [comment]
I see so it's the joomla field that renders that `data-position`. I only seen that being rendered with the `advancedparams[color]` field, that's why I made the assumption.

Either way this is now fixed and seems to work fine. If any of you guys can try the CI Build as soon as it's built that would be awesome.

Thanks!

**Comment by JoomFX** [comment]
@w00fz Works like it should. Just tested it with the latest CI,
Thanks Djamil 😉

**Comment by mbaggy** [comment]
I tested the following configuration:
Joomla 3.6.5, Gantry CI and AMM 7.0.3
Works great. Thanks!

**Comment by ecseley** [comment]
Hey thanks for getting to the bottom of this issue!  
@w00fz - when can we expect prod release with this fix?  I am on a production site and don't want to use the CI build.  

Cheers!

**Comment by w00fz** [comment]
I think we can do a release next week

**Comment by ecseley** [comment]
@w00fz any word on a exact day for that release?

**Comment by w00fz** [comment]
Plan is for tomorrow

**Comment by ecseley** [comment]
Awesome!  Thanks for the update! Cheers!
