### ISSUE TITLE
System - Regular Labs Library

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#1836]
When i have that installed System - Regular Labs Library i get this in the console when accessing Gantry 5 Admin

**Uncaught ReferenceError: jQuery is not defined**

**Comment by N8Solutions** [comment]
Is this related to #1832 ?

**Comment by DamirPecnik** [comment]
Dont know will see what @mahagr say

**Comment by w00fz** [comment]
We don't use jquery at all, the plugin must not be ensuring jquey gets loaded and just expects it to be always available.

**Comment by mahagr** [comment]
I agree with @w00fz on this. Joomla loads jQuery only on demand and Gantry doesn't load jQuery because we never use it in admin. I've actually reported a few bugs on this to Joomla and they were fixed a while ago. I guess the plugin should also be fixed. This kind of issues are common and even I have made similar mistakes of not loading jQuery/Mootools/Bootstrap a few times in the past.
