### ISSUE TITLE
Adding hidden-tablet class on sidebar

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#186]
If you add `hidden-tablet` class on sidebar, on tablet view will result in this: 

![capture](https://cloud.githubusercontent.com/assets/9744973/7474860/b6a16490-f34c-11e4-83cb-7d50dd6dbd5d.PNG)

The sidebar will be hidden but an empty space will still be there.

**Comment by adi8i** [comment]
Changing `block` flex to 100% will show fine 
![1](https://cloud.githubusercontent.com/assets/9744973/7475611/577fe2d4-f351-11e4-9de5-5303ba1502f9.PNG)

**Comment by kevlardev** [comment]
The hidden classes are meant more for hiding individual blocks are pieces of content, as opposed to affecting layout. Its not really possible to use them for something like collapsing side by side layout manager controlled sections, as its outside the scope of those classes (having a manually added class on a sidebar cant communicate to the layout manager that the main column currently at 75% needs to somehow become 100% even though its assigned 75%).

We do plan in the future to try and work on an implementation to have more responsive control for individual layouts so that you can create custom layout implementations for particular devices or perhaps designate sections to behave differently in different views all from the layout manager, but that will require a much more complex system than simply having a display: none class.

**Comment by adi8i** [comment]
Ok, then i will just add custom media :)
