### ISSUE TITLE
assets manager for particles, atoms, etc ....

### ISSUE THREAD

**Issue by 4evermaat** [gantry/gantry5#1904]
Similar to how grav admin has theme and plugin sections that allow users to add plugins/themes directly from admin panel, is it possible to add gantry particles, atoms, etc from approved centralized gantry assets market?  I saw a bunch of cool particles here:  http://www.inspiretheme.com/gantry5-particles  but I could not load them directly.

I find myself wanting to add particles that do not yet exist in my skeleton/theme, but one by one is quite tedious.  Unless I'm doing it wrong.   Then what happens when a particle gets updated?  I have to manually check the source for the update?

**Comment by JoomFX** [comment]
Adding/Installing particles from the Gantry5 Admin is not yet possible.
However, adding this functionality is in the G5 Roadmap.

Anyway, InspireTheme provide really good installation instructions (including video) for all platforms (Joomla, WordPress and Grav) for each and every particle. Just watch the video and follow the exact steps.

But I do agree with you that a "Particle Manager" should be implemented in the framework so the users can easily move particles between the templates.
Rockettheme (the core team behind the G5 framework) do not consider this as a high priority feature because they treat the particles as an integral part of the template, not as a separate/independent product. But if you browse the Rockettheme forum you can easily notice that this feature (making the particles installable from the G5 Admin) is being requested all the time and especially in the last couple of month it's been requested heavily.

You might want to have a look at [this issue](https://github.com/gantry/gantry5/issues/680) on Github where this topic was discussed in details.

IMHO, the "Particle Packaging" (making them installable from the G5 Admin) is a crucial feature that once available will increase the G5 popularity tremendously because many 3rd party developers will start developing and releasing particles and therefore will extend the G5 functionality a lot!

All that being said, all of us must realize that the G5 developers are busy as hell and that there are more important features that need to be implemented first. One of those features is the "Particle Translation" (Multilingual Implementation) where especially important is to be able to translate the dates in different languages.
Another important features (which in my personal opinion is not more important than the "Particle Packaging") is the "Front-end Editing".

As a conclusion - we just need to wait and contribute whatever we can so we can expedite the implementation of all the features we want/need.

**Comment by 4evermaat** [comment]
> Another important features (which in my personal opinion is not more important than the "Particle Packaging") is the "Front-end Editing"

Yes, I agree I will gladly push particle market for `front-end Editing`.  I was just watching video on Divi, Elementor, and a few other product claiming to allow complete drag/drop and adding particles right from the website page with instant preview [WYSIWYG].  And when you save the changes, they would be live instantly. .  Unfortunately, nothing like that that I know of for Grav; only wordpress and maybe Joomla.

Do you have a link for Front-end Editing issue?

**Comment by JoomFX** [comment]
Nope, unfortunately I couldn't find such an issue.

Btw, I'm not sure I understand what you said above... I mean, do you think that "Front-end Editing" is more important than the "Particle Packaging" or the other way around? 😄

**Comment by 4evermaat** [comment]
`Front end editing` is much more important.  I might even considering switching to wordpress for it.   It's more intuitive.
