### ISSUE TITLE
enable squeezebox from gantry admin for joomla

### ISSUE THREAD

**Issue by shoulders** [gantry/gantry5#1905]
To enable Squeezebox in joomla you need to add `JHTML::_('behavior.modal');` to the index.php usually so the libraries will be loaded. I have not idea why this is not an option in joomla.

Can you create an atom to load joomla libraries or at least the Modal Squeezebox library so i do not have to do any code edits. You could add it into the javascript frameworks atom

for reference here is my research (not that you guys needs it):
https://quantumwarp.com/kb/articles/30-joomla/606-joomla-modal-boxes-inbuilt-and-3rd-party-extensions

If I have missed this setting can you point me in the right direction and I will update my notes

thanks

shoulders

**Comment by JoomFX** [comment]
Since v5.4.0 you can just load the `Lightcase` atom which will bring the [Lightcase](http://cornel.bopp-art.com/lightcase/) functionality to your website.

However, adding the default Joomla's Modal functionality to the `JavaScript Frameworks` atom might be a good idea because some 3rd party extensions might rely on it.

**Comment by mahagr** [comment]
Do not use `JHTML::_('behavior.modal');` as it is considered to be a legacy feature from J2.5. Bootstrap has its own modal which is preferred in Joomla 3+.

**Comment by shoulders** [comment]
I have now updated my notes to use the new Bootstrap Modals.

Bootstrap Modals re-use the payload code rather than copying the code block like squeezebox so is definitely much better.

As such add Squeezebox code is a big step back
