### ISSUE TITLE
Wrong Layout on gantry 5 helium theme content tabs

### ISSUE THREAD

**Issue by toolsofexcellence** [gantry/gantry5#1925]
HI Guys,

I have a strange issue with the content tabs. Since Friday the layout is different. The tabs have an orange background and are also not in line. I cleared the cache of gantry and also added a new content tabs but the same issue. 
![bildschirmfoto 2017-03-13 um 09 57 57](https://cloud.githubusercontent.com/assets/26377324/23847617/90240c6c-07d3-11e7-9842-fbb237a8ef15.png)

Theme: Helium (v5.4.6 / g5_helium)
WordPress 4.7.3
http://toolsofexcellence.com/en/project-management-software

Thanks in advance for your help.

Cheers,

Colin

**Comment by newkind** [comment]
Hi,

The orange styling comes from a plugin - Ultimate Product Catalogue. They must be using also jQuery UI scripts and because of the generic classes the styling is being applied to both Helium tabs and that plugin itself. I'm gonna keep this open to prefix the UI tabs in a spare moment.

Thanks,
Jakub

**Comment by toolsofexcellence** [comment]
HI,

thanks for your answer! I used the plugin only for testing. After I deactivated it, the tabs are all fine now. Thanks for your help!
