### ISSUE TITLE
Grav - Layout tab particles list scrolling issue

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#1942]
Henning has brought this up a couple of times, so creating this ticket.
I can replicate this issue on all browsers (Macbook Pro).

Please see pic, the particles list does not get fixed so moves out of view when scrolling down the page. This makes it complicated to add new particles to sections which are further down.

![grav_g5_particleslist](https://cloud.githubusercontent.com/assets/5719486/24244097/cf624bf4-0fbd-11e7-8245-ac7f73924133.jpg)

**Comment by Neuronauten** [comment]
It is not easy but always possible, for example with scrolling the mouse while holding a particle.

INSTEAD THERE IS NO MULTILANGUAGE SITE IN GRAV POSSIBLE AT ALL (MENU ISSUE). PLEASE EXPLAIN WHY A SCROLLING ISSUE IS IMPORTANT AND LANGUAGE INTEGRATION NOT.

**Comment by w00fz** [comment]
@Neuronauten please open a separated issue if it's not there yet. All issues are equally important. What you are describing is something missing in Gantry that needs to be implemented, what's been reported here is an issue of an already existing bit of code, that's why it's set to important.

Thanks
