### ISSUE TITLE
How about Drupal version?

### ISSUE THREAD

**Issue by macmladen** [gantry/gantry5#1960]
If you do not have your plans to make it, maybe I can? I would need you hand to do it.

**Comment by newkind** [comment]
We don't have any plans for Drupal right now, but Gantry 5 is open source so if you want to put work  into adding Drupal support please feel free to do so :) We'll gladly accept new platforms :)

**Comment by macmladen** [comment]
Sure, I understand, it is **never** easy to add new platform unless you have someone on board who will sort out all quirks between theme as appearance, as functionality and as experience.

I will try to find some time and work on it but I have to familiarize myself with the theme itself.

Is there some just plain HTML version? (I have to download it yet, so I am not sure where to start from?)

**Comment by douglasgough** [comment]
I've thought about working on a Drupal 8 version of Gantry 5 for a while now. I can see two approaches. The easiest would be a Gantry based theme where the particles are used purely as theme-layer embellishments and don't deeply integrate with Drupal core. This may be the right place to start, but it wouldn't get much adoption in the Drupal community. The harder but much better path would require that Gantry layout elements (particles, sections etc) would be integrated with Drupal core in such a way that a Gantry section represents a Drupal 8 theme region, and a Gantry particle represents a Drupal block, or something like that. The successful implementation of Gantry on Drupal 8 would require that Gantry's page builder is creating and manipulating Drupal entities in the background. That could prove to be very difficult due to the fact that any Drupal developer can and most likely will create new custom entities for their projects. So Gantry would need to be able to accommodate not just the Drupal core entities (content types, blocks, users etc) but also any custom entities that require a presentation layer. I would be interested in helping out with a project like this on Drupal 8. I wouldn't suggest attempting it on Drupal 7 or earlier.

**Comment by mahagr** [comment]
Getting Gantry to "work" on a new platform is usually pretty easy, just taking a few days. But integrating Gantry to the CMS takes months of work and a lot of research.

In short, Gantry takes care of the rendering or the page and does it usually by replacing the main template file in the CMS. Gantry takes care of the structure of the layout and provides positions for the CMS to integrate with. So what I can see Drupal theme region = Gantry position. Particles are something which are built into Gantry itself, but all the supported platforms have also a module, wigdet or plugin to allow particles to be used directly from the CMS. Gantry position is just a special particle, which hooks into the CMS and in this case allows Drupal blocks to be injected.

**Comment by macmladen** [comment]
Looking into Bootstrap theme, I am not too happy how it is integrated (mostly because the main method is **bloat**) but it gained so much popularity as Zen and Omega 4 just lost interest in continuing the work. Mark Carver, by the way is not a nicest person to communicate and behaves autocratically just like Dries (sidenote).

There is also very interesting theme [Radix](https://www.drupal.org/project/radix) which is also Bootstrap based, much more flexible and frontend dev friendly, however it is not gaining ground (or it seems so although around 8k installs is not small user base, small to 140k of Bootstrap).

Radix is based on Panels in part and that may be a way to choose, however it seems necessary to have some deeper integration with twig overrides and some glue code to get that right. Possibly some similar magic like in WordPress and Joomla!

The light version (which is the core of Bootstrap theme) would be to implement some general layout, design and some other common needs and leave other things to developers so you have Gantry logic but not all the spices. That would be easiest to achieve and maintain so if it gets traction, community will lend in hands and move it forward.

Otherwise, it would need some interest to drive development like company/project sponsored to make that right (in a way [Kalatheme](https://www.drupal.org/project/kalatheme))

Notable, More than just a theme has many themes that are well positioned and yet they are not universal as Bootstrap but particular.

Just sayin' that maybe light approach may be perfectly sensible. 😄

**Comment by adi8i** [comment]
From what I read here https://www.drupal.org/docs/8/theming/twig, gantry and drupal have a common denominator

**Comment by greenlanegreb** [comment]
It's annoying as Joomla is as good as dead and groups like CiviCRM are focusing more on Drupal  by far.
