### ISSUE TITLE
Joomla article not showing

### ISSUE THREAD

**Issue by glcvr6** [gantry/gantry5#1984]
I inserted joomla article particle to page module and on that page I set to show grid of 4 articles. On that page everything is ok but when i click on "Read more", browser url is ok but it show to me main page of site - not full article to read. Am I missing sometnhing?

Do I maybe need to create different, stand-alone page for every article and link it?

I am using Helium theme

**Comment by JoomFX** [comment]
This is not related to Helium nor is it to the Gantry 5 framework. This is just how Joomla works.

The problem is in your site configuration. More specifically, you do not have a menu item for your articles/categories and therefore the articles are being opened on the Homepage. And the Homepage (the "Home" outline) in Helium does not have a [Page Content](http://docs.gantry.org/gantry5/particles/page-content) particle in its [layout](http://docs.gantry.org/gantry5/configure/layout-manager), therefore nothing is shown.

If you create a menu item for your articles/categories as you should (because as you know in Joomla "new page" = "new menu item") the articles will open in a new page.
The modules and the particles just take the URLs that are generated by Joomla.

Once again, it is just a site configuration issue. Remember, in any Joomla website, the most important thing is the Menu. It defines the site structure, it defines the URL structure, you assign modules to menu items, basically in Joomla everything is built around the Menus. It is a menu-centric CMS.

You might also want to search on Google for "joomla articles open on homepage".
