### ISSUE TITLE
Load images directly from the computer?

### ISSUE THREAD

**Issue by 4DevTek** [gantry/gantry5#199]
Please can you make the logo and other image loader tabs (like bg) load directly from the computer? ie not loading before hand into the images/media directory and then calling from there.

**Comment by w00fz** [comment]
You can drag from desktop into G5 image picker and it will automatically upload the file for you at that location. Right now this feature is kept hidden because it's not fully implemented (after successful upload you need to close and reopen the modal or switch to another directory and back to the one where you uploaded), but functionality wise it works :)

**Comment by 4DevTek** [comment]
Thanks. I did think RT would have it covered!
