### ISSUE TITLE
Assignements should not only apply to menus and menu items

### ISSUE THREAD

**Issue by sintos** [gantry/gantry5#2]
This is a Gantry's 4 fault that should not continue to Gantry 5.
The assignements should not only include menus and menu items because when you have a multilanguage site, and you have a template override for a specific language, every time you browse a page that is not a menu item as well, the menu returns to the one of the Default template.
Assignments probably should be more complicated to include menus, components, content (categories, articles, K2 categories, K2 items), users, specific url's and most important Languages !!!

**Comment by mahagr** [comment]
We already have this in our feature list, but right now there are more important things to do -- as getting stable version out there. We are planning to add other types of assignments when we add Wordpress support as Gantry4 for WP already has those features implemented.

**Comment by w00fz** [comment]
Yeah Assignments is one of the things we definitely want to improve like we did for Layout and Menu. It's just going to take some time before we get there.

**Comment by mahagr** [comment]
Just a note on assignments types. I find menus (meaning the menu itself, not the items in there), components and languages being the first and the most obvious assignment types to be implemented. The other ones are a bit iffy as having content based assignments may require some more effort to make it so that it's not overly complicated and slow.
