### ISSUE TITLE
Platform Settings - Joomla - Should go to Plugin Options?

### ISSUE THREAD

**Issue by blizam** [gantry/gantry5#2010]
In Grav and WordPress the Platform Settings options in the Extras menu goes to plugin settings but in Joomla it goes to the Component's permissions page... the equivalent would actually be the G5 Joomla Plugin settings and IMO that's where it should route

/2 cents

**Comment by mahagr** [comment]
In Joomla the settings point to plugin mostly because of the plugin is loaded on every page. The purpose was to add the settings into the component as well by a plugin event, but unfortunately, back in Joomla 3.4 the event was broken (gave an array without reference, so the data couldn't be updated).

I can investigate if the event has been fixed since then...

**Comment by mahagr** [comment]
Found a workaround on how to do it.
