### ISSUE TITLE
Menu offcanvas doesn't open  in desktop view  when  "toggle visibility" always on - Grav -

### ISSUE THREAD

**Issue by danabeo** [gantry/gantry5#2028]
When you set Offcanvas Styles "toggle visibility" to always (Grav), in desktop view menu doesn't not open. In mobile view works fine. I'm using Helium template. Same with Hydrogen template.

**Comment by w00fz** [comment]
This is a really confusing option but eventually remember what it was all about.
The behavior is working as expected, the option refers to the hamburger icon and allows to whether show it always or only when in the mobile viewport. Although, I am not quite sure why this is even an option to be entirely honest, but it is working as described and expected.

What you are trying to do is something that can be configured a few blocks below at the 'Breakpoints' section. The 'Mobile Menu' is the one you want to tweak so that the menu always shows in the sidebar even in desktop mode. For example instead of the default `48rem`, you can set it to `2048px` and the mobile menu will always be enabled even on your desktop.

Hope this makes sense.
