### ISSUE TITLE
Gantry 5 website slow

### ISSUE THREAD

**Issue by tortxp** [gantry/gantry5#2060]
Is there any way to speed up the work and load the site on gantry framework 5 ? 

Tried the same website, put on it a template on T3 framework and gantry 5 

On gantry loaded noticeably slower. But T3 is not satisfied with the capabilities to create and publish modules.

The server is using VPS - Debian - 2 cores - 2 gb RAM - sdd drive

site: http://trend-city.ru

**Comment by mahagr** [comment]
For me html for the page loads in ~400ms, which is fast. Your issue is that all the other files, like css, js, images, fonts etc are reloading on every single page load. 

https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fwww.trend-city.ru%2F&tab=desktop

This is more server configuration issue than issue with Gantry as PHP runs fast.
