### ISSUE TITLE
ID being displayed Twice

### ISSUE THREAD

**Issue by simmonsr** [gantry/gantry5#2088]
As a result of this commit:

https://github.com/gantry/gantry5/commit/56115df809736d1f6532c468f5268ff8d164eab1

particle ID (id="{{ id }}") may be displayed twice (at least I noticed it in Acronym template with particlesjs).

**Comment by marktaylor46** [comment]
I have confirmed this with Acronym and G5.4.16 and G5.4.15 - just installed standard Rocketlauncher and then updated to G5.4.16 and the particles particle displays the animated particles in a container of it's own instead of the background. The issue does seem to be caused by duplicating IDs.
![2017-08-22_16-27-30](https://user-images.githubusercontent.com/11683218/29573446-e6b71896-8756-11e7-8891-b725995cc18a.png)

![2017-08-22_16-25-26](https://user-images.githubusercontent.com/11683218/29573455-eb93e6aa-8756-11e7-8531-5f640051fbe7.png)

forum topic: http://www.rockettheme.com/forum/joomla-template-acronym/271710-option-section-only-in-particlesjs-not-working
