### ISSUE TITLE
Disable owCarousel on Read More Pages

### ISSUE THREAD

**Issue by Posmatrac** [gantry/gantry5#2101]
Good Evening together,

As the subject says I'm looking for a way to Disable the owCarousel on "Read More"-Page. Read More Pages are automatic generated Pages when I write a Article so I can't make a Layout for Read More pages. Has somebody a another way how to Disable the owCarousel on Read More pages?

Thank you in advance for Tips to my Problem.

**Comment by kat05** [comment]
Hi there,

I assume you're using Joomla? Menuless pages such as articles that are not assigned to any menu items will open 'inside' the Homepage with all modules that have been assigned to Home. In order to change that, you need to create a menu item that links to those articles, such as a Category blog layout and unassign the OwlCarousel from that new menu item.

Regards, Kat

**Comment by Posmatrac** [comment]
Hello kat05,

Yes i using Joomla! 3.7.5

This way don't help me in case. I would like that my visitors come to Homepage and read a Article if there would read more it can click ond "Read More" button and it open a Page without Modules and OwlCarousel. Your solution goes that a Visitor come to my Homepage and click a Menu item and thand click a readmor button this is a way but not a Solution for me.

I have sloved the Problem with a another way. I have created a Menu Item and Marked it as Hidden Menu and configured the Menu Layout like Blog Category etc. And all Articles i wirte goes in this Hidden Menu item on the Homepage Menu item i have set to show featured Articles. And when i write a Article and set it as Featured Article goes on the Homage. Now when a visitor on Homepage click on Read More than Open a new Page without Modules and OwlCarousel.

Sorry for my bad English!

My Problem is Sloved so you can Close it.

Regards, 
Posmatrac
