### ISSUE TITLE
Helium Theme contenttab edit default "layout manager" 403

### ISSUE THREAD

**Issue by swissb00m** [gantry/gantry5#2110]
Hello everybody

I set up my page by using the full package available from gantry.org (Helium Rocketlauncher)

When I want to edit the second item in:
"Theme: Helium" --> "Home - Particles" --> contenttabs

It says 403 - Forbidden - Access to this resource on the server is denied!

Any idea why this could be caused? The first item could be edited without issues.

Thanks for any input here.

Regards

swissb00m

**Comment by swissb00m** [comment]
Unfortunately this repeats for the default content:

"Theme: Helium" --> "Home - Particles" --> Expanded --> "Develop CMS themes quickly"

When I click here on the wheel next to "100%" it doesn't show any sub-menu but instead comes again with that 403 error.

Might the problem be with a certain file on my server itself?

**Comment by kat05** [comment]
Hi there,

did your Joomla session expire before you tried to edit the 2nd item?

**Comment by mahagr** [comment]
It's likely mod_security not liking the HTML inside the response. It falsely thinks it has SQL attack in it (just because of the content has 2 words in different sentences in it).

**Comment by pintobuck** [comment]
Wow, you guys are great!  The Layout pages for my Gantry 5 themes Hydrogen and Hassium (by JvgTheme) just started coming up blank.  Then, I read mahagr's comment, and disabled the jHackGuard plugin which I had just enabled.  Upon disable of jHackGuard, the Gantry 5 layout pages returned to normal.  (Info: jHackGuard is a Joomla extension by SiteGround.com, and a Github project. I'm using Joomla 3.7.5, PHP 7.0.98, on a large hosting service.)

**Comment by pintobuck** [comment]
Egg on face.  Disabling jhackguard plugin seemed to cure my problem, but then the problem came back. So, I think jHackGuard was just a coincident event.  Upon further experimentation, it seems that my bad bot IP blocking plugin did not like my public wifi site, and may have been the source of the problem.  I cleaned up an IP number, and all the plugins and Gantry 5 seem to be working happily together.  Thx again to mahagr for mentioning mod_security which put me on the right track to solve my problem.
