### ISSUE TITLE
Print Layout

### ISSUE THREAD

**Issue by yellowwebmonkey** [gantry/gantry5#2136]
When attempting to print a page, it is resized down to a tablet width.  In firebug, I can add media="screen" to the main template compiled css which fixes the issue.  Can this be incorporated at the framework level? This is in Joomla.

**Comment by mahagr** [comment]
@hexplor ?

**Comment by yellowwebmonkey** [comment]
I am going to have to attempt this myself in order to get my client's project closed out.  Can someone point me the right direction so I don't have to poke through a ton of files.  Where is the <head> generated?  Thanks!

**Comment by thexmanxyz** [comment]
I found a solution and leave it here, idk if this has to be modified within the core files but the solution is to modify `page_head.html.twig` @ line 9. Adding attribute media="screen".

src file: media\gantry5\engines\nucleus\templates
target file: templates\g5_hydrogen\custom\engine\templates

**Comment by loishee** [comment]
hi,
i am also have the similar problem as you metioned their , when i try to print my page the layout of page break in 2 pages , i follow the step from @thexmanxyz but the problem is my override file path:
i don't find  the file page_head.html.twig inside my : templates/{theme}/custom/engine/templates cause i am using gantry5 hydrozen template .so in my template folder  i don't have engine folder inside custom folder. thanks

**Comment by thexmanxyz** [comment]
@loishee the file isn't there by default you have to take the file from `media/gantry5/engines/nucleus/templates`, copy it to `templates/{theme}/custom/engine/templates` and modify it there

**Comment by loishee** [comment]
ok great @thexmanxyz ...i follow the steps.thanks

**Comment by thexmanxyz** [comment]
@loishee you are welcome, this should work :)
