### ISSUE TITLE
Extending how we pick up `custom.scss`

### ISSUE THREAD

**Issue by w00fz** [gantry/gantry5#215]
Right now when you drop a `custom.scss` in the `custom/scss` folder, it gets picked up by all the pages, which is awesome.

I think we should extend this to also go more specific per Configuration so if I have a `Callisto - Home` or `Callisto - Pages - Clients` I could drop a `custom_home.scss` and a `custom_pages_clients.scss` that will only be picked up and compiled for those configurations.

This would improve dramatically how dynamic can be customizing individual configuration.

**Comment by JoomFX** [comment]
Yep, it will be really nice.
I would also like to ask you to implement a Custom CSS for the Admin.

It might be already implemented but I couldn't figure out how to load it.
I tried to override the `administrator/components/com_gantry5/css-compiled/admin.css` because as you said in the Gitter chat, the CSS should be overridden, not the SCSS. I created `admin.css` in `g5_hydrogen/admin/css-compiled` but it didn't work.

**Comment by mahagr** [comment]
Need to check that one @JoomFX, maybe it's not using streams, but is hardcoded url.

**Comment by mahagr** [comment]
This feature is now implemented, though not by fixed SCSS file, but by adding support to add SCSS files just like you would add CSS files into your pages:

- Allow custom SCSS files to be inserted from particles and atoms by `<link rel="stylesheet" href="particle.scss" />`
- Allow custom SCSS files to be inserted from both `Page Settings` / `Assets` / `CSS` and `Assets Atom`
