### ISSUE TITLE
Can not install Gantry 5.4.19 plugin or themes on wordpress 4.8.2

### ISSUE THREAD

**Issue by TonyTheTech** [gantry/gantry5#2154]
Affected: Gantry Plugin/Helium Theme/Hydrogen Theme
Gantry Version: 5.4.19
Wordpress Version: 4.8.2

**Steps:**
1. Download gantry5 wordpress files from your official website download page.
2. Attempt to install via wordpress Admin
3. Installation fail with the errors below. 

**Issue:** When attempting to install the Theme or plugins, I get an error similar to the following:

![image](https://user-images.githubusercontent.com/5377158/31980907-8e61fe9c-b904-11e7-8b7c-dc9673b700e8.png)

**Information:** 

**1.** Installing the plugin from within the Wordpress marketplace instead of using the manual upload, allowed the plugin to be installed with no issue. 

**2.** Unzipping the theme locally on my Windows 10 PC and rezipping the file using 7zip into a .zip file, gives it a different error when attempting to re-upload the file. 

![image](https://user-images.githubusercontent.com/5377158/31980991-1879521a-b905-11e7-9c06-4ca9d68310e8.png)

The style.css file does exist in the zipfile, all the template values appear to be smushed together though like the following image. I tried seperating everything on their own line, but it didn't resolve the above style.css error. 

![image](https://user-images.githubusercontent.com/5377158/31981168-45b6b4a6-b906-11e7-9b31-eda4b05c29a8.png)

**3.** Other users have reported this issue in your forum. Seems to have been an issue since 5.4.17

- http://www.rockettheme.com/forum/gantry-for-wordpress/272667-error-could-not-extract-file-from-archive-g5-helium

- http://www.rockettheme.com/forum/gantry-solved-threads/272243-solved-latest-hydrogen-and-helium-templates-don-t-seem-to-be-working?start=0

**Comment by AlienDezine** [comment]
Installing Theme from uploaded file: wordpress-tpl_g5_hydrogen_v5.4.19.zip
Unpacking the package…
Installing the theme…
The package could not be installed. The theme is missing the style.css stylesheet.
Theme install failed.


Same problem here. I did Unpack and repack the file. But that is the message I get from WP.
Would you please help?

**Comment by newkind** [comment]
Did you try to re-zip the package without top level folder? Just all the files and folders inside?

**Comment by AlienDezine** [comment]
I tried to upzip and repack the folder but still got some problems. so I changed the folder name to g5_hydrogen.zip instead of " wordpress-tpl_g5_hydrogen_v5.4.19.zip " and everything was ok. There is something wrong with the name structure wordpress-tpl_g5_hydrogen_v5.4.19.zip maybe???
I am new to Gantry so I don't know much about it.

But anyhow. Thank you so much for your kind assistance, time and concerns guys. 
Thank you again.

Best regards

**Comment by Jahstar402** [comment]
Im so bloody frustrated. I too have this problem and have tried unzipping and rezipping without top level folder to no avail I've changed the zip name and have downloaded it helium and hydrogen from multiple places with same error of: 

Installing Theme from uploaded file: g5_hydrogen.zip
Unpacking the package…

Installing the theme…

The package could not be installed. The theme is missing the style.css stylesheet.

Theme installation failed.

Im only trying to set it on locally hosted box. Is this the problem? I get msg saying its installed but broken due to lack of CSS.. .  . I can find no where else that this is even an issue but this thread. Thank you in advance.

**Comment by newkind** [comment]
Are you sure you are using the proper package with latest version of Hydrogen 5.4.22 ?

Please redownload wordpress-tpl_g5_hydrogen_v5.4.22.zip from https://github.com/gantry/gantry5/releases and try again.

I just checked the file and it looks fine - style.css is there.

**Comment by Jahstar402** [comment]
thank you @newkind . I used the grav-tpl_g5_helium_v5.4.22.zip and it took.

**Comment by newkind** [comment]
Well then obviously you wanted to install Grav version of theme into WordPress. You should use the WordPress version.

**Comment by MaFeSa** [comment]
Hi, I have the same problem with 5.4.22 version!
I'm the only one?

**Comment by xcoded** [comment]
Hi I have same problem, I can not install the Hydrogen, I ve got also missing css style sheet error. I tried to zip it without top level folder, but no resolution.

**Comment by soyfifu** [comment]
Save problem with wordpress-tpl_g5_helium_v5.4.28.zip and wordpress-tpl_g5_hydrogen_v5.4.28.zip and also with joomla-tpl_g5_helium_v5.4.22 and joomla-tpl_g5_hydrogen_v5.4.22.

style.css sheet missing.
