### ISSUE TITLE
Hydrogen: Menu opens only per click

### ISSUE THREAD

**Issue by Omegatcu** [gantry/gantry5#22]
Hello :)

I don't know if you wanted it only that way to work but I would like the option that it opens on hoover.

Its nice for some Pages but most want to use hoover like the RokNav Menu has.

**Comment by JoomFX** [comment]
Yeah, I totally agree with that. Thanks @Omegatcu for opening this issue.

I discussed it with the guys in the Gitter chat, here's what I said:

*Is there going to be another option for the Main Menu (Menu Particle) where you do not need to click in order to expand the Dropdown? I mean as it is in Gantry 4 - you just need to hover over the Main Menu Item and the dropdown appears. The current version (in Gantry5) is great for touch devices (in terms of usability) but there should also be a "Hover" version so some clean/minimal designs can be developed (without the need of the arrow box in the Main Menu)*

And this is what @w00fz said:

*The reason it's click and not hover is for touch devices compatibility. On touch devises there is no concept of hover*

Guys, please consider this. There should be a clean, minimal "Hover Menu". Maybe you can just create a new Menu Particle so we have two options - "Click Menu Particle" and "Hover Menu Particle" :)

**Comment by Omegatcu** [comment]
I understand the "there is no hover for touch devices" but clients & users will just not klick through a Complex menu on their desktop. 

I showed the new template in my friends circle because I want to put together a new design for one of my sites - it was the first question of all "Testusers" why they have to click the menu.

Gantry 4 can do it with RokNav Menu - so I'm pretty sure it´s possible with Gantry 5 as well.

**Comment by mahagr** [comment]
This is going to be one of our main discussion points on todays team meeting. Stay tuned...

**Comment by w00fz** [comment]
Ok I see your guys points I think I can easily change this to detect whether it's a touch device or not and toggle the event trigger between `touch` and `mouseover`.
I'm going to look at it today

**Comment by w00fz** [comment]
We are going to look at the touch/mouseover events for touch devices and desktop. You will be able configure the event trigger for Standard menu entirely and the toplevel of Megamenu, altough the sublevels for Megamenu cannot be triggered by mouseover, it's just not practical and usable.

We are also going to add a way to configure via Styles tab the overlay look (color, opacity).

**Comment by JoomFX** [comment]
@w00fz @mahagr - Thank you very much guys :) It is really much, much appreciated!

**Comment by kevlardev** [comment]
I implemented the configuration of overlay color via the Styles tab fb18c5c99aff95258b322c108a131204bc84c772

**Comment by w00fz** [comment]
We are going to rework the menu pretty much entirely based on the limitations we came across, the great feedbacks provided by you guys and the issues we have found and that have been reported. We have a good plan of attack and to keep things easier to track and maintain I created an unified ticket (see #58) where all the issues regarding the menu are now grouped together.

I'm going to close this issue, if there's anything else to add please feel free to comment in issue #58.

Thank you!
