### ISSUE TITLE
add the abiltiy to add <link href=""> in gantry admin

### ISSUE THREAD

**Issue by shoulders** [gantry/gantry5#2218]
currently in the admin 'Page Settings' you can add custom 'Meta Tags' which works fine.

![image](https://user-images.githubusercontent.com/319997/35185498-78e2897c-fdfd-11e7-8671-1a910beabe01.png)

But I would lithe ability to add such <link> statements as this in the same way as meta tags.

````
<link href="/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon" />
````
The reason is because I have just been adding all of the required icons so I can support all of the various favicon requirements for the different OS and hardware out there. See https://realfavicongenerator.net/ for more specific information but below is an example of the code I need to add.

````
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#4db2b3">
<meta name="apple-mobile-web-app-title" content="QuantumWarp">
<meta name="application-name" content="QuantumWarp">
<meta name="theme-color" content="#ffffff">

````
**NB:** I am aware that you can use the 'Custom Content' box just below which is what I am doing at the minute.

thanks

Joomla 3.8.3
Gantry 5.4.22
Helium Tempalte

**Comment by paulzz3000** [comment]
What's wrong with using it the way you are? That's what it's for.

**Comment by shoulders** [comment]
I have OCD and like things to be neat. :)

If there is an ability to add meta tag then there should be one to add <links>. I would only have one or the other option to keep them streamlined. I appreciated it will not break anything how I am doing it now using the 'custom Code' box which makes the adding 'meta tag' above redundant.

Perhaps remove the 'meta tag' option?

**Comment by paulzz3000** [comment]
Why legislate one way or the other? It's better to have both.  If you have already prepared code, paste it in. If you wanna add one tag (or you're just riffing off the top of your head), use the meta tags. Both are neat.
To me, Gantry is a blessing—in 20-odd years of web dev, and latest five just on Wordpress—it's the best framework I've used, partly because of this kind of flexibility.
To be honest, there might be even better reasons but I'm just a low-level user. :-)

**Comment by paulzz3000** [comment]
And, as an afterthought, you could just add 'link' into the first box then, eg,  rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" into the next.
I think!

**Comment by w00fz** [comment]
If you use the Touch Icon field in the Assets section, you don't have to manually write that in the Custom area.

See https://github.com/gantry/gantry5/blob/develop/engines/common/nucleus/templates/page_head.html.twig#L42-L45

We do cover the most common scenarios and allow for the user input but generally speaking, there are so many different variations and preferences that it is impossible for us to cover them all. That's why we have the Custom Content and there's nothing wrong in using it.

Alternatively, if you are developing a theme, you could expand with your own atom and by extending the page_head you could make it fancier and more in line to what you are thinking.

Hope this helps.

**Comment by shoulders** [comment]
Thanks for the help.

should I close this issue?

**Comment by w00fz** [comment]
Sure go ahead 👍
