### ISSUE TITLE
Duplicated menu items in WP break menu admin

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#2265]
If you have two menu items with the same object_id in the WP menu ie. two same pages - it confuses the hell ouf of the G5 admin and breaks it.

**Comment by mahagr** [comment]
How should it behave? Imho that is a bug in the first place?

**Comment by mahagr** [comment]
For me, it doesn't break the page, but it doesn't display multiple items either.

The issue here is that I cannot use menu item id as WordPress regenerates those when you export/import your site. Now it looks like I cannot use object ids either as they aren't unique...

So basically you don't have any way to associate menu data unless you use the database to store the custom options?
