### ISSUE TITLE
How to call a block of 1 page in function.php? (wordpress)

### ISSUE THREAD

**Issue by minhphong2311** [gantry/gantry5#2280]
I want to get the information in the block out to include in the meta tag on the head written in the function.php file, people help me with.

![untitled](https://user-images.githubusercontent.com/37891754/38984843-05fc5f24-43f2-11e8-8908-e16fe5e21347.png)

**Comment by mahagr** [comment]
Particles aren't really be meant to contain information for the whole page; they are just widgets which are displayed as extra content. There can also be multiple instances of a particle in a single page. Because of this, I don't think that the particle is the right page to even have that information.

That said, there's a way to get particle instance from a page, though it would be hacky as you'd need to have custom code for every page you have.
