### ISSUE TITLE
Full Page Background

### ISSUE THREAD

**Issue by wise-wombat** [gantry/gantry5#2289]
Not sure if this is the correct place to be submitting this, but I am trying to place an image as the background for my site. I can get the image to go full width, but it doesn't go down to the bottom, only to the bottom of the article. Is there a way to make the picture go to the bottom of the screen and maybe even automatically scale to the size of the screen.

**Comment by N8Solutions** [comment]
@wise-wombat Please provide us with a link to your site so we can have a look in order to better understand what you are trying to accomplish. For example, are you trying to have an image as the background for the whole site or just the article section?

I have created a site where all the sections are either fully transparent or semi-transparent with an image in the background that repeats and is in a fixed position.

Once we know what you're after we can help you better.

**Comment by N8Solutions** [comment]
@wise-wombat It's almost midnight here in Greece. I'll take a look at it tomorrow but it seems like it'll be pretty easy to accomplish what you're looking for.

**Comment by wise-wombat** [comment]
Ok, thanks.

**Comment by N8Solutions** [comment]
@wise-wombat Use the inspector tools and have a look at [this site](https://www.xeiropraktiki.gr/en) so you can see what I did with it. Maybe that will help you out in the meantime.

**Comment by N8Solutions** [comment]
@wise-wombat I had a look at your site this morning and it looks like you figured some things out.
Just a couple of suggestions:

1) You don't need to use the `custom.scss` file to make the sections transparent. You can do it through the Styles tab in Gantry. You can adjust the transparency with the slider or you can simply click the button "transparent" to make the color fully transparent for the section. I've attached a picture to better illustrate this.

2) Something you should add to the `custom.scss` for when you have short articles 
```css
#g-container-main {
	min-height: 100vh;
}
```
That will cause the article section to expand preventing items in the footer from pulling up to the middle of the screen.

3) Regarding your background picture. I see that you added it to the `#g-container-main` section. If you decide to make the sections transparent, using the way I described above, you can set the background picture for the `body` of the site instead of a section. 
```css
body {
	background-image: url('../../../../image/_DSC0002edit1.jpg');
	background-repeat: no-repeat;
	background-size: cover;
	background-position: 50% 50%;
	background-attachment: fixed;
}
```
You'll also notice I added `background-attachment: fixed;`. That will cause the picture to stay fixed while the content moves on top of it.
Adding a background picture to the `body` of the site is like this is really the better way to go, especially if you start adding content to other sections of the site. It will insure that you always have a background picture in place. This is up to you though and what kind of look and style you want your site to have.

Let me know if you have any questions.


![image](https://user-images.githubusercontent.com/12389693/39506713-f96b506c-4de2-11e8-8a95-0b82b863ca73.png)

**Comment by wise-wombat** [comment]
Thanks, I'll give that a try.

**Comment by N8Solutions** [comment]
If it works for you let me know and close the ticket. It'll help cut down the work the Gantry guys have to do :wink:

**Comment by wise-wombat** [comment]
Yep i believe that all worked. Thanks!!!

**Comment by wise-wombat** [comment]
Thanks for all the help! I think the site looks pretty good now.

**Comment by N8Solutions** [comment]
Please see this.

https://github.com/gantry/gantry5/issues/3171#issuecomment-1681069321
