### ISSUE TITLE
A second level container in the default.yaml don't work

### ISSUE THREAD

**Issue by oakmountain** [gantry/gantry5#2374]
Hello I'm using a template from Inspire Theme, called "Headline". This template has a container on the first level in the default.yaml.
Now I want to wrap the Header and Navigation in a new container. I tried it like it is shown on the [video](https://youtu.be/rvT0vth6Wzk), but it doesn't work, like you see in the screenshots. A second level container does not allow me to access its settings (the cog wheel icon is missing in the Layout Manager). I think that this is a bug/limitation in the Gantry 5 framework.
![default-yaml](https://user-images.githubusercontent.com/43598784/46062178-464d5480-c169-11e8-9a5a-a360a1de8902.jpg)
![base-outline](https://user-images.githubusercontent.com/43598784/46062194-536a4380-c169-11e8-8927-33e7b52b9318.jpg)

**Comment by N8Solutions** [comment]
@oakmountain I haven't tried putting a container inside a container before but 2 things come to mind.

1. This functionality is probably intentional on the side of the developers. @w00fz & @mahagr would be able to better answer that.

2. If this is suppose to be possible you need to make sure that you are using `spaces` in your file instead of `tabs` as twig does not like tabs.

**Comment by mahagr** [comment]
Nested containers do not really work because of limitations on layout manager JS (by design). You may want to create separate containers for the sections instead.

**Comment by oakmountain** [comment]
OK, thank you for your help. I found a solution without second level container.
