### ISSUE TITLE
Particle cache not related to the page in production mode

### ISSUE THREAD

**Issue by salgua** [gantry/gantry5#2391]
I'm using Gantry 5.4.26 on Grav 1.5.3. 
In a custom particle I dynamically load a collection from the page (it's a slideshow). It works fine with Gantry in development mode. If I put Gantry in production mode, the particle loads the content once, after empty cache, then browsing page with the same layout, it doesn't load the content dynamically and loads always the same content/images.
it seems that particle cache, in production mode, is not related to the page but only to the Gantry layout.

**Comment by mahagr** [comment]
Yup, that is how the static caching works. If you have dynamic content in your particle, you need to remove the caching part in YAML file.

**Comment by salgua** [comment]
I found it! I have to remove:

    configuration:
        caching:
            type: static

Thank you!

**Comment by N8Solutions** [comment]
@salgua & @mahagr Instead of removing that could the `type` simply be changed to `dynamic` instead of `static`?

**Comment by mahagr** [comment]
There are 2 other types of caching, but those aren't "supported" right now as there are some issues with those approaches.

Yes, you can either just change the type to dynamic or just remove the lines.

**Comment by N8Solutions** [comment]
> There are 2 other types of caching, but those aren't "supported" right now as there are some issues with those approaches.

@mahagr I wanted to check in to see if the other options are supported yet? I am having a problem with a Gantry 5 Particle Joomla Module where it is not updating properly and must be related to caching.

The particle shows business hours. With the July 4th holiday coming up and the business closing for another day towards the end of the month, I have 5 of these Gantry 5 Particle Joomla Modules.
The standard business hours one was set to expire last night at midnight.
The July 4th holiday hours module was published to start at 00:00:00.
They both expired and published as expected.
However, the problem is that the hours did not change on the site even though they were set properly in the particle after it was published.
I checked the .yaml file and it does not have caching set, ie, this is missing from the file:
```yaml
configuration:
  caching:
    type: static
```
Caching for the Joomla modules is set to `no caching` so that's not the problem.
No apps like JCH are running so that wasn't the problem.
It wasn't the CDN because I bypassed it and the problem still existed.
I cleared the browsers cache and refreshed the page and still nothing.
I checked the hours entered for the module and they were correct.

What fixed the issue was when I went back in to the currently published module and saved it again.
After saving the module again, I refreshed the page, without clearing the browsers cache, and the module was showing the proper holiday hours.

Since the caching configuration is removed from the yaml file, and the module is set to no caching, I would expect the module to show the proper information without me having to go back in and saving it again.

Does this behavior sound normal to you?
Is there something else I should try doing like adding the caching configuration set to dynamic if only to server as an interrupt for the static setting?
```yaml
configuration:
  caching:
    type: dynamic
```
Any advice here would be greatly appreciated.

Cheers!

**Comment by mahagr** [comment]
Right now there are 4 cache types:
* `static` - **never** updates, cached forever
* `menu` - because of issues, commented out in the code
* `config_matches` - static caching, but allowing particle option to control it
* `disabled` - never cached

This caching is only being used inside Gantry -- if you're using Joomla module, it uses Joomla caching.

**Comment by N8Solutions** [comment]
> This caching is only being used inside Gantry -- if you're using Joomla module, should be using Joomla caching instead.

Thanks for the reply @mahagr 

So if I understand you correctly, even though it is a "Gantry 5 Particle" Joomla Module, it still uses Joomla caching no matter what?

If that is correct, any idea as to why this happened?

**Comment by mahagr** [comment]
I cannot remember how I did it, but I think that in modules it prefers the module caching settings. There may have been some logic to customize Joomla caching, I cannot remember.

**Comment by N8Solutions** [comment]
OK, thank you for the response @mahagr. I will work on troubleshooting this some more in a test environment to see what I can come up with. Once, and if, I'm able to reproduce the issue, I'll report back with my findings.

**Comment by mahagr** [comment]
Did you check with development mode as it turns off all particle caching..?
