### ISSUE TITLE
PHP 7+

### ISSUE THREAD

**Issue by davor77** [gantry/gantry5#2409]
Hi 

I am using timesfx theme and i have a problem when using PHP 7.x
with message
 Deprecated: Function create_function() is deprecated in C:\wamp64\www\ams\libraries\gantry\core\gantry.class.php on line 1043

Thank you

**Comment by JoomFX** [comment]
Hello there,

TimesFX is not a Gantry 5 template, it is a Gantry 4 template.
And this place is for Gantry 5 related issues only.

TimesFX is a 3rd party template so you need to use the contact form on the [developers' page on Themeforest](https://themeforest.net/user/joomfx?ref=joomfx) in order to get in touch with them.

**Comment by mahagr** [comment]
Also make sure that your Gantry 4 version and theme are up to date.

**Comment by davor77** [comment]
Thank you for a quick reply
