### ISSUE TITLE
How properly I can create new theme based on Helium ?

### ISSUE THREAD

**Issue by tetak99** [gantry/gantry5#2417]
Hello,

I have installed Gantry 5 framework and Helium theme. So please can you tell me how can I properly create new Wordpress theme based on Helium ? I want to create a new style, and later sell it on Themeforest. But I dont know what is best way to do that ? 

I can adjust all theme files from css-compiled folder,  and if I adjust style from css-compiled folder, how to protect if from updates and return to default css.

or is it better to create a new css file ?

Because i am not sure if is a good thing to override many things ?

http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet

Thank you

**Comment by newkind** [comment]
Please **DON'T** do any manual modifications to the `css-compiled` directory as they will always get overwritten. What you want to do is the edit the `*.scss` files under `scss` directory. These files then do get compiled by Gantry into the `*.css` files that you can see under `css-compiled.`

If you want to add new files to the theme just add them to the `scss` directory ie. `_my-new-file.scss` and then import it in the main `helium.scss` file.

You then need to either `Recompile CSS` via Gantry admin or enable the **Development Mode** so the CSS will get recompiled on each page refresh.

**Comment by adiwebdev** [comment]
You can use helium / hydrogen as a base for your new theme, you might want to get used to SCSS, TWIG and read [Theme Development ](http://docs.gantry.org/gantry5/theme-development) chapter.

**Comment by adiwebdev** [comment]
If you use Helium theme, those changes will be overwritten, so use `custom` folder.

**Comment by tetak99** [comment]
> If you use Helium theme and modify `scss` directory, those changes will be overwritten. What you did is right, follow the tutorial and use `custom` folder.

So, it's completely okay to create a new style in custom folder following [these instructions](http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet). Because later when i am done, my style will overriding Helium style.

Thanks

**Comment by JoomFX** [comment]
> _I have installed Gantry 5 framework and Helium theme. So please can you tell me how can I properly create new Wordpress theme based on Helium ? I want to create a new style, and later sell it on Themeforest._ 

You cannot sell WordPress Gantry 5 Themes on Themeforest because they do not accept Twig files.
For more details, have a look at [this discussion](https://forums.envato.com/t/twig-and-wordpress/46588).

> _Also, at this moment, I started to do modifications, but in different way using this tutorial: http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet_

If you build your own theme, which you are planning to sell, then you should not have a **custom.scss** file. The theme must come without the **custom.scss** file because this file is reserved for the end user to do the adjustments and customization they want.
When you build your own theme you need to edit the core SCSS files without caring about Helium updates.
Since this will be your own theme, you no longer need Helium updates. From now on you will be the one responsible to updating your own theme and fixing bugs in it.

**Comment by JoomFX** [comment]
Yes, I'm pretty sure.
But you can always contact them directly and double-check.

**Comment by tetak99** [comment]
ok. To be sure, i will contacnt them see what they will say.

Thanks
