### ISSUE TITLE
Helium Joomla registration form

### ISSUE THREAD

**Issue by svanschu** [gantry/gantry5#2439]
I installed the Helium template. On the joomla startpage I activated the "Theme Outline" "Home - Particles". As joomla default template "Theme Outline" "Standard"

I put the LogIn Form into the menu. If I click the "register" link it loads the right page, but with the "home - Particles" Layout.

If I made the "Standard" layout the layout of the startpage, the register link loads as expected.

I only want the "Home - Particles" Layout only on the startpage. Register etc. should load with the default "standard" layout.

Did I miss something or is this a bug?

**Comment by simmonsr** [comment]
You'll want to set the Default - Helium as the default (starred template). And Home as assigned to your Home menu. That's the typical setup we have our users doing.

**Comment by simmonsr** [comment]
For more information on Assignments, please see:

http://docs.gantry.org/gantry5/configure/assignments

**Comment by simmonsr** [comment]
The Register button link may require a separate menu by itself. Are you using any 3rd party extensions like Ohanah or JoomlaTools extensions (such as Joomla Tools framework / Nooku)? We have had issues with these plugins messing up assignments:

http://docs.gantry.org/gantry5/troubleshooting/assignment-issues

**Comment by joomlabeat** [comment]
@svanschu 
Just create a menu item for the com_users registration/login view - that's a good practice. Then the module's link should route you there with a nice sef url. You can then assign any template styles, modules etc that you desire on that menu item. 

Also note that for such "generic" Joomla questions (this is not strictly gantry related) it's better suited to ask on joomla forum or Joomla Stack Exchange site https://joomla.stackexchange.com.

**Comment by svanschu** [comment]
Thank you, this trick does help.

Even if it is a "generic" Joomla question, an entry in your FAQ or docs would be nice. It is always a problem to find the right place to ask those questions.
With Protostar it worked, with your template not. That's why I asked the question in here.

Thank you

**Comment by joomlabeat** [comment]
@svanschu - you are welcome! I am not part of the Gantry team - just a user/fan of Gantry5. My recommendation for posting such questions to other sites is only my personal tip for you, in order to help you getting answers - while keeping in mind that a github issues section should remain clean and focused on issues related to the dev side of things of the specific project. Joomla Stack Exchange site is a good place to search for answers. Most likely the majority of such questions has been asked and answered already - if not, you can post a new question. I am a moderator there and you are welcome to open up an account and participate (read the help section of that site before doing so). 
Best wishes for the season's holidays and a happy new year.
