### ISSUE TITLE
watchful.li stuck in update loop from 4.1.37 to 4.1.39 xml

### ISSUE THREAD

**Issue by jgallias** [gantry/gantry5#2458]
I use the watchful.li monitoring platform, and it keeps saying I need to update Gantry 4.1.37 to 4.1.39, but when I login to either Joomla! site it is already running 4.1.39! If I run the updater, it will say it's up to date for a brief moment, then send me another e-mail saying it needs to update form 4.1.37 to 4.1.39 again! Please help me break this loop!

I reported the issue to wathful.li but this was the response:
"This is an issue in Gantry package, they have some wrong version in their xml files. Nothing we can do about it, it has to be fixed by Gantry devs."

Any assistance is greatly appreciated!
Thanks.

**Comment by N8Solutions** [comment]
Hello @jgallias 

First, I want to point out that you are referring to Gantry 4. This area is for the Gantry 5 Framework and related free themes of Hydrogen & Helium. Since your question has to do with Gantry 4 please continue this discussion in the Gantry 4 Chat room here.
https://gitter.im/gantry/gantry4
I (a volunteer), or someone else from Gantry, will respond to it there. Please close this issue after you read this.

regards,

Michael

**Comment by mahagr** [comment]
Closing as the issue does not affect this project/product.
