### ISSUE TITLE
Access to atom values or to other particles

### ISSUE THREAD

**Issue by plnabais** [gantry/gantry5#2465]
Hello, I need to access the value of some variables stored in a atom but when I try to access it from another particle can't access to the correct values. 
For example when I try access to {% set aaa = gantry.config.get('particles.analytics.enabled') %}
the value of aaa do not return the correct value stored in the analytics atom. 
Can anybody help me to understend what I have to do to access the value stored in the atom.

**Comment by plnabais** [comment]
What we have to do to have some kind of interaction with anybody?
Best Regards

**Comment by blizam** [comment]
Your syntax looks OK to me...

That should set 'aaa' to either 'true' or 'false' IF the atom is enabled for the give page/Outline

**Comment by marktaylor46** [comment]
I did already answer this in the RT forum. It is not going to pull the atom instance value... it's only going to get the "default" value for the atom.

![2019-02-25_16-27-10](https://user-images.githubusercontent.com/11683218/53352264-62247480-391a-11e9-8c67-7dc4f6781d2a.png)


Regards, Mark.

**Comment by plnabais** [comment]
Thank you Mark, but as we have allready discussed I need to access to the values stored in the atoms particles of the current page. Access to the defaults values do not make any sense to me. I can understand why is dificult access to the values of standard particules, but not to the atom particles wo can be used to store comon parameters to the particles present in the page

**Comment by marktaylor46** [comment]
Atoms are just another flavour of particles. They are still "instances" when assign on the atom section. For example, you can assign as many "instances" of the same atom on the atom section as you like:

![2019-02-25_17-01-52](https://user-images.githubusercontent.com/11683218/53354668-2fc94600-391f-11e9-89c8-71dd486eea28.png)

How would you know which one you wanted to get the settings from? 

As far as I know there's no mechanism to obtain values from specific particle/atom instances.

Particles and atom (though modular design) are supposed to be independent and self-contained.

Where a setting needs to be shared (e.g. accent color) these are set up in the "styles" tab of the template and then the particles/atom access those values. Similarly in CSS you can set you own variables that you can use in multiple particles.

Regards, Mark.

**Comment by plnabais** [comment]
Thanks Mark for the clarifications, but I am developing a particle that shows content that depends on several parameters, 2 which are common to all instances of the particle present on the page. It made sense for me to use the atoms to keep these parameters, avoiding being duplicated in all the particles present. As for the fact that there could be several instances, could be solved with an array as in all cases similar to this. It would be for me an important and synonymous functionality of flexibility, however I understand that not everyone thinks like me.
I noticed from our exchange of previous impressions that I should put the question in this forum and that there could be some way to access that content. Apparently it was wrong.

Thank you and best regards.
Paulo

**Comment by blizam** [comment]
You could potentially still have an Atom output it's parameters into HTML or the DOM and then have your Particle(s) grab those parameters after the page/DOM loads.

Otherwise, yes, you'll have to keep those parameters in the particle itself

**Comment by marktaylor46** [comment]
Just to clarify where to ask questions:

- If your question is about a RocketTheme template or extension then you should ask in the RT forum
- If you believe you have found a bug in Gantry 5 Framework, or have a suggested improvement, then you raise an issue here.
- If you have general development "how to"  or "best technique" questions regarding the Gantry 5 framework then it's best to ask in the github chat project for Gantry 5 as this is where you will find a whole community of like-minded developers who will be able to make suggestions.

Returning to your question:

I really don't think you should have atoms/particles trying to get values from other atom/particles at all. "common" settings should be in the template "styles" settings which the atom/particles can then access. This is exactly what we do in the RT templates (e.g. accent color). 

That said, if you want a common value for a particle (not atom) then the technique your are using at the moment does get the "default" value for a particle type and you can change that value on the base outline "particle defaults" tab. What you can't do is get a value from particle/atom instances because there can be many of them and there's no way to state or identify which instance you want the value from.

Personally, from a modular point of view you should either keep the value within the particle/atom instance you are using or use the "styles" tab for "common" settings.

Regards, Mark.

**Comment by plnabais** [comment]
Thank you, Matt and Mark for your inputs,
Best regards,
Paulo

**Comment by mahagr** [comment]
It is possible to get all the particles and their configuration, but this really needs some custom PHP code in order to do what you want (as you shouldn't really write application logic into a template file).

**Comment by plnabais** [comment]
Hello Mathias, how can I access to the particles configuration via PHP ?
Best regards

**Comment by mahagr** [comment]
In PHP you can do something like this:

```php
// Render particle by id.
$gantry = Gantry\Framework\Gantry::instance();
$theme = $gantry['theme'];           
$layout = $theme->loadLayout();
$particle = $layout->find($id); // See Gantry\Component\Layout\Layout for what you can do
```

Looks like it works from Twig, too:

```twig
{% set particle = gantry.theme.loadLayout().find(id) %}
```

Should work too.
