### ISSUE TITLE
Featured Image Issue on Single Post (Wordpress)

### ISSUE THREAD

**Issue by chhinsras** [gantry/gantry5#2466]
I installed gantry with helium theme. Then, I created a new post. I go to it specific new post. It show okay. But when I added featured image to that post. Then, I go to specific post again. It does not show any thing (NO ERROR shown at all). I checked all created posts with feature image before installing gantry and helium. It showed fine.

Another scenario: I duplicate the old post. Just make edition. It showed fine.

Please help me. why when I create new post and add feature image. It does not work. I dont want to duplicate post

**Comment by DamirPecnik** [comment]
What version of WordPress? What's your setup, what plugins do you have installed?

**Comment by chhinsras** [comment]
I installed fresh new WordPress latest version 5.0.3 with latest version of gantry. Only thing I migrated posts from my existing WordPress.

**Comment by newkind** [comment]
Please enable WP_Debug in wp-config.php and enable debug in Settings > Gantry5 and post a link to your site.

**Comment by chhinsras** [comment]
> Please enable WP_Debug in wp-config.php and enable debug in Settings > Gantry5 and post a link to your site.

I did following your suggestions: here is the link to my site: https://crmngo.000webhostapp.com

**Comment by newkind** [comment]
For me the post you linked is still broken - empty white space, however other posts and featured images are working fine : https://monosnap.com/direct/VM3wDVsxxmI9AnkEbKIyzq6KHFLg2T

This means that there's either something wrong with your image or this particular post (other posts using the same template file are working fine). Since the page doesn't render any output at all - even with debug on - you'll have to check the PHP logs on your server. If you don't know how to do that, please ask your hosting provider to tell you where to locate them.

The only thing I can suggest besides checking logs is you to try to copy the whole contents of the post, delete it, recreate it again and try filling elements one by one, previewing the post after each of them to see where it breaks ie.

1. Create a new post
2. Paste the title and Publish
3. Refresh front end post page to see if it works
4. If it works, paste the post content, publish
5. Refresh the front end post page to see if it still works
etc.

At one point you should see what's failing and then we'll know where to look for the issue.

**Comment by chhinsras** [comment]
> For me the post you linked is still broken - empty white page, however other posts and featured images are working fine : https://monosnap.com/direct/VM3wDVsxxmI9AnkEbKIyzq6KHFLg2T
> 
> This means that there's either something wrong with your image or this particular post (other posts using the same template file are working fine). Since the page doesn't render any output at all - even with debug on - you'll have to check the PHP logs on your server. If you don't know how to do that, please ask your hosting provider to tell you where to locate them.
> 
> The only thing I can suggest besides checking logs is you to try to copy the whole contents of the post, delete it, recreate it again and try filling elements one by one, previewing the post after each of them to see where it breaks ie.
> 
> 1. Create a new post
> 2. Paste the title and Publish
> 3. Refresh front end post page to see if it works
> 4. If it works, paste the post content, publish
> 5. Refresh the front end post page to see if it still works
>    etc.
> 
> At one point you should see what's failing and then we'll know where to look for the issue.

As I mentioned earlier. Creating new post without feature image or remove feature image from that post are just working fine. The thing is when creating new post and add feature image. this problem happends

**Comment by newkind** [comment]
Does it happen with all images? Can you try an image from another post that you knows that works fine?

**Comment by chhinsras** [comment]
I have tried. It clearly demonstrated that creating new with featured image won't work.
1. Create new post without featured image (WORK)
2. Duplicate from old post with or without featured image (WORK)
3. Create new post with featured image (DOESNOT WORK)

**Comment by newkind** [comment]
DId you check your PHP logs? Is there anything in the logs?

**Comment by chhinsras** [comment]
Hello everyone.

Just updating you. The problem is fixed now. I don't know why too. 

What I have done are Update Wordpress to 5.1.1 and Update Gantry to the latest version.

Unexpectedly, I noticed the raised issue has gone.

Please let me know if anyone knows the root cause.

Thank you

**Comment by newkind** [comment]
Most likely PHP 7.3 issue with `cropzoom` filter fixed in latest Timber version. We always update Timber to the latest when releasing G5 update.

Anyways, I'm glad it's fixed!

**Comment by chhinsras** [comment]
I hope it won't coming back.
