### ISSUE TITLE
Nucleus grid calculation overlaps are not tight enough

### ISSUE THREAD

**Issue by blizam** [gantry/gantry5#2492]
/engines/nucleus/scss/configuration/nucleus/_breakpoints.scss
/engines/nucleus/scss/nucleus/mixins/_breakpoints.scss

This is a 1px issue present in both Chrome and Mozilla

The calculations there of + 0.062rem or - 0.062rem which creates a gap of  0.058px if 16px base rem.

In chrome or mozilla, if you put the browser on the exact edge of any of these breakpoints no CSS within Nucleus' breakpoints is applied... 

you can test here: http://demo.gantry.org/

at 1199px, 959px, and 767px... g-container is the easiest thing to look at

Changing the 0.062 values to 0.00125 resolved the issue for me which creates a gap of 0.019px

**Comment by adiwebdev** [comment]
IMHO the mixin should work slightly different, for example, this code
`@media only #{$media} and (min-width: $breakpoints-large-mobile-container + 0.062rem) and (max-width: $breakpoints-tablet-container - 0.062rem) { @content; }`

should be
`@media only #{$media} and (min-width: $breakpoints-large-mobile-container) and (max-width: $breakpoints-tablet-container - 0.062rem) { @content; }`

and this
`@media only #{$media} and (max-width: $breakpoints-large-mobile-container) { @content; }`

should be
`@media only #{$media} and (max-width: $breakpoints-large-mobile-container - 0.0625rem) { @content; }`

Also, the `container` should use `max-width` instead of `width`.

**Comment by blizam** [comment]
can this pretty please be addressed? I hate not being able to use the breakpoint mixins out of the box because there's a 1px gap at the range edges

**Comment by simmonsr** [comment]
Try CI Build, but there should no longer be any gaps:

http://gantry.org/downloads#ci-builds

**Comment by blizam** [comment]
> 
> 
> I'm just not seeing this "gap" that you guys are talking about specifically when using rem:
> 
> http://demo.gantry.org/

Windows 10, Firefox 75, 959px: https://imgur.com/a/32bQc7a
No media query is applied, the non-flush g-containers revert to their base width

.... but ya know what... I used to be able to do the exact same thing in Chrome... certainly back in May on #2492 I could do it in Chrome... but I can't anymore, 959px works fine

The compiler seems to be ok with 0.01rem, it's a tighter gap which I don't think anyone would argue is a bad thing and it's inline with other projects and recommendations out there; and it definitely resolves the issue in FF... so I would still push for that if possible.

**Comment by morphinestyle** [comment]
WOW! Works great!
All perfect working with px!
Also **Responsive Utility Classes**: `visible-phone`, `visible-tablet`, etc.

Thank you!
