### ISSUE TITLE
Simple Image Gallery conflict with Gantry CSS

### ISSUE THREAD

**Issue by LukeDouglas2** [gantry/gantry5#2495]
I am having an issue with thumbnails on Simple Image Gallery.  Here is the response from the JoomlaWorks development team.

-----------------------------------------------------------------------------
This is what kills paddings, margins etc. in SIGPro...

In https://vocalonline.org/media/gantry5/engines/nucleus/css-compiled/nucleus.css and around line 45:

*, *::before, *::after {
box-sizing: inherit;
}

If you comment out this rule it will probably restore other parts in your site that may have broken after the Gantry update. **Frankly, this is bad CSS because it applies a universal rule.**

If you wish to enforce the plugin to ignore these rules, simply open the gallery's CSS file and add "box-sizing:content-box !important;" on the <a> and <img> elements.

The result: https://jmp.sh/a8fuGgT (see how I disabled that rule on Chrome's CSS inspector - bottom right).
-----------------------------------------------------------------------------

So do they have a point on the CSS issue in the 'nucleus.css'?

**Comment by adiwebdev** [comment]
This is how nucleus code should be:

```
html { box-sizing: border-box; }
*, *:before, *:after { box-sizing: inherit; }
```

The default box-sizing is `content-box`. But, many projects, including gantry use something else.
The first part of the code is meant to reset the `box-sizing` to `border-box`, while the second part makes it easier for other components to change the box-sizing as needed.

If disabling that rule fixed the issue, then it might be because they use content-box. In my opinion would be better if they set the intended box sizing at extension level. I mean, you can't assume that every single template will use `content-box`.

Something like:
```
.sigFreeClassic { box-sizing: content-box; }
```

This [article](https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/) from CSS Tricks explains it in detail.

**Comment by mahagr** [comment]
@LukeDouglas2 Can this issue be marked as solved?
