### ISSUE TITLE
Jquery error with getElementById

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#252]
Setup:
Local MAMP for WINDOWS - PHP 5.6.3 - Joomla 3.4.1 - joomla-pkg_gantry5_v5.0.0-rc.1 - joomla-tpl_g5_hydrogen_v5.0.0-rc.1 - FireFox 38

I get this error in the FireFox Console while in the Joomla Control Panel Admin screen:
Empty string passed to getElementById(). 	jquery.min.js:2:0

The error repeats itself 9 times when I click on any empty spot on the page

**Comment by w00fz** [comment]
We don't use jQuery at all in Gantry5 nor in the themes, I have doubts that this issue is related to us at all.
If it is, that above is not enough informations :)
Did you try with no gantry to see if you still get the error? This is admin correct? What page are you in?

// Djamil Legato // From iPhone //

**Comment by DanGthatRokGallery** [comment]
Your correct its a J34 and FireFox issue.
