### ISSUE TITLE
Gantry 5 with Virtuemart issue, when recharging prices with multiple sending options

### ISSUE THREAD

**Issue by JimmyGuiu** [gantry/gantry5#2553]
Hi,
It's seems I found a incompatibility between Gantry 5 and Virtuemart.

The problem:
On purchase confirmation page of Virtuemart, when there are multiple sending options the sistem doesn't recharge the price if Gantry 5 is on use. I've tried with other templates, like Beez3, and the recharge is ok.

Is there a solution to fix it?

**Comment by thexmanxyz** [comment]
@JimmyGuiu I also wrote you on the Gitter channel please provide us a Screenshot of the browser console. There might appear a JS error when you execute the steps which result in the problem (not recalculating the price). If no JS error message appears you can omit adding the screenshot. But if there is an error please attach it to this issue and on Gitter so that we can check. Thanks.

**Comment by JimmyGuiu** [comment]
Hi, 
Let's go with the screenshots. The first one the browser console with mistakes when Beez3 template is loaded and the seconth with Gantry 5 Hydrogen.

This is url sites: https://www.mobiliarioficina.es
You can access with this username and password, both: pruebas33

Beez 3
![Beez3](https://user-images.githubusercontent.com/56632568/66915324-0463aa80-f019-11e9-9c69-e7c01b30707c.jpg)

Gantry5 Hydrogen
![Hydrogen](https://user-images.githubusercontent.com/56632568/66915444-4f7dbd80-f019-11e9-9bf2-3d112613943d.jpg)

**Comment by thexmanxyz** [comment]
@JimmyGuiu 

As I assumed it is a JS error. It is not a JSON error it is a error of a Virtuemart JS library not loaded correctly this can have multiple reasons. The highest probability for that error is, that the JQuery library is not loaded or there is some issue with JQuery or the library loaded by Virtuemart.

I have to ask you to provide additional information and attach it to this issue. So please provide us a listing of the `<head>` tag once with Gantry and once with an other theme where there is no issue. 

Please provide us the `<head>` content of the page where the error occurs so that we can verify what library is missing or what JS file is not getting loaded correctly. So you might be able to add a quick fix by loading that library manually. But we will see. Please attach those two listings (content within `<head>` tag as well to this issue).

**Comment by thexmanxyz** [comment]
@JimmyGuiu Oh i missed that you already provided the credentials I will check thanks!

**Comment by thexmanxyz** [comment]
Gantry loaded JS files
```HTML
<script src="/media/system/js/mootools-core.js"></script>
<script src="/media/system/js/core.js"></script>
<script src="/media/system/js/mootools-more.js"></script>
<script src="/media/plg_system_sl_scrolltotop/js/scrolltotop_mt.js"></script>
<script src="/media/jui/js/jquery.min.js"></script>
<script src="/media/jui/js/jquery-noconflict.js"></script>
<script src="/media/jui/js/jquery-migrate.min.js"></script>
<script src="/templates/g5_hydrogen/html/com_virtuemart/assets/js/materialize.js"></script>
<script src="/templates/g5_hydrogen/html/com_virtuemart/assets/js/flexible.js"></script>
<script src="/components/com_virtuemart/assets/js/jquery-ui.min.js"></script>
<script src="/components/com_virtuemart/assets/js/jquery.ui.autocomplete.html.js"></script>
<script src="/components/com_virtuemart/assets/js/jquery.noconflict.js" async=""></script>
<script src="/components/com_virtuemart/assets/js/vmsite.js"></script>
<script src="/components/com_virtuemart/assets/js/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
<script src="/templates/g5_hydrogen/js/dynupdate.js"></script>
<script src="/components/com_virtuemart/assets/js/vmkeepalive.js" async=""></script>
<script src="/modules/mod_bt_login/tmpl/js/jquery.simplemodal.js"></script>
<script src="/modules/mod_bt_login/tmpl/js/default.js"></script>
<script src="https://www.mobiliarioficina.es/modules/mod_flexible_vm3_cart/assets/js/flexible_update_cart.js"></script>
<script src="/media/jui/js/bootstrap.min.js"></script>
<script src="/media/widgetkit/uikit2-fffe5bee.js"></script>
<script src="/media/widgetkit/wk-scripts-1cac7a59.js"></script>
```

I assume that the JS file `dynupdate.js` is not loaded because that should be the file which contains the function which is not found.

**Comment by thexmanxyz** [comment]
I already found the issue i guess. Please copy the `/templates`/beez3/js/dynupdate.js` to `/templates/g5_hydrogen/js/dynupdate.js`. IDK why this happened but this might be the issue. Please make a backup and do not override the existing file!

**Comment by JimmyGuiu** [comment]
Thanks Andreas, I really appreciate.

**Comment by thexmanxyz** [comment]
@JimmyGuiu You are very welcome! Did this fix your issue? Please report that issue to Virtuemart so they can look after why the wrong is placed within the template directy of Hydrogen! Thanks!

**Comment by JimmyGuiu** [comment]
I'll revise the theme in other webs, it looks like to someone changed the content of this file on server folder. When I have clear the situation I reporting to Virtuemart.

**Comment by thexmanxyz** [comment]
@JimmyGuiu Alright! If you have the feeling, that Gantry is still the problem, please reopen the issue! Thanks and I wish you the best ;-).
