### ISSUE TITLE
Can't add rel="nofollow" to menu links

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2573]
In the Gantry 5 menu editor there is no possibility to add rel="nofollow" to the link. Data attributes are applied at the LI level (which is no good).

original forum topic: https://rockettheme.com/forum/joomla-template-ambrosia/282803-nofollow-menu-link

**Comment by thexmanxyz** [comment]
@marktaylor46 This is related to #2541 and 408f51dfba3366d8d265da3e46ebb86c8de2cded. Can you please clarify why it is not good to add attributes on `<li>` level? 

The `rel="nofollow"` should actually be applied in dependence of the link type (external / internal) or the actual `target` attribute but not forced manually. So if this issue is not related to manually adding additional attributes but rather only targeted on the `rel` attribute I would suggest to add this attribute depending on the link type and not manually apply this attribute on user level. But I agree it might be useful to apply attributes on the `<a>` as well as on the `<li>`. Please report back and I will target this issue in a PR.

**Comment by thexmanxyz** [comment]
@marktaylor46 Please cite the relevant posts from the RocketTheme forum as not all people are able to read the closed forums. Thanks in advance.

**Comment by marktaylor46** [comment]
I said "no good" not "not good" - rel="nofollow" has to be added on the <A> tag not the <LI> tag that surrounds it. In Gantry 5 menu editor attributes can be added but these are added to the<LI> tag for the menu item. Yes I am aware that this really only applies if the link is an external link and there is a rel attribute in Joomla menu manager - but this does not get rendered by the Gantry 5 menu.

I did cite the topic and I am well aware that only subscribers can access that ticket - I added it for the benefit of RT staff (of which I am one).

**Comment by thexmanxyz** [comment]
@marktaylor46 Sorry I'm no native English person. I know where the `rel="nofollow"` has to be added and that this attribute is not valid for `<li>` tags under W3C standard. That was not the point.

But after reviewing the menu generation code I know now that there is already a routine which generates the `rel` tag for `<a>` tags within the menu. The question is if there is something missing or if the `.rel` variable is inherited from another twig file. Please check the corresponding lines in the [twig 1](https://github.com/thexmanxyz/gantry5/blob/408f51dfba3366d8d265da3e46ebb86c8de2cded/engines/common/nucleus/particles/menu.html.twig#L45) / [twig 2](https://github.com/thexmanxyz/gantry5/blob/408f51dfba3366d8d265da3e46ebb86c8de2cded/engines/common/nucleus/particles/menu.html.twig#L58) file. You are wrong the `rel` is rendered by Gantry 5 menu as everything rendered within the menu DOM gets rendered by Gantry.

Yes you did cite the topic but that would not help the community to propose a fix for the issue. So I kindly asked that you can please post at least the important parts of the conversation or the content of the conversation so that people who are not paying for subscription can contribute. It might be useful for RT as well as stuff gets faster fixed.

There was a FR for adding attributes on the `<li>` tag but we can extend this on the `<a>` tag as well this is no problem at all. But as already outlined above there is already a routine for generating the `rel` attribute. So the question is, where this variable originates. I'm not sure if there is something missing in the code base or if it is somehow passed over from the CMS. But I will check on that in the next 1-2 hours or if @mahagr answers.

@mahagr Do you know where the `.rel` [here](https://github.com/thexmanxyz/gantry5/blob/408f51dfba3366d8d265da3e46ebb86c8de2cded/engines/common/nucleus/particles/menu.html.twig#L45) originates. Because it is not within the YAML files!

**Comment by marktaylor46** [comment]
Here are some screenshots for Joomla....

![2019-12-05_08-34-27](https://user-images.githubusercontent.com/11683218/70218024-2684c980-173a-11ea-9c61-9de54578ec5b.png)

![2019-12-05_08-33-31](https://user-images.githubusercontent.com/11683218/70218032-2ab0e700-173a-11ea-9776-e54ff451d4db.png)

My point was that user tried to add the rel attribute in Gantry 5 menu editor using the "tag attribute" field - but those get rendered on the LI tag so that is "no good" for this use case.

I would also add that a solution must be implemented for all three CMSs (Joomla, Wordpress and GRAV) - they all have equivalents. So that either means code for each CMS or a "generic" Rel attribute field adding to Gantry 5 menu editor that could be used for all three CMSs.

**Comment by thexmanxyz** [comment]
@marktaylor46 Thanks for your answer and clarification and screenshots. I already got your point from the beginning of the conversation and that the tag attributes are currently exclusive for `<li>`tags. But I'm no friend of explicitly defining the `rel` attribute because the user should not bother with these things. This should be done automatically and I assume it is already done. But I will now investigate and check how this is handled by Gantry somehow.

I just wanted to have the original description from the RT forums laid down here as well as it makes things easier to have the background information listed here. I will now check what we can do, what is already there and then report back. As I wrote the original PR #2541 I will also propose another PR if it is necessary. Stay tuned.

**Comment by thexmanxyz** [comment]
@marktaylor46 Ok I already found the issue the implementation for Joomla was missed in the `Menu.php` file I already have a working fix for at least passing the `rel=` setting of the Joomla menu over to Gantry. That is actually not a working fix for all CMS but I will target this as well in a PR.

**Comment by marktaylor46** [comment]
ok thanks @thexmanxyz

**Comment by thexmanxyz** [comment]
@marktaylor46 The PR #2575 includes a fix for the problem. I have to apologize because I confused `nofollow` with `noopener` and `noreferrer` which handles different behaviours. I'm sorry for that. But the fix also targets the use case of adding the `nofollow` attribute. Either manually over the Gantry menu item or directly over the platform (for Joomla and Wordpress). AFAIK Grav has no support for menu items to define the `rel` attribute on menu items.

**Comment by mahagr** [comment]
@marktaylor46 Fixed now!

**Comment by marktaylor46** [comment]
I tried thje CI build for this and it all works ok, But, there is one minor little use case when it's not quite right. If you use the "link rel attribute" field in joomla menu manager (which only let you pick one rel attribute - e.g. "nofollow" AND use the "link tag attribute" field in G5 menu manager to add a rel (e.g. "noindex, nofollow") then what actyually get's rendeerd is rel="nofollow noindex, nofollow" which is technically wrong because of space instead of comma and duplicate "nofollow". 

It's a minor point and easily overcome - just thought I ought to mention it.

Regards, Mark.

**Comment by thexmanxyz** [comment]
I will check this issue tomorrow but actually there is no comma generated
within the twig file. The other problem might not be preventable with
reasonable measures. But I will report back.

Mark Taylor <notifications@github.com> schrieb am Mi., 18. Dez. 2019, 17:32:

**Comment by mahagr** [comment]
@thexmanxyz I want a release out this week (before Christmas), so please look into this asap. :) Thanks.

**Comment by thexmanxyz** [comment]
@mahagr I'm already verifying the issue. Will post an update in the next hour.

**Comment by thexmanxyz** [comment]
@mahagr @marktaylor46 Fixed with some caveats, see #2585

**Comment by thexmanxyz** [comment]
@marktaylor46 Wait a moment. I relied on your post that `noindex, nofollow` is valid for the `rel` attribute. But actually it is not. Where did you get this type of attribution from? Neither [W3CSchool](https://www.w3schools.com/TAGS/att_a_rel.asp) nor [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel) list the `noindex` attribute. Actually only `nofollow` is valid. I even assume that the `,` is invalid within the `rel` because I never saw that. Attributes within `rel` are only valid if separated by a blank...I will updated my PR #2585 to reflect that finding.

**Comment by thexmanxyz** [comment]
@mahagr Please close

**Comment by marktaylor46** [comment]
It was a member in forum wanting to do that... and I (stupidly) believed them... but you are correct that "noindex" is not valid there, only "nofollow". Also if you use the link rel attribute in menu manager (where you can only select one value) AND use the link attribute field using rel then they are correctly concatenated with space (not comma) and duplication removed. 

So yes looks ok.

**Comment by thexmanxyz** [comment]
@marktaylor46 Nevermind, it was good that you pointed again on this issue and the PR related with this issue. Hence, I had the opportunity to look again on my implementation and further improve it. I really appreciate it.

There was of course a problem with the duplication of the `rel` attribute content in certain scenarios (e.g. when you added multiple attribute values separated by blank via the Gantry menu configuration which partly matched platform values). I omitted the checks for that case deliberately in the first place. But it is good that we have that checks now in so that no duplication happens whatever the user does (as long as the W3C is respected).

Also the implementation is now much sleeker. I again confused your first post...need to read more accurately before answering. But I was a bit in a hurry yesterday evening so I simply misinterpreted your post.
