### ISSUE TITLE
theme.yaml file can not be overwritten in custom folder

### ISSUE THREAD

**Issue by topwebs** [gantry/gantry5#2578]
Although docs (https://docs.gantry.org/gantry5/advanced/customizing-theme-files) indicate that gantry/theme.yaml can be customized in custom/gantry/theme.yaml, this does not work. See: https://rockettheme.com/forum/gantry5-for-joomla/282744-styling-new-section-properly?start=10#1420040

Can this be fixed?

**Comment by mahagr** [comment]
There's some work already been done in order to fix this:

https://github.com/gantry/gantry5/tree/feature/theme-config

**Comment by mahagr** [comment]
@topwebs 

I've finally implemented a way to use your own `custom/gantry/theme.yaml` file. I chose to go for a simple solution: if the file exists, it will be used instead of the default file. So if you override the file (or any other file), it is a good idea to check now and then if it has changed. Generally, themes have been very stable and most changes are between larger versions: 5.4 -> 5.5 -> 5.6...

Please check if it now works for you in CI build: https://gantry.org/downloads#ci-builds

PS. make sure you pick the correct file for your CMS.
