### ISSUE TITLE
Customizing Theme Files

### ISSUE THREAD

**Issue by Bootfair** [gantry/gantry5#2617]
Hi all,
I finaly came across to gantry and hated myself for not finding gantry before :) It is a wonderful framework.
Mine is not an issue but rather a plea for help... After reading the document about customizing theme files @ http://docs.gantry.org/gantry5/advanced/customizing-theme-files I have managed to get the image picker on the section.html.twig and the color picker on the layout.yaml but I could not figure out how to insert overlay data on the twig file. I realy would love to be able to add an image overlay color option too to the same file. I did figure out how to do iti section by section by copying showcase background options to the other sections but I think doing this through the theme yaml and html files would help the page speed because there will be lesser lines on the compiled css. Am I wrong in thinking so? If my theory is correct then could somebody with spare time perhaps advice me what else to add on section.html.twig. Best regards and many thanks again for the greatest ever framework.

**Comment by bomkallo** [comment]
I'm quiet sure that the page speed is the last concern. To enhance page loading speeds at !J or WP you need to play with general caching methods, image sizes, etc. Sometimes that's not enough because third-party extensions tend to improperly load its scripts and styles.

Run the debugger and look at network console - there you will see things that occupy most of load time, by the path you'll be able to classify if you can manage it or not. If something comes from an extension then you're out, because you must not modify its code, because potential update will bang changes :)

For the overlay issue, I don't have the code in reach :)

**Comment by Bootfair** [comment]
Thank you very much Bomkallo but I think I have been misunderstood. I don't have an issue with page speed what I am trying to do is be able to choose a color overlay from the section's options rather than styles panel. 
In the tutorial @ gantry docs we can enable an image picker by adding;

    **{% if attr_background %}<div class="section-background" style="background-image:url({{ url(attr_background) }})">{% endif %}**

and I can make an overlay by replacing that code with;

    **{% if attr_background %}<div class="section-background" style="background-image:linear-gradient(rgba(255,255,255,0.3),rgba(255,255,255,0.3)),url({{ url(attr_background) }})">{% endif %}**

and this makes all sections have the same linear gradient as overlay. But what I realy would like to do is to add one or two color pickers on the sections.yaml file so that I can choose different colored overlays per section if desired. This is all for saving a few kbs in compiled css and making the styles panel less crowded.

Best regards

**Comment by mahagr** [comment]
Generally, you would like to use inline styles if you have the setting inside a particle because you may have multiple particle instances in a single page with different settings. But if it is more a general thing, you'd like to do that in styles instead and add SCSS rules for them.
