### ISSUE TITLE
Cannot assign a layout to page wordpress

### ISSUE THREAD

**Issue by Grafiker29** [gantry/gantry5#2619]
I've just started using Gantry with the Helium theme. I have created an Outline and assigned it to a page. But when I view that page in the front end it doesn't reflect the layout of the Outline. Am I missing something. I have got WP Bakery plugin and thought that might be the problem but I deactivated it and problem persist.

**Comment by joomlabeat** [comment]
As this is mostly issues/bugs related to the development and not a direct support channel for the end user, In order to have more chances of getting help, maybe post your question here: https://gitter.im/gantry/gantry5 

Also the documentation is here: http://docs.gantry.org/

By the way, regarding your issue one thing that comes to mind is that it can be a conflict of assignments. For example, your page might use an another assignment of a menu item, post type etc.
