### ISSUE TITLE
Expand on Hover does not work

### ISSUE THREAD

**Issue by proof939** [gantry/gantry5#2621]
Hello,

the function "Expand on Hover" does not work for me at the moment. In the settings at "Layout" > "Menu" everything is set correctly (Expand on Hover is disabled). If you wipe to the right on your smartphone, the menu will open. This should be disabled.

Version: 5.4.32

thanks

**Comment by N8Solutions** [comment]
@proof939 In order to help you better with the Menu Hover issue you need to provide more information such as what CMS you are using. It would also help to have a link so the site can be inspected to better determine what the issue is you are experiencing.

As far as the "Swipe Gesture" is concerned. An option already exists to do that. All you need to do is to go in to the Layout tab of Gantry 5, preferably in the "Base Outline", scroll down to the very bottom and click on the cog wheel for the settings of the "Offcanvas" section. There you will see a box that you can tick or untick for the Swipe Gesture.

![image](https://user-images.githubusercontent.com/12389693/79196645-1d6ade00-7e39-11ea-99ca-dbedd9f7edf9.png)

**Comment by proof939** [comment]
@N8Solutions - Thanks a lot for your help! That was the solution. Sorry, i didn't see that before...
Thanks again.

**Comment by N8Solutions** [comment]
You're welcome! And don't worry about it. Gantry 5 is very versatile and has a lot of options. It can take a while to get to know all of them.
Have a great day!
