### ISSUE TITLE
rokSprocket's truncate function is not UTF-8 character friendly!

### ISSUE THREAD

**Issue by newjie** [gantry/gantry5#2635]
In components\com_roksprocket\lib\RokSprocket\Util\HTMLManipulator.php function truncate, this line
`if (!$amount || preg_match_all("/\s+/", $content, $junk) <= $amount) return $content;`
is problematic.

For example, Chinese texts don't use space to separate words, there won't be many "\s"s in it except for the "\s" separating paragraph. So when users set the "preview length" to be 20 on the backend, for Chinese texts if there are less than 20 paragraphs, there are most likely less than 20 "\s"s, not to mention there could be some "\s"s due to HTML tag. In those cases, the text will be return untouched instead of being truncated to 20 characters.

I've mentioned this kind of problem in https://github.com/gantry/gantry5/issues/2103, rokSprocket's truncate function is even more unfriendly to Chinese text if I didn't get the above code wrong.

**Comment by newjie** [comment]
Wait, what separates  passages is not "\s", so there are even fewer "\s"s in Chinese text..

**Comment by mahagr** [comment]
Closing as invalid because of rokSprocket is not part of Gantry 5 nor has ever been. I recommend creating your own particles for what you want to do as Gantry 5 provides that functionality.

That said, I will need to find some time to go through the old Gantry issues and look if there's some way to figure out how to detect Chinese and modify truncate based on that.

**Comment by newjie** [comment]
Thanks for clarifying. I love using Gantry 5 particle however in some use cases it doesn't  allow users to get non-Joomla content as easily .
