### ISSUE TITLE
Add bootstrat CSS + JS without breaking Custom styles

### ISSUE THREAD

**Issue by jbonlinea** [gantry/gantry5#2668]
Hi, 
I tried to add bootstrap to my wordpress gantry template, and so far so good, expect that quite many bootstrap style (color or typography related) break the custom styling of the theme ! 

that's pretty annoying ! 

How could I add bootstrap without having to fix it here and there ? 
Basically can't bootstrap be loaded before my custom scss and before gantry preset stttings ? 

I'm using a child theme

Thanks in advance for your help

**Comment by adrienionescu** [comment]
Over time there have been many discussions around the topic. I encourage you to use the search function on both GitHub and Gitter websites. Also, search official Bootstrap documentation and google for something like "integrating bootstrap into an existing project". Usually, front-end frameworks are useful when you want to build a theme or website from scratch, mixing them with existing styles will cause some troubles for sure.

Please note, these are not recommendations, I am just giving you some ideas, so you can do further research.

I guess the clean way is to use the SCSS version of bootstrap along with theme overrides and include only the files that work for you. Of course, it depends on your specific needs. For example, you could keep the base typography defined by theme and exclude bootstrap typography. But, make sure you include the bootstrap variables, because other components rely on them. See [Bootstrap theming](https://getbootstrap.com/docs/4.1/getting-started/theming/), [WordPress main style](https://github.com/gantry/gantry5/blob/develop/themes/helium/wordpress/scss/helium-wordpress.scss), and [common main style](https://github.com/gantry/gantry5/blob/develop/themes/helium/common/scss/helium.scss). 

Other ways to do it:
- You can try to prefix class names (when the framework allows it, as far as I know, bootstrap doesn't)
- Scope the style (.scope-class .boostrap-class), Bootstrap CSS will take effect as long as it is inside the "parent class". This might work if you plan to use Bootstrap for particles.

Scoped style inside a particle:
```
.oh-my-bootstrap {
    @include "boostrap-file";
    @include "another-bootstrap-file"l
}
```
```
<div class="oh-my-bootstrap">
    <ul class="list-group"></ul>
</div>
```

**Comment by jbonlinea** [comment]
Hi @adrienionescu 

Thank you very much for your reply, it is detailled and structure to will, and really helps.

I considered bootstrap, more than uikit for instance, as Gantry "javascript framework" atom invite to do so and it is a framework I'm comfortable with.
I believed it was "integrated" in some way, and it's only after some research here that I found that we had to manually ad the CSS since the atom only deal with the JS.

Broadly speaking, I usually do find insightful answers here, on Gantry github repo, but I've been less successfull on Gitter where I see that some question from various user are answered, and some not.

I'm well aware of how to theme bootstrap, but once again, I understood it was somehow integrated, and was surprised to find that there weren't a paved road to use it along gantry without re-defining many variables.
In this respect, I understand why you provided  the link to bootstrap theming, but not the two others ? I do understand that both file define which scss file have to be loaded/compiled for the theme, but not really what am I suppose to do with it ?


Finally, I was aware of the prefix approach but not the scope one, it seems light, robust and easy to implement ! thank's
Of course everything in the scope will loose its parent theming so we sort of bumped in the same problem, but at least not site wide, in some case it may be enough :)


I guess we can close this issue, which might nevertheless be useful for someone else over time!
Again thank's for your comprehensive reply !
Cheers
