### ISSUE TITLE
How to randomly render a module in a position?

### ISSUE THREAD

**Issue by newjie** [gantry/gantry5#2669]
I have several modules in a Gantry template's position, I want to display a random one of them on the front-end, how do I do this?

I post a [question ](https://joomla.stackexchange.com/questions/28239/randomly-render-one-of-the-modules-in-a-position)on joomla.stackexchange.com but I don't think the answer apply to Gantry.

**Comment by mahagr** [comment]
You need to create a new particle by copying `engines/joomla/nucleus/particles/position.html.twig` and `engines/joomla/nucleus/particles/position.yaml` into your theme and renaming them. Then instead of calling `{{ gantry.platform.displayModules(particle.key, {'style': particle.chrome|default('gantry')})|raw }}` inside the twig you need to call your own method which does the logic you want to.

This is the method which gets called from the twig, it should be easy to cop it to your theme class and make it to display a random module:

```php
    public function displayModules($position, $attribs = [])
    {
        $document = \JFactory::getDocument();
        if (!$document instanceof \JDocumentHTML) {
            return '';
        }

        $html = '';
        foreach (\JModuleHelper::getModules($position) as $module) {
            $html .= $this->displayModule($module, $attribs);
        }

        return $html;
    }
```

After adding a new method to your theme, you can simply call it from twig by something like this: `{{ gantry.theme.randomModules(particle.key, {'style': particle.chrome|default('gantry')})|raw }}`.

I will leave the actual implementation to you, you should now have all the pieces you need. :)

**Comment by newjie** [comment]
I've tried several ways but can't get my own function working. I ended up adding my function(displayRandomModule) directly into Platform.php and it works. But this is hardly a good practice. How do I exactly "adding a new method to your theme"? 
Imitating the instruction in the doc http://docs.gantry.org/gantry5/advanced/php-functions, here's what I do: 
1) Create a new file under mytemplate/custom/includes 
```
<?php
  class randomModule{
    public function displayRandomModule($position, $attribs = []){
      $document = \JFactory::getDocument();
      if (!$document instanceof \JDocumentHTML) {
          return '';
      }

      $html = '';
      foreach (\JModuleHelper::getModules($position) as $module) {
          $html .= $this->displayModule($module, $attribs);
      }

      return $html;
    }
  }

```
For test's sake, I didn't apply my own logic, just copy over everything to see if it works

2) in theme.php I added
```
include_once dirname(__FILE__).'/../custom/includes/randomModule.php';

$gantry['randomModule'] = new \randomModule();
```

Of course, this won't work because `$this` in the method is not the Platform object. 

Am I on the right track? If I am, then how do I properly call displayModule method in my own function?


I noticed that you mentioned `gantry.theme.randomModules`, how do I add a method to `theme` and where is this `theme` object located? I can't find this information in the Doc. 

Thanks for your help!

**Comment by mahagr** [comment]
Try something like `{{ gantry.randomModule.displayRandomModule('position_name')|raw }}` In your theme to make your current code to work.

Or just add the method inside the Theme class - it should be in the `theme.php` file, no need to add a new file for that. :)

**Comment by mahagr** [comment]
I'm not going to implement this into Gantry, so closing the issue.
