### ISSUE TITLE
/* @import "custom.scss" */

### ISSUE THREAD

**Issue by OpheliaHRPG** [gantry/gantry5#2672]
I've been trying to add custom css to the g5_helium theme, and was having no luck following the direction in the documentation. So, I went digging around and found that the content of g5_helium/custom/css-compiled/custom.css looks like this:
 
.......
/* GANTRY5 DEVELOPMENT MODE ENABLED.

   WARNING: This file is automatically generated by Gantry5. Any modifications to this file will be lost!

   For more information on modifying CSS, please read:

   http://docs.gantry.org/gantry5/configure/styles
   http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet
 */

/* @import "custom.scss" */
........

I am relatively new, and completely self taught, to CSS. But, am I right in thinking that the slash and asterisk combo flanking the @import means that it's a comment? And, that means that it isn't actually importing the code in the custom css file I set up at /g5_helium/custom/SCSS/custom.scss?

(Edit: I'm working in Wordpress.)

**Comment by marktaylor46** [comment]
For Wordpress place you custom.scss file in /wp-content/themes/g5_helium/custom/scss/   (note the case - you used "SCSS" instead of "scss") then you go to the base outline in Gantry 5 admin and press the "Recompile CSS" button (this is what creates the custom.css file in the css-compiled folder - you should never ever change the contents of this folder).

Tip: Also make sure that you are in "development" mode in Gantry 5 admin (EXTRAS button top right).

Regards, Mark.

**Comment by OpheliaHRPG** [comment]
Thanks for the prompt reply, Mark! I took another look at the documentation, and was finally able to figure out what I was doing wrong. I was attempting to create a sticky header. But, I don't know enough about javascript to do this. So, I grabbed a free code for an atom that does that from the internet, and followed the doc's instructions on how to create a new particle. Problem solved!
