### ISSUE TITLE
PHP 8.0 errors

### ISSUE THREAD

**Issue by simmonsr** [gantry/gantry5#2737]
![Screen Shot 2020-12-15 at 3 44 31 PM](https://user-images.githubusercontent.com/5002814/102276630-aff1de80-3eec-11eb-87ec-b58058dc425a.jpg)
![Screen Shot 2020-12-15 at 3 45 11 PM](https://user-images.githubusercontent.com/5002814/102276633-b1230b80-3eec-11eb-993a-1f1004b9c328.jpg)

**Comment by mahagr** [comment]
Gantry 5.4 cannot support PHP 8 because library versions that work in PHP 5.5 do not work in PHP 8.

**Comment by simmonsr** [comment]
Ok added 5.5 milestone. Getting same errors with the 5.5 packages

**Comment by mahagr** [comment]
I need to check if we can update those vendor libraries. If not, we need to go for PHP 7.1 minimum requirements.

**Comment by dmleeman** [comment]
Any news on Gantry5 & PHP8.0?
I notice that Joomla 3.9.23+ appear to be compatible, as is Joomla Phoca Cart. (don't really use Wordpress)

**Comment by SkylarAstarot** [comment]
I have a Joomla website running on the server with PHP8 and it generates the following error:
Twig \ Error \ RuntimeError
An exception has been thrown during the rendering of a template ("Trying to access array offset on value of type null").

All errors are in files inside gantry5/engines folders
In control Panel (Administrator) everything works fine, the problem is only in Front End.

When will Gantry Framework be updated to work with PHP 8?

**Comment by mahagr** [comment]
There is already a development version of Gantry 5.5 which works in PHP 8, but it is still not quite ready for production. It is a major rewrite in the code level to properly support the latest version of PHP and CMSes.

**Comment by simmonsr** [comment]
confirmed

**Comment by MicPou** [comment]
Hi,

Is there already a solution for this issue? I have the same problem which seems to be related to the nav-toolbar.html.twig/nav-toolbar.yaml in the Ivee E-commerce template. According to the developer of this template the issue is related to the Gantry default Menu particle. Without this particle everything works fine in PHP 8.0.

**Comment by wdburgdorf** [comment]
This is marked as fixed, but Gantry 5.5.17 is still not working with php 8 and Wordpress. Various "deprecated" errors in /plugins/gantry5/vendor/timber/timber/lib/Site.php. In particular affecting WooCommerce product editing pages.
