### ISSUE TITLE
Feature request - Independent particles

### ISSUE THREAD

**Issue by jmshey90** [gantry/gantry5#2824]
{loadposition} or {loadmodule} are really handy if you want to load a module/position inside an existing particle, particularly if its a Gantry 5 particles For example, I regularly use an accordion particle but like to place other dynamic particle content inside, so use the {loadmodule} feature. However, I'd prefer to keep it all within Gantry, so it would be great if there was a _Particles_ section underneath Offcanvas, where you can drop particles in, effectively as data sources, and then [particle-101] called inside any particle on that page.

**Comment by mahagr** [comment]
We decided against this as both Joomla and WordPress already provided modules and widgets. The only exception is Grav where you have a widget manager inside Grav.

Additionally, I would personally prefer using module/widget positions instead of injecting them directly into the layout in both of those platforms. My reasoning is the same as yours: use the features that CMS already provides.

**Comment by jmshey90** [comment]
For our purposes, we're basically only using Joomla as a wrapper, and using Gantry as our main editing interface - as its just easier, particularly for non-technical staff. Therefore, it would be helpful if it was all contained in one place to reduce training requirements. Similarly, when using a staging server, it is easier to sync the yaml via git than it is moving over SQL changes.

You never know, might even facilitate someone moving to Grav!
