### ISSUE TITLE
Gantry 5 broken when Wordpress updated to WP5.8

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2843]
If you update a Gantry 5 site to latest Wordpress version 5.8 then the "appearance> widgets" page no longer works correctly.

1. There are messages about "particle_widget" not working as the new "block" funtionality in WP5.8
2. IF you select the "Gantry 5 particle" widget then you then can't select a "particle" type and nor can you edit existing "Gantry 5 particles" that were added as widgets.
3. In the browser console you get "Object { code: "invalid_json", message: "The response is not a valid JSON response." }"

This all seems to relate to the new "block" functionality in WP5.8.

![Snag_8586bd](https://user-images.githubusercontent.com/11683218/127126753-c31062c8-7e50-433b-8b62-d862977d6a8b.png)
![2021-07-27_09-59-14](https://user-images.githubusercontent.com/11683218/127126776-7f3c78d7-466f-4063-b048-0b0f874587e0.png)

Frontend functionality appears to still be working though.

**Comment by JeroenZandvliet** [comment]
I have the same errors on my site, except that additionally none of my blocks will load. When do you think this issue will be fixed? It's a pretty critical error as a lot of the website doesn't function properly without the widgets.

![example](https://user-images.githubusercontent.com/79267186/127884702-5f188758-cb1e-400c-9c02-6bebdbee4d93.png)

**Comment by mahagr** [comment]
Please check out the fix from the above commit. It is in the upcoming Gantry 5.5 branch and I've not tested it yet in Gantry 5.4.

**Comment by pplopx** [comment]
This error no longer seems to occur under WP 5.8 & Gantry 5.5 dev 2/8/2021 packages. 

But I have not yet had time to test it thoroughly by playing with especially complex particles like those in JoomLead.

I'll report back if I discover anything!

**Comment by pplopx** [comment]
Definitely, although for general functionality the underlying problem has been fixed, it is not possible to insert a particle widget using 'Gantry 5 Particle' widget.

**Error in the browser console when adding it:**

![Captura de pantalla 2021-08-03 a las 17 08 45](https://user-images.githubusercontent.com/28963354/128050569-6471aaac-39e5-456e-b989-5fe31d429706.jpg)

**Error when saving changes:**

![Captura de pantalla 2021-08-03 a las 17 09 20](https://user-images.githubusercontent.com/28963354/128050397-2ab45362-2cfb-45a1-b743-64332d01aec7.jpg)

The end result is that the widget is not inserted.

---

I understand that the Gantry widget would be a 'Legacy Widget' according to the WordPress Block Editor documentation. It looks like some sort of interface that allows you to render previous widgets that have not been built as blocks.

I think this is a good starting point to investigate: https://developer.wordpress.org/block-editor/how-to-guides/widgets/legacy-widget-block/

I think either Legacy Widget compatibility should be pursued, or a block-widget should be built to replace the old Gantry 5 Particles.

I consider this a critical issue because of the increasing importance of block editing within the WordPress roadmap.

I think it would be wise to look for a good approach because as now widgets are not only restricted to use within a widget area.

Since WP 5.8 and its focus on Full Site Editing, there is no distinction: a widget is just a block, and as such can also be used within the post editor.  

For those of us who work with Gantry, this means being able to **insert particles into the content of a post in a much simpler way**.

**Comment by mahagr** [comment]
I have been working on fixing the content block support, but there are still some small compatibility issues, such as you can only have one gantry particle because the widgets are now duplicated (before there was just a single instance) and the JS cannot target the correct widget because of a single id.

**Comment by Safeworld4women** [comment]
Hi Mahagr
No pressure intended.
Do you have a rough idea when the G5 update might be ready?
Got a stack load of plugins on our non-profit site needing updating!

Take care and no stress

Andrew

**Comment by joomlabeat** [comment]
@mahagr 
Let us know how this goes and if there is anything we could do to help.

This update changes a lot and opens up new possibilities. 
I have some new full WP website development projects that I am working on. The update got it in the middle and although I can use the legacy widgets editor - I can't wait to see Gantry Particles be used as blocks.

**Comment by mahagr** [comment]
The Widget Editor should be fixed in the latest Gantry 5.5 builds.

**Comment by joomlabeat** [comment]
Hello @mahagr 

any plans to see the Gantry Particle widget as a block option in the Block Editor when editing posts?
Or any ideas of what it would take to achieve this?

I think having the ability to include Gantry Particles as blocks in the block editor of any post would be a game changer.

**Comment by mahagr** [comment]
Right now there are no plans -- my main goal is to get the remaining bugs fixed (and start preparing for PHP 8.1 updates).
