### ISSUE TITLE
Gantry 5.5.5 - menu items appearing in incorrect columns

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2957]
If you have multiple columns for a "parent" menu item then if some of those items are "hidden" or "unpublished" then the item placement in those columns appears to go awry.

RT Topic where this was first reported https://rockettheme.com/forum/joomla-general-questions/287507-gantry-5-menu-items-displaying-in-wrong-column

**Comment by mahagr** [comment]
Confirmed the issue in Joomla.

The issue here is that in order not to break the menu every time someone works with the menu items in the CMS, I had to move the data we store into the database. I also had to change the list of menu items per color into more simple counters as the older implementation was causing the new menu items to be in the wrong order in Gantry Menu Manager.

Unfortunately, it looks like Joomla removes the hidden menu items when I get them, thus messing up the column calculations -- instead of say 4 items, there may be 2-3.

As a workaround, I would make sure that no menu items (in all but the last column) have been disabled and there are no ACL-restricted menu items in any of the columns except for the last one.

**Comment by mahagr** [comment]
@marktaylor46 This should now be fixed.

**Comment by marktaylor46** [comment]
Appears to be fixed - confirmed.

**Comment by joomlabeat** [comment]
Not sure if this applies here - after upgrading Gantry from 5.4.x to 5.5 - on a custom template, all submenu items in columns lost their previous distribution and they took a random order and placement inside the columns - including any placed modules inside the columns. 
In addition, and this must be similar / related to #2975 - gantry menu manager displays all menu items, even if those are unpublished. Not a big deal since the menu items still do not appear in the front-end - but it's different than before, when unpublished menu items were not appearing or had a visual indication.

**Comment by marktaylor46** [comment]
1. Did you save the menus in G5 immediately after updating to G5.5.x 
2. Are you using G5.5.8 CI build (which contains several fixes)?

Regards, Mark.

**Comment by joomlabeat** [comment]
@marktaylor46 
1. I am not sure - can't remember if I did that right after the update - most likely I didn't, because right after the gantry update, the whole gantry thing broke and I had to go through the scss compiler errors.

2. No, just the official 5.5.7

Overall, not a big deal - I am re-ordering the submenu items manually now.
I can be patient with those unpublished menu items that interfere with the rest with no visual indication. 
BTW, in the previous version, the unpublished submenu items were not visible at all.

**Comment by marktaylor46** [comment]
If you're getting scss errors that will be because you didn't update template to latest version too. All RT Joomla templates have for G5 have been updated now to make the scss compatible with the new compiler in G5.5.x - GRAV and Wordpress themes have yet to be uipdated.

G5.5.x moves the menu config from flat file to the database - so that's why it's important to save the menuis in G5.5.x as soon as you have updated.

**Comment by joomlabeat** [comment]
@marktaylor46 
It's a custom template - so I had to update Gantry first and then work out any issues.
So, I am still working on this template locally before I upload its updated version to the live website and update gantry afterwards. 
So, do you say that after updating Gantry, the first thing I should do is to go in Gantry Menu and save the menus, or do I need to do something else?
I want to avoid to have the "menu re-arrangement" once again on the live site, after the update.

So, with Gantry5.5 all our menu settings will be saved to the database? Not a big deal... but how this is going to work when we try to keep synced a local install with a live one? Moving the config files to the server was enough - now we will have to update the database if we want to move menu settings?

**Comment by marktaylor46** [comment]
Ok if it's your own template then, yes, you will have to update your own scss files to ensure compatibility with the new scss compiler.

Yes, the first thing you do having update from G5.4.x to G5.5.x is to go to Gantry 5 menu editor and just save the menus. This will move the menu config from flat files  to the joomla database and will then delete the original flat files to avoid confusion. 

Yes, you will have to update the database if you want to move settings for the menu. All the info is now stored in the menu items in the joomla database (this includes all the extra information that Gantry 5 provides for configuring the menu, such as columns, particles and modules in menu.

**Comment by joomlabeat** [comment]
Thanks for the info - really important and helpful 
@marktaylor46

**Comment by marktaylor46** [comment]
You're very welcome. :)
