### ISSUE TITLE
'Back to Setup' button sends to nowhere (404 Error) when deleting last Outline

### ISSUE THREAD

**Issue by hugoaf** [gantry/gantry5#296]
For the benefit of UX, an error handling should be added to check when the deleted outline was the last modified to prevent the 404 error message.
Steps to reproduce:
1. In outline setup select the outline (ie. 'test outline')
2. from there go to outlines and delete same outline
3. click on Back to Setup, you will get a 404 error message.

![deleting-outline](https://cloud.githubusercontent.com/assets/8611472/7669311/be8ce2be-fc21-11e4-8b15-d30e5d4850db.jpg)

**Comment by w00fz** [comment]
Agreed on that. We actually are aware of the issue, still needs to be fixed. Good to have it ticketed though, so thank you.

What do you think should be the expected behavior? I initially thought, like you, that we should just show a warning, notifying the Outline was deleted and not available anymore, but then I thought of a few other possibilities:

1. If the Outline is not available anymore, `Back to Setup` will show up a warning
2. If the Outline is not available anymore, `Back to Setup` will take you to the `Base Outline`
3. The moment the current Outline gets deleted, we just hide the `Back to Setup` button so you are forced to edit a different one from the list.

**Comment by adi8i** [comment]
Just go back to layout manager or styles, like it was first time :P

**Comment by hugoaf** [comment]
I like this:
> 2) If the Outline is not available anymore, Back to Setup will take you to the Base Outline

**Comment by w00fz** [comment]
Thanks this is implemented now :)
