### ISSUE TITLE
Problem with owl_carousel - Gantry 5.5.7 (Helium) - with Joomla 4.0.5

### ISSUE THREAD

**Issue by OlivierCARRE-O2C** [gantry/gantry5#2978]
We update our website from Joomla 3.10/Gantry 5.0 - Helium to Joomla 4.0/Gantry 5.5 - Helium (and PHP 8.0) a few days ago
We do not have any problem except with owl_carousel which "disappear" - the screen is empty - with Joomla 4
I am not a website developer ! I have just used inspection on Google chrome to look for the error "TypeError : e.indexof is not a function at S.fn.init.S.fn.load (jquery.min.js?3.6.0:2)". JQuery is not used by Joomla 4, so I suppose than Gantry ask for loading it. With Joomla 3.10, JQuery was in v1.2 with security patch add-on, here it is 3.6 version - perhaps to far from the original 1.2 ! but I do not know how to limit the version into Gantry (or Joomla). I search for this kind of problem on internet and find only similar problem with WordPress but nobody speak about Joomla. Can you help me ? or/and confirm the problem.
Our website is o2c-sc.com, the owl_carousel is available by a click on the home image or by the menu "Notre savoir-faire", sub-menu "Conseil". Gantry 5.5 is the only plugin of Joomla except JCE editor v2.9.18

**Comment by mahagr** [comment]
Try enabling jquery manually from the Gantry Base Outline > Page Settings. In the bottom of the page there should be Frameworks atom, which you can use to manually enable jquery in your pages.

**Comment by OlivierCARRE-O2C** [comment]
Hello Mahagr,
As you ask me, I have enable JQuery Framework (only that line by using small icon parameter on JavaScript framework after defined it as a framework atom). Then I have clear all buffers (Gantry & Joomla) without any result as you can see on our website. Is there an other think to do or an other line of JS framework to enable ? Where is my mistake ? Thank you for your help and for your time

**Comment by mahagr** [comment]
Not sure. Look at the html source code if you see something going wrong in there. What you should see, is script tags loading jquery once.

**Comment by OlivierCARRE-O2C** [comment]
Hello,
scripts link to jQuery in the html source are :
<script src="/media/vendor/jquery/js/jquery.min.js?3.6.0"></script>
<script src="/media/legacy/js/jquery-noconflict.min.js?04499b98c0305b16b373dff09fe79d1290976288"></script>
and moreover the use of jQuery to load the owlcarousel function

**Comment by mahagr** [comment]
That looks correct. Also, it looks like the page is using jquery that is shipped with Joomla 4.

Helium doesn't have owl carousel, maybe it was added manually? In that case, you may want to update it to the latest version.

**Comment by marktaylor46** [comment]
I've tested Helium G5.5.7 with J4 and owlcarousel works fine for my on PHP 8.

That said, I do recognise the error that you mentioned and it is usually caused by some JS somewhere using $(window).load(function () { which has now been deprecated in the version of jQuery now included in Joomla 4. The function should now be used as $(window).on( 'load', function() {

So, you'll need to check if you have any third-party code using that. I checked owlcarousel particle and it does not use that.

Regards, Mark.

**Comment by OlivierCARRE-O2C** [comment]
Sorry but Helium from Gantry 5 does have a particule named owlcarousel

**Comment by marktaylor46** [comment]
I was just trying to help you with diagnosing the issue. 

Here's a video of my Helium site on PHP 8.01 and Helium G5.5.7 and the owlcarousel working on Joomla 4.0.6 (i did try 4.0.5 also and that was fine too). https://www.screencast.com/t/BfHIppEtU

If you want to send me login details I can take a look at your site for you.

**Comment by OlivierCARRE-O2C** [comment]
Your video is explicit ! How can I send you our login securely ? My email address is olivier.carre@o2c-sc.com

**Comment by marktaylor46** [comment]
Ok thanks for providing the login details and I've now checked your site. The problem is caused by your own override of the owlcarousel particle in /custom/particles/ and the specific issue is what I've already mentioned i.e the use of jQuery(window).load instead of using jQuery(window).on('load', ..... or better still in this case jQuery(document).ready.

If you look at the Helium G5.5.7 code that we provide for the owlcarousel particle you will see that it has been updated to use jQuery(window).ready

Whenever you create an override it becomes your responsibility to maintain that code and update it as and when new versions of the original code are released.

![2022-01-19_15-40-13](https://user-images.githubusercontent.com/11683218/150166140-d86272db-157b-42ce-8329-52e1ce53ce7e.png)

![2022-01-19_15-46-17](https://user-images.githubusercontent.com/11683218/150166188-f12b388d-0a05-4bc4-ad38-8c13eb4828c7.png)

Regards, Mark.

**Comment by OlivierCARRE-O2C** [comment]
Ok, thank you very much. I understand my error : I have updated the custom file - only the css one - and I have forgotten that all others files have to be copy from the original particle ! I will change my internal documentation to be aware about that
