### ISSUE TITLE
How to assign an additional class to a block .g-content?

### ISSUE THREAD

**Issue by kosh2323** [gantry/gantry5#3042]
In the side section aside, if you place a module, for example a menu, then unnecessary margin and padding are added. I don't understand how to remove it through the settings?I need to remove these margins only in one side section. In the code inspector, you can see that the margins are added to the class .g-content. How to assign an additional class to the desired block with a class .g-content? Please tell me who knows.

![1](https://user-images.githubusercontent.com/82117170/168852885-4e9e298c-9459-4151-9c98-cc931e24f3d0.jpg)

![2](https://user-images.githubusercontent.com/82117170/168852916-cde238ad-090f-4313-82c6-8229ab681a57.jpg)

**Comment by N8Solutions** [comment]
Hello @kosh2323 There is an easy fix for this. You simply need to add a **CSS ID** then write the CSS so that it affects the `g-content`.

For example, if we use what we see in your screenshot above, you are using the position `aside-c`. So if you choose to, you can add the CSS ID of `aside-c` and that will sit above `g-content` for that block and any particle placed in that block will be affected by your code.

So your code would look like this:

```
#aside-c {
     .g-content {
          margin: 0;
          padding: 0;
     }
}
```

To add the **CSS ID** you need to access the **Block Settings**.
https://docs.gantry.org/gantry5/tutorials/using-block-settings#accessing-block-settings

Right below, on the same page as the information above, is the section on **CSS ID**:
https://docs.gantry.org/gantry5/tutorials/using-block-settings#css-id

After adding the **CSS ID** to the Block, you need to add the CSS above to your template, I'm assuming you know how to do that with the **custom.scss** file.
In case you don't, here is the link on how to do that in the Gantry 5 documentation.
https://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet

If you would like to see a demo of the above in action, check out my demo site where I test things.
On this page, _Fixed Module_, I have added the **CSS ID** of `sidebar-left` to the particle that says "Sidemenu".
If you inspect the code, you'll see the ID is directly above the section for `g-content` which is why writing the code like that above has an affect on it.
https://g5test.n8solutions.org/fixed-module

![Block Settings - CSS ID](https://user-images.githubusercontent.com/12389693/172056861-d139f926-66a1-4bd0-a7a3-11256ed6b29a.jpg)


If you compare that to the homepage, the same particle called "Sidemenu" does not have the **CSS ID** added so the CSS code does not affect the margin and padding.
https://g5test.n8solutions.org

Hope this helps.

Let me know if you need any further clarification.

**Comment by kosh2323** [comment]
Hi, thank you very much for the advice and hint. It works. There are 3 modular positions in the Aside section and it is the first one that allows you to set the class that will be closer to .gcontent

![1](https://user-images.githubusercontent.com/82117170/172063009-6d6a7a74-1cc6-4136-94d5-82ad6cb4f6a7.jpg)

![2](https://user-images.githubusercontent.com/82117170/172063012-7c6a56a8-87c1-46cb-a350-56172d5da000.jpg)

**Comment by kosh2323** [comment]
The question can probably be closed, thank you all. I'm closing the topic.
