### ISSUE TITLE
Cannot override Presets

### ISSUE THREAD

**Issue by uglyeoin** [gantry/gantry5#306]
I tried to create new presets for Hydrogen. I created a folder: templates/g5_hydrogen/custom/gantry/presets.yaml

but when I upload it the same presets still exist.  The documentation indicates that this is possible, and I think it will be an amazing feature.

**Comment by mahagr** [comment]
Its a known issue to me, nothing in ```gantry``` folder is overrideable because of the hack I used to do it in a hurry. Thanks for the report, now I may even remember to fix it.

**Comment by Bodge-IT** [comment]
I think someone should send out a search party for Mahagr memory!  This is a necessary feature, wothout it styles are a waste of time.  Can this please get fixed and not moved on to another milestone?

**Comment by mahagr** [comment]
I've not forgotten this one, I've actually been making some changes towards this feature. The thing is that this issue hasn't been the highest priority and such other issues have been picked up before this one.

**Comment by w00fz** [comment]
This appears to be working now.

**Comment by JoomFX** [comment]
@w00fz So is the `gantry` folder overridable in `custom` now? :hankey:

**Comment by mahagr** [comment]
Not fully as far as I know.. I've been working towards it when I have time.

**Comment by w00fz** [comment]
@nikola3244 specifically had me know that this particular issue (`presets.yaml`) are overridable as expected.

We still have other issues open re the `gantry` folder overrides and I even don't entirely like this solution in here, we do need a way to MERGE when needed and not just OVERRIDE. You want to add more presets without having to copy over all the other ones, otherwise keeping in sync updates is going to be hard.

**Comment by JoomFX** [comment]
Thanks guys!
