### ISSUE TITLE
Stick footer at bottom?

### ISSUE THREAD

**Issue by simone80an** [gantry/gantry5#3063]
Im trying to stick the footer at the bottom, im using Helium theme in Joomla, so i added this code to custom.scss:

```
.bottom {
position: absolute;
width: 100%;
bottom: 0px;
}
```

then applied the class bottom to the footer section but then the footer goes over the content, if i comment bottom: 0px; i correctly see all the content but the footer isn't displayed properly all or just disappear in pages where there is much content.

**Comment by N8Solutions** [comment]
Hello @simone80an :wave:

This is a question better asked in the Gitter chat ([https://gitter.im/gantry/gantry5](https://gitter.im/gantry/gantry5)) rather than opening an "Issue" because the "issues" are reserved for potential bugs and/or feature requests related to the Gantry 5 Framework, and the Hydrogen & Helium themes.

You could also ask your question in the Joomla Stack Exchange here.
[https://joomla.stackexchange.com/questions](https://joomla.stackexchange.com/questions)

Also, if you have a Rocket Theme membership you can ask your question in their forum. Since Rocket Theme is the company behind Gantry 5 you may get better answers there.
[https://rockettheme.com/forum/joomla](https://rockettheme.com/forum/joomla)

To that end, since your question is outside the scope of what the issues are used for, you should close this issue and ask your question in the places I've pointed out above.


P.S. - if I had answer for you. I would private message you with it, but this is not something I've ever done or attempted to do.


regards,

Michael

**Comment by simone80an** [comment]
Ok thanks Michael!

**Comment by N8Solutions** [comment]
@simone80an Happy to help, and don't forget to close this issue :wink:
