### ISSUE TITLE
Transparent menu

### ISSUE THREAD

**Issue by komir2004** [gantry/gantry5#3067]
How can make the menu transparent till the user start to scroll the page?
Something like this template has
https://www.joomshaper.com/joomla-templates/luxyort

**Comment by N8Solutions** [comment]
@komir2004 Before I comment, please know that the "issues" are suppose to be reserved for problems relating to how the Gantry 5 framework works in combination with the Hydrogen & Helium templates. In the future, you should ask for help regarding these kinds of questions in the Gantry 5 Chat here:
https://gitter.im/gantry/gantry5

You can also search related templates with [Rocket Theme](https://rockettheme.com/joomla/templates) and [Inspire Theme](https://www.inspiretheme.com/joomla-templates) that accomplish what you want.

After reading the information below, given that it is not an actual issue with the Gantry 5 Framework or related Hydrogen & Helium templates, kindly close this issue since you are asking for design help.

About trying to accomplish what you want. You can study the [Helium template](https://demo.gantry.org/) by installing it on your web host. It has a transparent menu on the home page and a colorized menu on the other pages.

As far as making the menu "fixed" or "sticky", you can use either the "Fixed Header Atom" or the "Headroom.js Atom" from Inspire Theme to accomplish what you want. Check out the blog post for both available here:
https://www.inspiretheme.com/blog/freebies/42-fixed-sticky-header-atoms-for-gantry-5-freebies

For further help on this issue, please go through the Gantry 5 chat room I linked above.

kind regards and good luck!
