### ISSUE TITLE
The update notification for 5.5.16 is missing

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#3163]
It has been about 3 months since gantry 5.5.16 came out but no Gantry site has notified me of the update. Why ? Doesn't the automatic update work anymore ? Or does it cause problems to upgrade from 5.5.15 to 5.5.16 ?

**Comment by N8Solutions** [comment]
Hello @mariantanase This is something they are aware of. There was an issue when they originally released v5.5.16 and then immediately fixed it but while they worked on it they turned off the automatic update and will most likely turn it back on when they release v5.5.17. You can read the response from @hexplor here https://github.com/gantry/gantry5/issues/3138#issuecomment-1529046851. If you would, please close this ticket.

regards,

Michael

**Comment by mariantanase** [comment]
Ok thanks, 
to be on the safe side I'll keep the 5.5.15 until the 5.5.17 will be available.

**Comment by N8Solutions** [comment]
You're welcome @mariantanase! The "fixed" version of v5.5.16 does work just fine in my experience. I have not ran into any issues with it and no one else has reported any issues since @hexplor fixed it. In my opinion I'd say it is safe to upgrade to you but you should of course test it out for yourself in a staging area just to be sure your sites don't have any issues.


kind regards,

Michael
