### ISSUE TITLE
Blank page with php 8.2

### ISSUE THREAD

**Issue by Schnok** [gantry/gantry5#3179]
Hello Team,

I use Joomla 3.10.12 with gantry 5.5.16 and manticore template 1.5.0.
With php 7.4 everything works fine on the front end. The site was developed with this version of php.
On my development server I switched to php 8.2. Everything I did in php 7.4 works in php 8.2. But if I want to add content I get a blank page with just "error".
Has anyone had this problem before?
regards,
Phil

**Comment by N8Solutions** [comment]
@Schnok You should really think about upgrading to Joomla 4 and stick with PHP 8.1 for now. I don't believe they (Gantry) have worked out all the bugs associated with PHP 8.2.

**Comment by Schnok** [comment]
@N8Solutions Thank you for your feedback.
Regarding the move to Joomla 4, I agree with you and most of the sites I maintain are under J4, but some of my customers aren't always, and unfortunately I have to deal with that.
For my problem we were able to identify the cause yesterday, and in the end it wasn't directly due to Gantry.

**Comment by N8Solutions** [comment]
@Schnok Glad you got it sorted! Since you figured it out, would you please share the solution here so it can help others since as you say it was directly due to Gantry. Also, once you do share the solution, please close the ticket to help the admins.

**Comment by Schnok** [comment]
@N8Solutions There isn't really a solution. It was coming from an extension plugin. I didn't assume it could be coming from there when I first disabled the various plugins, so I didn't see it.
I'm talking to the developer to see what's going on. I may come back here if it's not a problem specific to my website.

I'm surprised that Gantry and RT no longer intervene on the supports. Do you think we should be worried about the future of this solution?

**Comment by rslaliberte** [comment]
I'm a little concerned.  When was the last Gantry release? Because the website says 5 months ago but the release is dated 2022.  It looks like I installed it just after the release date (if that date is off by a year).  I have quite a bit invested in this framework, and I'd like to keep working with it. But if I have to switch because these things are not going to get fixed I'd rather know that sooner rather than later.

**Comment by N8Solutions** [comment]
@rslaliberte
v5.5.15 was released Sept. 5th, 2022.
v5.5.16 was released Apr. 4th, 2023.

Gantry has said many times they are short staffed at the moment but are working on things. @hexplor was the one who did the updates for v5.5.16. @mahagr did them previously but he said a while ago that he isn't able to work much due to suffering from Long Covid. Another team member, Mark Taylor (MrT), passed away recently from Cancer

Others have expressed the same concerns as you, and like you, I too have have invested a significant amount of time and resources to develop my sites using Gantry. We're not seeing a lot of improvements and there hasn't been a new template released in quite a while. The latest version, 5.5.16, fixes some PHP bugs to make it work better with v8.1. It's not quite fully compatible with PHP 8.2 though.

I'd like to believe that @rhukster and the others behind Gantry and Rocket Theme will get things back on track soon.

Maybe one of them will chime in here and comment on how things are going or make a post in the Rocket Theme Forum with an update.


kind regards
