### ISSUE TITLE
Joomla 5 back-end Atum and Fontawesome 6

### ISSUE THREAD

**Issue by tonamphong** [gantry/gantry5#3196]
Hi there,
The Joomla 5 back-end template Atum uses FontAwesome 6 and I noticed that the Gantry 5 back-end icons are missing. Are there any plans to extend the Fontawesome version?

![fontawesome](https://github.com/gantry/gantry5/assets/2299347/231e0b23-c8f9-4e0d-8b40-39de9328027a)

Thank you

**Comment by N8Solutions** [comment]
I opened a ticket for something similar, and made a pull request, but it had to do with J2Store breaking the icons in Gantry 5. However, I believe it is also because the icons should have been coded, FA5 in Gantry 5.

https://github.com/gantry/gantry5/issues/3194

With that said, I agree, that if Joomla 5 is using FA6, it would be a great idea to move Gantry 5 to that as well.

What do you say @hexplor, is this doable?

**Comment by hexplor** [comment]
Of course. Not for 5.5.17 but for next release for sure.
