### ISSUE TITLE
Menu fixed on top

### ISSUE THREAD

**Issue by AbeAlpha** [gantry/gantry5#328]
Is there any way to fix the menu on top?
I try but ```#g-page-surround {transform: translate3d(0px, 0px, 0px);}```...
Why not load this class only on click offcanvas buton and remove on oncanvasoff?

**Comment by kevlardev** [comment]
This issue is along the same lines as #316 and #307 and a few others. Basically the fixed behavior doesnt function properly when a transform is in effect. Were working now with some different approaches to the offcanvas / g-page-surround interaction to get away from transform and the buggy rendering to work around this issue as well as others related to fixed navs, fixed headers, and fixed backgrounds.
