### ISSUE TITLE
Menu not displaying on 404 error page

### ISSUE THREAD

**Issue by paulinohio** [gantry/gantry5#3289]
I don't understand why the menu is unformulated of the 404 error page. The navigation is inherited from the base outline, which seems to work on all the other pages.

https://neilrisko.com/DELETE/xx

![Screenshot 2024-11-30 at 9 19 30 AM](https://github.com/user-attachments/assets/d4fe77d6-7096-4ad6-b533-425880b826db)

Thanks

**Comment by paulinohio** [comment]
I believe this is a CSS issue in the error.php but I'm not sure what to change to get to reference my custom CSS.

$className = __DIR__ . '/custom/includes/gantry.php';
if (!is_file($className)) {
    $className = __DIR__ . '/includes/gantry.php';
}

**Comment by N8Solutions** [comment]
@paulinohio Check out this answer from @mahagr on an old thread from 9 years ago.
https://github.com/gantry/gantry5/issues/918#issuecomment-149156008

> Joomla doesn't load JQuery in error pages. In fact it doesn't load any CSS or JavaScript -- those just get dropped out by Joomla itself. Also no content, plugin output or modules will work from error page.
> 
> The issue is that Joomla has special Document type error which gets used instead of html. The document type makes sure that no output from Joomla gets leaked into error page.
> 
> Because of above reasons the only things that work from the error page are the particles and atoms, which are not Joomla specific.


Since you are using **DJ MegaMenu**, your menu won't work on the error page. You can always contact the developer of DJ MegaMenu and see if he has a workaround for you but since Joomla is the issue here I think you'll need to find another way like creating a basic menu using the Gantry 5 menu system to be used only on the error page if you wanted. All you really need is to provide a link for the visitor to be able to reach the home page easily. I would say that is your best, easiest, and quickest option. It's not worth trying to figure out a workaround.

Hope this has helped!

**Comment by paulinohio** [comment]
Thanks for the information. I did end up just removing all nav menus.

**Comment by N8Solutions** [comment]
@paulinohio You're welcome. Can you please mark this as closed to help out the Gantry 5 team?

**Comment by paulinohio** [comment]
Do you know if you can use a joomla extension as the mobile off canvas menu? Do you just make a module instance or or module position where the off canvas particle goes or is there more to it? I feel like I tried it a while back and it didn't work.
