### ISSUE TITLE
Add *transparent* as an option in the colorpicker

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#334]
I don't know if this is possible, but it would be nice if *transparent* could be added to the colorpicker.

Right now, if zoo want to set the background of an element to be transparent using the colorpicker, you have one of two choices. Either you directly type the word *transparent* in the text field of the colorpicker (not everyone will realise they can type in a value in the input box) or you open the colorpicker ans then use the slider on the right to bring down the opacity to 0.

It would probably help some people if there was a button in the colorpicker called *transparent* that the user could click and insert *transparent* into the input box.

![screen 20shot 202015-05-22 20at 2001 17 07](https://cloud.githubusercontent.com/assets/1498512/7760935/7d28d794-0020-11e5-83f3-5386edd6a647.png)

**Comment by w00fz** [comment]
The only way to do so right now is to drag the transparency slider all the way down to 0, like you said. 

What's good about this is that it allows to keep stored the original color. The moment you want to change it back, later on, all you have to do is to move up the transparency slider again and you have your color restored.

I can look at adding the transparent button, although with that it will loose the capability of storing the color, clicking on the picker when the value is set to `transparent` will probably have to fallback to `rgba(255, 255, 255, 0)` since `transparent` isn't really a color and doesn't belong to any of the color picker values.

**Comment by alisamii** [comment]
Adding to the above, I think it would be great to have a gradient colour generator that would allow a simple method of adding a gradient background (with alpha transparency).

For example, I need to apply a gradient underlay on a section that contains 2 other sections (thank you @adi8i for your help with that. Also, with the help of @JoomFX I was able to extend the section settings to allow the application of background images. I was planning on applying an sag background image set to "contain" on the inner-wrapper section, but I have some problems which I cannot seem to resolve, such as misalignment of the background regardless how I set it.

An option, therefore, would be to define a gradient background for the section. But the colour picker does not support gradients, it only supports a single solid and alpha channel colour.

**Comment by JoomFX** [comment]
@alisamii  You can create a gradient yourself. It the Admin it might not look very well but you can do it:

1. Create two Color Picker fields in the Admin - Color 1 and Color 2
2. Then add the code in the Twig or in the SCSS that will generate the gradient on the frontend.

SCSS Example:
```
#g-wrapper {
  @include background-image(linear-gradient($wrapper-color1, $wrapper-color2));
}
```

The above is just an example, you got the idea.

Now, back to Gantry and its options/features...
Well, I'm againts adding every possible option to the Gantry Core. There are many reasons for that but here are the main ones:

1. I would like to keep the framework clean, simple and lightweight. If some specific feature should be implemented, this would be best to be implemented on per Template/Theme basis.
2. I definitely do NOT want Gantry5 to become a **Page Builder** where you have each and every possible option and you can create a website/design without touching the code.

To be a Frontend Developer, Designer, Website Builder or whatever you want to call it is a profession. It involves good understanding of UI, UX and coding. 

These are my 2c ;)

**Comment by alisamii** [comment]
@JoomFX I agree with you in most cases...except in the case where you are developing for a non-professional who still wants to maintain full control and will afterwards make changes.

In that case, you need to build a system that will enable point-and-click management, leveraging the power of Gantry and Joomla and the web developer's own ingenuity to build an integrated turn-key solution.

**Comment by JoomFX** [comment]
@alisamii I'm not talking for you (and your customer) personally, I'm talking in general :)

*except in the case where you are developing for a non-professional who still wants to maintain full control and will afterwards make changes.*

We all develop for non-professionals. Otherwise they would do it themselves.
And in your particular case, a non-professional cannot control everything. I really do not understand what a customer that is :) 65 years old lady. Yes, customer is always right. She has the options in the backend, because of the hard work you put, but:

1. Does she know what "Backround-Attachment" is?
2. Does she know what "Margin" and "Padding" are, and *how to use them*?
3. Does she has an understanding of basic Design concepts and so on?

@alisamii You have really good intention for this "young" lady, but the project you very is really, really rare case :)

**Comment by mahagr** [comment]
I would just say to the customer that it's not possible in the current system and if you implement it, that would cost a lot of money. The feature might be a nice one to implement -- at some point, but as there's perfectly fine workaround, I don't think it's important to have.

And if you want to make a field with 2 color pickers in it, it shouldn't even be hard to do. Just take the existing one and make the new field to combine those two fields into a single hidden one.

**Comment by JoomFX** [comment]
@mahagr would you please paste an example code explaining what you mean with the following:

*Just take the existing one and make the new field to combine those two fields into a single hidden one. *

I tried with this code but it doesn't seem to work:

```
    Gradient:
      type: input.hidden
      label: Gradient

        color-1:
          type: input.colorpicker
          label: Accent Color 1
          default: "#439A86"
        color-2:
          type: input.colorpicker
          label: Accent Color 2
          default: "#8F4DAE"
```

I just want to see how it will look at the backend (a field combining other fields). Thanks.

**Comment by mahagr** [comment]
Of course you need to create new input type that supports 2 colors. :) Might be something like input.colorgradient and in there you need to:

* create two text fields with color pickers (without name)
* hidden field for combined input (with name)
* some JS to get the input from the two visible fields and combine them together in hidden field

Shouldn't really be that hard. :)

Might also work without combining inputs, but using nested array... Haven 't thought how it would work, though. :)

**Comment by JoomFX** [comment]
I also tried the following but I still cannot make it to work:

```
    gradient:
      type: collection.list
      array: true
      label: Gradient
      value: title
      ajax: true

      fields:
        .color-1:
          type: input.colorpicker
          label: Accent Color 1
          default: "#439A86"
        .color-2:
          type: input.colorpicker
          label: Accent Color 2
          default: "#8F4DAE"
```

I need to say that I'm doing this under the Styles tab (not Layout). I get the collection list an I can add new items, but when I click on the item, the pop opens and gives 404 error.

Yeah, probably `collection.list` is not what I'm looking for but I need to try, you know ;)
This is what I'm trying to achieve - https://github.com/gantry/gantry5/issues/305 (see my comment there).

Oh, you just updated this issue. Thanks :)
Well, how do I create a new input type? In which file do I declare it?
But I would really like to achieve it with nested array and with the input.types we already have.

As a conclusion - how do you think I can achieve the thing I described in https://github.com/gantry/gantry5/issues/305. Thanks ;)

**Comment by mahagr** [comment]
Collection is not what you want, really, as you seem to want just to group multiple fields together so they will always appear as identical group of options.

For that take a look at our existing types in here:

https://github.com/gantry/gantry5/tree/develop/platforms/common/templates/forms

Maybe just use a normal set:

https://github.com/gantry/gantry5/blob/develop/platforms/common/templates/forms/fields/container/set.html.twig

The idea is to first create a set and then make a new type from it by converting your yaml into an array that you fill to the set.

**Comment by JoomFX** [comment]
It looks a bit advanced but I'll give it a try.
Thanks @mahagr

**Comment by mahagr** [comment]
Well, to me it's time you to get your hands dirty. Would be nice if we would have some other experts on Gantry 5 than just our team. :)

**Comment by JoomFX** [comment]
@mahagr I agree with you Matias :)
Unfortunately, my knowledge is limited mostly to frontend development.
Thanks to you and @w00fz I feel quite confident with G5 (including Twig and Yaml), but as I said above I won't be able to write the low level code you do or to implement anvanced JS solutions as @w00fz does.

Anyway, I would really love to contribute as much as I can to G5 so feel free to give me tasks that you think are suitable for me.

On a side note, there are couple more users that in my opinion are also feeling very confortable with G5 already. One of them is @adi8i :)

**Comment by adi8i** [comment]
I could try, but first i need to see an example, where that set is used.

**Comment by mahagr** [comment]
Actually this shouldn't be hard, its just going to be some twig. I don't think that even JS is needed for this one. All you need to do is to render 2 identical fields, but append something like [first] and [last] to the input field names. You also need to forward value.first and value.last to those and you're basically done.

**Comment by w00fz** [comment]
This is now implemented as a `transparent` button below the different color modes like in the mockup. 

![transparent](https://cloud.githubusercontent.com/assets/11734/7951620/8430221c-095e-11e5-9579-967be6ee5d2d.jpg)

Note that because I really didn't like the idea of supporting the `transparent` word for various different reasons<sup>1</sup>, this new button just acts as a shortcut for the opacity slider set to `0`. This will transform the color to `rgba` if necessary and make it transparent. 

The benefit with this approach is that the original color will always be preserved, stored and reusable later on, if required.

<sup>1</sup> Event though the `transparent` word is totally valid in CSS as a color, it really isn't mappable to any color and even less to the color picker itself, adding a layer of complexity to the math necessary to calculate handles and indicator positions. Also, as explained in the previous comments, forcing to transparent makes the old color to be lost and not retrievable.

**Comment by DanGthatRokGallery** [comment]
In Antares and Photon when I click the TRANSPARENT button in the color picker this is the color code generated:
`rgba(255, 255, 255, -0.00)`

On trying to SAVE I get this error message:
INVALID FIELDS
Please review the fields in the page and ensure you correct any invalid one.

If I manually change the code to 
`rgba(255, 255, 255, 0.0)`

it SAVES.

**Comment by mahagr** [comment]
@DanGthatRokGallery Can you create a new issue on this. Closed issues do not count; they have already been implemented/solved (you can however refer them from your new issue).
