### ISSUE TITLE
Make particle settings panels/cards collapsible.

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#349]
If you have a lot of particles defined in your template, the setting page begins to become very long.

![panels-expanded](https://cloud.githubusercontent.com/assets/1498512/7788535/8a4c87b6-023e-11e5-9b2e-f631de6b222d.png)

The solution may be to make each panel collapsable as in this design:

![panels-collapsed](https://cloud.githubusercontent.com/assets/1498512/7788538/a5516c34-023e-11e5-845f-ae632642b77b.png)

This also gives you a bird's-eye view of what particles are defined and which have been enabled (globally, or specifically for a particular outline).

**Comment by JoomFX** [comment]
I like the idea :)

**Comment by federone** [comment]
i like too, really useful

**Comment by alisamii** [comment]
Yippie!

**Comment by sural98** [comment]
+1 for saving screen space

**Comment by JoomFX** [comment]
I was thinking about this again, especially for the Styles tab and I would really like to see it implemented.
To have all sections under Styles tab "closed" will be awesome, the user will just see the available sections and once he clicks on a particular section it will expand and will show all available options for the section.

In my imagination I see this as a great UX improvement. Honestly, it is not just that I would like to have this feature for myself and my Templates, I do think it will be a great UX improvement in general.

And I'm also cross-referrencing this issue https://github.com/gantry/gantry5/issues/305

**Comment by w00fz** [comment]
Yeah collapsible sections was already in the list of things to do. The only details are regarding what state this should start with.
I understand starting collapsed would make it look cleaner but we loose the ability to see right away what are the values. 
If starting collapsed would solve the OP issue, it would introduce the opposite issue where in order to see all the sections values you need to expand them. Even though a global toggle for collapsing/expanding all the sections in one click would still carry the issue.

**Comment by JoomFX** [comment]
@w00fz Thanks! I'm really happy that you are already considering this.

Well, here's a suggestion:

1. The template/theme developer will decide if the sections (and the Particles under the Settings tab) will be collapsed or not by default. There will be an option in the `theme.yaml` file and there the developer will be able to chose the default state. Depending on this setting a particular class will be added by default to the sections in the admin.

2. As you said, there will be a Global Toggle Button.

Now, when I'm thinking again, point 1 is not really needed. It just overcomplicates the things and will make the different G5 Templates/Themes not consistent (some will be expanded by default, others not). So, probably a well visible Global Toggle Button might be enough.

**Comment by w00fz** [comment]
I personally thing the default behavior should be all visible and then the user or developer accessing the Styles will decide if they want to collapse some sections or not.
So basically the functionality will just be to be able to collapse sections. But I strongly believe everything initially visible is the expected behavior here.

**Comment by JoomFX** [comment]
@w00fz If I had to make this decision, I would probably choose to have them collapsed by default without giving too much thought about the issues it might bring. I just like to have everything clean, tidy and not allocating too much space.

But you have more experience than me with such things :) You might vote internally in RT and see what comes out :D

But having the collapsible option is good enough on its own!

**Comment by alisamii** [comment]
I think that there could be a solution if we can implement some sort of persistent state, meaning, whether the global default is collapsed or open, when a user toggles the state of a panel, a cookie or some mechanism is used to remember the users chosen state.

Then, the next time the user views the settings panel, the panels are displayed in the state the user last left them.

This could be a good compromise that addresses Djamil's concern that the user won't know what options are available on first load, and also addresses Ivo's concern for a clean interface.

Now what remains is a decision as to what the default state should be... Open or collapsed.

My vote is collapsed, with the toggle all button to open them all.

Best regards,

Ali

**Comment by mariantanase** [comment]
+1 for collapsed :+1:

**Comment by gyvermac** [comment]
+1 for collapsed :+1:

**Comment by federone** [comment]
hi, I was playing around, and in "administrator/components/com_gantry5/js/main.js" at bottom added:

```$('head').append('<style type="text/css">#settings .card.closed{background-color:#EEE;border:0}#settings .card.closed h4{background-color:#FFF;padding:10px;border:1px solid #DDD;margin:-10px}</style>');
$('#settings .card h4').prepend('<i class="fa fa-angle-right"></i>');
$('#settings .card h4 i').css({"cursor":"pointer"});
$('#settings .card,#settings .card h4,#settings .card .inner-params').addClass('closed');
$('#settings .card .inner-params').hide();
$('#settings .card h4 i').click(function(){
	if($(this).parent().hasClass('closed')){
		$(this).parent().removeClass('closed').addClass('opened');
		$(this).parent().parent().removeClass('closed').addClass('opened');
		$(this).removeClass("fa-angle-right").addClass("fa-angle-down");
		$(this).parent().next().removeClass('closed').addClass('opened').show();
	} else {
		$(this).parent().removeClass('opened').addClass('closed');
		$(this).parent().parent().removeClass('opened').addClass('closed');
		$(this).removeClass("fa-angle-down").addClass("fa-angle-right");
		$(this).parent().next().removeClass('opened').addClass('closed').hide();
	}
});```

and works well like its on screenshot .... only not called in ajaxify :), for testing its good i think

Best Regards,
Federico

**Comment by w00fz** [comment]
Thanks I'm now looking into this.
Looks like it's common agreement that collapsed should be the default behavior and I'm the only one thinking otherwise :smile: 

So this change will also be integrated into the Styles tab, for consistency. Both Styles and Settings will have collapse/expand capabilities as well as global toggle for all.

Sounds good?

**Comment by JoomFX** [comment]
@w00fz it does not sound good......... it sounds awesome :D
Thanks Djamil !

**Comment by federone** [comment]
> So this change will also be integrated into the Styles tab, for consistency. Both Styles and Settings will have collapse/expand capabilities as well as global toggle for all.

yes, that will be great,

**Comment by newkind** [comment]
Allright, so I think that alot of people won't figure out expanding the sections. I agree that the sections should be collapsible, but the default behavior should be open with a button to collapse all sections. I fully agree with Djamil on that one. This will be a usability PITA if we stick with it.

Again collapsible - yes, one button collapse/expand for all sections - yes, but default behavior should be EXPANDED!

**Comment by federone** [comment]
> Again collapsible - yes, one button collapse/expand for all sections - yes, but default behavior should be EXPANDED!

you are right, some people wont understand that, so default behavior should be expanded

**Comment by JoomFX** [comment]
@w00fz @newkind I do believe that having them collapsed by default will not bring any confusion or usability issues. I mean, there will be a well visible Toggle Button which should catch the user attention immediately. And also, what kind of a user should you be to not figure out that these "things" are expandable. Yah, completely agree that there are many types of users, but come on... why would you have just the Section Names or just the Particle Names there is you cannot do anything with them. I mean it is really easy to figure out that these are expendable.

Anyway guys, this is just my opinion and as I said earlier, you have more experience with me so I believe that whatever you decide will be the correct choice.

**Comment by DamirPecnik** [comment]
@w00fz @newkind Totaly agree with this it sohuld be like this:
One button collapse/expand for all sections - yes, but default behavior should be EXPANDED!
For Settings and Styles also!

**Comment by w00fz** [comment]
Yah on further discussion with @newkind and @mahagr and as I already outlined above, to me having them all collapsed on first load can be potentially problematic.

If I'm new to a theme and I just install it for the first time, seeing everything collapsed on first load might look like there are no options, realizing that the sections are expandable could not be that obvious.

Perhaps we can store the state. So we start expanded and whatever you expand/collapse at that point will be stored and you'll keep loading them that way until you clear your cookies or install it on another site.

**Comment by adi8i** [comment]
Finally we have an agreement on this one  :D

**Comment by JoomFX** [comment]
Yes, please store the state.

**Comment by mahagr** [comment]
I think there's a point of NOT having all collapsed on first load. People will make questions before even trying anything and it would become a support issue.

On the other hand everyone will start looking how to collapse the content after 5 minutes of use and the common ways are either to click on the header rows or to find a button to collapse it all.

Stored state is must, though, otherwise it will be nightmare -- regardless if its collapsed or not.

**Comment by w00fz** [comment]
Ok I think we are all agreeing now, I'll get to work :+1:

**Comment by alisamii** [comment]
I concur that the initial state should be open and as mentioned by me previously below, stored state is high value enhancement that addresses the concerns of Djamil et al and brings Enhanced usability for the experienced user.

Best regards,

Ali

**Comment by w00fz** [comment]
Hey guys, I have the implementation with localStorage done. I'm still missing the global toggles but that's minor to implement at this point.

One cool feature I also added is for the particles  to be able to go against the default `expanded` behavior from the `YAML` definition.

So if we take the Social Particle (`social.yaml`):

``` yaml
name: Social
description: Display social buttons.
type: particle

form:
  fields:
    enabled:
      type: input.checkbox
      label: Enabled
      ...
```

You can now do this:

``` yaml
name: Social
description: Display social buttons.
type: particle

form:
  collapsed: true # note here
  fields:
    enabled:
      type: input.checkbox
      label: Enabled
      ...
```
Which will make the Social now collapsed by default instead of expanded. 

Another change that happened is that now the cards are using the CSS3 `column-count` instead of the `flex` approach of before. This change has been necessary because otherwise when collapsed, flex would do its job and keep the same height with the sibling card which obviously now it's not desired anymore.

Feel free to have a play with it with the [CI Builds](http://gantry.org/downloads#ci-builds)

**Comment by alisamii** [comment]
Hi Djamil,

Adding the setting in the yaml is a great addition.

Best regards,

Ali

**Comment by gyvermac** [comment]
just tested the last build.. Collapse is fine on Styles and Settings... but not implemented in Layout ?

**Comment by w00fz** [comment]
Alright this is now fully implemented with a couple treats: Filters and the swatches in Styles are now collapsible as well.

![filters](https://cloud.githubusercontent.com/assets/11734/7850916/f58727a6-049c-11e5-8776-d1a26d72e2cd.jpg)

![swatches](https://cloud.githubusercontent.com/assets/11734/7850940/308efbb2-049d-11e5-941c-0dfa35c2053b.jpg)
