### ISSUE TITLE
Keep loading, when navigate in Layout Manager

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#353]
Sometimes when navigate in layout manager, often to Settings or Layout, will just keep loading, till you refresh the page. 

Well, i think is a bit hard to catch bug, may be some thing that may cause this. Some of them may be from my side, i am not too sure. 

But i will open this issue just in case, you know :) .
@w00fz

**Comment by mariantanase** [comment]
True, the same thing happens to me
![g5](https://cloud.githubusercontent.com/assets/3976174/7812871/5894c3ae-03b6-11e5-9dd2-d90448affc3d.png)

**Comment by w00fz** [comment]
This is most likely some JS error caused by either a bad ajax response or some bug in the JS itself.
It would be extremely helpful if you guys could keep the Developer bar open and keep  an eye on it when this happens again.
When and if it happens again you could then report back the JS error, if any, and the body response in the Ajax call.

Unfortunately I am unable to reproduce this one and without a way to reproduce it, I cannot fix it.

Thank you!

**Comment by adi8i** [comment]
Ok i will take a look when will happen again, is not all the time :)

**Comment by w00fz** [comment]
I'm going to close this for inactivity, feel free to reopen if it happens again. It might be already fixed in the current version.
