### ISSUE TITLE
Auto Update Travis CI version

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#368]
@w00fz, Joomla will update to RC2. Or this is how it works ? :P 

![capture](https://cloud.githubusercontent.com/assets/9744973/7836060/25fc7998-0486-11e5-8b9d-76e07f540bbe.PNG)

**Comment by w00fz** [comment]
If you mean that after a CI Build you are prompted to update to RC2, this is intentional.
What we are doing is hiding the purple update notification in Gantry 5 admin but the Platform will still recognize the development version as lower than the stable one.

```
dev-f93f1b1d6 < 5.0.0-rc.2
```

We also like to keep it this way, it makes it easy to revert back to stable from a `dev` version.
