### ISSUE TITLE
Assignments' Filter Issue

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#398]
I have 133 menu types and 1800+ menu items in a multi-language Joomla.
Assignments page thus covers a long screen space.
On the other hand I face 2 issues on this page:
1. Toggling Select/unselect near the filter makes the page unresponsive probably because of the number of items
2. Searching (filtering) a menu item won't hide the unrelated menus and we will still need to scroll down to find which one is filtered. We could be able to filter by the menu types also.
![assignments](https://cloud.githubusercontent.com/assets/1849490/7913107/9f752d7c-0875-11e5-8a18-75ee755dab77.png)

**Comment by w00fz** [comment]
1. You should definitely toggling all per menu type rather than using the global one, with those many items it's just a lot of weight for your browser. I did have an async implementation before and it was better but caused issues with the Changes Indicator, I might revisit it.
2. I will look into hiding the sections if they are empty after filter, makes no sense to show them like that, I  agree.

Thanks!

**Comment by w00fz** [comment]
This is now implemented. The cards that don't match will get hidden and I also changed approach for the global toggle. It should be a bit faster.

**Comment by sural98** [comment]
I have tried the implementation. **Regardless of the filtered term** the following cards are also being listed. 
Tablolar
Top menu en
top menu-kr
Uncategorized-en
Uncategorized-ru
User menu al
User menu ar
User menu en
User menu es
User menu tr
![assignments](https://cloud.githubusercontent.com/assets/1849490/7959506/6272090c-0a02-11e5-9e43-9d9f279d6118.png)
