### ISSUE TITLE
Create a fake sub-menu item. 

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#419]
Would be possible to add a module/particle as `sub item` to a menu item that doesn't have any child ?

![11](https://cloud.githubusercontent.com/assets/9744973/8019401/c2fde03a-0c54-11e5-9d4b-77324cedd312.png)

**Comment by adi8i** [comment]
Because we all are busy, and for sure you have other things to do, i will close this one for now :)

**Comment by mahagr** [comment]
We kind of did have this feature (displaying empty sub-menus), but we decided to remove it as there was no use for it at the time we didn't have any particles to add to the menu.

It should be fairly easy to put it back; just remove the additional logic we added for it. :)

**Comment by alisamii** [comment]
I think that this is an important missing feature. As @mahagr explains, the logic is there but code has been added to disable the functionality.

I now find myself in need of exactly this functionality, and it is unfortunate that it has been disabled.

I looked in the code in this path `/administrator/components/com_gantry5/templates/menu` but I wasn't sure what the additional code that needed to be removed was.

If this is a simple fix, I hope that it can be addressed soon because it will greatly enhance the menu functionality.

**Comment by w00fz** [comment]
We really never had this functionality but just very flexible code to support it. Before you were able to click on this non-parent items but nothing was happening except for a spinner showing and hiding, because we've been always filtering out the submenu for those items that didn't have any children.

Anyway this is now available and working :+1:
