### ISSUE TITLE
Menu - Feature Request

### ISSUE THREAD

**Issue by TGoodrich** [gantry/gantry5#427]
First i want to say great job with Gantry 5 .. I'm loving it!!

I was was thinking a good addition to the menu editor would would be to include options to make the front-end nav menu stay static or hide when scrolling the page similar to the Gantry 4 Anacron template. Maybe give this ability to either or both the header and nav sections. Is this something that can be integrated into Gantry 5 or will it need to stay template dependent?

**Comment by w00fz** [comment]
This is something we wanted to keep template dependent. Since It's not something that is a must for every theme, nor something that everyone will want, I think adding this feature built into Gantry 5 itself, will just add too much code and logic.
We want to keep Gantry 5 and Hydrogen to the bare minimum so that they can be easily extended and they are as fast as possible, without the clutter of very specific options.

That said, I've seen some implementing fixed headers with [headroom](http://wicky.nillia.ms/headroom.js/), like @adi8i and I think @JoomFX as well. I am sure if you join the [Gitter Chat](https://gitter.im/gantry/gantry5) someone can help you with setting that up. With the `Custom JS/CSS` atoms and a bit of `custom.scss`, you should be able to achieve this fairly easily.
