### ISSUE TITLE
Add a change Log to the CI builds 

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#436]
It would be great to add a change log to the CI builds.

A command such as:

`git diff --name-status [SHA1 [SHA2]]`

include enough of the SHA to identify the commits plus you get a simple prefix telling you what happened to the file (modified, deleted, added...)

This could then be saved as a file and linked to below the CI build download links.

**Comment by w00fz** [comment]
There really isn't any changelog. If you go to the [Download Page](http://gantry.org/downloads#ci-builds) the SHA is already linked and will take you to the change that triggered that commit.
That is the only changelog because CI Build get rebuilt at every commit so there's not going to be anything else in there.

If you are far behind with the CI Build, you can always manually do a diff yourself via GitHub.

Example: https://github.com/gantry/gantry5/compare/5159cd452...efc1097fc
