### ISSUE TITLE
The Menu styling is a bit messy

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#449]
I'm opening this issue as per our conversation in the chat.

There is a bit strange thing in Hydrogen.
I suppose it's been done on purpose but still, it is strange for me.
If you change the "Main" background from the Styles tab, the background of the Active Menu also takes this background.
The code responsible for this is located in `g5_hydrogen/scss/mixins/_nav.scss`:

```
@mixin main-nav-colors($section-background: $navigation-background, $section-text-color: $navigation-text-color, $section-active-background: $main-background, $section-active-text-color: $main-text-color)
...
...
...
                &.active {
                    background: $section-active-background;
```

**Comment by JoomFX** [comment]
@kevlardev @w00fz guys, the Main Menu styling is all over the place, really.
I'm trying to bring it into a more consistent state for the last one hour and I'm really struggling with it.

Can't we have just one centralized location, for example `scss/hydrogen/menu.scss` where we have the whole styling, which does not depend on "strange" variables and then just have some small adjustments in the `scss/hydrogen/_header.scss` and "`scss/hydrogen/_nav` if needed?

Currently, the biggest part of the styling is located in `scss/mixins/_nav.scss`. Then you import it in `scss/mixins/_base.scss` and then you import it in `scss/_dependencies.scss`. Well, is it really needed? Have a look at Ethereal for example - there is no `scss/mixins` folder at all and `scss/mixins/_nav.scss` has been moved into `scss/rt_ethereal/_mainnav.scss`

Also, back in Hydrogen, the whole menu styling is dependent on "strange" variables. Have a look at the mixin `main-nav-colors`:

```
@mixin main-nav-colors($section-background: $navigation-background, $section-text-color: $navigation-text-color, $section-active-background: $main-background, $section-active-text-color: $main-text-color) {
```

What does the `$main-background` has to do with the Menu? Furthermore, my layout does not have a Main Section, so I removed it from Styles, I removed the !default from `_colors.scss`, I removed the `$main-background` variable completely. Well, I do understand that in this example it is my own problem, but what does the `$main-background` variable has to do with the Menu in general?
Also, the whole styling is dependent on the `$navigation-background`, `$navigation-text-color`, `$header-background` and  $header-text-color. Basically, it is dependent on the `main-nav-colors` mixin. can't it be done with `inherit` in most places. And then apply some adjustments in `scss/hydrogen/_header.scss` and `scss/hydrogen/_nav.scss`. Or maybe the Menu can have it's own variable and colorpicker under the Styles tab and then the styling will be much more consistent and centralized in just one file?

I hope you understand what I mean.

**Comment by kevlardev** [comment]
Basically the menu is a pretty large construct, its easily the largest amount of scss in the entire theme itself. A large amount of the scss will not change from theme to theme, barring large menu redesigns or modifications, so those portions of the menu are housed inside of nucleus to make it easier to use from theme to theme as well as make maintenance and bug fixes more streamlined.

The portions of the menu that will usually be modified on the theme level are generally colors, paddings and margins, alignment, and so on. So those parts of the menu are housed inside the theme scss. The _nav.scss in hydrogen contains all of this theme side menu scss with the exception of one major portion, the block of scss in the mixins.

The reason this was set up as a mixin is that it provides dozens of menu elements with different colors. The menu in hydrogen is designed to be used either in the Header section or the Navigation section. Because these two sections can have completely different background and text colors, we needed to be able to pass the variables for those sections through the menu.

Youll notice in both _header.scss and _nav.scss we are calling that mixin and providing the variables for those sections so the dropdown colors and such blend perfectly with the section they are in. If we didnt have those variables, we would have to repeat all the same scss in both files, making maintenance and bug fixes a pain because any change you make to the menu you would have to make in both files every time (or even more files should you add menu color support to other sections). Inherit isnt sufficient as there are many unique elements and classes that have to pick up the section colors, as well as in many cases the link colors for a section arent always the same colors you want to use for menu links due to the stylistic differences of a dropdown menu and its active/hover effects.

The reason that $main-background is used, is because the active state of the tab was designed to match the main background color to create a 'tabbed' appearance. When there isnt a showcase active, the active tab in navigation section (the optimum section to use for the menu) is up against the main body area.

![screen shot 2015-06-12 at 10 27 15 am](https://cloud.githubusercontent.com/assets/4529755/8133570/c3ba42a4-10ee-11e5-97b4-d75585bd2973.png)

So it made sense that if the main-background color changed, the active tab should change with it to adapt and match. Obviously this is a theme specific stylistic choice for Hydrogen, each theme can and will be different in approach due to its unique design needs. Because Hydrogen was design mainly to use the menu in the navigation section to achieve this affect, the scss was set up to reflect this (as well as be reusable and portable to provide drop in support for other sections).

In regards to dependencies, much of the menu scss and the scss throughout hydrogen is reliant upon nucleus mixins as well as bourbon mixins and functions. So those dependencies must be imported so that those utilities can be used. SCSS offers a lot of power and portability, its ability to make things modular helps keep duplicated code down (from a development standpoint) so that one change in one file can be used in multiple files.

**Comment by JoomFX** [comment]
@kevlardev thank you very much for the detailed explanation Kevin. It is really appreciated!

Yah, I understand it is a Theme (Hydrogen) specific approach. And now, when I look at it again I actually realize that everything has been grouped/placed very consistently - you have the _nav.scss in the mixins folder as it is actually a mixin, etc.

Thanks again! I will just move some code around and modify it so it suits my needs best. I'm building a kind of a "Starter" theme that I will use as a start point for all my Templates and it is quite different than Hydrogen ;)
