### ISSUE TITLE
Css Issue box-sizing

### ISSUE THREAD

**Issue by 810** [gantry/gantry5#45]
Please remove :
/media/gantry5/engines/nucleus/scss/nucleus/_core.scss

*, *::before, *::after {
	@include box-sizing(border-box);
}

This is conflicting with padding on ul li paddings:

before:
![1](https://cloud.githubusercontent.com/assets/876623/6960446/bafc6484-d922-11e4-8331-0e5cc5eb9149.jpg)
after: 
![2](https://cloud.githubusercontent.com/assets/876623/6960450/c41e5a5e-d922-11e4-86e2-c9193f6c770f.jpg)

**Comment by 810** [comment]
our issue, so i closing this one

**Comment by mahagr** [comment]
Looks like above rule breaking bootstrap markup here and there. Looks like things like separators with 1px height and background colors etc get collapsed.

**Comment by kevlardev** [comment]
Unfortunately thats not something that can be changed globally. Our entire layout system and all elements have been built around that box model as its much better (bootstrap 3 as well as nearly every other framework and modern approach on the planet use border box now). Im probably going to have to reverse the rule for joomla component output instead, since i cant be sure all what joomla/bootstrap 2 elements will be adversely affected.
