### ISSUE TITLE
Add "delete element" overlay to Menu Editor

### ISSUE THREAD

**Issue by Crolug** [gantry/gantry5#458]
...similar to that of Layout Editor. Now there's no way to delete anything other way then manually inside YAML file.

**Comment by w00fz** [comment]
What do you mean exactly, you can delete Particles and Modules. 
There isn't any implementation for deleting items themselves, you have to use the platform (Joomla / Wordpress) to manage that. The Gantry 5 Menu editor only allows you to reorder the items and change their properties, as well as drop in Particles and Modules that you can delete.

**Comment by mahagr** [comment]
It might be just me, but I've not found a way to delete particle from the menu.

**Comment by w00fz** [comment]
There was just 1 case where it wouldn't show and that was when you drag dropped a particle / module and then canceled. In that case you couldn't delete the particle but it didn't make any difference because the particle was never stored, even after save so after a refresh it would have gone.

Anyway this is now made more clear and you can delete them even when you cancel.

**Comment by Crolug** [comment]
Is it live or will be part of next RC?
