### ISSUE TITLE
Open menu item on click and/or in a modal

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#471]
Right now, we have the ability to add a *fake drop-down* as per #419 which significantly improves functionality of the menu settings.

It would be good to be able to select, per item, how the menu item opens.

Use case would be for a login menu item.

It would be useful to be able to set the menu item to open only on click, while retaining on-hover the default menu item opening. This would allow a menu item such as login not to drop-down automatically when hovered over, while allowing other menu items to open on hover.

Likewise, it would be useful to be able to set the on-click behaviour to open the dropdown element in a modal window. Again, in regards to the login module, this would allow a clean interface where the module opens in a modal window.

The current implementation of the menu system assumes that all menu sub-items are to be opened in a drop-down, either as a simple or an extended menu layout, and that the drop-down trigger is on-hover.

**Comment by w00fz** [comment]
I like the idea, however I don't think this should be built-in into Gantry but rather implemented if needed by the developer.

The first reason is we do not have a modal for the front-end and quite frankly we do not intend to provide one, it is a lot of extra code that would rarely get used or, worse, gets loaded and never used, i.e, you decide to use Bootstrap modal instead.

The second reason is if we are to implement this in Gantry core, we need to take into account an incredible amount of possibilities and handle them all: 
  
  1. You have multiple modules/particles in the submodule
  2. You have columns in the submodule
  3. Is the parent a separator? Is it a link? (we already had to implement logic to handle touch devices so that you can have parent items that are both links and parents, imagine adding a 3rd click behavior)
  4. Styles need to handle it all, all the time, in all case scenarios

This is all it comes off the top of my head at the moment but I'm sure there's plenty more. When it comes to menu, it's never easy.

If this was all handled by the developer, things are much simpler because contrary to us that have to guarantee stuff to be working all the time with all themes in all scenarios, you only have to worry about your own environment. You know how you want it to look like, what it should do, that, for instance, you are only going to support those items with a specific class or attribute.

The way I would implement this is via Tag Attributes and some JavaScript.
First I would add a `data-set` attribute, for instance `data-menu-modal`. Then via JavaScript I would target that element, add a click handler to open the login subelement in the modal of your choice and stop the propagation for this event.

Describing how I would implement it makes it even more clear that this should be custom rather than built-in into Gantry.

I would love to see what you come up with though!
