### ISSUE TITLE
Menu Styling dependent on $navigation-text-color and $navigation-background

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#49]
In the _nav.scss file (g5_hydrogen\scss\hydrogen) the Menu Styling uses these two variables.
But what if the user moves the Menu Particle in the Header (or other) position?

Wouldn't it be better to choose the Menu Styling from the Menu Particle itself? Hmm, but then it will not be consistent.

Anyway, can the Menu Particle has its own variables and section in the "Styles" section in the backend so it does not matter in which section you put the Menu Particle?

**Comment by kevlardev** [comment]
The design of Hydrogen is intended to have the Gantry menu particle located in the navigation or header sections only. I'm going to change the color value inheritance so that it will be based on the section its published in, so menu elements when in header will make use of $header-background and $header-text-color and when in navigation use the navigation elements.

Moving the menu particle to other locations of the theme presents a lot of other non color based technical problems, particularly in places such as the sidebar or the footer, where the entire megamenu system and javascript will not be able to function properly. It would require a large amount of additional css and javascript to be able to handle every possible position throughout the entire theme, and that will also change from theme to theme based on each one's unique design.

Ultimately this is not a Gantry limitation, but rather something that we want to control via the theme itself for design and stylistic purposes. Each theme, and each theme developer, can choose what locations make the most sense for the primary Gantry menu particle to have style and operational support

**Comment by JoomFX** [comment]
Thanks @kevlardev .

**Comment by mahagr** [comment]
See #58
