### ISSUE TITLE
System messages particle adds a new row

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#506]
I have installed G5 "Version: dev-358b0bae4 / Released: June 27, 2015"
I am using Ethereal w/ Logo and menu in Header, System messages in Top
System messages particle adds the following blank row on top of Header and creates an extra blank area.

```<section id="g-top">
                <div class="g-container">                        
    <div class="g-grid">
    <div class="g-block size-100">
    <div class="g-content">
    </div>
    </div>
    </div>
            </div>
    </section>```

![system_messages](https://cloud.githubusercontent.com/assets/1849490/8396234/48ebf9f4-1da6-11e5-9fc8-0197f6c1d7e4.gif)

**Comment by mahagr** [comment]
Well, this is side effect of making enqueued messages to work at all (#496). I guess we just need to find yet another way to do this, because of we do not have enough information for not to render the block until everything has been rendered.

**Comment by muffindcc** [comment]
As the section still has to be rendered so that when a system message is active, it appears, the simplest workaround is to remove the margin/padding on .g-content. To do this, simply use the preset block variations No Margin and No Padding together, or the CSS Class flush, if using a RocketTheme club template (you can add your own flush class if using a non-RT template). This will remove the margin and padding on the .g-content DIV and the block will collapse completely, as if it was never rendered in the first place.

**Comment by sural98** [comment]
Setting no padding no margin as block variations just works as a workaround
