### ISSUE TITLE
Css Divider dropdown

### ISSUE THREAD

**Issue by 810** [gantry/gantry5#51]
/media/gantry5/assets/css/bootstrap-gantry.css

Remove:
.dropdown-menu .divider { 
border-bottom: 1px solid #ffffff;
}

Its having double color, and now on dropdown-menu, the divider have no color.

**Comment by mahagr** [comment]
More information what is broken, please. :)

**Comment by kevlardev** [comment]
Im not sure I understand what the issue is here. All of the dropdown css is purely bootstrap 2, it sets the dropdown color to #ffffff by default, then has a divider with a background of #e5e5e5 and border of #ffffff ( i guess to create some bevel effect, though its kind of lost when the background and border are the same color. Either way, this is purely bootstrap, not anything modified for gantry or hydrogen

**Comment by kevlardev** [comment]
Also, just to clarify what the 'bootstrap-gantry.css' file is. Its a direct copy of the bootstrap.css from joomla's jui, the only modifications being the removal of out of date vendor prefixes (no longer needed with gantry's browser requirements), some html reset stuff (already included in nucleus), and the .carousel classes (have never come across any joomla or third party utility making use of these, thought they could be added back in if they are needed somewhere) to trim down the files size a bit.

**Comment by 810** [comment]
The dropdown menu have a white background, when you add a divider, but on the css, you see it has a border-bottom: 1px solid #ffffff; 

That's wrong , white on white have no effect. When you remove the line, you get a 1px height with color: #e5e5e5

So its the same as border-bottom: 1px solid #e5e5e5;

**Comment by kevlardev** [comment]
I understand, my point is that its how it is in default bootstrap. We don't want to modify the default bootstrap css/file itself, as we cant be sure how other third party components and such are making use of it. So rather than remove it from bootstrap, we can look at changing the behavior from Hydrogen.

**Comment by 810** [comment]
the issue is 
````
*, *::before, *::after {
box-sizing: border-box;
}
````
/media/gantry5/engines/nucleus/scss/nucleus/_core.scss

then https://github.com/gantry/gantry5/issues/45 is also fixed

**Comment by kevlardev** [comment]
Unfortunately thats not something that can be changed globally. Our entire layout system and all elements have been built around that box model as its much better (bootstrap 3 as well as nearly every other framework and modern approach on the planet use border box now). Im probably going to have to reverse the rule for joomla component output instead, since i cant be sure all what joomla/bootstrap 2 elements will be adversely affected.
