### ISSUE TITLE
Full-width/Boxed and Nested sections - take 2

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#521]
In the screenshot below, there are two issues.

One is that nested sections display oddly within the layout manager.

![nested-sections](https://cloud.githubusercontent.com/assets/1498512/8473407/b2dd3bf6-20a9-11e5-8a61-2e900d1aa535.png)

The other is nesting of sections and where the `g-container` div is implemented.

Here, there is a `container` that needs to be `full-width`.

Within it is a section called `Second-wrapper` and a section called `showcase`.

`Second-wrapper` is also supposed to be `full-width`.

`Second-wrapper` has two nested sections, `header` and `navigation` which are supposed to be `boxed`.

This layout allows assigning a background image to the `container`, and a different background image to the `Second-wrapper` which would overlay the background image of the `container`.

If the `Second-wrapper` is not `full-width` you have visual disharmony as in this screenshot:

![disharmony](https://cloud.githubusercontent.com/assets/1498512/8473398/a14186c2-20a9-11e5-8a3d-6d1a4087099a.png)

From the backend-point of view, the Layout Manager should allow something like this:

![nested-target-layout](https://cloud.githubusercontent.com/assets/1498512/8473476/3223cc5e-20aa-11e5-958b-c36431a8520f.png)

Before the `fix` was implemented for `full-width` vs `boxed`, (https://github.com/gantry/gantry5/issues/301, https://github.com/gantry/gantry5/issues/319 and https://github.com/gantry/gantry5/issues/434) the above could be achieved. Now, that isn't doable by default, and ugly hacks have to be implemented to try to force this, but it doesn't always work on all platforms and it is not an elegant solution. In a way, the `fix` for https://github.com/gantry/gantry5/issues/301, https://github.com/gantry/gantry5/issues/319 and https://github.com/gantry/gantry5/issues/434 `broke` a feature (even if that feature wasn't complete or elegant as it was, it was workable...now it really isn't).

**Comment by kevlardev** [comment]
Just to bring you up to speed, and continuing our discussion about this from last week. We are working on a better system of handling this to allow for several functionalities that should cover all of the use cases for nesting sections and so on. Im going to be creating specific issues for each item here soon and will reference this issue to it.

But basically, we are going to work on trying to implement better handling of containers so that there is better control over where they are placed (or restricted). This will also allow for better contorl of nested sections. In addition to that, we want to implement an easy mechanism of wrapping sections in divs as well (for those cases where you just need a few wrappers for cosmetic effects and dont need a full "section" worth of controls).

**Comment by alisamii** [comment]
Hi @kevlardev that sounds great, thanks.

Since you have my Akeeba backup and you played around with Itt, maybe while you're at fixing this issue, you can also look at improving the way I set up my custom `section.html.twig` and `section.yaml` as the way I have it set up is really inefficient but it gets the job done. I'm sure there's a better way to do it and I'd love your input on that.

**Comment by mahagr** [comment]
I would love to see your workaround as it may give some clues on the issue and different ways to get it fixed.

**Comment by kevlardev** [comment]
Consolidating these issues to the new main issues for reworking the container and nested sections control
