### ISSUE TITLE
RTL: mobile menu incorrect positioning

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#525]
first reported by mark for our upcoming july template. (ticket #91)

> I'm not sure what needs to change here since we use the same left opening mobile menu for LTR and RTL. But at the moment the scrollbar for the RTL menu second level sits on top of the menu items - not sure if it's the menu items or the scrollbar that needs to move?

**Comment by w00fz** [comment]
I'm not sure I understand this issue. Although if by `same left opening mobile menu` you mean the Offcanvas section, note that it's not stuck on left, it can be changed to be on the right side. (`LM -> Offcanvas Section gear -> Position`)

**Comment by mahagr** [comment]
I think that it should be automatically repositioned / mirrored on RTL. If your site has both LTR and RTL languages, it's not really optimal to force it to be on right in English version.

**Comment by w00fz** [comment]
I disagree. There are designs where an offcanvas on the right side might look more appealing than on the left and it wouldn't necessary mean it's RTL.

**Comment by kevlardev** [comment]
Im not sure which way to go on this honestly. The control for left/right toggle was placed for the purpose of allowing people to choose which type of menu approach they want. There are many sites that use a right hand panel on LTR sites, so its not as if every site thats LTR will always have a left hand panel. And if someone desires a right hand panel, what happens when it switches to RTL mode, does it stay on the right, does it flip? Im not sure this is something that should be forced

**Comment by marktaylor46** [comment]
I didn't know you could change the side - so I'm ok with it now - thanks

**Comment by w00fz** [comment]
:+1:

**Comment by drorp** [comment]
Hey guys,
I use Hebrew - RTL.
The - Offcanvas, although can be which side of my choosing, but always within the configuration menu of LTR.
Left-aligned text, icons on the left side. And if I make the definition `#g-offcanvas {text-align:right;}`
Only right-aligned text, but the arrows of the sub menu covers the text.
And, of course, also direction the movement of the sub menu, as LTR.

**Comment by mahagr** [comment]
@drorp Can you create a new issue about this as the one we're in is closed a long time ago?
