### ISSUE TITLE
hydrogen - navigation - new module instance pushes menu up

### ISSUE THREAD

**Issue by nzimas** [gantry/gantry5#531]
I'm trying to add a module instance to the navigation section of the layout.
The module in question displays 4 social icons inline.
<img width="661" alt="screenshot 2015-07-05 21 58 42" src="https://cloud.githubusercontent.com/assets/6955694/8513470/47959128-2364-11e5-891b-49857fe6a49d.png">
<img width="1214" alt="screenshot 2015-07-05 21 58 30" src="https://cloud.githubusercontent.com/assets/6955694/8513473/47b9d3bc-2364-11e5-86a7-2c624aaec01b.png">

**Comment by kevlardev** [comment]
Were there any other steps you took? Different configuration options you set up or custom styling perhaps? I can't seem to replicate this on a default install. The menu itself inside of the g-navigation section has a negative margin (applied to the g-main-nav class) in order to make the menu item blocks flush with the navigation strip, however this shouldn't affect other module positions as that margin is only applied to the menu class. When i place other module positions or particles side by side with the menu in the navigation section, they render fine for me. So just trying to narrow down how to reproduce what you have here.


![screen shot 2015-07-08 at 3 13 08 pm](https://cloud.githubusercontent.com/assets/4529755/8581058/df10b5d4-2583-11e5-8842-4f0b866e40cc.png)

**Comment by kevlardev** [comment]
Im going to go ahead and close this for now, as I can't seem to find a way to reproduce this. Please feel free to reopen if you are still experiencing this issue.
