### ISSUE TITLE
It's possible to set "block size" to 0% when changing a particle's settings

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#539]
A member had this in RT forum so I thought i'd raise a ticket... 

When changing a particle's settings on the layout it is possible to enter a value of "0%" for the block size - the minimum you can set when using the layout is 5%. It would seem to make sense to not allow entry of less that 5% in the particle settings too?

If you do enter 0% (or a small value) it also wrecks the layout too in admin (overlapping elements).

![2015-07-07_15-13-37](https://cloud.githubusercontent.com/assets/11683218/8548258/ac57ef36-24bb-11e5-997f-a9076da66ddc.png)

**Comment by w00fz** [comment]
Yeah this is sort of known. We do not have a proper validation on that field.
The idea is to pass the lower and upper limits to the block size field so that you cannot put any unexpected value.
We haven't got that far yet has we found the tendency is to use the drag & drop slider anyway.

Thanks for ticketing it, we will look at it after the release. The workaround for the moment is to put in proper values or use the slider which will not let you go as low.

**Comment by mahagr** [comment]
@w00fz Resizing particle doesn't really work; it doesn't properly change the sizes of the other particles if the size of the first particle is greater than next one -5%.

**Comment by mahagr** [comment]
First issue was fixed in here: https://github.com/gantry/gantry5/commit/953ce45a773390bcb70007351cce6213db36dbea

Sorry about the wrong commit message; I accidentally hit enter while having focus on send button.

**Comment by w00fz** [comment]
I am not sure what you mean by your first comment. Are you referring to the Block Size within the properties or the drag and drop resize?

**Comment by mahagr** [comment]
I've so far limited range of the value to be between 5 ... 100%, but there are still issues when resizing the block from the settings. For example if you have 33 - 33 - 33 layout and you resize first item to 80%, you end up getting 80 - 5 - 33.

**Comment by mahagr** [comment]
Opened a new issue for the remaining stuff. Closing.

**Comment by w00fz** [comment]
All this issue was about was the missing validation in the Block Size. Your fix in 953ce45 really only masquerade the problem and wasn't a true fix.

I now implemented all the logic bits to make this properly validate via JS. The issue was there for long time and we knew about it, I just never had the time to get to it because it was very complicated. Anyway now it's sorted and looks like this:

![block-size-limits](https://cloud.githubusercontent.com/assets/11734/9531175/4fa473ba-4cb9-11e5-90e2-af57d6721f56.jpg)

There is still an issue when trying to manually edit a Block Size of an Equalized grid (ie, 33.33 | 33.33 |  33.33), which you already splitted from this one in #753, although it is not properly described :)

**Comment by w00fz** [comment]
Also this is another view of it:

![blocksize-range](https://cloud.githubusercontent.com/assets/11734/9531613/a43abef0-4cbb-11e5-9394-ab9193cd4786.jpg)

So it basically always set the proper min and max range you can set the value (manually) with.

**Comment by mahagr** [comment]
I agree that this is much better approach. I had my simple fix mostly because of I wanted to avoid the obvious wrong values, but without having the information from the other blocks around the current one, it was impossible to really fix the issue.

Your fix looks really great, though!
