### ISSUE TITLE
no index.html files included in directories inside our launcher/demo builds

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#545]
while doing further testing for:
https://github.com/gantry/gantry5/issues/501

i noticed that for example in the callisto launcher directories, we do not have any index.html files anywhere, not sure if they get removed by our build system.

please see pic which is a compare between callisto and mixxmag launcher builds.

![g5_indexhtml](https://cloud.githubusercontent.com/assets/5719486/8571363/951caebc-2586-11e5-8684-f5b75b10f455.jpg)

**Comment by mahagr** [comment]
Those index.html files were used in older versions of Joomla to prevent directory travelsal by obscurity. It was considered to be bad practice, especially as everyone knew which files are present in any given extension, so there was absolutely no security benefit on having those files present. On the other hand those files caused some other issues, which is why they aren't recommended to be used anymore in Joomla.

The only reason to have the files may be to add empty directory.
