### ISSUE TITLE
Bootstrap is not loaded if menu item type is Gantry 5 - Custom

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#546]
Bootstrap is not loaded if menu item type is Gantry 5 - Custom.
![new outline](https://cloud.githubusercontent.com/assets/9744973/8573044/51ed568e-2598-11e5-874a-f40d1c00b558.PNG)

**Comment by mahagr** [comment]
You can still load those files by

    {% do gantry.theme.joomla(true) %}

in your particle (adding any Joomla module will do the same), but I agree that there needs to be a better way to load jQuery, Bootstrap or any other javascript file in Joomla.

PS. Above can be called as many times as you want to. Same is true on loading any other css/js file as long as you have identical filename.

**Comment by w00fz** [comment]
None of the assets from joomla are loaded in the custom view and it was made as so on purpose.
It is the job of an extension to trigger the bootstrap/jquery behavior in order to get loaded.

The Gantry custom view doesn't need any of that and so it won't load it. The view is meant to be a simplified version of the joomla one that speeds up the load of the page when no assets are required.

If you remember you opened a ticket in Joomla about some assets not being loaded. This was related to the custom view.

I don't think we should start loading bootstrap at all times, most of the times for minor things such as opening a dropdown, joomla has to load the entire jQuery and bootstrap which is wasteful.

**Comment by mahagr** [comment]
By @w00fz in Gitter chat: We should probably have platform specific hooks for doing things like gantry.loadBootstrap() or gantry.loadJquery() etc

**Comment by mahagr** [comment]
Postponing this to 5.0.1 as it's really not a bug...

**Comment by mahagr** [comment]
Already implemented.

**Comment by The-Scifer** [comment]
Sorry for the stupid question but how do I put {% do gantry.theme.joomla(true) %} in a particle?
Will this allow me to use $ instead of jQuery?

**Comment by mahagr** [comment]
You can add it into anywhere in particle twig. Or you can just enable Bootstrap in the outline (easier). Just go to Page Settings and include Frameworks particle with Bootstrap turned on.
