### ISSUE TITLE
Menu ordering not reflected in Joomla/Gantry menu

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#552]
This is a reopen of https://github.com/gantry/gantry5/issues/463

The issue does not seem to be resolved. I just tested it with the latest CI Build and here's what happens:

_Clean install of Joomla 3.4.3 + latest CI Build of both G5 and Hydrogen_
1. Created a new Menu Item of type External Link (Item1)
2. Created another Menu Item of type External Link (Item2)
3. Changed the order of the above menu items - WORKS on the front end
4. Renamed the above menu items - WORKS on the front end
5. Went to the G5 Admin (Menu Editor) and added a custom class and an icon to the above menu items
6. Went back to the Menu Manager and changed the order of the menu items - DOES NOT WORK on the front end anymore
7. Went back to the Menu Manager and renamed the menu items - DOES NOT WORK on the front end anymore

**Comment by mahagr** [comment]
Looks that I didn't notice all the ordering issues. Menu has been generally very hard one to fix as Joomla event that was supposed to work didn't allow any modifications to be made.

**Comment by JoomFX** [comment]
Hey @mahagr 

I see that you have changed the title of the issue.
I just want to mention that the issue is not only with the re-ordering, it is also with renaming the Menu Items.

Here's what happens:

1. If you do a clean Joomla + G5 + Hydrogen installation and start testing the Menu stuff everything will work fine

2. If you then go to G5 Admin -> Menu Editor, do some changes and hit "Save", the changes you make from this moment on, in the Menu Manager, will not be working.

**Comment by marktaylor46** [comment]
Please note there is definitely still an issue with menu renaming. I had to do this for a member. I renamed menu item and it did not change in frontend or g5 menu manager. I can't pin in down, but I've seen it happen again and that was with 5.0.0 - I will try locally again on latest CI to try and narrow it down.

**Comment by JoomFX** [comment]
I thought it was fixed but now I see that it is not :smile: 
I just experienced it with 5.1.5 (which according to the above milestones is normal).

@mahagr Matias, will you have the chance/time to fix this for the next release or it will be postpone again?

**Comment by mahagr** [comment]
There's some problems with Joomla event system sending data in array instead of object or reference, which means that I cannot change content from those events. So there's really no easy way to fix this unless I figure out some other way to do this.

**Comment by marktaylor46** [comment]
Whatever the underlying technical reasons, this does keep coming up often in the RT forums. As such it is perceived as a Gantry 5 issue. That may be unfair, but I think we have no alternative but to seek an alternative solution to the issue, Just my opinion of course.

**Comment by jameswadsworth** [comment]
Gantry 5.2.13 and Requim 1.1.2
If I change the order of menu items in the joomla menu manager these changes are NOT reflected in the Gantry template menu manager. And vice versa: you can change the order of the menu items in the template and then go to the joomla menu manager and the order is different. Gantry menu order is always implemented in the frontend not the order under Joomla menu manager. It is not very intuitive and I will love explaining this to my clients (plus I am not sure I want my client having access to the template to change the menu order. They have enough trouble understanding updating content and linking menus. Now they have to go the template menu to change the order!!!)

**Comment by mahagr** [comment]
Yeah.. I really need to take another look into this and figure out a way to fix it. The main issue is that Joomla has event that I can hook into to fix the issue, but unfortunately they also have a bug in that method making it not to work properly. Likely nobody ever needed the feature...

Anyway, this is something that I probably need to fix first in Joomla and then re-enable it in Gantry.

**Comment by jameswadsworth** [comment]
Hi mahagr do you know if a bug has raised on the joomla bug tracker for the issue you have indicated?

**Comment by mahagr** [comment]
No, I never added an issue as I was always going to fix it myself. I cannot remember details, but the issue was event sending an array to be modified by plugin -- and array was copied, so no changes were applied to the object. It may be a bit tricky to fix because of the array should have been sent as object, but that would break all the existing plugins (though its unlikely there are any, except if a plugin is using a wrong event in the first place).

**Comment by jameswadsworth** [comment]
We went back to save the alias of the different languages as they were originally in English, which returns the menu order back to normal, we have now lost all the child menu links. Is it possible that they are connected to the alias of the parent?

**Comment by mahagr** [comment]
Can you join to gitter and PM me. Leave also notice to https://gitter.im/gantry/gantry5 as PMs do not seem to show up always. I need access to your server to figure it out.

**Comment by jameswadsworth** [comment]
Had a look at the what was being returned. In this case it not gantry which is causing the problem but falang. We had changed back the alias into English for the parent item, but in the translated child item the menu path still contained the translated alias e.g. productos/lavado-con-agua. To resolve the problem we changed to products/lavado-con-agua and the correct association was returned.

We would like to get Gantry 5 menu working nicely with Joomla menus. I'll join you gitter to see if we move forward on this.

**Comment by mahagr** [comment]
I cannot really help much on falang, but I'm glad it wasn't Gantry. Will be back in 2-3 hours.

**Comment by hennysmafter** [comment]
Sorry to report this but this bug is still there! I just received a question about it on our helpdesk. 

A customer just added a page via the Joomla Menu Manager and this page is not in the correct order. So I explained to him that he needed to set the correct order via the Gantry Menu Manager. His reaction was literally:

That is stupid.

Now you guys know I love Gantry (even while I have been absent from the chat.) but I kind of have to agree a little bit with my customer it is kind of strange we have to set the order twice. And I can understand a lot but this issue is now from 5.0.0 all the way up to 5.3.3 and it kept being pushed further and further away?

I wished I had the solution for it but sadly I don't but I really hope you guys can figure it out. But maybe with the help of these chat rooms some Joomla dev can help:

https://gitter.im/joomladevelopers/chat
https://gitter.im/joomla/joomla-cms
https://gitter.im/joomla/joomla-framework?source=all-rooms-list

**Comment by w00fz** [comment]
I agree, the menu integration with platforms is quite a mess at this stage and it's been pushed over for too long.

As you guys might know, our focus right now is Grav + Gantry, after that I think this should become a priority.

/cc @mahagr this is your territory 😉

**Comment by mahagr** [comment]
I fully agree with everyone, its just not something that is trivial to fix and may take days or even a week to just get this one issue fixed. So it gets pushed back as the main focus hasn't been on fixing this single issue.

It looks like syncing menu ordering was turned off in Joomla by purpose, likely because of some menu corruption issue. Unfortunately I cannot remember the reason anymore.

**Comment by N8Solutions** [comment]
Hey Guys, Just curious as to how this is coming along? I, like @hennysmafter, had to explain this to one of my clients today and he wasn't at all happy about it. I simply told him it was something that was being worked on and hoped a fix would be provided soon.

**Comment by mahagr** [comment]
Fixing this will be a major undertaking and may involve patch in Joomla as well. As there have not been too many complaints on this, I've left the issue alone.

I don't know when I have time to look into this, but I doubt that it will be fixed before 5.4 gets out as there haven't been a lot of complaints on this one. Priority can change, though, if more people request the fix.

**Comment by hacki65** [comment]
I think this is only be solving with a database check.
In the Joomla DB tabelle #___menu are 2 columns: **lft** & **rtg**.
The entries reflecting the ordering of the menuitems.

1.
The relevant THEME-NAME.yaml for the menu must have 2 new entries per menuitem (equal to the database): lft & rgt in the tabelle #___menu of joomla.

2. (anyone re-order in Joomla)
The Menueditor of Gantry must request the database BEFORE it loads the menu in Gantry and check if the entries in DB and YAML are different. If the entries in the DB are changed it must immediately save this in the YAML and load the changes in the Editor.

3. If anyone re-order menuitems in the Menueditor of Gantry and save, this changes must also be pushed to the Database (#___menu).

I hope this BUG could be fixed soon. Good luck... ;)

Best regards hacki65
![gantry_menu_re-ordering](https://cloud.githubusercontent.com/assets/20481746/19096061/04464d74-8a9a-11e6-9528-22ff41e5a29e.jpg)

**Comment by mahagr** [comment]
I'm fully aware on how nested DB items works in Joomla. We are not using the database directly but we are calling Joomla JTable /JMenu APIs instead. 

1) Its not enough to do this in our menu editor as user may skip Gantry editor and go directly to frontend. Joomla has an event which we could hook into, but last time I tried to do it, there was some kind of issue (cannot remember), either the event didn't fire properly or something else went wrong. 

2) We were already updating Joomla menu ordering, but I disabled the feature because of menu corruption. Though now that I think about it, there was reordering bug in some earlier version of Joomla..

I'll take a quick look into this, if not for anything else, to figure out why the feature didn't work / had to be disabled.

**Comment by hacki65** [comment]
I agree with the 1 point. In this case it solves not the problem. Is it possible to develop a little plugin for Joomla, that watch at the menu manager of joomla to figure out if changes were made?

**Comment by topwebs** [comment]
I agree that this is a really important issue. It is best not to give clients access to G5, but just allow them to edit particles in the module manager. When they reorder the Joomla menu and don't see it work, they are then not able to fix it in G5. Even when we give them access to G5, why should they have to reorder twice? It really needs to be fixed soon.

**Comment by N8Solutions** [comment]
@mahagr I know this particular issue is a difficult one and that it will be very time consuming and that you are also very busy with other things. I also realize there haven't been a lot of people who have complained about this. I believe there are more people than you think that are frustrated by this problem than those who actually say something. I myself found this problem annoying but I dealt with it because I knew what to do. I only spoke up about it after my clients started to complain and they were not happy about it at all.

From what I gather by your comments, this is not a Gantry 5 issue but rather a Joomla 3.x issue. If you know the exact nature of the issue please tell us so a ticket can be opened in Joomla and we can pester them about it 😉

I'll just throw this idea out there, and take it with a grain of salt because I have no idea about the likelihood or merit of it, but isn't it also possible that other Joomla Frameworks are having a similar or same issue? It would be interesting to find out if they are and what they are doing about it. Maybe someone has already come up with a fix for it and we just need to find a way to port it over to work with Gantry 5. If no fix has been found a collaboration effort with others might be in order. For something like this I think it would be worth reaching out to ask others about this issue.

One last thing, I would hate for this issue to be forgotten or fall by the wayside so I wanted to mention that it is not currently assigned to any milestone, not even the [Future Releases Milestone](https://github.com/gantry/gantry5/milestone/6) or the [5.4 Milestone](https://github.com/gantry/gantry5/milestone/38) as you suggested it could be in.

/cc @w00fz 

p.s. I hope you are enjoying your vacation

**Comment by w00fz** [comment]
I added it to 5.4.0 for now, although that release is going to be reserved for Grav, I am not sure if Matias will be able to look into this issue as well, so probably more in a 5.4.X release.

I deliberately didn't have it in Future Release because this is definitely something we need earlier. As you can notice though, I added the important flag, as that's what we are considering this issue to be.

I hope we can get to this soon enough.

**Comment by antoniotheant** [comment]
Hello
I get this problem. How to fix it?
thanks

**Comment by JoomFX** [comment]
This will be fixed in a future Gantry release.
Until then just drag and drop the Menu Items in the [Menu Editor](http://docs.gantry.org/gantry5/configure/menu-editor) and arrange them as you wish.

**Comment by Dave-Skye** [comment]
I hope this can be addressed really soon.

My client wishes to edit the ordering on the menu in Joomla, but I don't want them to have access to gantry so they can't damage the design and layout.

**Comment by N8Solutions** [comment]
@mahagr I know this issue isn't going to be an easy one to fix and on top of that it is also one that will be very time consuming to work on. It has been just over 3 years now since this issue was originally raised and Joomla! 4 is on the horizon. Would it be possible for you guys to take another look at this and possibly even dive under the hood with Joomla! 4 to see if the issue still exists in the beta version? If it does, with work being put in to J! 4, now would be a great time to bring up the issue with Joomla! so it can be fixed.

**Comment by rogernclarke** [comment]
I've got this exact same problem. I first found it on a site I manage earlier this year and ended up deleting menu items to get the ordering correct. I've now got the same issue in a new site I am building. The Joomla menu item ordering should work. It seems crazy it can show an order that isn't applied. +1 for getting this issue fixed.

**Comment by topwebs** [comment]
Really need to see this fixed. Gantry menu should sync with Joomla menu. I don't see any reason why the ordering in Gantry should be different than Joomla.

**Comment by topwebs** [comment]
We are seeking to expand our client base and this menu issue is really a nightmare. Do you think that clients are happy when we have to tell them they have to set their menu in Joomla and then follow some complicated instructions to set it again in Gantry? If we don't do that, we must lock them out of Gantry and answer dozens of requests about what's wrong with their menus. This issue has been unresolved for four years. Although we love Gantry, this is becoming a showstopper. Please see how this can be fixed.

**Comment by N8Solutions** [comment]
@mahagr, @w00fz, @newkind, @rhukster 
I know you guys are dealing with a lot, however, as @topwebs pointed out, we are closing 4 years now that this issue has been open. There hasn't been a single response from a Gantry rep since Oct. 2016. I appreciate all you guys have done but a renewed interest in fixing this issue is needed. As I wrote last year:

> 
> 
> @mahagr I know this issue isn't going to be an easy one to fix and on top of that it is also one that will be very time consuming to work on. It has been just over 3 years now since this issue was originally raised and Joomla! 4 is on the horizon. Would it be possible for you guys to take another look at this and possibly even dive under the hood with Joomla! 4 to see if the issue still exists in the beta version? If it does, with work being put in to J! 4, now would be a great time to bring up the issue with Joomla! so it can be fixed.

Since the issue obviously still exists in Joomla! v3.x then it would be a good idea to nip this in the bud and find out if it also exists in Joomla! v4.x so it can be fixed on the Joomla! side.

We really need this fixed and it would be really nice if someone were to reply to this thread if only to provide us with some kind of an update.

**Comment by yellowwebmonkey** [comment]
@mahagr, @w00fz, @newkind, @rhukster
First of all, I really appreciate the awesome framework.  I agree with @topwebs and @N8Solutions on the menus though.  Is there anything we can do to help?  Please let us know if there is any specific testing or whatnot that we can do.  Thanks!

**Comment by mahagr** [comment]
I'm planning on updating Joomla minimum to J!3.8/J!3.9 soon because we need also to update PHP requirement to  5.6 in order to keep our dependencies updated. Basically, it also means to update the code to be mostly J!4.0 compatible and is indeed a good time to look into this issue as well.

**Comment by jameswadsworth** [comment]
I agree with the other comments. Gantry is amazing but the non syncing of menu items between Joomla menus and Gantry template menu manager is a pain both for us developers and worse for clients who can understand why then need to update in 2 different places! Looking forward to an update soon and I'm willing to help/test/contribute.

**Comment by saraheagle** [comment]
I too agree that this is a real major issue for non-techie clients. Essentially the template breaks something so fundamental and basic to Joomla, that my clients think it's rubbish and don't want to use it. But of course I do want to use it as everything else is so fab!

**Comment by N8Solutions** [comment]
Let's hope with Joomla 4 finally coming to fruition that this is something that will be fixed.

@mahagr, Have you looked in to whether or not this problem still exists in Joomla 4?

**Comment by N8Solutions** [comment]
> 
> I'm planning on updating Joomla minimum to J!3.8/J!3.9 soon because we need also to update PHP requirement to 5.6 in order to keep our dependencies updated. Basically, it also means to update the code to be mostly J!4.0 compatible and is indeed a good time to look into this issue as well.

Let's hope with Joomla 4 finally coming to fruition that this is something that will be fixed.

@mahagr, Have you looked in to whether or not this problem still exists in Joomla 4?

**Comment by jameswadsworth** [comment]
Looking forward to hopefully some positive news from @mahagr!

**Comment by mahagr** [comment]
This one has been fixed in upcoming Gantry 5.5

**Comment by jameswadsworth** [comment]
Great news. Is it ready for testing yet?

**Comment by mahagr** [comment]
Yes, see https://github.com/gantry/gantry5/issues/2789
