### ISSUE TITLE
WP nonce should get updated on admin page refresh

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#554]
@w00fz assigning this to you as @mahagr thinks it should be handled by JS

So the issue is that when you keep G5 admin page open long enough for WP nonce to expire this happens on save : http://monosnap.com/image/IlLAPV3s3nlwN0Z4PEwVJgZKVgSkKB.png

Simple refresh/hard refresh doesn't update the nonce in the url so you need to exit G5 admin to any other admin page and get back to it to make it work again.

Some info about nonces : https://codex.wordpress.org/WordPress_Nonces#Nonce_lifetime

**Comment by w00fz** [comment]
I'm not sure how I can replace the nonce token on refresh since it's just a page refresh?

**Comment by w00fz** [comment]
What if we just simulate Joomla's `keepAlive` instead?

**Comment by alisamii** [comment]
Stack overflow again here,

http://stackoverflow.com/questions/12597176/how-to-keep-session-alive-without-reloading-page

**Comment by w00fz** [comment]
Yup that's my idea also and basically what Joomla's `keepAlive` does. Ajax call every `SESSION_EXPIRE_TIME - few_seconds` to prevent from letting the session expire.

**Comment by mahagr** [comment]
That won't fix the issue for laptops because of the hibernation. I've never had this issue in my desktop, but in laptop it happens all the time in both Joomla and WP.

**Comment by mahagr** [comment]
Looks like WP opens a login window with some Javascript.. It just happened to me, but I didn't have inspect turned on to see the request.

**Comment by mahagr** [comment]
This is what WP does:

```POST http://wp-nucleus.local/wp-admin/admin-ajax.php```

Request:

    interval: "60"
    _nonce: "XXXX"
    action: "heartbeat"
    screen_id: "toplevel_page_layout-manager"
    has_focus: "false"

Response: 

    wp_auth_check: "false"
    server_time: 1436516654

```GET http://wp-nucleus.local/wp-login.php?interim-login=1```

**Comment by w00fz** [comment]
After digging into the issue, none of what was suggested above had anything to do with the `nonce`, the `nonce` is not a keep alive but a use_only_once token. 
The original issue reported by @newkind was about the `nonce` token not getting updated when refreshing the page.

When the `nonce` expires, Wordpress shows the error **Are you sure you want to continue? Please try again**, this is the normal behavior for Wordpress but because the `nonce` token was never refreshed, clicking the **try again** link wouldn't work.

This is now fixed.

// For future reference, to lower the `nonce_life` lifetime it can be changed from the `pluggable.php` file.
