### ISSUE TITLE
Indicators in outline dropdown list

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#555]
Just an idea that I thought i'd mention.

I think it would be useful if there were indicators shown in the outline dropdown list

1. a "default" template indicator - some members change the default template in template manager and don't rename the "default" outline name - so it gets awfully confusing when tracking issues down.
2. An "assigned" indicator that shows that the outline is assigned to at least one menu item specifically. This is so you know whether the outline is actually used or not. Again this makes it easier when tracking things down when there are lots of outlines in the list.

**Comment by w00fz** [comment]
Ok so I have enhanced how the default Outline look in the Outlines page, giving it a bit of highlight so it stands out. It is also noticeable because it's the only one that cannot be deleted of the User ones:

![default-outline](https://cloud.githubusercontent.com/assets/11734/9184939/333907da-3f6d-11e5-8d0f-1ec11dab3b60.jpg)


I didn't want to add extra data in the Outlines dropdown, I think it's going to get too busy and complicated, you already asked to add in there ids, assigned check and default indicator. That is a lot of extra informations, imho, for just a dropdown. Beside this would be purely for Joomla which is the only platform with a Menu Item concept, in Wordpress for instance, none of this does really apply.

Regarding the Assignments, you can easily see this in the Joomla Templates page where you always get a :white_check_mark: whenever a Style (Outline) is assigned.

![assigned](https://cloud.githubusercontent.com/assets/11734/9184986/8641c7c8-3f6d-11e5-9ed9-2735102986ad.jpg)

Hope it's a good compromise!

**Comment by marktaylor46** [comment]
Ok - I would have preferred what i suggested but I understand your reasoning. Having to go out of Gantry 5 admin to look at template manager and then go back to Gantry 5 admin seems a bit long-winded to me when the info could be in the dropdown - but fair enough.
