### ISSUE TITLE
still some issues with layout manager not adding up to 100% on section row

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#556]
i've seen it randomly before and again just now on a core joomla test install with ethereal and gantry hebe linked (just pulled half hour ago too, so all is updated)

in the ethereal - home style i went to the layout manager and dragged the 'page content' particle to the right of the 'latest shots' imageblock particle which is in 'main'.

'latest shots' had correctly 100% at first, but after adding 'page content' they both went to 33.3%, leaving an empty gap on the right. please see pic

![g5_lm](https://cloud.githubusercontent.com/assets/5719486/8615999/f13c7ea8-26f7-11e5-9192-2746a0e454c8.jpg)

**Comment by w00fz** [comment]
Are you able to reproduce this consistently?

**Comment by kat05** [comment]
i wish i could, but it's randomly happening.

**Comment by adi8i** [comment]
I've seen something similar too, happening when you fast move particles in layout, or use undo/redo buttons. Sometimes particles are subducted , you need to remove them from layout and add again. 
@w00fz if you remember i've told you or i've opened an issue some time ago, but i am not able to reproduce this consistently. And this happend only 2 or 3 times for me.

**Comment by kat05** [comment]
i agree, sometimes i was doing some undo and redo actions etc before this happened. this last time i did not, but i dont know if the issue once occured, if it will stay broken on that same install and keep happening.

**Comment by w00fz** [comment]
Great part of this was fixed sometime ago when we found out with you Kat that the touchpad was cause of some odd behaviors with ghost particles left over and such. Even though I don't think this is related to that.

Ever since then I haven't seen any reports re this problem but I'm not denying they are there, I'm just unable to fix it without being able to see it.

My feeling is this must have to do with some delayed events happening for whatever reason. Perhaps the CPU/GPU are busier at the moment when you are experiencing the issue and the events fail to catch up leaving it in that weird state. I truly don't know.

I just wish I knew how to replicate and fix it.

**Comment by alisamii** [comment]
I've seen this behaviour add recently add this past Friday on a CI build from earlier in the week. Not exactly sure what I was doing but I switched to a different outline without saving and came back because even though I tried to delete the particles that were affected and drag them back in, they kept resizing incorrectly (added first particle, 100%, added second particle, both at 50%, added third particle and all Patricks were at 25% and a blank space with no particle but basically 25%.

Also tried it with the same issue, 3rd particle sizing them all at 25%, saved, reloaded the outline and on reload, the particles 33% each. Tried to resize the middle particle to 34% and the right particle automatically changed to 32%.

Odd behaviour but not sure what causes it. I can only reproduce it randomly.

Best regards,

Ali

**Comment by adi8i** [comment]
From my point of view this issue is not a so important one, because is not happen consistently adn don't cause major problems, are other improvements with higher priority,  is an issue that must stay opened and be tracked, at a time maybe we found a solution for this.

**Comment by kat05** [comment]
Ok, so today I am doing testing on WP and ran into this issue again on a WP core install with Gantry hebe linked.

I've been playing on this install a bit already but can kind of recall what I did before this happened, which is no guarantee that it is a solid way to trigger this issue.

Anyways, I have my own Outline called 'Testing' which is a duplicate of the Home outline.
This outline is assigned to all pages.

I have loaded the '3 Column - Right' layout.
I added a new row to the 'Navigation' section and dropped the 'System Messages' particle into it and saved.
Then I added another new row to the 'Navigation' section and dropped a 'Widget Instance' into it and saved. Then I hit the Gear icon on the 'Widget Instance' and hit the 'Pick Widget' button inside the popup. Another popup appeared which was titled 'Pick a Module' but there were no modules or widgets to pick from so I closed the popups. Then I added a 'Widget Position' to the left of the 'Widget Instance' and that's when the issue showed up.

Please see pic.

![g5_wp_layoutmanager](https://cloud.githubusercontent.com/assets/5719486/8775464/d5544fce-2ee8-11e5-915b-fb9163061071.png)

**Comment by alisamii** [comment]
I've also noticed this happen. It happens when you add a particle to the left off the row, rather than to the right.

If you add it to the right then reorganised three particles, it won't happen.

Best regards,

Ali

**Comment by w00fz** [comment]
Still cannot reproduce.

**Comment by adi8i** [comment]
If you re-size a particle, then remove another one, and hit Undo, the particle will not revert to initial position. 

Proof: http://screencast.com/t/qPCUILsIl4

**Comment by w00fz** [comment]
Woohoo, thank you @adi8i that video made it possible for me to reproduce it :)
I am so annoyed by the amount of time it took me to fix this and then look at the fix! Just a stupid typo.

Seriously, look at that! https://github.com/gantry/gantry5/commit/1f5cafc0cf32c79477d78ddb8c31f63d30225ef2#diff-64b3a997d57f852412d93894216b05e6

At least now it's sorted! :dancer:
