### ISSUE TITLE
Add template version on "available themes" and "theme" page header

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#560]
It would be very useful if the template version number could be shown on the "available themes" page and the "theme" header. it would save having to look under extensions manager > manage.

Even better still would be also to flag that version with "[out of date]" legend if the template was not the latest one available.

![2015-07-11_10-53-29](https://cloud.githubusercontent.com/assets/11683218/8633367/31fb7e48-27bc-11e5-89ba-f67d134dc88f.png)

![2015-07-11_10-54-26](https://cloud.githubusercontent.com/assets/11683218/8633368/3ae54f48-27bc-11e5-9f14-01206f188c96.png)

**Comment by alisamii** [comment]
Maybe, a button could be displayed next to the configure and preview buttons when an update is available that will take you directly to the update manner.

Best regards,

Ali

**Comment by marktaylor46** [comment]
I'm not so keen on the button to go to joomla update manager. Before doing any update your should first take a backup. If we were to go straight to joomla updater it might mean that users do not take a backup first. I'd be happy with just the Legend showing not up-to-date.

Also don't forget Gantry 5 is multi-platform so each platform would need to go to a different place for updates so I think that would be a bit OTT.

Regards, Mark.

**Comment by alisamii** [comment]
I understand the concern there. Having said that, I think that you can't build something with the advanced capabilities of gantry 5 and then assume the end user is not capable of taking the most basic concepts of site maintenance in mind. Also, in most cases I would assume that the end user developing the site will be more likely a web developer or designer building a site for a client, and that the client themselves will more often than not edit content rather than template, so the end user won't access the gantry component that frequently. Also, if an end user does have super admin access rights, upon login to the admin backend, joomla default configuration has an update checker for both core joomla and any components or extensions that have an available update and the end user can have a one click access to the update manager right from the admin control panel page. A similar situation is also in play for WordPress, Drupal, Magento,  and most other platforms.

Best regards,

Ali

**Comment by marktaylor46** [comment]
I think you're proving my point... it would make it too complex IMHO, having now to check for access levels etc. But let's see what the DEVS say.

**Comment by alisamii** [comment]
Not at all. I'm in no way suggesting checking access levels. I'm saying that joomla will prompt, on the admin backend cpanel that there are extension updates available.

Most developers, when they build and develop a site for their clients, will not limit the client's access in any way, and most clients would object to a final delivery where their access is limited. So these no need to check acl.

However, few if any clients will actually access the gantry 5 component. Their concern is with content. Nonetheless, when they log into the admin interface, they will see updates available and can update the site software without the proper precautions of backing up first.

Therefore, I don't see any disadvantage to adding an "Update" button when an update is available directly from within the gantry component as the same button basically exists already on the front page of the joomla administrator. As a developer, however, I rarely log into the front page and usually go directly into the component or area I'm most often working on. So seeing that button would be a nice reminder to me.

I also wish there was a shortcut way off getting directly into the configure screen of the template I'm working on via a drop-down submenu of the gantry menu item in the components menu, bypassing the component front page and directly loading the template's settings, much the same way as clicking on the template from the template manager load the template settings directly.

Best regards,

Ali

**Comment by mahagr** [comment]
Actually updates already work via Joomla update manager, but currently paid templates do not have automated updates, mostly because of some logic is missing to verify if users are allowed to download the new version.

Most of the argued issues relate to us checking if user has changed any files that may be overridden during update. We already have MD5 generated for every file, but there are no checks to verify if the files have been changed or not.

**Comment by marktaylor46** [comment]
All the stuff about "update" is of secondary concern to me. The primary reason for me raising the ticket was to get Versions number visible in the two locations that I indicated.

**Comment by marktaylor46** [comment]
@kevlardev Thanks - I just tried it out and it looks great!
