### ISSUE TITLE
OFFCanvas Slide in from top and bottom with X close button full screen

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#561]
It would be nice to have ability for offcanvas to be full width with x close button and maybe add a slide from top and from bottom as position. So when user clicks the button it would slide from top to bottom or vice versa. Also fade in from background would also be awesome effect ...

**Comment by kevlardev** [comment]
We actually do have the ability in there for the offcanvas to go full width (by setting the panel width to 100% for instance) however we don't have a close button within the panel itself. It's something we can look into later, detecting if its 100% and adding a close button in that event, as well as some possible other direction options and transitions.

**Comment by w00fz** [comment]
The close in the offcanvas can be easily added via a Custom HTML particle. Drop it as first Particle in  the Offcanvas section and just add this html:

```
<div class="g-offcanvas-toggle" data-offcanvas-toggle><i class="fa fa-fw fa-bars"></i></div>
```

Any element, anywhere in the page, that has a data-set `data-offcanvas-toggle` will trigger the open/close of the offcanvas. You have available these 3 types:
 - `data-offcanvas-toggle`
 - `data-offcanvas-open`
 - `data-offcanvas-close`

So technically you could also just use this HTML, since you only want to close it:

```
<div class="g-offcanvas-toggle" data-offcanvas-close><i class="fa fa-fw fa-bars"></i></div>
```


Like Kevin said,  we don't have a top/bottom offcanvas capability, yet. We have discussed this early in its implementation and we decided to postpone this to later versions.
