### ISSUE TITLE
Checkbox is not working in scss

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#593]
You can't add a default value in scss for checkbox.

**Comment by kevlardev** [comment]
I'm not exactly sure I understand the problem you are running into, could you elaborate a bit more on this?

**Comment by adi8i** [comment]
I am talking about `blueprints/styles`, for any other input, like `select.selectize` you add a default value in `yaml` file, then you add your code in `scss` to use that variable, and also you need to define that variable like: `$my-variable: value !default;`.

Is a bit weird, and misleading, @w00fz  knows about this, we've talked on gitter.
I've used `content: $my-variable` to debug.

If i add `$my-variable: `1` !default` and under `styles` tab `input.checkbox` is checked, will render as `content: 1` this is the expected behaivior, so it works.

But if you want to disable it, so under `styles` tab `input.checkbox` is unchecked, will still render as `content: 1`, but it should render as `content: 0`.

If you try it, you will see what i mean. 

Without any `my-variable: value !default`  enabled input will render `content: 1` and disabled input will render `content: ` , i think this may be the issue, because disabled will render just empty and it should render `content: 0`.

Here is the chat on gitter, not sure if you can click on it:
:point_up: [July 17, 2015 11:55 PM](https://gitter.im/gantry/gantry5?at=55a96bcdc57ead8c6be02afe)

**Comment by mahagr** [comment]
It's not just SCSS, that's the limitation of using checkbox in general and affects also PHP or any programming language you use to parse the form.

The only purpose of checkbox is to add or enable something, you cannot use it to remove or disable any feature. This is because of checkbox will not have a value if not checked. This means that it has only two states: set or undefined.

So basically you are asking your SCSS to use either 1 if the checkbox had been set or 1 if it was unset. If you want to have value in disabled state, you need to use either toggle, radio button or select.

Another side effect of using checkbox is that you cannot really override it in admin either... Because of if you set value in the base configuration, it will always make the value to be set and you cannot unset it.

**Comment by adi8i** [comment]
I think i've tried `enable` too, and had the same behavior. Anyway, now i understand what you mean, so it's up to you to close it or leave it open.

**Comment by mahagr** [comment]
Try out radio button, select or toggle type.
