### ISSUE TITLE
Block Variation

### ISSUE THREAD

**Issue by lokomotivan** [gantry/gantry5#619]
Dont know is this a right place to write a sugestion but i think the block variations are bad solution. I think its better to match heights of the blocks child elements and add custom classes to child element rather then blocks. With block variations, we are actualy adding style to module position it self, so every module published in that position will look the same. We can still use joomla moduile class sfx, but then height of modules dosent match, and block variotions are usless.

**Comment by mahagr** [comment]
@kevlardev I think this one is for you. :)

**Comment by kevlardev** [comment]
The block variations were created to provide positional and block based style effects. This allows for same height side by side blocks as well as other stylistic effects that are only possible on the block level due to the way the flex structure is set up. Users can either create individual blocks for each module if they want individual modules to be same height, otherwise the adjacent blocks will be same height housing multiple modules. It can be configured either way.
