### ISSUE TITLE
Before/After field for the "Custom JS/CSS" atom

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#62]
As per Andy's request I'm opening this issue.

Can you please add fields/options so the user will be able to choose where the custom JS/CSS will be loaded (Before `</head>`, Before `</body>`, etc).

Also, currently the "Custom JS/CSS" atom is a bit limited. It only allows you to put the file location. This file can be on CDN or local. So far so good, but what if you want to add other code in the `<head>`, for example FB Open graph:

`<meta property="og:type" content="article" />`

Probably an empty text field will be the best solution. In this empty field you'll be able to add the whole code, not just the "File Location", for example:

```
		<script>
			jQuery(document).ready(function($) {
				$('.counter').counterUp({
					delay: 10,
					time: 1200
				});
			});
		</script>
```

Sorry for putting two things in one issue but in my opinion they are quite relatated to each other :)

**Comment by w00fz** [comment]
This I want to be a new Metadata Atom field that I can see being a Collection field and each item in the collection implementing the Keyvalue field so that you can build up multiple meta tags in the same element.

The only reason I've been holding off of this was because we need to take into consideration the Platforms ways of adding metadata, like in Joomla. 
So I'm not sure if we should either let the Platform do their stuff and then we just also output our Metadata stuff. Or if we should merge the two together?

Probably something we need to discuss @mahagr

**Comment by w00fz** [comment]
Just linking #65 with this issue as they are related with each other.

**Comment by mahagr** [comment]
All platforms seem to support adding header tags, was it inline or file reference to the asset. Other positions can be emulated where needed.

**Comment by Omegatcu** [comment]
Also pease check the structure of JS files and CSS files.

If i add custom js/css its before your teplate stuff eg.

```html
  <script src="/test.js" type="text/javascript"></script>
  <script src="/media/jui/js/bootstrap.min.js" type="text/javascript"></script>
```

that´s very very bad because if i want to use jquery I run into problems.

**Comment by w00fz** [comment]
That's a good point, we should append the custom js/css rather than prepending them.

**Comment by newkind** [comment]
We'll definitely need to address this for WP too as wp_footer() will have to render it's scripts right before ```</body>```. I also think that we could have a dropdown or checkbox with ```<head>``` and ```</body>``` where you could select where the script should get rendered - what do you think about that ?
Also being able to set script priorities will let us avoid issues with JS frameworks like mentioned before ie. priority 0 for all frameworks that should be loaded firstly and  > 0 for the rest of them like we have in G4 ?

**Comment by Omegatcu** [comment]
Sorry for the Off-Topic question but why don't your templates render all Javascript in the Footer?
I thought of this as a best practice as for the loading-time of content.

**Comment by rhukster** [comment]
I'll wait for @w00fz to answer that one :)

**Comment by w00fz** [comment]
Placing scripts at the bottom of the `<body>` tag is totally fine and overall what's suggested as the best practice. It speeds the page up quite a bit since the renderer doesn't have to wait for the scripts in the `<head>` to finish downloading. It also guarantees that your DOM tree is there and accessible from your scripts. 

> As a side note: adding the `defer` attribute to a script in the `<head>` is pretty much the same as adding the script at the bottom of the `<body>` tag. Altough it might have some issues in IE < 9

There are a few exceptions where it is still best to load the scripts in the `<head>`.
   
1. If you are loading a library that does feature detections like Modernizr and that perhaps applies classnames to the `<html>`, you want it available before your page has rendered and your other scripts  start running.
2. If you are using CSS or JS transforms like `LESS.js` or `REACT-transform.js`, as well as JS bootloaders like RequireJS. Especially if you are compiling LESS/SCSS on the fly, you definitely want to delay the rendering of the page otherwise you could end up with an unstyled page until the compiled files are available.

As of why our templates always render in the `<head>` rather than in the `<body>`, well, that's because we use whatever platform offers to add assets to the page (in Joomla it is `Document::addScript`) and it is the platform that decides to put all this in the head rather than body.

**Comment by w00fz** [comment]
Also forgot to mention that with Gantry 5 this is changing, we already have support for `$in_footer` so you can place the files at the bottom of `<body>` if desired.

**Comment by Omegatcu** [comment]
Thank you for the Time you took to explain this :)
Very appreciated :+1:
