### ISSUE TITLE
Suggestion: recompile SCSS from frontend when changes detected

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#642]
As discussed with @mahagr turn off recompile SCSS from base outline (for all outlines) in backend to speed things up and instead recompile SCSS (for outline being used) in frontend when changes are detected in SCSS.

**Comment by w00fz** [comment]
I think this was added a long time ago with the Production Mode setting?

**Comment by mahagr** [comment]
I think the purpose of this issue was to add an option to turn off SCSS compiling in admin when you are in development mode and do it in frontend when you reload the page.

Some shared servers are really slow and recompiling all CSS files from the base outline (especially if you have a lot of outlines) can take easily 30 seconds or even more time. The plan was to add an option to lazy-compile CSS only when needed to make it faster to play with differerent settings.

**Comment by mahagr** [comment]
THe latest SCSS compiler is much faster and takes much less memory, so I don't think this is required anymore.
