### ISSUE TITLE
Ability to add a variation to widget on widgets page

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#693]
We need an extra selectbox field in the Widgets, that would allow users to use a variation for a widget.

**Comment by mahagr** [comment]
What's the variation of the widget?

**Comment by w00fz** [comment]
Isn't this what the Block -> Variation is for? Like for any other Particle?

**Comment by newkind** [comment]
Yah, but what about widgets placed on the Appearance > Widgets page ? For example you could place a single widget position in the Layout Manager, then on the Appearance > Widgets page place couple widgets, and you might want to set each of them a different variation.

**Comment by w00fz** [comment]
Every time you drop a Widget instance in the LM, it's an instance of it's own. I can have 2 of the same Widgets in the Layout Manager with different classnames and variations in the Block panel, they won't interfere with each other.
It's like the Position Particle, you can have 10 in a page all with different or shared variations and the Particle is still 1 (position).

Unless I'm missing something?

**Comment by newkind** [comment]
Yah, but this forces you to use Widget Instances in Layout Manager. What if you need to use position and place the widgets in the native WP core widgets page ?

**Comment by mahagr** [comment]
@kevlardev How did we deal with this in Joomla? I thought we only support assigning classes in the block level, or can those classes also be used from Joomla modules?

**Comment by kevlardev** [comment]
They are only supported on the block level. With the way the layout works, individual items are "blocks" with each block utilizing the flex rules that provide size as well as same height functionality as well as the margins and paddings for each. In order for those variations to work and be assignable from the layout manager, they must be on the block level outside of the platform. Our goal was to make the variation system easier to use and assignable, allowing us to prepopulate lists of available variations and have free reign as to how they are assigned and configured without relying on SQL from the platform and settings from the platform. In order to do this, they had to be moved to the layout system rather than being set from the module manager (there isnt a way to prepopulate lists of variations in joomla, nor can you use joomla to set variations on non joomla elements such as custom particles).
