### ISSUE TITLE
[Issue] Search Box doesn't work in 5.1.0

### ISSUE THREAD

**Issue by Legoman99573** [gantry/gantry5#724]
I tried to search my webpage, and it didn't find results for anything. Can someone help me out.

**Comment by w00fz** [comment]
Are you trying to search Particles? That is a known issue (see #237), other than that there are no known issue, you should be able to search Joomla content just fine.

**Comment by w00fz** [comment]
Like explained in the Gitter Chat, this doesn't seem to be related to Gantry 5 at all. Seems an issue with the search plugin you are using, since creating a Search Menu Item causes the whole page to go blank.

Without further details this is not something we can help you with, please feel free to reopen if you have more details or find a solution.

Thanks!
