### ISSUE TITLE
Hydrogen conflict with jQuery

### ISSUE THREAD

**Issue by jasonday** [gantry/gantry5#745]
Getting a silent failure on the front end, I believe it is related to jQuery.

Maps, tabs, carousels, etc. are not initializing and failing silently (no script errors). This is only occurring with the Hydrogen theme.

**Comment by newkind** [comment]
Hi,

We need more informations ie. platform, Gantry version, your site url ?



Dnia 23 sie 2015 o godz. 21:36 Jason Day <notifications@github.com> napisał(a):

**Comment by jasonday** [comment]
@newkind (sorry, I have my own repositories and should know to supply more info).

Wordpress 4.3
Gantry & Hydrogen 5.1 (stable)
Issue presents with multiple plugins, multiple jQuery plugin libraries (google maps, jQuery UI tabs, carousel, etc.

Carousel & Map non functional:
http://www.movemaine.com/properties/53-river-street/

**Comment by newkind** [comment]
No problem ;)

Gantry 5.1.0 contains a bug that can cause js and css to load in wrong place ie. footer instead of head. This has beed fixed already and the fix is present in the CI builds.

Can you please download the CI build and give it a go ?

Thanks! 



Dnia 23 sie 2015 o godz. 22:02 Jason Day <notifications@github.com> napisał(a):
