### ISSUE TITLE
Adding a script/style from the template without overriding core G5 files

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#751]
I'm opening this issue as per our conversation in Gitter.

Currently, one needs to override the `page_head.html.twig` or the `page.html.twig` file in order to load a script/style needed for a particular template.

It would be great if there is a file in the template directory by default that contains an empty `{% assets %}` or something so the developer can just drop their scripts and styles there and they will be automatically injected in the markup.

@w00fz suggested to include something like `page_head_custom.html.twig`

Well, just a real life scenario.... RT has several G4 templates that come with WOW.js and Animate.css. So currently, in order to implement WOW.js and Animate.css in a G5 template, @arifinrt would have to override the `page_head.html.twig` for every template. Over time you will have 10+ such templates. Then adding a new feature to the framework might require to modify the core `page_head.html.twig` file. And then you will need to update all those 10+ templates ;)

**Comment by w00fz** [comment]
To add to this, Gantry 5 capabilities of overriding are great, although the thing we lack on is a way to easily extend.

One of the ideas I had was to provide more handles for the twig `extends`, some ways for the template developer to avoid passing through the override again. Right now for instance, we do have `@nucleus/` but it's not usable from an override because it loops through the stream and ends up in the override again. Something like `@nucleus-core` could help with that, where only the core files are part of it and the template overrides are excluded.

Another idea was to just allow better entry points for overrides, like including `page_head_custom.html.twig` so that one wouldn't have to worry about future updates.

In general this apply to most twigs, some are more crucial than others, like `page.html.twig` or `page_head.html.twig`.

Any thoughts?

**Comment by mahagr** [comment]
Basically what we would like to have is to be able to call parent twig file by something like:

    {% extends parent %}

So instead of needing another location for the file, you could just override any file and make them to extend the original one. So something similar to what we have with YAML configuration files...

Unfortunately twig doesn't have support for this and the workaround they propose isn't that great either.

As an unrelated note, we really need the same functionality in blueprints, too.

**Comment by w00fz** [comment]
This is now possible with the Page Settings feature (https://github.com/gantry/gantry5/tree/feature/page-settings)

**Comment by JoomFX** [comment]
Thanks @w00fz !

I have a question though... is this option related to the G5 Admin only? I mean are you talking about "Custom Content" field?

![alt](http://awesomazing.es/page-settings.jpg)

If so, what about the `page_head_custom.html.twig` we talked about previously? It would be great if we can hardcode some assets in the template instead of adding them from the G5 Admin where the user could easily remove them.

Also, from your screenshot I cannot see it... so is there a "Custom Content" for the "Body Attributes" as well? What if the user wants to add a script before `</body>`? Oh, I just looked at the screenshot again... I suppose we can add scripts in the "Before `</body>`" field, right?

Anyway, the "Page Settings" feature is really awesome, really!

**Comment by w00fz** [comment]
That screenshot is outdated, i added a few more things since then, including the assets.
 Have a look here at the docs, https://github.com/gantry/docs/blob/feature/page-settings/pages/01.gantry5/02.configure/04.page-settings/docs.md

Still rough and Ryan has to go through them but you can get a clear idea at least.

// Djamil Legato // From iPhone //

**Comment by JoomFX** [comment]
Thanks @w00fz , it looks really good.

But what about the `page_head_custom.html.twig` we talked about earlier?
Adding your assets from the "Page Settings" is great, but in my opinion it is something for the user, not for the template developer.

Image a template that is purely based on BS3. It simply cannot work without loading the BS3 assets. In this case, I think that the BS3 assets should be hardcoded in the template and not be available for the user in the G5 Admin.
And having in mind the above example, let's go back to what this issue was opened about - are you still planning to *extend* the `page_head.html.twig` file by adding an option for `page_head_custom.html.twig` located in the template folder so no overriding of the original `page_head.html.twig` will be needed?

Sorry for being annoying :smile:

**Comment by w00fz** [comment]
There are still plans to implement a way for extending twig files as well as YAML files, I think @mahagr was looking into that but I'm not sure where we are at with it.

I think the plan was to have `page_head.html.twig` overridable and then you could extend from it with `{% extend parent %}`

The point of Page Settings though, is that you can now also manage assets from the admin. Often times we've seen people asking how to globally add files globally to the site without having to override any file. With that it's now possible.

The Twig/Yaml overrides are for more advanced users / developers, but we will get that in as well of course!

**Comment by JoomFX** [comment]
Thanks again for the explanation @w00fz ;)

Definitely! Don't get me wrong, the "Page Settings" feature is totally awesome and I've also had many customers asking how to add some 3rd party scripts and/or CSS libraries in the template. And now they can easily do it from the G5 Admin, which is really cool.

I don't really have that big issues with overriding the original `page_head.html.twig` file, but if there could be a better option, we should go for it ;)

I will wait for it to come :smile:

**Comment by mahagr** [comment]
Regarding to full BS3 template, I would do it a bit another way than extending nucleus: it should really replace our engine with its own. 

What comes to overriding twig files I'm not sure what it takes. At least we would need to override some parts of twig, but how much I cannot tell until I take a look into it.

**Comment by JoomFX** [comment]
@mahagr Hi Matias,

Thanks for looking into this.

BS3 was just an example, even though I was considering adding such framework to my templates.
I was thinking of replacing Nucleus with the particular framework but this seems to be a very time consuming task and I'm not sure how well I'll do it, since the LM is based on Nucleus.

I'm also not sure how all this will work with the G5 updates.

Anyway, it might be something I will look at in the future.

**Comment by mahagr** [comment]
One of the main goals of Gantry 5 was to allow people to create their own engines. In principle they should be as simple as install and use in template. Updates should work just fine, too, as most of the logic would be inside engine itself, so you'd just would need to maintain your own updates for that framework.

That is the theory of it, I bet that there are some missing bits that I've not considered yet as we were a bit busy on getting Gantry to work by using a single framework first...
