### ISSUE TITLE
To Top possible issue (maybe other particles too)

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#772]
When i sent PR for `to top` particle, default values from Blueprints were ignored. Since 5.1.1 this issue is fixed. `Changelog: Load default configuration values from Blueprints (#117, #154)`.

Now `to top` text is displayed all the time, in order to remove it, you need to enable the field, remove the text and save empty field.

A possible fix: replace `default` with `placeholder`

**Comment by mahagr** [comment]
Actually the issue is a bit more complicated, needing in many cases changes also in twig files.

Saving empty field doesn't mean empty if there's a default value in twig file. So basically we need to go through all the particles and think of the desired fix for them. Also we need to remember to keep the old behavior in all the existing themes, which may not have stored all the data.

**Comment by w00fz** [comment]
In the meantime i think we are good with ToTop (335b5a4). I also went through all the Hydrogen core particles and I haven't seen anyone affected, can you confirm that @adi8i ?

**Comment by adi8i** [comment]
Yup, confirmed
