### ISSUE TITLE
Centralizing: Collections Regresion

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#773]
With the latest update, Gantry v5.1.1, there are a number of problems. Because there are many issues opened on the same topic, this one it's intended to group all of them, in order to be tracked more easily.

The issue was mostly fixed in the latest CI Build: http://gantry.org/downloads#ci-builds

Issues: #761 #762 #764 #767 #768 #769

**Comment by marktaylor46** [comment]
I think we should close this "group" issue because there is more than one issue in G5.1.1. The separate issues that we have cover this - I don't see that this issue add anything. The issues are not fixed in latest CI either - we are working on it together and will update each issue separately as we address them.

Regards, Mark.
