### ISSUE TITLE
How to share/use particle's block tab options for a particle module

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#789]
The following are based on my current Salient Joomla installation of 10 languages (multi-language site)
1- Instead of duplicating an outline I used "Salient - Home with Home positions" for home menu item of every language.
2- I used module positions instead of particles so that modules that are assigned to different languages would share the same positions in the same layout.
3- However particle module is lacking the block tab existing in regular particle and thus I can't use the options in the block tab for particle module.
4- You can say I can do it in module position particle but this particle may need different options for different languages and thus it is not practical.
Is there a way to use those in a particle's **block tab** in a PARTICLE MODULE or in a Roksprocket module.
OR why is it lacking this block tab?

**Comment by w00fz** [comment]
The thing is that the Block of a Particle `Module Position` is shared by any module published in that position. 

Rough representation:

```
Possibility 1:
-------------
Block 1
    Particle A
        Module α


Possibility 2:
-------------
Block 1
    Particle A
        Module α
Block 2
    Particle A
        Module α


Possibility 3:
-------------
Block 1
    Particle A
        Module α
        Module β
        Module γ
```

In Possibility 1, the simplest case, there is no problem because you only have to worry about 1 module and you can just customize as you like from the layout manager. Although when you get into more complex layouts where a Particle (and so its Block) is housing multiple modules (Possibility 3) or even when a Particle is duplicated and has different Block parents (Possibility 2), we can't really distinguish nor separate the settings for the Block.

When you are in the Gantry 5 Particle module type, you are at the 3rd level of the layout, what you are trying to do is to escalate back to its Particle / Block to customize the settings from that module. Even if this was possible (ie, we add a Block tab at the Gantry 5 Particle module level), you can see how this would cause issues for other modules that might not want to share the same settings.

This is the reason why Gantry 5 Particle module does not have a Block, because you are at the inner most level and you cannot tweak back up its wrappers.

One way I can think of to work around this would be to create a new Particle, identical to the Particle `Module Position` with the addition of all the settings you want to customize between modules and that renders with a deeper level. So your module would now render at Level 4 (rather than Level 3 like shown in my rough representation) and at the Particle level (new Level 3) you can customize the settings for each individual instance.

I hope it does make sense.

**Comment by mahagr** [comment]
Nice that you actually take advantage of modules on creating multilanguage site. I would have done the same; just keep the static items in layout manager and make everything that changes into modules.

I know I'm going to repeat what @w00fz already said, but let me try to explain the same thing by using a bit different approach.

I would use the possibility 3 from @w00fz comment and assign all the different languages into the same module position. As position contains the block, you can style all the variants of the particle in at once, just what you would do with particle.

There is a small quirk when editing the layout: particles do not have block settings by themselves just like modules or module positions do not have them. The block level is actually parent of the particle or module position, but just represented as a tab in the settings.

**Comment by sural98** [comment]
Thanks for your valuable comments.
Best implementation after all would be that:
For example, I will create 3 module position particles in Showcase container and assign 3 Roksprocket lists modules to Showcase A,B,C positions for English. They will be "bordered".
I will create another 3 module position particles in again Showcase container and assign 3 particle modules of having different variations to Showcase AA,BB,CC for French.
This approach will allow to use different classes, variations, class IDs etc independent of language.
I hope this discussion will add much more to existing G5 development.

**Comment by sural98** [comment]
Based on the current discussion may I add the following suggestion regarding the usability of G5 in a multi-language installation?
With G5 the most feasible way seems to be MODULE POSITION approach.
However this forces us going between Joomla module manager and G5 administration.
If you can find a way of assigning particles in layout manager to Joomla's installed languages we can play only with layout manager.
That is particles will have a language drop-down in block settings, and that will interact with Joomla's language-related tables (#__menu only?) and whichever language loads in the front G5 will load those particles.
With G5's ```index.php?option=com_gantry5&view=custom``` approach together with this solution 1 layout for all languages would be possible I think.

**Comment by mahagr** [comment]
We have plans on greatly extending language support for Gantry 5 particles, but until we find time to do it, I think that the method above might be the only feasible way to do it.

**Comment by mahagr** [comment]
After some consideration, I'm closing this issue as inactive. We already have issues on language support and styles not being applied in module chrome; might be better to continue discussion in those.
