### ISSUE TITLE
Simple Counter seems to break RokSprocket

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#806]
To replicate, just use a Callisto Launcher install and in the Home outline, add a simple counter.
All instances of RokSprocket on the Homepage will break.

Chrome console shows the following:
The specified value "t" is not a valid email address.
mootools-yui-compressed.js:292

This issue was originally reported by DanG for Callisto, but I believe it's not template specific.

**Comment by w00fz** [comment]
This is not Gantry related.

That said, the yellow notice you are getting is just a notice/warning, not an error, it doesn't prevent any other JS from functioning.

The main problem is that the Simple Counter Particle is force loading MooTools via Google's ajax library and since RokSprocket also uses MooTools from Joomla, there are now 2 loaded, causing all kind of fancy issues like RokSprocket not functioning.

**Comment by mahagr** [comment]
Closing the issue as non-Gantry one.

@kat05 @arifinrt You may want to open a new one for Callisto.

**Comment by kat05** [comment]
ok, we have tickets in the internal bug tracker.
