### ISSUE TITLE
SCSS compiler: Undefined font variable errors

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#807]
With latest CI build I'm getting this error frontend and in backend when saving outline on styles

"Undefined variable $font_family_mono: failed at `font-family: $font-family-mono;` xxxxxxxxxxxx/media/gantry5/engines/nucleus/scss/nucleus/theme/_typography.scss on line 51

**Comment by mahagr** [comment]
@kevlardev Can you take a look into this issue -- it might be related to latest update on SCSS compiler.

**Comment by kat05** [comment]
i can confirm this issue too.

**Comment by marktaylor46** [comment]
I should add this was with clean latest salient RL and regressing to 5.1.2 fixes the issue.

**Comment by mahagr** [comment]
I have tracked this down to SCSS compiler update. With older version it works, though I still get white pages, likely because of memory runs out.

@kevlardev Can you check how the variable has been defined and if there are issues with the definition.

**Comment by kevlardev** [comment]
I've added a fallback in nucleus that will prevent the font family variable from being undefined in any case. It does seem the compiler has been changed however to be more strict with missing variables, as each theme seems to have some stray unused variables being defined that were never caught during testing because the compiler ignored them. However, that is not part of this particular issue but rather a separate one and I'll be fixing each theme's problems one by one

**Comment by mahagr** [comment]
This affects also other templates, include all the already installed ones, so I'm looking for a workaround that displays some kind of warning to the user, but doesn't prevent CSS compilation.
