### ISSUE TITLE
Base outline settings problem for Atom particles

### ISSUE THREAD

**Issue by beamaria** [gantry/gantry5#808]
In  Hydrogen template (5.1.2) "Base Outline - Settings" I can't add custom css/js in Atom Particles. Clicking on the + symbol beside " CSS" or "JS" doesn't produce any result

Working in local (MAMP) OS Mavericks  Joomla 3.4.3 Gantry 5 and Hydrogen template 5.1.2 (not CI, official release from Gantry website

**Comment by w00fz** [comment]
Which browser are you using? It seems to be working fine for me. Clicking on the `[ + ]` button adds a new item as expected.

**Comment by w00fz** [comment]
Could you try the CI Build since it's your local host, and test if the current development state works? You can always revert back later.

We can't reproduce this at all and I can't think of any reason why it wouldn't work, expect perhaps some JS conflicts in which case you might want to open the inspector and see if you get any JS error and report them back in here.

**Comment by beamaria** [comment]
Hi Djamil,
I can see now that the same problem is true for all the settings of styles laying in the right column of my administrator panel; for instance if I try to expand or collapse “accent colors” or to change the colors with color-picker nothing happens; same behaviour with “subfeature colors” “main colors” “footer colors” and “Offcanvas colors”. Also this happens to all the particle settings in the right column
(menu, mobile menu, sample content, social, to top etc). As I’ve said, no problem in Chrome. Inspecting with Firebug I can’t find js errors, so no idea why this trouble crops up...



Il giorno 08/set/2015, alle ore 20:39, Djamil Legato <notifications@github.com> ha scritto:

**Comment by w00fz** [comment]
Are you running the latest version of Firefox? Which version is it?

**Comment by beamaria** [comment]
No, I use Safari 7 (which is where I have problem) or Chrome v 45.0 which is perfect

Il giorno 09/set/2015, alle ore 00:08, Djamil Legato <notifications@github.com> ha scritto:

**Comment by w00fz** [comment]
I see, Safari 7 is a bit old, the latest is Safari 8.0.8. A lot of the new CSS3 and HTML5 things that we use I don't think were available with Safari 7.
I can't even test this now because I don't think any of us still has it, but my guess is this is related to the Columns approach we are using when we display the cards.

We will investigate.

**Comment by mahagr** [comment]
Safari 7 is too old and is not supported in admin.
