### ISSUE TITLE
[Joomla] Template Settings on FrontEnd shows Gantry Error

### ISSUE THREAD

**Issue by simmonsr** [gantry/gantry5#824]
Log in on the frontend and have the "All FrontEnd Views" module available, select the Template Settings (there is also a Display Template Options menu item you can set up). 

You will see an error message that shows Gantry 5 is not installed.

![screen shot 2015-08-28 at 11 17 54 am](https://cloud.githubusercontent.com/assets/5002814/9819270/98c2dd06-5872-11e5-813c-f6890a229378.jpg)

**Comment by mahagr** [comment]
What is "All FrontEnd Views" module?

The error likely comes from a gantry menu item or particle module being loaded without Gantry 5 being initialized first.

**Comment by simmonsr** [comment]
"All FrontEnd Views" is a menu that comes with a Testing package of Joomla. 

But you can set up a New Menu item > type as "Display Template Options":

![screen shot 2015-09-11 at 12 41 51 pm](https://cloud.githubusercontent.com/assets/5002814/9859039/deb25188-5ae9-11e5-9dfd-3d992b959ee9.jpg)

**Comment by mahagr** [comment]
Oh, we aren't using those template settings and in admin we are just intersecting the request and forwarding it to Gantry.

**Comment by w00fz** [comment]
Sorry I was able to reproduce this after talking with Reggie and forgot to forward it to you Matias.
Yeah the issue is we have our own custom template settings, the question is if we want to support it on frontend and how do we want to present it.

I'm not very thrilled by the idea of loading the whole G5 admin on frontend, I can see issues after issues coming up with the amount of unknown assets that might be loaded already.

**Comment by mahagr** [comment]
I agree.

**Comment by mahagr** [comment]
@kat05 This patch needs to be applied to all released templates. See changes from the commit.

**Comment by kat05** [comment]
Patch is now applied to all five G5 club templates.
