### ISSUE TITLE
After upgrading to 5.1.3 compiler warnings

### ISSUE THREAD

**Issue by castor01** [gantry/gantry5#844]
Hi,
after each Recompile CSS I have compiler warnings (localhost and online):

File: custom Undefined variable $prefix_for_webkit: failed at `}` C:/xampp/htdocs/gemchor-obiwil/media/gantry5/engines/nucleus/scss/vendor/bourbon/addons/_prefixer.scss on line 11
Undefined variable $prefix_for_mozilla: failed at `}` C:/xampp/htdocs/gemchor-obiwil/media/gantry5/engines/nucleus/scss/vendor/bourbon/addons/_prefixer.scss on line 16
Undefined variable......

see attached file

Best regards
![compiler_warnings](https://cloud.githubusercontent.com/assets/13590527/9903613/06aba43e-5c78-11e5-9e02-2999f7c7406a.jpg)

**Comment by mahagr** [comment]
Not a bug but a fix that displays issues in SCSS code. You need to update template to the latest version.

**Comment by castor01** [comment]
Hi mahagr,
thanks for your response. I've been using the latest version of Theme: Callisto (v1.3.0 / rt_callisto).
I will wait for the next release of callisto. This issue is just a warning and the files are compiled cleanly.
Best regards

**Comment by gospelpowered** [comment]
Hey @mahagr i'm now having the same issues since 5.1.3 and i don't think i have any scss errors :(

It seems to think i have the wrong scss code however i don't think i do. For example it seems to think i have $section_1_image in my _section-1.scss file and i don't, this is what's in there:

#g-section-1 {
	padding: 0;
	background-image: url($section-1-image);
	border-top: 3px solid darken($accent-color-1, 10%);
	background: $section-1-background;
	color: $section-1-text-color;
}

There are no underscores. What am i missing? :(

![compile error](https://cloud.githubusercontent.com/assets/12219933/9958633/9dcb988e-5e3e-11e5-9b3c-4e762435068b.png)

**Comment by adi8i** [comment]
Hello @gospelpowered, welcome back :D. Every single variable need to be defined. 
You need to add: `$section-1-image: false !default`, or replace `false` if you have a default image url.

**Comment by gospelpowered** [comment]
Hey that worked thanks @adi8i. All i did was i added a custom scss file where i declared the custom section image variables and set them as $section-1-image: false !default; for each one. Then the compiler worked fine.
