### ISSUE TITLE
Issue With Grid Block Size

### ISSUE THREAD

**Issue by arifinrt** [gantry/gantry5#85]
I added 3 blocks like shown in this screenshot:
http://pleaselook.at/33.33_2015-04-14_18-57-46.jpg
At the first time, they are correctly divided equally 33.3%

Then, I clicked one of the particles block and just click the Apply button without any other change:
http://pleaselook.at/33.333_2015-04-14_18-58-46.jpg

The width is changed:
http://pleaselook.at/33_2015-04-14_18-59-29.jpg

Can the width be kept same without any change?

**Comment by w00fz** [comment]
Decimals are not support in Layout Manager. We did have decimals support before but after long discussions we thought it was best to remove them, except for the few specific cases where they are equals and they divide in decimals (like 33.3). This is why there is the Equalize button, at the right of the grid, that allows you to reset to equal sizes all blocks in a grid. Although if you start resizing a block, it will loose the floating, this is by design and intended this way.

There is still a bug. In the case of `33.3%`, it should render the class as `size-33-3` and not `size-33` like you are getting.

@mahagr is looking into it.
