### ISSUE TITLE
JS error on customizer page

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#864]
Looks like our stuff is causing JS errors on the Customizer page. Saving regular widgets via AJAX doesn't work, our Gantry 5 Particle doesn't render any content or at least the page doesn't get refreshed.
![customize gantry5 wordpress 2015-09-22 21-39-38](https://cloud.githubusercontent.com/assets/1641534/10029536/b9511354-6172-11e5-9047-aa2542821928.jpg)

**Comment by w00fz** [comment]
You see how it is `"DIV.widget.%2s,DIV.widget.%2s,DIV.widget.%2s"`. Looks like it gets URL encoded when it shouldn't.

**Comment by w00fz** [comment]
Well I think I fixed it but you might want to double check that it's not affecting other locations where `before_widget` gets used. The issue is the Customizer expects `%1$s` format and not `%1s` like we had.

This might require also updates in other RT themes since the `before_widget` gets defined in the `theme.yaml` as well.

Please @mahagr @newkind make sure this is not breaking anything else. I am not entirely sure where it gets used, I tested widgets on frontend and they are still working fine for me.

**Comment by mahagr** [comment]
sprintf() supports the syntax.
