### ISSUE TITLE
Implement support for Joomla objects in twig

### ISSUE THREAD

**Issue by mahagr** [gantry/gantry5#873]
Right now there is no way to call (for example) JFactory::getUser() or JUser::getInstance() from twig templates.

Implement two functions, which can be used as following:

    {% set document = gantry.platform.factory('document') %}
    {% set user = gantry.platform.instance('user', 128) %}

In this example first one is JFactory call and the second gets instance of JUser. Both functions take arbitrary number of parameters (or the parameters from the original function).

After assigning object to a variable, you can use it just like in Joomla. Just replace `->` with `.`.

**Comment by pau1a** [comment]
excellent thanks 👍

**Comment by pau1a** [comment]
Hi team, Ive been using this to try and extract the details of the current user in a particle but it doesn't seem to be working.

Im using it as follows:

{% set user = joomla.factory('user') %}

I then place that variable into a URL in order to select the folder relevant to the user however I get the following in my URL : /Joomla%5CCMS%5CUser%5CUser/

Am I doing something daft?
