### ISSUE TITLE
Implement support for static Joomla function calls in twig

### ISSUE THREAD

**Issue by mahagr** [gantry/gantry5#874]
We need a way to call functions like:

    JHtml::_('behavior.framework');
    JRoute::_('index.php?option=com_content');
    JPluginHelper::isEnabled('system', 'gantry5');

**Comment by mahagr** [comment]
Example particle:

```twig
{% extends '@nucleus/partials/particle.html.twig' %}

{% block particle %}
    {% set user = joomla.factory('user') %}
    {% if user.guest %}
        <div>{{ joomla.html('link', joomla.route('index.php?option=com_users'), 'JLOGIN'|trans)|raw }}</div>
    {% else %}
        <div>{{ joomla.html('link', joomla.route('index.php?option=com_users'), 'JLOGOUT'|trans)|raw }}, {{ user.name }}</div>
        <div>Last visit {{ joomla.html('date.relative', user.lastvisitDate, 'day') }}</div>
        <div>{{ joomla.call('JPluginHelper::isEnabled', 'system', 'gantry5') }}</div>
    {% endif %}
{% endblock %}
```

**Comment by JoomFX** [comment]
Yes, yes, yes !
Simply awesome!
Thanks a lot @mahagr :smile:

**Comment by JoomFX** [comment]
@mahagr Just a quick question :)

I added the following in `page_head.html.twig` and all 3 jQuery assets that come from Joomla were loaded just fine:

```
{{ joomla.html('jquery.framework') }}
```

So far so good :)

Now, I'm wondering what is the best way to load jQuery from a Particle. Since it is not a script nor a stylesheet, it cannot be loaded with `{% assets %}`, `{% scripts %}` and {% styles %} as explained in the [Documentation](http://docs.gantry.org/gantry5/advanced/css-js-twig).

So, I just added `{{ joomla.html('jquery.framework') }}` immediately after `{% block particle %}` and jQuery was loaded just fine:

```
{% extends '@nucleus/partials/particle.html.twig' %}

{% block particle %}
	{{ joomla.html('jquery.framework') }}
        ...
        ...
        ...
{% endblock %}
```

Sorry for the long (and probably unnecessary) explanation :)
My question is, is the above the best way? Thanks!

**Comment by JoomFX** [comment]
Nevermind, I figured it out.
It should be inside `{% block particle %}`.
Even the `{% assets %}`, `{% scripts %}` and `{% styles %}` must be inside `{% block particle %}` 

Silly me :smile:

**Comment by mahagr** [comment]
I think you can alternatively use

```twig
{% do joomla.html('jquery.framework') %}
```
To say to twig that there's no output. Not tested, tho...

**Comment by JoomFX** [comment]
Yep, adding `{% do joomla.html('jquery.framework') %}` before `{% block particle %}` works.
Thanks :smile:

**Comment by jameswadsworth** [comment]
Hi @mahagr is it possible to set xhtml to false with joomla.route? For example is possible in the follow to set xhtml to false:
`href="{{ joomla.route(particle.url)|default(gantry.siteUrl()) }}"`

**Comment by mahagr** [comment]
@jameswadsworth It's always off in Gantry 5, you just need to apply `|raw` filter not to let twig to escape it.

**Comment by jameswadsworth** [comment]
Thanks. Works great.
