### ISSUE TITLE
Display issue on some Android internet browser.

### ISSUE THREAD

**Issue by mixahlos** [gantry/gantry5#897]
There is an issue in the default Android's internet browser.
So far tested in Samsung Galaxy S3 / Android 4.3, and unknown device andoird 5.0.2  responsive  doesn't work at all.
In the folowing devices works fine : 
Samsung Galaxy S4 & S5 running android 5.0.0
Samsung Galaxy s4 / 5.0.1
HTC One - Android 5.0.2

I tested it in the default Gantry 5 installation w/o any customization or overrides.
In chrome browsers displays well, the problem is only on the android's default browser.

Samsung Galaxy S3 / android 4.3 Screenshots :
Portrait : http://prntscr.com/8obbhm
Landscape : http://prntscr.com/8obbot

**Comment by mahagr** [comment]
Older and cheap models of Samsung use very old version of Android browser which doesn't support flexbox. Unfortunately Samsung haven't maintained the custom software used in many of its phones, so there's no updates that will fix the issues. In order to get responsive working, you need to install Chrome or get a new Android version to your phone.

http://caniuse.com/#feat=flexbox

**Comment by mixahlos** [comment]
Thank you @mahagr
