### ISSUE TITLE
Google and Facebook retargetting scripts problems

### ISSUE THREAD

**Issue by dozerontop** [gantry/gantry5#910]
Hello,

I have problems creating inline custom JS particles for Google and Facebook retargetting.

When I put in my code, the "<noscript>" portion of the codes get stripped off. How should I fix that?

Thanks

**Comment by w00fz** [comment]
Can you try converting those double quotes to singles '?

// Djamil Legato // From iPhone //

**Comment by dozerontop** [comment]
Sorry, I just noticed that my post was modified...
What actually gets stripped off is the **noscript** tag and its content.

Thanks

**Comment by w00fz** [comment]
I see. Could you paste the whole content for the inline js? You can use triple backticks to wrap the code, so that it gets rendered and not removed by GitHub.

**Comment by dozerontop** [comment]
This is the code I need to put before the closing head tag:
```
<script>(function() {
var _fbq = window._fbq || (window._fbq = []);
if (!_fbq.loaded) {
var fbds = document.createElement('script');
fbds.async = true;
fbds.src = '//connect.facebook.net/en_US/fbds.js';
var s = document.getElementsByTagName('script')[0];
s.parentNode.insertBefore(fbds, s);
_fbq.loaded = true;
}
_fbq.push(['addPixelId', '470029339846466']);
})();
window._fbq = window._fbq || [];
window._fbq.push(['track', 'PixelInitialized', {}]);
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?

id=470029339846466&amp;ev=PixelInitialized" /></noscript>
```

**Comment by w00fz** [comment]
Ok the issue is the inline JS of Atoms are meant to be JS only. Anything you write in there gets wrapped by a `<script></script>` and the browser (not Gantry 5), removes the `<noscript>` because it's an HTML element.

This is going to be easier to do in the next version, 5.2.0, since you will be having access directly to the bottom of `</body>` which means both `<script>` and `<noscript>` will be valid.
A workaround right now is to just put the script portion in the Atom:

```js
(function() {
var _fbq = window._fbq || (window._fbq = []);
if (!_fbq.loaded) {
var fbds = document.createElement('script');
fbds.async = true;
fbds.src = '//connect.facebook.net/en_US/fbds.js';
var s = document.getElementsByTagName('script')[0];
s.parentNode.insertBefore(fbds, s);
_fbq.loaded = true;
}
_fbq.push(['addPixelId', 'XXX']);
})();
window._fbq = window._fbq || [];
window._fbq.push(['track', 'APP', {}]);
```

And just ignore the `<noscript>` or create a Custom HTML particle and place the `<noscript>` in there.
This just until the new 5.2.0 is out where you will be able to be more flexible about manipulating `<head>` and `<body>` outside the Layout scope.

> NOTE: I edited your comment to hide the App Id as well as the App Name.

**Comment by dozerontop** [comment]
Cool! Thanks for your help and edits!!

**Comment by w00fz** [comment]
You're welcome!
