### ISSUE TITLE
Separate configuration for each Multi Site blog

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#921]
Right now we only have one location to store the custom/config/ and this can be a big issue with Multi Site installation where each of the created blogs/users/ should have it's own custom/config. I need to test that and we need to address it on 5.2

**Comment by dudewithamood** [comment]
Hi, to clarify how this works, any changes I make to the Hydrogen theme in custom will not be available to any site under the multisite that uses this theme... so if I want all instances of the theme to utilize these changes it would be best to make a copy of Hydrogen and make it a new theme, making the changes directly in the new theme rather than under custom?
