### ISSUE TITLE
Overrides not cleared out when saving

### ISSUE THREAD

**Issue by w00fz** [gantry/gantry5#929]
When you have an override in a card of this kind:

![particle](https://cloud.githubusercontent.com/assets/11734/10591459/1dbc1d2c-766b-11e5-8e3a-d0dfc150526d.jpg)

Trying to uncheck the field and then saving, so that the whole card gets inherited, doesn't actually remove the `yaml` from the filesystem, causing the value to always getting loaded.

This is not a problem if there are 2+ more overrides, although going from 1 to 0 doesn't work.

> The issue was firstly noticed and reported privately on Gitter by @mixahlos

**Comment by JoomFX** [comment]
@w00fz @mahagr guys, I'm not sure if it is related to this issue, I think it is, but I experience something very similar with all `input.checkbox` fields in my Particles. And because of this issue I gave up using `input.checkbox`.

So here is the issue - the `input.checkbox` doesn't work for if the default value is `1` (checked). If it is checked by default, then it does what it has to do according to the Twig, but if I uncheck it, it still behaves as if it is checked. And if I close the Particle popup and then I opened it again, the checkbox is checked, even though I unchecked it and saved it.

If the default value for `input.checkbox` is `0` (unchecked) it seems to work properly. The Twig correctly interprets that it is false and does not do anything, then if I check the box, Twig correctly interprets the condition as `true`.

So, as a conclusion, for me an `input.checkbox` that is `true` by default, does not work, I cannot make it `false`, I cannot uncheck the box.

**Comment by w00fz** [comment]
I think this is a different issue, mostly related to the uniqueness of the checkbox behavior.
The checkbox issue I believe was reported already by @adi8i some time ago, it's just not as simple to fix and the suggestion was to switch to dropdown.

The issue I reported is more serious and apply to any field of any override. When you are left with 1 enabled field in a card, of any kind, it is impossible to get rid of it, unless you manually delete the `yaml` file.

**Comment by mahagr** [comment]
How the logic works is this:

There is an extra hidden field called `logo` which tells that there are variables like `logo[image]` inside it. If you have a single checked field, POST request will look like this:

    logo
    logo[image]: ...

In PHP the first value will get ignored and the result is `['logo' => ['image' => '...']]`. If no variables are set, logo becomes empty string, which triggers removal of the file.

**Comment by w00fz** [comment]
Then you had the `hidden` field `particles[name]` in the wrong location because they were never sent in the POST when saving overrides, ever :wink: 
Also there seems to be no hidden field for `styles[name]`, are those supposed to be following the same Settings approach?

**Comment by mahagr** [comment]
Styles saves the data into a single file, so it doesn't need to have logic telling it which sections exist. So it should be all good.
