### ISSUE TITLE
Update to 5.2 removed Layout setting from Container

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#967]
Please see pic, on the Container (other sections are fine) the setting for 'Layout' i.e Default, Boxed, Fullwidth has disappeared.

This is causing an issue in Callisto on the frontpage and also on the blog page (as an example).

![g5_layoutoncontainer](https://cloud.githubusercontent.com/assets/5719486/10906063/df79b64a-821e-11e5-888c-e84ed1de92bb.png)

![g5_callisto1](https://cloud.githubusercontent.com/assets/5719486/10906064/df7e09fc-821e-11e5-9485-06cb32b1e5cd.png)

![g5_callisto2](https://cloud.githubusercontent.com/assets/5719486/10906046/b5def958-821e-11e5-91e2-5306156ad4ba.png)

**Comment by kat05** [comment]
it is weird, this issue happens on some installs but not others. it also effects the other themes.

i have more than ethereal 1.2.1 install with gantry 5.2.1, in the default outline, one of the installs shows the setting on the container just fine, on the other it's missing and causing issues for example on the blog page.

![g5_ethereal](https://cloud.githubusercontent.com/assets/5719486/10906344/13cfbb68-8221-11e5-94b6-29b4369a6850.png)

**Comment by marktaylor46** [comment]
I have the same issue on my local Callisto - the layout field is missing from the container section. As a result this then in turn means that the "g-container" class is missing from "g-main" section in frontend so the content then is fullwidth flushed content instead of fullwidth boxed.

![2015-11-05_10-41-32](https://cloud.githubusercontent.com/assets/11683218/10966247/34515092-83aa-11e5-9497-269d276e2256.png)

I also have a member with same issue too
http://www.rockettheme.com/forum/joomla-template-callisto/250104-some-page-templates-go-full-width?start=0#1248094

If it helps, my local and members site were updated to 5.2.0 and then subsequently to 5.2.1

**Comment by marktaylor46** [comment]
Another member with same issue - this time on Ethereal
http://www.rockettheme.com/forum/joomla-template-ethereal/250295-maximum-template-width-differ?start=0#1248117

**Comment by kat05** [comment]
Confirmed, latest CI fixes the issue for me.

**Comment by marktaylor46** [comment]
yup confirmed - fixes it for me also.
