### ISSUE TITLE
Layout manager needs more improvements ie. columns

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#980]
We need more improvements that we talked about sometime ago ie. functionallity of divider in G4 WP where you could divide a widget position into multiple columns. 

Right now it's not possible to have setup like this, where Location particle would take 2 rows and have two particles on it's left, without modifying yaml and splitting into more sections : https://monosnap.com/file/DMfz4NSUfY5Adp20hgSHYwBHWrX6FR.png

**Comment by newkind** [comment]
More accurate picture of what it should work like : https://monosnap.com/file/dozGReMJfeEkpIecvtT9P9jL5vEMao.png

**Comment by w00fz** [comment]
This was the way it was initially and we removed all that functionality because it was said to be too confusing. What you want to do is achievable in some ways by creating a new grid and adding spacers.
The whole nucleus grid system and the grid > block approach wouldn't really allow this so we can't change that.
