### ISSUE TITLE
How to programmatically populate select.select/select.selectize field with custom data?

### ISSUE THREAD

**Issue by kmbt** [gantry/gantry5#987]
Hi all,

I am getting familiar with the Gantry 5 framework for Wordpress and so far I like it a lot - especially the fact that it makes use of the Timber plugin which I am already familiar with.

From the Gantry 5 docs I have learned that it is possible to add a select.select or select.selectize field with options defined upfront, in the YAML file. What I would like to do is to populate the field options by a custom PHP function. Such function might for example fetch custom posts of some type by means of Timber::get_posts.

Another one would be pulling CSS class names from a stylesheet file by means of a regular expression. The possibilities are countless, therefore I think that being able to write a function to generate options would be a great feature.

Is there any feasible way to populate select fields in such a way?

**Comment by mahagr** [comment]
Yes, we already have some fields that populate data by using a function call. But in order to do that, right now you need to create a new field type (`forms/fields/x/y.html.twig`) and use it instead of the normal select fields. Check out `forms/fields/menu/item.html.twig` for an example on how to do it.

**Comment by kmbt** [comment]
Thank you for your answer. I have another related question.

Let's assume that I have built a field that lets me choose a custom post and internally stores a post ID. Now I would like to render the particle containing the post content. One obvious approach would be to pull the post right from the twig template - but that seems to be against my understanding of what templates are for (at least in my MVC kind of thinking). Is there any place where I can inject some preprocessing code so that the field received by the template is already containing a post object?

It's just an idea, but maybe there should be some sort of callback/hook/filter mechanism so that a php function could be automatically called prior to rendering a particle. This might also allow caching the processing results. Also a similar hook/callback could fire a function prior to rendering the field template.

**Comment by mahagr** [comment]
Sorry for my delayed answer -- been having a bad flu.

What comes to WP, it already processes most of its data inside template (functions.php and index.php etc), usually just before rendering head. That is no different with particles, which get all processed before head gets called. Well, they actually get rendered, too, as because of the nature of particles, you cannot know what is inside them until you render the content. Again that is not so much against WP ways of thinking as it doesn't have MVC. Also widgets in WP get only rendered from the template level, so actually particles get rendered before (other) widgets do.

To me pulling post from a particle is like pulling it from a widget as long as you do not have any real code inside your template file.

**Comment by kmbt** [comment]
I am sorry to hear that you were sick. I hope that you are better now.

I agree that WP itself by no means  follows nor encourages the MVC (MTV) pattern. It pulls data from "Model" all over the template which often makes us write non-presentation logic directly inside the template. That is one of the reasons, I believe, the Timber plugin was created. On the Timber website it says:

> This cleans-up your theme code so your PHP file can focus on supplying the data and logic, while your twig file can focus 100% on the display and HTML.

If one looks at supplied examples and takes a little dive into the Timber Starter Theme it becomes apparent that the Timber developers lean much towards the Model-Template-View approach. The PHP files  store the Controller logic, Twig files are the Templates, and Timber provides us with objects to act as Models (which we can extend by inheritance in functions.php). All the data is already mostly processed before rendering the template and "pushed" to it instead of being "pulled" so that the twig template stays "dumb" and doesn't need to "know" much about how the data got there. 

Why would one desire that? I think that "dumb" templates lead to more reusable, modular and maintainable code which is the reason why I choose to use another templating engine on top of PHP, which can already work as a templating engine by itself. 

Of course, the fact that Timber developers lean towards MVC does not readily imply that Gantry developers should. I just wanted to share my personal point of view on the subject, presuming that I am not its sole representative :) Thank you for taking your time to explain yours.

**Comment by mahagr** [comment]
Well, you are correct on Timbers approach except that you cannot really do that for widgets and particles because of they are outside of the main MVC logic. They are not part of the main content, but extra output in positions which are driven by the theme, not by application (WordPress). 

Because of widgets and particles only have display function, all the logic happens when they are displayed. In fact in this particles are much closer to MVC than widgets are, as they contain only presentation layer (V) and they just use context and/or Timber, WP and Gantry models to display the content. Widgets on the other hand are PHP classes with HTML inside of them -- which is really, really bad practise.

Also I don't think that everything you might want to use should be in a single model (in twig context array) because of you cannot ever predict all the possible data you may need to display the view. Also I don't believe that view should be locked to use only a single model. So making calls from the view to fetch data it needs is perfectly fine to me. This is as long as it doesn't have application logic in it.

**Comment by mahagr** [comment]
Closed due to 30 days of inactivity. If you still have questions regarding this issue, please be free to reopen the issue.
