### ISSUE TITLE
Does not save when you change the menu from Hydrogen to MainMenu

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#99]
On a fresh Joomla 3.4.1 full install (with sample data) I installed gantry 5 beta 3.
Look at this scenario.
![gantry5b3menu](https://cloud.githubusercontent.com/assets/3976174/7247381/359ccc02-e809-11e4-9c2c-a127c83450a3.png)

**Extensions > Template Manager > Hydrogen Home**
Click on *Menu*, and from *Menu Editor* try to change from *Hydrogen* to *MainMenu* and hit **Save Menu**.
On frontend appears the same *Hydrogen* not *MainMenu* as you see on the next screenshot.
![gantry5b3menu2](https://cloud.githubusercontent.com/assets/3976174/7247401/634e04cc-e809-11e4-805e-66091d2869f3.png)

**Comment by JoomFX** [comment]
@mariantanase have a look at this issue https://github.com/gantry/gantry5/issues/95

@w00fz mate, in the above issue you said - *The confusion resides in the fact that in the Menu Editor it's always the default menu set in joomla to load, changing from the dropdown and saving will not change that.* - so what is the point of having the dropdown for menu selection in the Menu Editor? Or am I missing something?

**Comment by mahagr** [comment]
Menu editor is really just like Joomla menu editor and it lives outside of the layout. There are long term plans to support multiple menus in the layout and to replace Joomla menu module so you can just use particles and have icons, module positions etc support in all your menus.

Right now because of the lack of the time we've had to make a few shortcuts on menu support, but the fact is that menu manager is still outside of styles and doesn't know which menu is being used in different configurations.

**Comment by adi8i** [comment]
Was a long discussion about this on chat, yesterday :P, you can chose the menu you want from particle menu settings :)

**Comment by w00fz** [comment]
Alright guys, I have a UI/UX change that should make things more clear. You can [see it here](https://cloudup.com/cP4pzpHNCpA).
 
Thanks all for the feedbacks!
