### ISSUE TITLE
Open Link In New Window

### ISSUE THREAD

**Issue by rgblogs** [gantry/gantry5#990]
Is it possible to open URL of Image / Logo Particle in new window?

Using joomla with Hydrogen template.

**Comment by w00fz** [comment]
There isn't the option in the particle but you can very easily add it or simply force all links to new window, by overriding the `logo.html.twig` particle itself.
You can follow this guide, only instead of creating a new one, you are just overriding, paths are the same.
http://docs.gantry.org/gantry5/advanced/creating-a-new-particle

**Comment by paulinohio** [comment]
I know this is an old post.  If I understand it correctly you have to create a YAML file and TWIG file? I'm confused as where to get the information to fill the YAML file. The particle I'm using does not have a title.  

The page with the link that I'm trying to get to open in a new window: https://neilrisko.com/HCE/index.php/office-information-test
