### ISSUE TITLE
Gantry 5 module still renders title and container when particle is disabled

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#991]
I discovered this on a members site. This was the scenario:

A Gantry 5 module particle (contact particle) was published to a position on the homepage. The title of the module and the container were rendering on the homepage but the particle content itself was not.

@kat05 tracked this down to the fact that the contact particle was disabled in the base outline > settings.

Under these circumstances I would actually expect that no content at all should be rendered. I.e. if the particle is disabled then the module itself should not be rendered: no container, no title, nothing (just like what would happen if you unpublished the module or did not have access level to view the module).

**Comment by w00fz** [comment]
I think rather than completely collapsing it, if the particle has been disabled from the Outline, it should render in frontend as it is now but instead of empty with a warning:

> The Particle <name> has been disabled from the Outline and won't render

Something like that. I think the behavior is right, if you don't want it to render at all, it should be the module to be unpublished, not the particle.

**Comment by marktaylor46** [comment]
Ok, I can live with that. At least it's then obvious what you need to do rather being left scratching your head :)

**Comment by mahagr** [comment]
I was able to change the code in both WP and Joomla so that nothing gets rendered if you disable particle either from the outline or from module/widget.

After a thought I think that @marktaylor46 is right about displaying nothing when the particle is disabled (to keep the behaviour consistent), I also agreed that there should be visible message on debug mode to point out why the particle will not be rendered. So in the end I implemented both options: collapse by default, but display message if in debug...

**Comment by marktaylor46** [comment]
wow - good job @mahagr  :) thanks!
